// Code generated by box-gantry. DO NOT EDIT.
package dev.unofficialbox;

/**
 * Generated behavioral tests (FR-7.8, VR-4): a per-union round-trip
 * (known-tag dispatch, discriminator survival, open-union unknown
 * retention / closed-union rejection) plus the tri-state (D-110) and
 * date/time serialization checks, against the real generated codec.
 * Runs as a plain {@code main} (no test framework) — exits non-zero on
 * the first failure.
 */
public final class GeneratedTests {
    private static int _checks = 0;

    private GeneratedTests() {}

    public static void main(String[] args) {
        serialization();
        unions();
        System.out.println("OK: " + _checks + " checks passed");
    }

    private static void check(boolean cond, String message) {
        _checks++;
        if (!cond) {
            throw new AssertionError(message);
        }
    }

    private static Object parse(String json) {
        return dev.unofficialbox.core.Json.parse(json);
    }

    private static void serialization() {
        check(java.time.LocalDate.parse(dev.unofficialbox.core.Json.asString(parse("\"2026-07-12\""))).toString().equals("2026-07-12"), "date round-trip");
        java.time.OffsetDateTime _dt = java.time.OffsetDateTime.parse("2026-07-12T10:30:00Z");
        check(_dt.isEqual(java.time.OffsetDateTime.parse(_dt.toString())), "date-time round-trip");
        // tri-state (D-110) against a real struct: absent omits the key,
        // null reads back null, a value round-trips.
        dev.unofficialbox.model.schemas.AppItemAssociations _absent = dev.unofficialbox.model.schemas.AppItemAssociations.fromJson(parse("{}"));
        check(_absent.nextMarker().isAbsent(), "tri-state absent: dev.unofficialbox.model.schemas.AppItemAssociations");
        check(!dev.unofficialbox.core.Json.asObject(_absent.toJson()).containsKey("next_marker"), "tri-state absent omits key: dev.unofficialbox.model.schemas.AppItemAssociations");
        dev.unofficialbox.model.schemas.AppItemAssociations _nullv = dev.unofficialbox.model.schemas.AppItemAssociations.fromJson(parse("{\"next_marker\":null}"));
        check(_nullv.nextMarker().isNull(), "tri-state null: dev.unofficialbox.model.schemas.AppItemAssociations");
        dev.unofficialbox.model.schemas.AppItemAssociations _value = dev.unofficialbox.model.schemas.AppItemAssociations.fromJson(parse("{\"next_marker\":\"x\"}"));
        check(_value.nextMarker().isPresent() && "x".equals(_value.nextMarker().value()), "tri-state value: dev.unofficialbox.model.schemas.AppItemAssociations");
    }

    private static void unions() {
        {
            dev.unofficialbox.model.schemas.AiAgent _u = dev.unofficialbox.model.schemas.AiAgent.fromJson(parse("{\"type\":\"ai_agent_ask\"}"));
            check(_u instanceof dev.unofficialbox.model.schemas.AiAgentAsk, "known-tag dispatch: dev.unofficialbox.model.schemas.AiAgent");
            check("ai_agent_ask".equals(dev.unofficialbox.core.Json.asString(dev.unofficialbox.core.Json.asObject(_u.toJson()).get("type"))), "discriminator survives: dev.unofficialbox.model.schemas.AiAgent");
            dev.unofficialbox.model.schemas.AiAgent _unk = dev.unofficialbox.model.schemas.AiAgent.fromJson(parse("{\"type\":\"__gantry_unknown__\"}"));
            check(_unk instanceof dev.unofficialbox.model.schemas.AiAgent.Unknown, "open unknown retained: dev.unofficialbox.model.schemas.AiAgent");
        }
        {
            dev.unofficialbox.model.schemas.AiAgentAllowedEntity _unk = dev.unofficialbox.model.schemas.AiAgentAllowedEntity.fromJson(parse("{\"type\":\"__gantry_unknown__\"}"));
            check(_unk instanceof dev.unofficialbox.model.schemas.AiAgentAllowedEntity.Unknown, "open unknown retained: dev.unofficialbox.model.schemas.AiAgentAllowedEntity");
        }
        {
            dev.unofficialbox.model.schemas.AiAskAgent _u = dev.unofficialbox.model.schemas.AiAskAgent.fromJson(parse("{\"type\":\"ai_agent_ask\"}"));
            check(_u instanceof dev.unofficialbox.model.schemas.AiAgentAsk, "known-tag dispatch: dev.unofficialbox.model.schemas.AiAskAgent");
            check("ai_agent_ask".equals(dev.unofficialbox.core.Json.asString(dev.unofficialbox.core.Json.asObject(_u.toJson()).get("type"))), "discriminator survives: dev.unofficialbox.model.schemas.AiAskAgent");
            dev.unofficialbox.model.schemas.AiAskAgent _unk = dev.unofficialbox.model.schemas.AiAskAgent.fromJson(parse("{\"type\":\"__gantry_unknown__\"}"));
            check(_unk instanceof dev.unofficialbox.model.schemas.AiAskAgent.Unknown, "open unknown retained: dev.unofficialbox.model.schemas.AiAskAgent");
        }
        {
            dev.unofficialbox.model.schemas.AiExtractAgent _u = dev.unofficialbox.model.schemas.AiExtractAgent.fromJson(parse("{\"type\":\"ai_agent_extract\"}"));
            check(_u instanceof dev.unofficialbox.model.schemas.AiAgentExtract, "known-tag dispatch: dev.unofficialbox.model.schemas.AiExtractAgent");
            check("ai_agent_extract".equals(dev.unofficialbox.core.Json.asString(dev.unofficialbox.core.Json.asObject(_u.toJson()).get("type"))), "discriminator survives: dev.unofficialbox.model.schemas.AiExtractAgent");
            dev.unofficialbox.model.schemas.AiExtractAgent _unk = dev.unofficialbox.model.schemas.AiExtractAgent.fromJson(parse("{\"type\":\"__gantry_unknown__\"}"));
            check(_unk instanceof dev.unofficialbox.model.schemas.AiExtractAgent.Unknown, "open unknown retained: dev.unofficialbox.model.schemas.AiExtractAgent");
        }
        {
            dev.unofficialbox.model.schemas.AiExtractStructuredAgent _u = dev.unofficialbox.model.schemas.AiExtractStructuredAgent.fromJson(parse("{\"type\":\"ai_agent_extract_structured\"}"));
            check(_u instanceof dev.unofficialbox.model.schemas.AiAgentExtractStructured, "known-tag dispatch: dev.unofficialbox.model.schemas.AiExtractStructuredAgent");
            check("ai_agent_extract_structured".equals(dev.unofficialbox.core.Json.asString(dev.unofficialbox.core.Json.asObject(_u.toJson()).get("type"))), "discriminator survives: dev.unofficialbox.model.schemas.AiExtractStructuredAgent");
            dev.unofficialbox.model.schemas.AiExtractStructuredAgent _unk = dev.unofficialbox.model.schemas.AiExtractStructuredAgent.fromJson(parse("{\"type\":\"__gantry_unknown__\"}"));
            check(_unk instanceof dev.unofficialbox.model.schemas.AiExtractStructuredAgent.Unknown, "open unknown retained: dev.unofficialbox.model.schemas.AiExtractStructuredAgent");
        }
        {
            dev.unofficialbox.model.schemas.AiLlmEndpointParams _u = dev.unofficialbox.model.schemas.AiLlmEndpointParams.fromJson(parse("{\"type\":\"openai_params\"}"));
            check(_u instanceof dev.unofficialbox.model.schemas.AiLlmEndpointParamsOpenAi, "known-tag dispatch: dev.unofficialbox.model.schemas.AiLlmEndpointParams");
            check("openai_params".equals(dev.unofficialbox.core.Json.asString(dev.unofficialbox.core.Json.asObject(_u.toJson()).get("type"))), "discriminator survives: dev.unofficialbox.model.schemas.AiLlmEndpointParams");
            dev.unofficialbox.model.schemas.AiLlmEndpointParams _unk = dev.unofficialbox.model.schemas.AiLlmEndpointParams.fromJson(parse("{\"type\":\"__gantry_unknown__\"}"));
            check(_unk instanceof dev.unofficialbox.model.schemas.AiLlmEndpointParams.Unknown, "open unknown retained: dev.unofficialbox.model.schemas.AiLlmEndpointParams");
        }
        {
            dev.unofficialbox.model.schemas.AiTaxonomySource _u = dev.unofficialbox.model.schemas.AiTaxonomySource.fromJson(parse("{\"type\":\"taxonomy\"}"));
            check(_u instanceof dev.unofficialbox.model.schemas.AiTaxonomyReference, "known-tag dispatch: dev.unofficialbox.model.schemas.AiTaxonomySource");
            check("taxonomy".equals(dev.unofficialbox.core.Json.asString(dev.unofficialbox.core.Json.asObject(_u.toJson()).get("type"))), "discriminator survives: dev.unofficialbox.model.schemas.AiTaxonomySource");
            dev.unofficialbox.model.schemas.AiTaxonomySource _unk = dev.unofficialbox.model.schemas.AiTaxonomySource.fromJson(parse("{\"type\":\"__gantry_unknown__\"}"));
            check(_unk instanceof dev.unofficialbox.model.schemas.AiTaxonomySource.Unknown, "open unknown retained: dev.unofficialbox.model.schemas.AiTaxonomySource");
        }
        {
            dev.unofficialbox.model.schemas.AiTextGenAgent _u = dev.unofficialbox.model.schemas.AiTextGenAgent.fromJson(parse("{\"type\":\"ai_agent_text_gen\"}"));
            check(_u instanceof dev.unofficialbox.model.schemas.AiAgentTextGen, "known-tag dispatch: dev.unofficialbox.model.schemas.AiTextGenAgent");
            check("ai_agent_text_gen".equals(dev.unofficialbox.core.Json.asString(dev.unofficialbox.core.Json.asObject(_u.toJson()).get("type"))), "discriminator survives: dev.unofficialbox.model.schemas.AiTextGenAgent");
            dev.unofficialbox.model.schemas.AiTextGenAgent _unk = dev.unofficialbox.model.schemas.AiTextGenAgent.fromJson(parse("{\"type\":\"__gantry_unknown__\"}"));
            check(_unk instanceof dev.unofficialbox.model.schemas.AiTextGenAgent.Unknown, "open unknown retained: dev.unofficialbox.model.schemas.AiTextGenAgent");
        }
        {
            dev.unofficialbox.model.schemas.AppItemAssociatedItem _unk = dev.unofficialbox.model.schemas.AppItemAssociatedItem.fromJson(parse("{\"type\":\"__gantry_unknown__\"}"));
            check(_unk instanceof dev.unofficialbox.model.schemas.AppItemAssociatedItem.Unknown, "open unknown retained: dev.unofficialbox.model.schemas.AppItemAssociatedItem");
        }
        {
            dev.unofficialbox.model.schemas.CollaborationAccessGrantee _unk = dev.unofficialbox.model.schemas.CollaborationAccessGrantee.fromJson(parse("{\"type\":\"__gantry_unknown__\"}"));
            check(_unk instanceof dev.unofficialbox.model.schemas.CollaborationAccessGrantee.Unknown, "open unknown retained: dev.unofficialbox.model.schemas.CollaborationAccessGrantee");
        }
        {
            dev.unofficialbox.model.schemas.CollaborationItem _unk = dev.unofficialbox.model.schemas.CollaborationItem.fromJson(parse("{\"type\":\"__gantry_unknown__\"}"));
            check(_unk instanceof dev.unofficialbox.model.schemas.CollaborationItem.Unknown, "open unknown retained: dev.unofficialbox.model.schemas.CollaborationItem");
        }
        {
            dev.unofficialbox.model.schemas.Item _unk = dev.unofficialbox.model.schemas.Item.fromJson(parse("{\"type\":\"__gantry_unknown__\"}"));
            check(_unk instanceof dev.unofficialbox.model.schemas.Item.Unknown, "open unknown retained: dev.unofficialbox.model.schemas.Item");
        }
        {
            dev.unofficialbox.model.schemas.MetadataQueryResultItem _unk = dev.unofficialbox.model.schemas.MetadataQueryResultItem.fromJson(parse("{\"type\":\"__gantry_unknown__\"}"));
            check(_unk instanceof dev.unofficialbox.model.schemas.MetadataQueryResultItem.Unknown, "open unknown retained: dev.unofficialbox.model.schemas.MetadataQueryResultItem");
        }
        {
            dev.unofficialbox.model.schemas.RecentItemResource _unk = dev.unofficialbox.model.schemas.RecentItemResource.fromJson(parse("{\"type\":\"__gantry_unknown__\"}"));
            check(_unk instanceof dev.unofficialbox.model.schemas.RecentItemResource.Unknown, "open unknown retained: dev.unofficialbox.model.schemas.RecentItemResource");
        }
        {
            dev.unofficialbox.model.schemas.Resource _unk = dev.unofficialbox.model.schemas.Resource.fromJson(parse("{\"type\":\"__gantry_unknown__\"}"));
            check(_unk instanceof dev.unofficialbox.model.schemas.Resource.Unknown, "open unknown retained: dev.unofficialbox.model.schemas.Resource");
        }
        {
            dev.unofficialbox.model.schemas.SearchResultItem _unk = dev.unofficialbox.model.schemas.SearchResultItem.fromJson(parse("{\"type\":\"__gantry_unknown__\"}"));
            check(_unk instanceof dev.unofficialbox.model.schemas.SearchResultItem.Unknown, "open unknown retained: dev.unofficialbox.model.schemas.SearchResultItem");
        }
        {
            dev.unofficialbox.model.schemas.SearchResultsResponse _u = dev.unofficialbox.model.schemas.SearchResultsResponse.fromJson(parse("{\"type\":\"search_results_items\"}"));
            check(_u instanceof dev.unofficialbox.model.schemas.SearchResults, "known-tag dispatch: dev.unofficialbox.model.schemas.SearchResultsResponse");
            check("search_results_items".equals(dev.unofficialbox.core.Json.asString(dev.unofficialbox.core.Json.asObject(_u.toJson()).get("type"))), "discriminator survives: dev.unofficialbox.model.schemas.SearchResultsResponse");
            dev.unofficialbox.model.schemas.SearchResultsResponse _unk = dev.unofficialbox.model.schemas.SearchResultsResponse.fromJson(parse("{\"type\":\"__gantry_unknown__\"}"));
            check(_unk instanceof dev.unofficialbox.model.schemas.SearchResultsResponse.Unknown, "open unknown retained: dev.unofficialbox.model.schemas.SearchResultsResponse");
        }
        {
            dev.unofficialbox.model.schemas.SearchResultWithSharedLinkItem _unk = dev.unofficialbox.model.schemas.SearchResultWithSharedLinkItem.fromJson(parse("{\"type\":\"__gantry_unknown__\"}"));
            check(_unk instanceof dev.unofficialbox.model.schemas.SearchResultWithSharedLinkItem.Unknown, "open unknown retained: dev.unofficialbox.model.schemas.SearchResultWithSharedLinkItem");
        }
        {
            dev.unofficialbox.model.schemas.HubAccessGrantee _unk = dev.unofficialbox.model.schemas.HubAccessGrantee.fromJson(parse("{\"type\":\"__gantry_unknown__\"}"));
            check(_unk instanceof dev.unofficialbox.model.schemas.HubAccessGrantee.Unknown, "open unknown retained: dev.unofficialbox.model.schemas.HubAccessGrantee");
        }
        {
            dev.unofficialbox.model.schemas.HubDocumentBlockEntry _unk = dev.unofficialbox.model.schemas.HubDocumentBlockEntry.fromJson(parse("{\"type\":\"__gantry_unknown__\"}"));
            check(_unk instanceof dev.unofficialbox.model.schemas.HubDocumentBlockEntry.Unknown, "open unknown retained: dev.unofficialbox.model.schemas.HubDocumentBlockEntry");
        }
        {
            dev.unofficialbox.model.schemas.HubItemReference _unk = dev.unofficialbox.model.schemas.HubItemReference.fromJson(parse("{\"type\":\"__gantry_unknown__\"}"));
            check(_unk instanceof dev.unofficialbox.model.schemas.HubItemReference.Unknown, "open unknown retained: dev.unofficialbox.model.schemas.HubItemReference");
        }
        {
            dev.unofficialbox.model.schemas.ShieldListContent _unk = dev.unofficialbox.model.schemas.ShieldListContent.fromJson(parse("{\"type\":\"__gantry_unknown__\"}"));
            check(_unk instanceof dev.unofficialbox.model.schemas.ShieldListContent.Unknown, "open unknown retained: dev.unofficialbox.model.schemas.ShieldListContent");
        }
        {
            dev.unofficialbox.model.schemas.ShieldListContentRequest _unk = dev.unofficialbox.model.schemas.ShieldListContentRequest.fromJson(parse("{\"type\":\"__gantry_unknown__\"}"));
            check(_unk instanceof dev.unofficialbox.model.schemas.ShieldListContentRequest.Unknown, "open unknown retained: dev.unofficialbox.model.schemas.ShieldListContentRequest");
        }
    }
}
