// Code generated by box-gantry 0.1.0 (spec ee7d55aedefe2fa0) for Box API 2024.0. DO NOT EDIT.
package dev.unofficialbox.model.schemas;

import module java.base;
import dev.unofficialbox.core.Tristate;

public record AcceptanceRequirementsStatusTermsOfServiceRequirement(
    Tristate<Boolean> isAccepted,
    Optional<TermsOfServiceBase> termsOfService) {
    public java.util.Map<String, Object> toJson() {
        java.util.Map<String, Object> _m = new java.util.LinkedHashMap<>();
        if (isAccepted().isPresent()) { _m.put("is_accepted", isAccepted().value()); }
        else if (isAccepted().isNull()) { _m.put("is_accepted", null); }
        termsOfService().ifPresent(_v -> _m.put("terms_of_service", (_v == null ? null : _v.toJson())));
        return _m;
    }

    public static AcceptanceRequirementsStatusTermsOfServiceRequirement fromJson(Object _json) {
        java.util.Map<String, Object> _m = dev.unofficialbox.core.Json.asObject(_json);
        return new AcceptanceRequirementsStatusTermsOfServiceRequirement(
            !_m.containsKey("is_accepted") ? dev.unofficialbox.core.Tristate.<Boolean>absent() : (_m.get("is_accepted") == null ? dev.unofficialbox.core.Tristate.<Boolean>ofNull() : dev.unofficialbox.core.Tristate.of(dev.unofficialbox.core.Json.asBoolean(_m.get("is_accepted")))),
            (!_m.containsKey("terms_of_service") || _m.get("terms_of_service") == null) ? java.util.Optional.<TermsOfServiceBase>empty() : java.util.Optional.of((_m.get("terms_of_service") == null ? null : TermsOfServiceBase.fromJson(_m.get("terms_of_service"))))
        );
    }

    /** A fluent builder; unset optional fields default to empty. */
    public static Builder builder() {
        return new Builder();
    }

    public static final class Builder {
        private Tristate<Boolean> isAccepted;
        private Optional<TermsOfServiceBase> termsOfService = java.util.Optional.empty();

        public Builder isAccepted(Tristate<Boolean> isAccepted) {
            this.isAccepted = isAccepted;
            return this;
        }
        public Builder termsOfService(TermsOfServiceBase termsOfService) {
            this.termsOfService = java.util.Optional.ofNullable(termsOfService);
            return this;
        }

        public AcceptanceRequirementsStatusTermsOfServiceRequirement build() {
            return new AcceptanceRequirementsStatusTermsOfServiceRequirement(
                isAccepted,
                termsOfService
            );
        }
    }
}
