// Code generated by box-gantry 0.1.0 (spec ee7d55aedefe2fa0) for Box API 2024.0. DO NOT EDIT.
package dev.unofficialbox.model.schemas;

import module java.base;

public record AiAgentInfoModels(
    Optional<String> name,
    Optional<String> provider,
    Optional<String> supportedPurpose) {
    public java.util.Map<String, Object> toJson() {
        java.util.Map<String, Object> _m = new java.util.LinkedHashMap<>();
        name().ifPresent(_v -> _m.put("name", _v));
        provider().ifPresent(_v -> _m.put("provider", _v));
        supportedPurpose().ifPresent(_v -> _m.put("supported_purpose", _v));
        return _m;
    }

    public static AiAgentInfoModels fromJson(Object _json) {
        java.util.Map<String, Object> _m = dev.unofficialbox.core.Json.asObject(_json);
        return new AiAgentInfoModels(
            (!_m.containsKey("name") || _m.get("name") == null) ? java.util.Optional.<String>empty() : java.util.Optional.of(dev.unofficialbox.core.Json.asString(_m.get("name"))),
            (!_m.containsKey("provider") || _m.get("provider") == null) ? java.util.Optional.<String>empty() : java.util.Optional.of(dev.unofficialbox.core.Json.asString(_m.get("provider"))),
            (!_m.containsKey("supported_purpose") || _m.get("supported_purpose") == null) ? java.util.Optional.<String>empty() : java.util.Optional.of(dev.unofficialbox.core.Json.asString(_m.get("supported_purpose")))
        );
    }
}
