// Code generated by box-gantry 0.1.0 (spec ee7d55aedefe2fa0) for Box API 2024.0. DO NOT EDIT.
package dev.unofficialbox.model.schemas;

public record AiExtractResponse() {
    public java.util.Map<String, Object> toJson() {
        java.util.Map<String, Object> _m = new java.util.LinkedHashMap<>();
        return _m;
    }

    public static AiExtractResponse fromJson(Object _json) {
        return new AiExtractResponse();
    }

    /** A fluent builder; unset optional fields default to empty. */
    public static Builder builder() {
        return new Builder();
    }

    public static final class Builder {
        public AiExtractResponse build() {
            return new AiExtractResponse();
        }
    }
}
