// Code generated by box-gantry 0.1.0 (spec ee7d55aedefe2fa0) for Box API 2024.0. DO NOT EDIT.
package dev.unofficialbox.model.schemas;

import module java.base;

public record AiExtractStructuredFields(
    String key,
    Optional<String> description,
    Optional<String> displayName,
    Optional<String> prompt,
    Optional<String> type,
    Optional<List<FieldsOptions>> options,
    Optional<List<AiExtractSubField>> fields,
    Optional<String> taxonomyKey,
    Optional<String> namespace,
    Optional<AiOptionsRules> optionsRules) {
    public java.util.Map<String, Object> toJson() {
        java.util.Map<String, Object> _m = new java.util.LinkedHashMap<>();
        _m.put("key", key());
        description().ifPresent(_v -> _m.put("description", _v));
        displayName().ifPresent(_v -> _m.put("displayName", _v));
        prompt().ifPresent(_v -> _m.put("prompt", _v));
        type().ifPresent(_v -> _m.put("type", _v));
        options().ifPresent(_v -> _m.put("options", dev.unofficialbox.core.Json.encodeList(_v, _x0 -> (_x0 == null ? null : _x0.toJson()))));
        fields().ifPresent(_v -> _m.put("fields", dev.unofficialbox.core.Json.encodeList(_v, _x0 -> (_x0 == null ? null : _x0.toJson()))));
        taxonomyKey().ifPresent(_v -> _m.put("taxonomy_key", _v));
        namespace().ifPresent(_v -> _m.put("namespace", _v));
        optionsRules().ifPresent(_v -> _m.put("options_rules", (_v == null ? null : _v.toJson())));
        return _m;
    }

    public static AiExtractStructuredFields fromJson(Object _json) {
        java.util.Map<String, Object> _m = dev.unofficialbox.core.Json.asObject(_json);
        return new AiExtractStructuredFields(
            dev.unofficialbox.core.Json.asString(_m.get("key")),
            (!_m.containsKey("description") || _m.get("description") == null) ? java.util.Optional.<String>empty() : java.util.Optional.of(dev.unofficialbox.core.Json.asString(_m.get("description"))),
            (!_m.containsKey("displayName") || _m.get("displayName") == null) ? java.util.Optional.<String>empty() : java.util.Optional.of(dev.unofficialbox.core.Json.asString(_m.get("displayName"))),
            (!_m.containsKey("prompt") || _m.get("prompt") == null) ? java.util.Optional.<String>empty() : java.util.Optional.of(dev.unofficialbox.core.Json.asString(_m.get("prompt"))),
            (!_m.containsKey("type") || _m.get("type") == null) ? java.util.Optional.<String>empty() : java.util.Optional.of(dev.unofficialbox.core.Json.asString(_m.get("type"))),
            (!_m.containsKey("options") || _m.get("options") == null) ? java.util.Optional.<List<FieldsOptions>>empty() : java.util.Optional.of(dev.unofficialbox.core.Json.decodeList(_m.get("options"), _x0 -> (_x0 == null ? null : FieldsOptions.fromJson(_x0)))),
            (!_m.containsKey("fields") || _m.get("fields") == null) ? java.util.Optional.<List<AiExtractSubField>>empty() : java.util.Optional.of(dev.unofficialbox.core.Json.decodeList(_m.get("fields"), _x0 -> (_x0 == null ? null : AiExtractSubField.fromJson(_x0)))),
            (!_m.containsKey("taxonomy_key") || _m.get("taxonomy_key") == null) ? java.util.Optional.<String>empty() : java.util.Optional.of(dev.unofficialbox.core.Json.asString(_m.get("taxonomy_key"))),
            (!_m.containsKey("namespace") || _m.get("namespace") == null) ? java.util.Optional.<String>empty() : java.util.Optional.of(dev.unofficialbox.core.Json.asString(_m.get("namespace"))),
            (!_m.containsKey("options_rules") || _m.get("options_rules") == null) ? java.util.Optional.<AiOptionsRules>empty() : java.util.Optional.of((_m.get("options_rules") == null ? null : AiOptionsRules.fromJson(_m.get("options_rules"))))
        );
    }

    /** A fluent builder; unset optional fields default to empty. */
    public static Builder builder() {
        return new Builder();
    }

    public static final class Builder {
        private String key;
        private Optional<String> description = java.util.Optional.empty();
        private Optional<String> displayName = java.util.Optional.empty();
        private Optional<String> prompt = java.util.Optional.empty();
        private Optional<String> type = java.util.Optional.empty();
        private Optional<List<FieldsOptions>> options = java.util.Optional.empty();
        private Optional<List<AiExtractSubField>> fields = java.util.Optional.empty();
        private Optional<String> taxonomyKey = java.util.Optional.empty();
        private Optional<String> namespace = java.util.Optional.empty();
        private Optional<AiOptionsRules> optionsRules = java.util.Optional.empty();

        public Builder key(String key) {
            this.key = key;
            return this;
        }
        public Builder description(String description) {
            this.description = java.util.Optional.ofNullable(description);
            return this;
        }
        public Builder displayName(String displayName) {
            this.displayName = java.util.Optional.ofNullable(displayName);
            return this;
        }
        public Builder prompt(String prompt) {
            this.prompt = java.util.Optional.ofNullable(prompt);
            return this;
        }
        public Builder type(String type) {
            this.type = java.util.Optional.ofNullable(type);
            return this;
        }
        public Builder options(List<FieldsOptions> options) {
            this.options = java.util.Optional.ofNullable(options);
            return this;
        }
        public Builder fields(List<AiExtractSubField> fields) {
            this.fields = java.util.Optional.ofNullable(fields);
            return this;
        }
        public Builder taxonomyKey(String taxonomyKey) {
            this.taxonomyKey = java.util.Optional.ofNullable(taxonomyKey);
            return this;
        }
        public Builder namespace(String namespace) {
            this.namespace = java.util.Optional.ofNullable(namespace);
            return this;
        }
        public Builder optionsRules(AiOptionsRules optionsRules) {
            this.optionsRules = java.util.Optional.ofNullable(optionsRules);
            return this;
        }

        public AiExtractStructuredFields build() {
            return new AiExtractStructuredFields(
                key,
                description,
                displayName,
                prompt,
                type,
                options,
                fields,
                taxonomyKey,
                namespace,
                optionsRules
            );
        }
    }
}
