// Code generated by box-gantry 0.1.0 (spec ee7d55aedefe2fa0) for Box API 2024.0. DO NOT EDIT.
package dev.unofficialbox.model.schemas;

import module java.base;

public record AiExtract(String prompt, List<AiItemBase> items, Optional<AiExtractAgent> aiAgent) {
    public java.util.Map<String, Object> toJson() {
        java.util.Map<String, Object> _m = new java.util.LinkedHashMap<>();
        _m.put("prompt", prompt());
        _m.put("items", dev.unofficialbox.core.Json.encodeList(items(), _x0 -> (_x0 == null ? null : _x0.toJson())));
        aiAgent().ifPresent(_v -> _m.put("ai_agent", (_v == null ? null : _v.toJson())));
        return _m;
    }

    public static AiExtract fromJson(Object _json) {
        java.util.Map<String, Object> _m = dev.unofficialbox.core.Json.asObject(_json);
        return new AiExtract(
            dev.unofficialbox.core.Json.asString(_m.get("prompt")),
            dev.unofficialbox.core.Json.decodeList(_m.get("items"), _x0 -> (_x0 == null ? null : AiItemBase.fromJson(_x0))),
            (!_m.containsKey("ai_agent") || _m.get("ai_agent") == null) ? java.util.Optional.<AiExtractAgent>empty() : java.util.Optional.of((_m.get("ai_agent") == null ? null : AiExtractAgent.fromJson(_m.get("ai_agent"))))
        );
    }

    /** A fluent builder; unset optional fields default to empty. */
    public static Builder builder() {
        return new Builder();
    }

    public static final class Builder {
        private String prompt;
        private List<AiItemBase> items;
        private Optional<AiExtractAgent> aiAgent = java.util.Optional.empty();

        public Builder prompt(String prompt) {
            this.prompt = prompt;
            return this;
        }
        public Builder items(List<AiItemBase> items) {
            this.items = items;
            return this;
        }
        public Builder aiAgent(AiExtractAgent aiAgent) {
            this.aiAgent = java.util.Optional.ofNullable(aiAgent);
            return this;
        }

        public AiExtract build() {
            return new AiExtract(
                prompt,
                items,
                aiAgent
            );
        }
    }
}
