// Code generated by box-gantry 0.1.0 (spec ee7d55aedefe2fa0) for Box API 2024.0. DO NOT EDIT.
package dev.unofficialbox.model.schemas;

import module java.base;

public record AiExtractStructuredMetadataTemplate(
    Optional<String> templateKey,
    Optional<MetadataTemplateType> type,
    Optional<String> scope) {
    public java.util.Map<String, Object> toJson() {
        java.util.Map<String, Object> _m = new java.util.LinkedHashMap<>();
        templateKey().ifPresent(_v -> _m.put("template_key", _v));
        type().ifPresent(_v -> _m.put("type", (_v == null ? null : _v.toJson())));
        scope().ifPresent(_v -> _m.put("scope", _v));
        return _m;
    }

    public static AiExtractStructuredMetadataTemplate fromJson(Object _json) {
        java.util.Map<String, Object> _m = dev.unofficialbox.core.Json.asObject(_json);
        return new AiExtractStructuredMetadataTemplate(
            (!_m.containsKey("template_key") || _m.get("template_key") == null) ? java.util.Optional.<String>empty() : java.util.Optional.of(dev.unofficialbox.core.Json.asString(_m.get("template_key"))),
            (!_m.containsKey("type") || _m.get("type") == null) ? java.util.Optional.<MetadataTemplateType>empty() : java.util.Optional.of((_m.get("type") == null ? null : MetadataTemplateType.fromJson(_m.get("type")))),
            (!_m.containsKey("scope") || _m.get("scope") == null) ? java.util.Optional.<String>empty() : java.util.Optional.of(dev.unofficialbox.core.Json.asString(_m.get("scope")))
        );
    }

    /** A fluent builder; unset optional fields default to empty. */
    public static Builder builder() {
        return new Builder();
    }

    public static final class Builder {
        private Optional<String> templateKey = java.util.Optional.empty();
        private Optional<MetadataTemplateType> type = java.util.Optional.empty();
        private Optional<String> scope = java.util.Optional.empty();

        public Builder templateKey(String templateKey) {
            this.templateKey = java.util.Optional.ofNullable(templateKey);
            return this;
        }
        public Builder type(MetadataTemplateType type) {
            this.type = java.util.Optional.ofNullable(type);
            return this;
        }
        public Builder scope(String scope) {
            this.scope = java.util.Optional.ofNullable(scope);
            return this;
        }

        public AiExtractStructuredMetadataTemplate build() {
            return new AiExtractStructuredMetadataTemplate(
                templateKey,
                type,
                scope
            );
        }
    }
}
