// Code generated by box-gantry 0.1.0 (spec ee7d55aedefe2fa0) for Box API 2024.0. DO NOT EDIT.
package dev.unofficialbox.model.schemas;

import dev.unofficialbox.core.Tristate;

public record AiLlmEndpointParamsGoogle(
    AiLlmEndpointParamsGoogleType type,
    Tristate<Double> temperature,
    Tristate<Double> topP,
    Tristate<Double> topK) implements AiLlmEndpointParams {
    public java.util.Map<String, Object> toJson() {
        java.util.Map<String, Object> _m = new java.util.LinkedHashMap<>();
        _m.put("type", (type() == null ? null : type().toJson()));
        if (temperature().isPresent()) { _m.put("temperature", temperature().value()); }
        else if (temperature().isNull()) { _m.put("temperature", null); }
        if (topP().isPresent()) { _m.put("top_p", topP().value()); }
        else if (topP().isNull()) { _m.put("top_p", null); }
        if (topK().isPresent()) { _m.put("top_k", topK().value()); }
        else if (topK().isNull()) { _m.put("top_k", null); }
        return _m;
    }

    public static AiLlmEndpointParamsGoogle fromJson(Object _json) {
        java.util.Map<String, Object> _m = dev.unofficialbox.core.Json.asObject(_json);
        return new AiLlmEndpointParamsGoogle(
            (_m.get("type") == null ? null : AiLlmEndpointParamsGoogleType.fromJson(_m.get("type"))),
            !_m.containsKey("temperature") ? dev.unofficialbox.core.Tristate.<Double>absent() : (_m.get("temperature") == null ? dev.unofficialbox.core.Tristate.<Double>ofNull() : dev.unofficialbox.core.Tristate.of(dev.unofficialbox.core.Json.asDouble(_m.get("temperature")))),
            !_m.containsKey("top_p") ? dev.unofficialbox.core.Tristate.<Double>absent() : (_m.get("top_p") == null ? dev.unofficialbox.core.Tristate.<Double>ofNull() : dev.unofficialbox.core.Tristate.of(dev.unofficialbox.core.Json.asDouble(_m.get("top_p")))),
            !_m.containsKey("top_k") ? dev.unofficialbox.core.Tristate.<Double>absent() : (_m.get("top_k") == null ? dev.unofficialbox.core.Tristate.<Double>ofNull() : dev.unofficialbox.core.Tristate.of(dev.unofficialbox.core.Json.asDouble(_m.get("top_k"))))
        );
    }

    /** A fluent builder; unset optional fields default to empty. */
    public static Builder builder() {
        return new Builder();
    }

    public static final class Builder {
        private AiLlmEndpointParamsGoogleType type;
        private Tristate<Double> temperature;
        private Tristate<Double> topP;
        private Tristate<Double> topK;

        public Builder type(AiLlmEndpointParamsGoogleType type) {
            this.type = type;
            return this;
        }
        public Builder temperature(Tristate<Double> temperature) {
            this.temperature = temperature;
            return this;
        }
        public Builder topP(Tristate<Double> topP) {
            this.topP = topP;
            return this;
        }
        public Builder topK(Tristate<Double> topK) {
            this.topK = topK;
            return this;
        }

        public AiLlmEndpointParamsGoogle build() {
            return new AiLlmEndpointParamsGoogle(
                type,
                temperature,
                topP,
                topK
            );
        }
    }
}
