// Code generated by box-gantry 0.1.0 (spec ee7d55aedefe2fa0) for Box API 2024.0. DO NOT EDIT.
package dev.unofficialbox.model.schemas;

import module java.base;
import dev.unofficialbox.core.Tristate;

public record AiStudioAgentTextGenResponse(
    AiAgentTextGenType type,
    String accessState,
    String description,
    Tristate<String> customInstructions,
    Optional<List<String>> suggestedQuestions,
    Optional<AiStudioAgentBasicGenToolResponse> basicGen) {
    public java.util.Map<String, Object> toJson() {
        java.util.Map<String, Object> _m = new java.util.LinkedHashMap<>();
        _m.put("type", (type() == null ? null : type().toJson()));
        _m.put("access_state", accessState());
        _m.put("description", description());
        if (customInstructions().isPresent()) { _m.put("custom_instructions", customInstructions().value()); }
        else if (customInstructions().isNull()) { _m.put("custom_instructions", null); }
        suggestedQuestions().ifPresent(_v -> _m.put("suggested_questions", _v));
        basicGen().ifPresent(_v -> _m.put("basic_gen", (_v == null ? null : _v.toJson())));
        return _m;
    }

    public static AiStudioAgentTextGenResponse fromJson(Object _json) {
        java.util.Map<String, Object> _m = dev.unofficialbox.core.Json.asObject(_json);
        return new AiStudioAgentTextGenResponse(
            (_m.get("type") == null ? null : AiAgentTextGenType.fromJson(_m.get("type"))),
            dev.unofficialbox.core.Json.asString(_m.get("access_state")),
            dev.unofficialbox.core.Json.asString(_m.get("description")),
            !_m.containsKey("custom_instructions") ? dev.unofficialbox.core.Tristate.<String>absent() : (_m.get("custom_instructions") == null ? dev.unofficialbox.core.Tristate.<String>ofNull() : dev.unofficialbox.core.Tristate.of(dev.unofficialbox.core.Json.asString(_m.get("custom_instructions")))),
            (!_m.containsKey("suggested_questions") || _m.get("suggested_questions") == null) ? java.util.Optional.<List<String>>empty() : java.util.Optional.of(dev.unofficialbox.core.Json.decodeList(_m.get("suggested_questions"), _x0 -> dev.unofficialbox.core.Json.asString(_x0))),
            (!_m.containsKey("basic_gen") || _m.get("basic_gen") == null) ? java.util.Optional.<AiStudioAgentBasicGenToolResponse>empty() : java.util.Optional.of((_m.get("basic_gen") == null ? null : AiStudioAgentBasicGenToolResponse.fromJson(_m.get("basic_gen"))))
        );
    }
}
