// Code generated by box-gantry 0.1.0 (spec ee7d55aedefe2fa0) for Box API 2024.0. DO NOT EDIT.
package dev.unofficialbox.model.schemas;

import module java.base;

public record AiTaxonomyFileReference(
    Optional<AiCitationType> type,
    Optional<String> taxonomyKey,
    Optional<String> id) implements AiTaxonomySource {
    public java.util.Map<String, Object> toJson() {
        java.util.Map<String, Object> _m = new java.util.LinkedHashMap<>();
        type().ifPresent(_v -> _m.put("type", (_v == null ? null : _v.toJson())));
        taxonomyKey().ifPresent(_v -> _m.put("taxonomy_key", _v));
        id().ifPresent(_v -> _m.put("id", _v));
        return _m;
    }

    public static AiTaxonomyFileReference fromJson(Object _json) {
        java.util.Map<String, Object> _m = dev.unofficialbox.core.Json.asObject(_json);
        return new AiTaxonomyFileReference(
            (!_m.containsKey("type") || _m.get("type") == null) ? java.util.Optional.<AiCitationType>empty() : java.util.Optional.of((_m.get("type") == null ? null : AiCitationType.fromJson(_m.get("type")))),
            (!_m.containsKey("taxonomy_key") || _m.get("taxonomy_key") == null) ? java.util.Optional.<String>empty() : java.util.Optional.of(dev.unofficialbox.core.Json.asString(_m.get("taxonomy_key"))),
            (!_m.containsKey("id") || _m.get("id") == null) ? java.util.Optional.<String>empty() : java.util.Optional.of(dev.unofficialbox.core.Json.asString(_m.get("id")))
        );
    }

    /** A fluent builder; unset optional fields default to empty. */
    public static Builder builder() {
        return new Builder();
    }

    public static final class Builder {
        private Optional<AiCitationType> type = java.util.Optional.empty();
        private Optional<String> taxonomyKey = java.util.Optional.empty();
        private Optional<String> id = java.util.Optional.empty();

        public Builder type(AiCitationType type) {
            this.type = java.util.Optional.ofNullable(type);
            return this;
        }
        public Builder taxonomyKey(String taxonomyKey) {
            this.taxonomyKey = java.util.Optional.ofNullable(taxonomyKey);
            return this;
        }
        public Builder id(String id) {
            this.id = java.util.Optional.ofNullable(id);
            return this;
        }

        public AiTaxonomyFileReference build() {
            return new AiTaxonomyFileReference(
                type,
                taxonomyKey,
                id
            );
        }
    }
}
