// Code generated by box-gantry 0.1.0 (spec ee7d55aedefe2fa0) for Box API 2024.0. DO NOT EDIT.
package dev.unofficialbox.model.schemas;

import module java.base;

public record AppItemEventSource(
    String id,
    AppItemType type,
    String appItemType,
    Optional<UserMini> user,
    Optional<GroupMini> group) {
    public java.util.Map<String, Object> toJson() {
        java.util.Map<String, Object> _m = new java.util.LinkedHashMap<>();
        _m.put("id", id());
        _m.put("type", (type() == null ? null : type().toJson()));
        _m.put("app_item_type", appItemType());
        user().ifPresent(_v -> _m.put("user", (_v == null ? null : _v.toJson())));
        group().ifPresent(_v -> _m.put("group", (_v == null ? null : _v.toJson())));
        return _m;
    }

    public static AppItemEventSource fromJson(Object _json) {
        java.util.Map<String, Object> _m = dev.unofficialbox.core.Json.asObject(_json);
        return new AppItemEventSource(
            dev.unofficialbox.core.Json.asString(_m.get("id")),
            (_m.get("type") == null ? null : AppItemType.fromJson(_m.get("type"))),
            dev.unofficialbox.core.Json.asString(_m.get("app_item_type")),
            (!_m.containsKey("user") || _m.get("user") == null) ? java.util.Optional.<UserMini>empty() : java.util.Optional.of((_m.get("user") == null ? null : UserMini.fromJson(_m.get("user")))),
            (!_m.containsKey("group") || _m.get("group") == null) ? java.util.Optional.<GroupMini>empty() : java.util.Optional.of((_m.get("group") == null ? null : GroupMini.fromJson(_m.get("group"))))
        );
    }

    /** A fluent builder; unset optional fields default to empty. */
    public static Builder builder() {
        return new Builder();
    }

    public static final class Builder {
        private String id;
        private AppItemType type;
        private String appItemType;
        private Optional<UserMini> user = java.util.Optional.empty();
        private Optional<GroupMini> group = java.util.Optional.empty();

        public Builder id(String id) {
            this.id = id;
            return this;
        }
        public Builder type(AppItemType type) {
            this.type = type;
            return this;
        }
        public Builder appItemType(String appItemType) {
            this.appItemType = appItemType;
            return this;
        }
        public Builder user(UserMini user) {
            this.user = java.util.Optional.ofNullable(user);
            return this;
        }
        public Builder group(GroupMini group) {
            this.group = java.util.Optional.ofNullable(group);
            return this;
        }

        public AppItemEventSource build() {
            return new AppItemEventSource(
                id,
                type,
                appItemType,
                user,
                group
            );
        }
    }
}
