// Code generated by box-gantry 0.1.0 (spec ee7d55aedefe2fa0) for Box API 2026.0. DO NOT EDIT.
package dev.unofficialbox.model.schemas;

public record AutomateWorkflowActionType(String value) {
    public static final AutomateWorkflowActionType WORKFLOW_ACTION = new AutomateWorkflowActionType("workflow_action");

    public String toJson() {
        return value;
    }

    public static AutomateWorkflowActionType fromJson(Object _json) {
        return new AutomateWorkflowActionType(dev.unofficialbox.core.Json.asString(_json));
    }
}
