// Code generated by box-gantry 0.1.0 (spec ee7d55aedefe2fa0) for Box API 2026.0. DO NOT EDIT.
package dev.unofficialbox.model.schemas;

public record AutomateWorkflowReferenceType(String value) {
    public static final AutomateWorkflowReferenceType WORKFLOW = new AutomateWorkflowReferenceType("workflow");

    public String toJson() {
        return value;
    }

    public static AutomateWorkflowReferenceType fromJson(Object _json) {
        return new AutomateWorkflowReferenceType(dev.unofficialbox.core.Json.asString(_json));
    }
}
