// Code generated by box-gantry 0.1.0 (spec ee7d55aedefe2fa0) for Box API 2024.0. DO NOT EDIT.
package dev.unofficialbox.model.schemas;

public record ClassificationUpdateRequest2(
    PutUpdateOp op,
    FieldsKey fieldKey,
    String enumOptionKey,
    PutAddData data) {
    public java.util.Map<String, Object> toJson() {
        java.util.Map<String, Object> _m = new java.util.LinkedHashMap<>();
        _m.put("op", (op() == null ? null : op().toJson()));
        _m.put("fieldKey", (fieldKey() == null ? null : fieldKey().toJson()));
        _m.put("enumOptionKey", enumOptionKey());
        _m.put("data", (data() == null ? null : data().toJson()));
        return _m;
    }

    public static ClassificationUpdateRequest2 fromJson(Object _json) {
        java.util.Map<String, Object> _m = dev.unofficialbox.core.Json.asObject(_json);
        return new ClassificationUpdateRequest2(
            (_m.get("op") == null ? null : PutUpdateOp.fromJson(_m.get("op"))),
            (_m.get("fieldKey") == null ? null : FieldsKey.fromJson(_m.get("fieldKey"))),
            dev.unofficialbox.core.Json.asString(_m.get("enumOptionKey")),
            (_m.get("data") == null ? null : PutAddData.fromJson(_m.get("data")))
        );
    }
}
