// Code generated by box-gantry 0.1.0 (spec ee7d55aedefe2fa0) for Box API 2024.0. DO NOT EDIT.
package dev.unofficialbox.model.schemas;

public record CollaboratorVariableVariableType(String value) {
    public static final CollaboratorVariableVariableType USER_LIST = new CollaboratorVariableVariableType("user_list");

    public String toJson() {
        return value;
    }

    public static CollaboratorVariableVariableType fromJson(Object _json) {
        return new CollaboratorVariableVariableType(dev.unofficialbox.core.Json.asString(_json));
    }
}
