// Code generated by box-gantry 0.1.0 (spec ee7d55aedefe2fa0) for Box API 2024.0. DO NOT EDIT.
package dev.unofficialbox.model.schemas;

import module java.base;

public record CollaborationAllowlistEntry(
    Optional<String> id,
    Optional<CollaborationAllowlistEntryType> type,
    Optional<String> domain,
    Optional<CollaborationAllowlistEntryDirection> direction,
    Optional<CollaborationAllowlistEntryEnterprise> enterprise,
    Optional<OffsetDateTime> createdAt) {
    public java.util.Map<String, Object> toJson() {
        java.util.Map<String, Object> _m = new java.util.LinkedHashMap<>();
        id().ifPresent(_v -> _m.put("id", _v));
        type().ifPresent(_v -> _m.put("type", (_v == null ? null : _v.toJson())));
        domain().ifPresent(_v -> _m.put("domain", _v));
        direction().ifPresent(_v -> _m.put("direction", (_v == null ? null : _v.toJson())));
        enterprise().ifPresent(_v -> _m.put("enterprise", (_v == null ? null : _v.toJson())));
        createdAt().ifPresent(_v -> _m.put("created_at", (_v == null ? null : _v.toString())));
        return _m;
    }

    public static CollaborationAllowlistEntry fromJson(Object _json) {
        java.util.Map<String, Object> _m = dev.unofficialbox.core.Json.asObject(_json);
        return new CollaborationAllowlistEntry(
            (!_m.containsKey("id") || _m.get("id") == null) ? java.util.Optional.<String>empty() : java.util.Optional.of(dev.unofficialbox.core.Json.asString(_m.get("id"))),
            (!_m.containsKey("type") || _m.get("type") == null) ? java.util.Optional.<CollaborationAllowlistEntryType>empty() : java.util.Optional.of((_m.get("type") == null ? null : CollaborationAllowlistEntryType.fromJson(_m.get("type")))),
            (!_m.containsKey("domain") || _m.get("domain") == null) ? java.util.Optional.<String>empty() : java.util.Optional.of(dev.unofficialbox.core.Json.asString(_m.get("domain"))),
            (!_m.containsKey("direction") || _m.get("direction") == null) ? java.util.Optional.<CollaborationAllowlistEntryDirection>empty() : java.util.Optional.of((_m.get("direction") == null ? null : CollaborationAllowlistEntryDirection.fromJson(_m.get("direction")))),
            (!_m.containsKey("enterprise") || _m.get("enterprise") == null) ? java.util.Optional.<CollaborationAllowlistEntryEnterprise>empty() : java.util.Optional.of((_m.get("enterprise") == null ? null : CollaborationAllowlistEntryEnterprise.fromJson(_m.get("enterprise")))),
            (!_m.containsKey("created_at") || _m.get("created_at") == null) ? java.util.Optional.<OffsetDateTime>empty() : java.util.Optional.of((_m.get("created_at") == null ? null : java.time.OffsetDateTime.parse(dev.unofficialbox.core.Json.asString(_m.get("created_at")))))
        );
    }

    /** A fluent builder; unset optional fields default to empty. */
    public static Builder builder() {
        return new Builder();
    }

    public static final class Builder {
        private Optional<String> id = java.util.Optional.empty();
        private Optional<CollaborationAllowlistEntryType> type = java.util.Optional.empty();
        private Optional<String> domain = java.util.Optional.empty();
        private Optional<CollaborationAllowlistEntryDirection> direction = java.util.Optional.empty();
        private Optional<CollaborationAllowlistEntryEnterprise> enterprise = java.util.Optional.empty();
        private Optional<OffsetDateTime> createdAt = java.util.Optional.empty();

        public Builder id(String id) {
            this.id = java.util.Optional.ofNullable(id);
            return this;
        }
        public Builder type(CollaborationAllowlistEntryType type) {
            this.type = java.util.Optional.ofNullable(type);
            return this;
        }
        public Builder domain(String domain) {
            this.domain = java.util.Optional.ofNullable(domain);
            return this;
        }
        public Builder direction(CollaborationAllowlistEntryDirection direction) {
            this.direction = java.util.Optional.ofNullable(direction);
            return this;
        }
        public Builder enterprise(CollaborationAllowlistEntryEnterprise enterprise) {
            this.enterprise = java.util.Optional.ofNullable(enterprise);
            return this;
        }
        public Builder createdAt(OffsetDateTime createdAt) {
            this.createdAt = java.util.Optional.ofNullable(createdAt);
            return this;
        }

        public CollaborationAllowlistEntry build() {
            return new CollaborationAllowlistEntry(
                id,
                type,
                domain,
                direction,
                enterprise,
                createdAt
            );
        }
    }
}
