// Code generated by box-gantry 0.1.0 (spec ee7d55aedefe2fa0) for Box API 2024.0. DO NOT EDIT.
package dev.unofficialbox.model.schemas;

import module java.base;

public record CollaboratorVariable(
    CollaboratorVariableType type,
    CollaboratorVariableVariableType variableType,
    List<CollaboratorVariableVariableValue> variableValue) {
    public java.util.Map<String, Object> toJson() {
        java.util.Map<String, Object> _m = new java.util.LinkedHashMap<>();
        _m.put("type", (type() == null ? null : type().toJson()));
        _m.put("variable_type", (variableType() == null ? null : variableType().toJson()));
        _m.put("variable_value", dev.unofficialbox.core.Json.encodeList(variableValue(), _x0 -> (_x0 == null ? null : _x0.toJson())));
        return _m;
    }

    public static CollaboratorVariable fromJson(Object _json) {
        java.util.Map<String, Object> _m = dev.unofficialbox.core.Json.asObject(_json);
        return new CollaboratorVariable(
            (_m.get("type") == null ? null : CollaboratorVariableType.fromJson(_m.get("type"))),
            (_m.get("variable_type") == null ? null : CollaboratorVariableVariableType.fromJson(_m.get("variable_type"))),
            dev.unofficialbox.core.Json.decodeList(_m.get("variable_value"), _x0 -> (_x0 == null ? null : CollaboratorVariableVariableValue.fromJson(_x0)))
        );
    }

    /** A fluent builder; unset optional fields default to empty. */
    public static Builder builder() {
        return new Builder();
    }

    public static final class Builder {
        private CollaboratorVariableType type;
        private CollaboratorVariableVariableType variableType;
        private List<CollaboratorVariableVariableValue> variableValue;

        public Builder type(CollaboratorVariableType type) {
            this.type = type;
            return this;
        }
        public Builder variableType(CollaboratorVariableVariableType variableType) {
            this.variableType = variableType;
            return this;
        }
        public Builder variableValue(List<CollaboratorVariableVariableValue> variableValue) {
            this.variableValue = variableValue;
            return this;
        }

        public CollaboratorVariable build() {
            return new CollaboratorVariable(
                type,
                variableType,
                variableValue
            );
        }
    }
}
