// Code generated by box-gantry 0.1.0 (spec ee7d55aedefe2fa0) for Box API 2024.0. DO NOT EDIT.
package dev.unofficialbox.model.schemas;

import module java.base;

public record CommentCreateRequest(String message, Optional<String> taggedMessage, PostItem item) {
    public java.util.Map<String, Object> toJson() {
        java.util.Map<String, Object> _m = new java.util.LinkedHashMap<>();
        _m.put("message", message());
        taggedMessage().ifPresent(_v -> _m.put("tagged_message", _v));
        _m.put("item", (item() == null ? null : item().toJson()));
        return _m;
    }

    public static CommentCreateRequest fromJson(Object _json) {
        java.util.Map<String, Object> _m = dev.unofficialbox.core.Json.asObject(_json);
        return new CommentCreateRequest(
            dev.unofficialbox.core.Json.asString(_m.get("message")),
            (!_m.containsKey("tagged_message") || _m.get("tagged_message") == null) ? java.util.Optional.<String>empty() : java.util.Optional.of(dev.unofficialbox.core.Json.asString(_m.get("tagged_message"))),
            (_m.get("item") == null ? null : PostItem.fromJson(_m.get("item")))
        );
    }
}
