// Code generated by box-gantry 0.1.0 (spec ee7d55aedefe2fa0) for Box API 2025.0. DO NOT EDIT.
package dev.unofficialbox.model.schemas;

public record DocGenJobStatus(String value) {
    public static final DocGenJobStatus SUBMITTED = new DocGenJobStatus("submitted");
    public static final DocGenJobStatus COMPLETED = new DocGenJobStatus("completed");
    public static final DocGenJobStatus FAILED = new DocGenJobStatus("failed");
    public static final DocGenJobStatus COMPLETED_WITH_ERROR = new DocGenJobStatus("completed_with_error");
    public static final DocGenJobStatus PENDING = new DocGenJobStatus("pending");

    public String toJson() {
        return value;
    }

    public static DocGenJobStatus fromJson(Object _json) {
        return new DocGenJobStatus(dev.unofficialbox.core.Json.asString(_json));
    }
}
