// Code generated by box-gantry 0.1.0 (spec ee7d55aedefe2fa0) for Box API 2025.0. DO NOT EDIT.
package dev.unofficialbox.model.schemas;

import module java.base;

public record DocGenTemplateBase(Optional<FileReference> file) {
    public java.util.Map<String, Object> toJson() {
        java.util.Map<String, Object> _m = new java.util.LinkedHashMap<>();
        file().ifPresent(_v -> _m.put("file", (_v == null ? null : _v.toJson())));
        return _m;
    }

    public static DocGenTemplateBase fromJson(Object _json) {
        java.util.Map<String, Object> _m = dev.unofficialbox.core.Json.asObject(_json);
        return new DocGenTemplateBase(
            (!_m.containsKey("file") || _m.get("file") == null) ? java.util.Optional.<FileReference>empty() : java.util.Optional.of((_m.get("file") == null ? null : FileReference.fromJson(_m.get("file"))))
        );
    }

    /** A fluent builder; unset optional fields default to empty. */
    public static Builder builder() {
        return new Builder();
    }

    public static final class Builder {
        private Optional<FileReference> file = java.util.Optional.empty();

        public Builder file(FileReference file) {
            this.file = java.util.Optional.ofNullable(file);
            return this;
        }

        public DocGenTemplateBase build() {
            return new DocGenTemplateBase(
                file
            );
        }
    }
}
