// Code generated by box-gantry 0.1.0 (spec ee7d55aedefe2fa0) for Box API 2025.0. DO NOT EDIT.
package dev.unofficialbox.model.schemas;

public record DocGenJobType(String value) {
    public static final DocGenJobType DOCGEN_JOB = new DocGenJobType("docgen_job");

    public String toJson() {
        return value;
    }

    public static DocGenJobType fromJson(Object _json) {
        return new DocGenJobType(dev.unofficialbox.core.Json.asString(_json));
    }
}
