// Code generated by box-gantry 0.1.0 (spec ee7d55aedefe2fa0) for Box API 2025.0. DO NOT EDIT.
package dev.unofficialbox.model.schemas;

import module java.base;

public record DocGenTag(String tagContent, DocGenTagTagType tagType, List<String> jsonPaths) {
    public java.util.Map<String, Object> toJson() {
        java.util.Map<String, Object> _m = new java.util.LinkedHashMap<>();
        _m.put("tag_content", tagContent());
        _m.put("tag_type", (tagType() == null ? null : tagType().toJson()));
        _m.put("json_paths", jsonPaths());
        return _m;
    }

    public static DocGenTag fromJson(Object _json) {
        java.util.Map<String, Object> _m = dev.unofficialbox.core.Json.asObject(_json);
        return new DocGenTag(
            dev.unofficialbox.core.Json.asString(_m.get("tag_content")),
            (_m.get("tag_type") == null ? null : DocGenTagTagType.fromJson(_m.get("tag_type"))),
            dev.unofficialbox.core.Json.decodeList(_m.get("json_paths"), _x0 -> dev.unofficialbox.core.Json.asString(_x0))
        );
    }

    /** A fluent builder; unset optional fields default to empty. */
    public static Builder builder() {
        return new Builder();
    }

    public static final class Builder {
        private String tagContent;
        private DocGenTagTagType tagType;
        private List<String> jsonPaths;

        public Builder tagContent(String tagContent) {
            this.tagContent = tagContent;
            return this;
        }
        public Builder tagType(DocGenTagTagType tagType) {
            this.tagType = tagType;
            return this;
        }
        public Builder jsonPaths(List<String> jsonPaths) {
            this.jsonPaths = jsonPaths;
            return this;
        }

        public DocGenTag build() {
            return new DocGenTag(
                tagContent,
                tagType,
                jsonPaths
            );
        }
    }
}
