// Code generated by box-gantry 0.1.0 (spec ee7d55aedefe2fa0) for Box API 2025.0. DO NOT EDIT.
package dev.unofficialbox.model.schemas;

public record DocGenTemplateCreateRequest(FileReference file) {
    public java.util.Map<String, Object> toJson() {
        java.util.Map<String, Object> _m = new java.util.LinkedHashMap<>();
        _m.put("file", (file() == null ? null : file().toJson()));
        return _m;
    }

    public static DocGenTemplateCreateRequest fromJson(Object _json) {
        java.util.Map<String, Object> _m = dev.unofficialbox.core.Json.asObject(_json);
        return new DocGenTemplateCreateRequest(
            (_m.get("file") == null ? null : FileReference.fromJson(_m.get("file")))
        );
    }
}
