// Code generated by box-gantry 0.1.0 (spec ee7d55aedefe2fa0) for Box API 2024.0. DO NOT EDIT.
package dev.unofficialbox.model.schemas;

public record EmailAliasType(String value) {
    public static final EmailAliasType EMAIL_ALIAS = new EmailAliasType("email_alias");

    public String toJson() {
        return value;
    }

    public static EmailAliasType fromJson(Object _json) {
        return new EmailAliasType(dev.unofficialbox.core.Json.asString(_json));
    }
}
