// Code generated by box-gantry 0.1.0 (spec ee7d55aedefe2fa0) for Box API 2024.0. DO NOT EDIT.
package dev.unofficialbox.model.schemas;

import module java.base;

public record EmbeddingsStrategy(Optional<String> id, Optional<Long> numTokensPerChunk) {
    public java.util.Map<String, Object> toJson() {
        java.util.Map<String, Object> _m = new java.util.LinkedHashMap<>();
        id().ifPresent(_v -> _m.put("id", _v));
        numTokensPerChunk().ifPresent(_v -> _m.put("num_tokens_per_chunk", _v));
        return _m;
    }

    public static EmbeddingsStrategy fromJson(Object _json) {
        java.util.Map<String, Object> _m = dev.unofficialbox.core.Json.asObject(_json);
        return new EmbeddingsStrategy(
            (!_m.containsKey("id") || _m.get("id") == null) ? java.util.Optional.<String>empty() : java.util.Optional.of(dev.unofficialbox.core.Json.asString(_m.get("id"))),
            (!_m.containsKey("num_tokens_per_chunk") || _m.get("num_tokens_per_chunk") == null) ? java.util.Optional.<Long>empty() : java.util.Optional.of(dev.unofficialbox.core.Json.asLong(_m.get("num_tokens_per_chunk")))
        );
    }
}
