// Code generated by box-gantry 0.1.0 (spec ee7d55aedefe2fa0) for Box API 2025.0. DO NOT EDIT.
package dev.unofficialbox.model.schemas;

public record EnterpriseConfigurationUserSettings2(Object value) {
    public Object toJson() {
        return value;
    }

    public static EnterpriseConfigurationUserSettings2 fromJson(Object _json) {
        return new EnterpriseConfigurationUserSettings2(_json);
    }
}
