// Code generated by box-gantry 0.1.0 (spec ee7d55aedefe2fa0) for Box API 2025.0. DO NOT EDIT.
package dev.unofficialbox.model.schemas;

import module java.base;

public record EnterpriseConfiguration(
    Optional<String> id,
    Optional<EnterpriseConfigurationType> type,
    Optional<EnterpriseConfigurationSecurity2> security,
    Optional<EnterpriseConfigurationContentAndSharing2> contentAndSharing,
    Optional<EnterpriseConfigurationUserSettings2> userSettings,
    Optional<EnterpriseConfigurationShield2> shield) {
    public java.util.Map<String, Object> toJson() {
        java.util.Map<String, Object> _m = new java.util.LinkedHashMap<>();
        id().ifPresent(_v -> _m.put("id", _v));
        type().ifPresent(_v -> _m.put("type", (_v == null ? null : _v.toJson())));
        security().ifPresent(_v -> _m.put("security", (_v == null ? null : _v.toJson())));
        contentAndSharing().ifPresent(_v -> _m.put("content_and_sharing", (_v == null ? null : _v.toJson())));
        userSettings().ifPresent(_v -> _m.put("user_settings", (_v == null ? null : _v.toJson())));
        shield().ifPresent(_v -> _m.put("shield", (_v == null ? null : _v.toJson())));
        return _m;
    }

    public static EnterpriseConfiguration fromJson(Object _json) {
        java.util.Map<String, Object> _m = dev.unofficialbox.core.Json.asObject(_json);
        return new EnterpriseConfiguration(
            (!_m.containsKey("id") || _m.get("id") == null) ? java.util.Optional.<String>empty() : java.util.Optional.of(dev.unofficialbox.core.Json.asString(_m.get("id"))),
            (!_m.containsKey("type") || _m.get("type") == null) ? java.util.Optional.<EnterpriseConfigurationType>empty() : java.util.Optional.of((_m.get("type") == null ? null : EnterpriseConfigurationType.fromJson(_m.get("type")))),
            (!_m.containsKey("security") || _m.get("security") == null) ? java.util.Optional.<EnterpriseConfigurationSecurity2>empty() : java.util.Optional.of((_m.get("security") == null ? null : EnterpriseConfigurationSecurity2.fromJson(_m.get("security")))),
            (!_m.containsKey("content_and_sharing") || _m.get("content_and_sharing") == null) ? java.util.Optional.<EnterpriseConfigurationContentAndSharing2>empty() : java.util.Optional.of((_m.get("content_and_sharing") == null ? null : EnterpriseConfigurationContentAndSharing2.fromJson(_m.get("content_and_sharing")))),
            (!_m.containsKey("user_settings") || _m.get("user_settings") == null) ? java.util.Optional.<EnterpriseConfigurationUserSettings2>empty() : java.util.Optional.of((_m.get("user_settings") == null ? null : EnterpriseConfigurationUserSettings2.fromJson(_m.get("user_settings")))),
            (!_m.containsKey("shield") || _m.get("shield") == null) ? java.util.Optional.<EnterpriseConfigurationShield2>empty() : java.util.Optional.of((_m.get("shield") == null ? null : EnterpriseConfigurationShield2.fromJson(_m.get("shield"))))
        );
    }

    /** A fluent builder; unset optional fields default to empty. */
    public static Builder builder() {
        return new Builder();
    }

    public static final class Builder {
        private Optional<String> id = java.util.Optional.empty();
        private Optional<EnterpriseConfigurationType> type = java.util.Optional.empty();
        private Optional<EnterpriseConfigurationSecurity2> security = java.util.Optional.empty();
        private Optional<EnterpriseConfigurationContentAndSharing2> contentAndSharing = java.util.Optional.empty();
        private Optional<EnterpriseConfigurationUserSettings2> userSettings = java.util.Optional.empty();
        private Optional<EnterpriseConfigurationShield2> shield = java.util.Optional.empty();

        public Builder id(String id) {
            this.id = java.util.Optional.ofNullable(id);
            return this;
        }
        public Builder type(EnterpriseConfigurationType type) {
            this.type = java.util.Optional.ofNullable(type);
            return this;
        }
        public Builder security(EnterpriseConfigurationSecurity2 security) {
            this.security = java.util.Optional.ofNullable(security);
            return this;
        }
        public Builder contentAndSharing(EnterpriseConfigurationContentAndSharing2 contentAndSharing) {
            this.contentAndSharing = java.util.Optional.ofNullable(contentAndSharing);
            return this;
        }
        public Builder userSettings(EnterpriseConfigurationUserSettings2 userSettings) {
            this.userSettings = java.util.Optional.ofNullable(userSettings);
            return this;
        }
        public Builder shield(EnterpriseConfigurationShield2 shield) {
            this.shield = java.util.Optional.ofNullable(shield);
            return this;
        }

        public EnterpriseConfiguration build() {
            return new EnterpriseConfiguration(
                id,
                type,
                security,
                contentAndSharing,
                userSettings,
                shield
            );
        }
    }
}
