// Code generated by box-gantry 0.1.0 (spec ee7d55aedefe2fa0) for Box API 2025.0. DO NOT EDIT.
package dev.unofficialbox.model.schemas;

import module java.base;

public record EnterpriseConfigurationItem(Optional<Boolean> isUsed) {
    public java.util.Map<String, Object> toJson() {
        java.util.Map<String, Object> _m = new java.util.LinkedHashMap<>();
        isUsed().ifPresent(_v -> _m.put("is_used", _v));
        return _m;
    }

    public static EnterpriseConfigurationItem fromJson(Object _json) {
        java.util.Map<String, Object> _m = dev.unofficialbox.core.Json.asObject(_json);
        return new EnterpriseConfigurationItem(
            (!_m.containsKey("is_used") || _m.get("is_used") == null) ? java.util.Optional.<Boolean>empty() : java.util.Optional.of(dev.unofficialbox.core.Json.asBoolean(_m.get("is_used")))
        );
    }
}
