// Code generated by box-gantry 0.1.0 (spec ee7d55aedefe2fa0) for Box API 2025.0. DO NOT EDIT.
package dev.unofficialbox.model.schemas;

import module java.base;

public record EnterpriseConfigurationContentAndSharingCollaborationRestrictions(
    Optional<Boolean> isUsed,
    Optional<List<String>> value) {
    public java.util.Map<String, Object> toJson() {
        java.util.Map<String, Object> _m = new java.util.LinkedHashMap<>();
        isUsed().ifPresent(_v -> _m.put("is_used", _v));
        value().ifPresent(_v -> _m.put("value", _v));
        return _m;
    }

    public static EnterpriseConfigurationContentAndSharingCollaborationRestrictions fromJson(Object _json) {
        java.util.Map<String, Object> _m = dev.unofficialbox.core.Json.asObject(_json);
        return new EnterpriseConfigurationContentAndSharingCollaborationRestrictions(
            (!_m.containsKey("is_used") || _m.get("is_used") == null) ? java.util.Optional.<Boolean>empty() : java.util.Optional.of(dev.unofficialbox.core.Json.asBoolean(_m.get("is_used"))),
            (!_m.containsKey("value") || _m.get("value") == null) ? java.util.Optional.<List<String>>empty() : java.util.Optional.of(dev.unofficialbox.core.Json.decodeList(_m.get("value"), _x0 -> dev.unofficialbox.core.Json.asString(_x0)))
        );
    }

    /** A fluent builder; unset optional fields default to empty. */
    public static Builder builder() {
        return new Builder();
    }

    public static final class Builder {
        private Optional<Boolean> isUsed = java.util.Optional.empty();
        private Optional<List<String>> value = java.util.Optional.empty();

        public Builder isUsed(Boolean isUsed) {
            this.isUsed = java.util.Optional.ofNullable(isUsed);
            return this;
        }
        public Builder value(List<String> value) {
            this.value = java.util.Optional.ofNullable(value);
            return this;
        }

        public EnterpriseConfigurationContentAndSharingCollaborationRestrictions build() {
            return new EnterpriseConfigurationContentAndSharingCollaborationRestrictions(
                isUsed,
                value
            );
        }
    }
}
