// Code generated by box-gantry 0.1.0 (spec ee7d55aedefe2fa0) for Box API 2024.0. DO NOT EDIT.
package dev.unofficialbox.model.schemas;

import module java.base;

public record EntriesContent(Optional<String> urlTemplate) {
    public java.util.Map<String, Object> toJson() {
        java.util.Map<String, Object> _m = new java.util.LinkedHashMap<>();
        urlTemplate().ifPresent(_v -> _m.put("url_template", _v));
        return _m;
    }

    public static EntriesContent fromJson(Object _json) {
        java.util.Map<String, Object> _m = dev.unofficialbox.core.Json.asObject(_json);
        return new EntriesContent(
            (!_m.containsKey("url_template") || _m.get("url_template") == null) ? java.util.Optional.<String>empty() : java.util.Optional.of(dev.unofficialbox.core.Json.asString(_m.get("url_template")))
        );
    }
}
