// Code generated by box-gantry 0.1.0 (spec ee7d55aedefe2fa0) for Box API 2025.0. DO NOT EDIT.
package dev.unofficialbox.model.schemas;

import module java.base;

public record ExternalUsersSubmitDeleteJobResponse(List<ExternalUserDeletionResult> entries) {
    public java.util.Map<String, Object> toJson() {
        java.util.Map<String, Object> _m = new java.util.LinkedHashMap<>();
        _m.put("entries", dev.unofficialbox.core.Json.encodeList(entries(), _x0 -> (_x0 == null ? null : _x0.toJson())));
        return _m;
    }

    public static ExternalUsersSubmitDeleteJobResponse fromJson(Object _json) {
        java.util.Map<String, Object> _m = dev.unofficialbox.core.Json.asObject(_json);
        return new ExternalUsersSubmitDeleteJobResponse(
            dev.unofficialbox.core.Json.decodeList(_m.get("entries"), _x0 -> (_x0 == null ? null : ExternalUserDeletionResult.fromJson(_x0)))
        );
    }

    /** A fluent builder; unset optional fields default to empty. */
    public static Builder builder() {
        return new Builder();
    }

    public static final class Builder {
        private List<ExternalUserDeletionResult> entries;

        public Builder entries(List<ExternalUserDeletionResult> entries) {
            this.entries = entries;
            return this;
        }

        public ExternalUsersSubmitDeleteJobResponse build() {
            return new ExternalUsersSubmitDeleteJobResponse(
                entries
            );
        }
    }
}
