// Code generated by box-gantry 0.1.0 (spec ee7d55aedefe2fa0) for Box API 2024.0. DO NOT EDIT.
package dev.unofficialbox.model.schemas;

public record FieldsType3(String value) {
    public static final FieldsType3 STRING = new FieldsType3("string");
    public static final FieldsType3 FLOAT = new FieldsType3("float");
    public static final FieldsType3 DATE = new FieldsType3("date");
    public static final FieldsType3 ENUM = new FieldsType3("enum");
    public static final FieldsType3 MULTISELECT = new FieldsType3("multiSelect");
    public static final FieldsType3 TAXONOMY = new FieldsType3("taxonomy");

    public String toJson() {
        return value;
    }

    public static FieldsType3 fromJson(Object _json) {
        return new FieldsType3(dev.unofficialbox.core.Json.asString(_json));
    }
}
