// Code generated by box-gantry 0.1.0 (spec ee7d55aedefe2fa0) for Box API 2024.0. DO NOT EDIT.
package dev.unofficialbox.model.schemas;

import module java.base;

public record FileVersionMini(String id, FileVersionType type, Optional<String> sha1) {
    public java.util.Map<String, Object> toJson() {
        java.util.Map<String, Object> _m = new java.util.LinkedHashMap<>();
        _m.put("id", id());
        _m.put("type", (type() == null ? null : type().toJson()));
        sha1().ifPresent(_v -> _m.put("sha1", _v));
        return _m;
    }

    public static FileVersionMini fromJson(Object _json) {
        java.util.Map<String, Object> _m = dev.unofficialbox.core.Json.asObject(_json);
        return new FileVersionMini(
            dev.unofficialbox.core.Json.asString(_m.get("id")),
            (_m.get("type") == null ? null : FileVersionType.fromJson(_m.get("type"))),
            (!_m.containsKey("sha1") || _m.get("sha1") == null) ? java.util.Optional.<String>empty() : java.util.Optional.of(dev.unofficialbox.core.Json.asString(_m.get("sha1")))
        );
    }

    /** A fluent builder; unset optional fields default to empty. */
    public static Builder builder() {
        return new Builder();
    }

    public static final class Builder {
        private String id;
        private FileVersionType type;
        private Optional<String> sha1 = java.util.Optional.empty();

        public Builder id(String id) {
            this.id = id;
            return this;
        }
        public Builder type(FileVersionType type) {
            this.type = type;
            return this;
        }
        public Builder sha1(String sha1) {
            this.sha1 = java.util.Optional.ofNullable(sha1);
            return this;
        }

        public FileVersionMini build() {
            return new FileVersionMini(
                id,
                type,
                sha1
            );
        }
    }
}
