// Code generated by box-gantry 0.1.0 (spec ee7d55aedefe2fa0) for Box API 2024.0. DO NOT EDIT.
package dev.unofficialbox.model.schemas;

import module java.base;

public record FileRequestUpdateRequest(
    Optional<String> title,
    Optional<String> description,
    Optional<FileRequestStatus> status,
    Optional<Boolean> isEmailRequired,
    Optional<Boolean> isDescriptionRequired,
    Optional<OffsetDateTime> expiresAt) {
    public java.util.Map<String, Object> toJson() {
        java.util.Map<String, Object> _m = new java.util.LinkedHashMap<>();
        title().ifPresent(_v -> _m.put("title", _v));
        description().ifPresent(_v -> _m.put("description", _v));
        status().ifPresent(_v -> _m.put("status", (_v == null ? null : _v.toJson())));
        isEmailRequired().ifPresent(_v -> _m.put("is_email_required", _v));
        isDescriptionRequired().ifPresent(_v -> _m.put("is_description_required", _v));
        expiresAt().ifPresent(_v -> _m.put("expires_at", (_v == null ? null : _v.toString())));
        return _m;
    }

    public static FileRequestUpdateRequest fromJson(Object _json) {
        java.util.Map<String, Object> _m = dev.unofficialbox.core.Json.asObject(_json);
        return new FileRequestUpdateRequest(
            (!_m.containsKey("title") || _m.get("title") == null) ? java.util.Optional.<String>empty() : java.util.Optional.of(dev.unofficialbox.core.Json.asString(_m.get("title"))),
            (!_m.containsKey("description") || _m.get("description") == null) ? java.util.Optional.<String>empty() : java.util.Optional.of(dev.unofficialbox.core.Json.asString(_m.get("description"))),
            (!_m.containsKey("status") || _m.get("status") == null) ? java.util.Optional.<FileRequestStatus>empty() : java.util.Optional.of((_m.get("status") == null ? null : FileRequestStatus.fromJson(_m.get("status")))),
            (!_m.containsKey("is_email_required") || _m.get("is_email_required") == null) ? java.util.Optional.<Boolean>empty() : java.util.Optional.of(dev.unofficialbox.core.Json.asBoolean(_m.get("is_email_required"))),
            (!_m.containsKey("is_description_required") || _m.get("is_description_required") == null) ? java.util.Optional.<Boolean>empty() : java.util.Optional.of(dev.unofficialbox.core.Json.asBoolean(_m.get("is_description_required"))),
            (!_m.containsKey("expires_at") || _m.get("expires_at") == null) ? java.util.Optional.<OffsetDateTime>empty() : java.util.Optional.of((_m.get("expires_at") == null ? null : java.time.OffsetDateTime.parse(dev.unofficialbox.core.Json.asString(_m.get("expires_at")))))
        );
    }

    /** A fluent builder; unset optional fields default to empty. */
    public static Builder builder() {
        return new Builder();
    }

    public static final class Builder {
        private Optional<String> title = java.util.Optional.empty();
        private Optional<String> description = java.util.Optional.empty();
        private Optional<FileRequestStatus> status = java.util.Optional.empty();
        private Optional<Boolean> isEmailRequired = java.util.Optional.empty();
        private Optional<Boolean> isDescriptionRequired = java.util.Optional.empty();
        private Optional<OffsetDateTime> expiresAt = java.util.Optional.empty();

        public Builder title(String title) {
            this.title = java.util.Optional.ofNullable(title);
            return this;
        }
        public Builder description(String description) {
            this.description = java.util.Optional.ofNullable(description);
            return this;
        }
        public Builder status(FileRequestStatus status) {
            this.status = java.util.Optional.ofNullable(status);
            return this;
        }
        public Builder isEmailRequired(Boolean isEmailRequired) {
            this.isEmailRequired = java.util.Optional.ofNullable(isEmailRequired);
            return this;
        }
        public Builder isDescriptionRequired(Boolean isDescriptionRequired) {
            this.isDescriptionRequired = java.util.Optional.ofNullable(isDescriptionRequired);
            return this;
        }
        public Builder expiresAt(OffsetDateTime expiresAt) {
            this.expiresAt = java.util.Optional.ofNullable(expiresAt);
            return this;
        }

        public FileRequestUpdateRequest build() {
            return new FileRequestUpdateRequest(
                title,
                description,
                status,
                isEmailRequired,
                isDescriptionRequired,
                expiresAt
            );
        }
    }
}
