// Code generated by box-gantry 0.1.0 (spec ee7d55aedefe2fa0) for Box API 2024.0. DO NOT EDIT.
package dev.unofficialbox.model.schemas;

import module java.base;

public record FileFullClassification(
    Optional<String> name,
    Optional<String> definition,
    Optional<String> color) {
    public java.util.Map<String, Object> toJson() {
        java.util.Map<String, Object> _m = new java.util.LinkedHashMap<>();
        name().ifPresent(_v -> _m.put("name", _v));
        definition().ifPresent(_v -> _m.put("definition", _v));
        color().ifPresent(_v -> _m.put("color", _v));
        return _m;
    }

    public static FileFullClassification fromJson(Object _json) {
        java.util.Map<String, Object> _m = dev.unofficialbox.core.Json.asObject(_json);
        return new FileFullClassification(
            (!_m.containsKey("name") || _m.get("name") == null) ? java.util.Optional.<String>empty() : java.util.Optional.of(dev.unofficialbox.core.Json.asString(_m.get("name"))),
            (!_m.containsKey("definition") || _m.get("definition") == null) ? java.util.Optional.<String>empty() : java.util.Optional.of(dev.unofficialbox.core.Json.asString(_m.get("definition"))),
            (!_m.containsKey("color") || _m.get("color") == null) ? java.util.Optional.<String>empty() : java.util.Optional.of(dev.unofficialbox.core.Json.asString(_m.get("color")))
        );
    }

    /** A fluent builder; unset optional fields default to empty. */
    public static Builder builder() {
        return new Builder();
    }

    public static final class Builder {
        private Optional<String> name = java.util.Optional.empty();
        private Optional<String> definition = java.util.Optional.empty();
        private Optional<String> color = java.util.Optional.empty();

        public Builder name(String name) {
            this.name = java.util.Optional.ofNullable(name);
            return this;
        }
        public Builder definition(String definition) {
            this.definition = java.util.Optional.ofNullable(definition);
            return this;
        }
        public Builder color(String color) {
            this.color = java.util.Optional.ofNullable(color);
            return this;
        }

        public FileFullClassification build() {
            return new FileFullClassification(
                name,
                definition,
                color
            );
        }
    }
}
