// Code generated by box-gantry 0.1.0 (spec ee7d55aedefe2fa0) for Box API 2024.0. DO NOT EDIT.
package dev.unofficialbox.model.schemas;

import module java.base;

public record FileFullRepresentations(Optional<List<RepresentationsEntries>> entries) {
    public java.util.Map<String, Object> toJson() {
        java.util.Map<String, Object> _m = new java.util.LinkedHashMap<>();
        entries().ifPresent(_v -> _m.put("entries", dev.unofficialbox.core.Json.encodeList(_v, _x0 -> (_x0 == null ? null : _x0.toJson()))));
        return _m;
    }

    public static FileFullRepresentations fromJson(Object _json) {
        java.util.Map<String, Object> _m = dev.unofficialbox.core.Json.asObject(_json);
        return new FileFullRepresentations(
            (!_m.containsKey("entries") || _m.get("entries") == null) ? java.util.Optional.<List<RepresentationsEntries>>empty() : java.util.Optional.of(dev.unofficialbox.core.Json.decodeList(_m.get("entries"), _x0 -> (_x0 == null ? null : RepresentationsEntries.fromJson(_x0))))
        );
    }
}
