// Code generated by box-gantry 0.1.0 (spec ee7d55aedefe2fa0) for Box API 2024.0. DO NOT EDIT.
package dev.unofficialbox.model.schemas;

public record FileVersionLegalHoldType(String value) {
    public static final FileVersionLegalHoldType FILE_VERSION_LEGAL_HOLD = new FileVersionLegalHoldType("file_version_legal_hold");

    public String toJson() {
        return value;
    }

    public static FileVersionLegalHoldType fromJson(Object _json) {
        return new FileVersionLegalHoldType(dev.unofficialbox.core.Json.asString(_json));
    }
}
