// Code generated by box-gantry 0.1.0 (spec ee7d55aedefe2fa0) for Box API 2024.0. DO NOT EDIT.
package dev.unofficialbox.model.schemas;

public record FileClassificationUpdateRequest(PutOp op, PutPath path, String value) {
    public java.util.Map<String, Object> toJson() {
        java.util.Map<String, Object> _m = new java.util.LinkedHashMap<>();
        _m.put("op", (op() == null ? null : op().toJson()));
        _m.put("path", (path() == null ? null : path().toJson()));
        _m.put("value", value());
        return _m;
    }

    public static FileClassificationUpdateRequest fromJson(Object _json) {
        java.util.Map<String, Object> _m = dev.unofficialbox.core.Json.asObject(_json);
        return new FileClassificationUpdateRequest(
            (_m.get("op") == null ? null : PutOp.fromJson(_m.get("op"))),
            (_m.get("path") == null ? null : PutPath.fromJson(_m.get("path"))),
            dev.unofficialbox.core.Json.asString(_m.get("value"))
        );
    }
}
