// Code generated by box-gantry 0.1.0 (spec ee7d55aedefe2fa0) for Box API 2024.0. DO NOT EDIT.
package dev.unofficialbox.model.schemas;

import module java.base;

public record FileFullExpiringEmbedLink(
    Optional<String> accessToken,
    Optional<Long> expiresIn,
    Optional<AccessTokenTokenType> tokenType,
    Optional<List<ResourceScope>> restrictedTo,
    Optional<String> url) {
    public java.util.Map<String, Object> toJson() {
        java.util.Map<String, Object> _m = new java.util.LinkedHashMap<>();
        accessToken().ifPresent(_v -> _m.put("access_token", _v));
        expiresIn().ifPresent(_v -> _m.put("expires_in", _v));
        tokenType().ifPresent(_v -> _m.put("token_type", (_v == null ? null : _v.toJson())));
        restrictedTo().ifPresent(_v -> _m.put("restricted_to", dev.unofficialbox.core.Json.encodeList(_v, _x0 -> (_x0 == null ? null : _x0.toJson()))));
        url().ifPresent(_v -> _m.put("url", _v));
        return _m;
    }

    public static FileFullExpiringEmbedLink fromJson(Object _json) {
        java.util.Map<String, Object> _m = dev.unofficialbox.core.Json.asObject(_json);
        return new FileFullExpiringEmbedLink(
            (!_m.containsKey("access_token") || _m.get("access_token") == null) ? java.util.Optional.<String>empty() : java.util.Optional.of(dev.unofficialbox.core.Json.asString(_m.get("access_token"))),
            (!_m.containsKey("expires_in") || _m.get("expires_in") == null) ? java.util.Optional.<Long>empty() : java.util.Optional.of(dev.unofficialbox.core.Json.asLong(_m.get("expires_in"))),
            (!_m.containsKey("token_type") || _m.get("token_type") == null) ? java.util.Optional.<AccessTokenTokenType>empty() : java.util.Optional.of((_m.get("token_type") == null ? null : AccessTokenTokenType.fromJson(_m.get("token_type")))),
            (!_m.containsKey("restricted_to") || _m.get("restricted_to") == null) ? java.util.Optional.<List<ResourceScope>>empty() : java.util.Optional.of(dev.unofficialbox.core.Json.decodeList(_m.get("restricted_to"), _x0 -> (_x0 == null ? null : ResourceScope.fromJson(_x0)))),
            (!_m.containsKey("url") || _m.get("url") == null) ? java.util.Optional.<String>empty() : java.util.Optional.of(dev.unofficialbox.core.Json.asString(_m.get("url")))
        );
    }
}
