// Code generated by box-gantry 0.1.0 (spec ee7d55aedefe2fa0) for Box API 2024.0. DO NOT EDIT.
package dev.unofficialbox.model.schemas;

import module java.base;
import dev.unofficialbox.core.Tristate;

public record FileRequest(
    String id,
    FileRequestType type,
    Optional<String> title,
    Tristate<String> description,
    Optional<FileRequestStatus> status,
    Optional<Boolean> isEmailRequired,
    Optional<Boolean> isDescriptionRequired,
    Optional<OffsetDateTime> expiresAt,
    FolderMini folder,
    Optional<String> url,
    Tristate<String> etag,
    Optional<UserMini> createdBy,
    OffsetDateTime createdAt,
    Optional<UserMini> updatedBy,
    OffsetDateTime updatedAt) {
    public java.util.Map<String, Object> toJson() {
        java.util.Map<String, Object> _m = new java.util.LinkedHashMap<>();
        _m.put("id", id());
        _m.put("type", (type() == null ? null : type().toJson()));
        title().ifPresent(_v -> _m.put("title", _v));
        if (description().isPresent()) { _m.put("description", description().value()); }
        else if (description().isNull()) { _m.put("description", null); }
        status().ifPresent(_v -> _m.put("status", (_v == null ? null : _v.toJson())));
        isEmailRequired().ifPresent(_v -> _m.put("is_email_required", _v));
        isDescriptionRequired().ifPresent(_v -> _m.put("is_description_required", _v));
        expiresAt().ifPresent(_v -> _m.put("expires_at", (_v == null ? null : _v.toString())));
        _m.put("folder", (folder() == null ? null : folder().toJson()));
        url().ifPresent(_v -> _m.put("url", _v));
        if (etag().isPresent()) { _m.put("etag", etag().value()); }
        else if (etag().isNull()) { _m.put("etag", null); }
        createdBy().ifPresent(_v -> _m.put("created_by", (_v == null ? null : _v.toJson())));
        _m.put("created_at", (createdAt() == null ? null : createdAt().toString()));
        updatedBy().ifPresent(_v -> _m.put("updated_by", (_v == null ? null : _v.toJson())));
        _m.put("updated_at", (updatedAt() == null ? null : updatedAt().toString()));
        return _m;
    }

    public static FileRequest fromJson(Object _json) {
        java.util.Map<String, Object> _m = dev.unofficialbox.core.Json.asObject(_json);
        return new FileRequest(
            dev.unofficialbox.core.Json.asString(_m.get("id")),
            (_m.get("type") == null ? null : FileRequestType.fromJson(_m.get("type"))),
            (!_m.containsKey("title") || _m.get("title") == null) ? java.util.Optional.<String>empty() : java.util.Optional.of(dev.unofficialbox.core.Json.asString(_m.get("title"))),
            !_m.containsKey("description") ? dev.unofficialbox.core.Tristate.<String>absent() : (_m.get("description") == null ? dev.unofficialbox.core.Tristate.<String>ofNull() : dev.unofficialbox.core.Tristate.of(dev.unofficialbox.core.Json.asString(_m.get("description")))),
            (!_m.containsKey("status") || _m.get("status") == null) ? java.util.Optional.<FileRequestStatus>empty() : java.util.Optional.of((_m.get("status") == null ? null : FileRequestStatus.fromJson(_m.get("status")))),
            (!_m.containsKey("is_email_required") || _m.get("is_email_required") == null) ? java.util.Optional.<Boolean>empty() : java.util.Optional.of(dev.unofficialbox.core.Json.asBoolean(_m.get("is_email_required"))),
            (!_m.containsKey("is_description_required") || _m.get("is_description_required") == null) ? java.util.Optional.<Boolean>empty() : java.util.Optional.of(dev.unofficialbox.core.Json.asBoolean(_m.get("is_description_required"))),
            (!_m.containsKey("expires_at") || _m.get("expires_at") == null) ? java.util.Optional.<OffsetDateTime>empty() : java.util.Optional.of((_m.get("expires_at") == null ? null : java.time.OffsetDateTime.parse(dev.unofficialbox.core.Json.asString(_m.get("expires_at"))))),
            (_m.get("folder") == null ? null : FolderMini.fromJson(_m.get("folder"))),
            (!_m.containsKey("url") || _m.get("url") == null) ? java.util.Optional.<String>empty() : java.util.Optional.of(dev.unofficialbox.core.Json.asString(_m.get("url"))),
            !_m.containsKey("etag") ? dev.unofficialbox.core.Tristate.<String>absent() : (_m.get("etag") == null ? dev.unofficialbox.core.Tristate.<String>ofNull() : dev.unofficialbox.core.Tristate.of(dev.unofficialbox.core.Json.asString(_m.get("etag")))),
            (!_m.containsKey("created_by") || _m.get("created_by") == null) ? java.util.Optional.<UserMini>empty() : java.util.Optional.of((_m.get("created_by") == null ? null : UserMini.fromJson(_m.get("created_by")))),
            (_m.get("created_at") == null ? null : java.time.OffsetDateTime.parse(dev.unofficialbox.core.Json.asString(_m.get("created_at")))),
            (!_m.containsKey("updated_by") || _m.get("updated_by") == null) ? java.util.Optional.<UserMini>empty() : java.util.Optional.of((_m.get("updated_by") == null ? null : UserMini.fromJson(_m.get("updated_by")))),
            (_m.get("updated_at") == null ? null : java.time.OffsetDateTime.parse(dev.unofficialbox.core.Json.asString(_m.get("updated_at"))))
        );
    }
}
