// Code generated by box-gantry 0.1.0 (spec ee7d55aedefe2fa0) for Box API 2024.0. DO NOT EDIT.
package dev.unofficialbox.model.schemas;

import module java.base;

public record FileVersionCurrentCreateRequest(Optional<String> id, Optional<FileVersionType> type) {
    public java.util.Map<String, Object> toJson() {
        java.util.Map<String, Object> _m = new java.util.LinkedHashMap<>();
        id().ifPresent(_v -> _m.put("id", _v));
        type().ifPresent(_v -> _m.put("type", (_v == null ? null : _v.toJson())));
        return _m;
    }

    public static FileVersionCurrentCreateRequest fromJson(Object _json) {
        java.util.Map<String, Object> _m = dev.unofficialbox.core.Json.asObject(_json);
        return new FileVersionCurrentCreateRequest(
            (!_m.containsKey("id") || _m.get("id") == null) ? java.util.Optional.<String>empty() : java.util.Optional.of(dev.unofficialbox.core.Json.asString(_m.get("id"))),
            (!_m.containsKey("type") || _m.get("type") == null) ? java.util.Optional.<FileVersionType>empty() : java.util.Optional.of((_m.get("type") == null ? null : FileVersionType.fromJson(_m.get("type"))))
        );
    }
}
