// Code generated by box-gantry 0.1.0 (spec ee7d55aedefe2fa0) for Box API 2024.0. DO NOT EDIT.
package dev.unofficialbox.model.schemas;

import dev.unofficialbox.core.Tristate;

public record FileVersionUpdateRequest(Tristate<String> trashedAt) {
    public java.util.Map<String, Object> toJson() {
        java.util.Map<String, Object> _m = new java.util.LinkedHashMap<>();
        if (trashedAt().isPresent()) { _m.put("trashed_at", trashedAt().value()); }
        else if (trashedAt().isNull()) { _m.put("trashed_at", null); }
        return _m;
    }

    public static FileVersionUpdateRequest fromJson(Object _json) {
        java.util.Map<String, Object> _m = dev.unofficialbox.core.Json.asObject(_json);
        return new FileVersionUpdateRequest(
            !_m.containsKey("trashed_at") ? dev.unofficialbox.core.Tristate.<String>absent() : (_m.get("trashed_at") == null ? dev.unofficialbox.core.Tristate.<String>ofNull() : dev.unofficialbox.core.Tristate.of(dev.unofficialbox.core.Json.asString(_m.get("trashed_at"))))
        );
    }
}
