// Code generated by box-gantry 0.1.0 (spec ee7d55aedefe2fa0) for Box API 2024.0. DO NOT EDIT.
package dev.unofficialbox.model.schemas;

import module java.base;

public record FileVersionLegalHold(
    Optional<String> id,
    Optional<FileVersionLegalHoldType> type,
    Optional<FileVersionMini> fileVersion,
    Optional<FileMini> file,
    Optional<List<LegalHoldPolicyAssignment>> legalHoldPolicyAssignments,
    Optional<OffsetDateTime> deletedAt) {
    public java.util.Map<String, Object> toJson() {
        java.util.Map<String, Object> _m = new java.util.LinkedHashMap<>();
        id().ifPresent(_v -> _m.put("id", _v));
        type().ifPresent(_v -> _m.put("type", (_v == null ? null : _v.toJson())));
        fileVersion().ifPresent(_v -> _m.put("file_version", (_v == null ? null : _v.toJson())));
        file().ifPresent(_v -> _m.put("file", (_v == null ? null : _v.toJson())));
        legalHoldPolicyAssignments().ifPresent(_v -> _m.put("legal_hold_policy_assignments", dev.unofficialbox.core.Json.encodeList(_v, _x0 -> (_x0 == null ? null : _x0.toJson()))));
        deletedAt().ifPresent(_v -> _m.put("deleted_at", (_v == null ? null : _v.toString())));
        return _m;
    }

    public static FileVersionLegalHold fromJson(Object _json) {
        java.util.Map<String, Object> _m = dev.unofficialbox.core.Json.asObject(_json);
        return new FileVersionLegalHold(
            (!_m.containsKey("id") || _m.get("id") == null) ? java.util.Optional.<String>empty() : java.util.Optional.of(dev.unofficialbox.core.Json.asString(_m.get("id"))),
            (!_m.containsKey("type") || _m.get("type") == null) ? java.util.Optional.<FileVersionLegalHoldType>empty() : java.util.Optional.of((_m.get("type") == null ? null : FileVersionLegalHoldType.fromJson(_m.get("type")))),
            (!_m.containsKey("file_version") || _m.get("file_version") == null) ? java.util.Optional.<FileVersionMini>empty() : java.util.Optional.of((_m.get("file_version") == null ? null : FileVersionMini.fromJson(_m.get("file_version")))),
            (!_m.containsKey("file") || _m.get("file") == null) ? java.util.Optional.<FileMini>empty() : java.util.Optional.of((_m.get("file") == null ? null : FileMini.fromJson(_m.get("file")))),
            (!_m.containsKey("legal_hold_policy_assignments") || _m.get("legal_hold_policy_assignments") == null) ? java.util.Optional.<List<LegalHoldPolicyAssignment>>empty() : java.util.Optional.of(dev.unofficialbox.core.Json.decodeList(_m.get("legal_hold_policy_assignments"), _x0 -> (_x0 == null ? null : LegalHoldPolicyAssignment.fromJson(_x0)))),
            (!_m.containsKey("deleted_at") || _m.get("deleted_at") == null) ? java.util.Optional.<OffsetDateTime>empty() : java.util.Optional.of((_m.get("deleted_at") == null ? null : java.time.OffsetDateTime.parse(dev.unofficialbox.core.Json.asString(_m.get("deleted_at")))))
        );
    }

    /** A fluent builder; unset optional fields default to empty. */
    public static Builder builder() {
        return new Builder();
    }

    public static final class Builder {
        private Optional<String> id = java.util.Optional.empty();
        private Optional<FileVersionLegalHoldType> type = java.util.Optional.empty();
        private Optional<FileVersionMini> fileVersion = java.util.Optional.empty();
        private Optional<FileMini> file = java.util.Optional.empty();
        private Optional<List<LegalHoldPolicyAssignment>> legalHoldPolicyAssignments = java.util.Optional.empty();
        private Optional<OffsetDateTime> deletedAt = java.util.Optional.empty();

        public Builder id(String id) {
            this.id = java.util.Optional.ofNullable(id);
            return this;
        }
        public Builder type(FileVersionLegalHoldType type) {
            this.type = java.util.Optional.ofNullable(type);
            return this;
        }
        public Builder fileVersion(FileVersionMini fileVersion) {
            this.fileVersion = java.util.Optional.ofNullable(fileVersion);
            return this;
        }
        public Builder file(FileMini file) {
            this.file = java.util.Optional.ofNullable(file);
            return this;
        }
        public Builder legalHoldPolicyAssignments(List<LegalHoldPolicyAssignment> legalHoldPolicyAssignments) {
            this.legalHoldPolicyAssignments = java.util.Optional.ofNullable(legalHoldPolicyAssignments);
            return this;
        }
        public Builder deletedAt(OffsetDateTime deletedAt) {
            this.deletedAt = java.util.Optional.ofNullable(deletedAt);
            return this;
        }

        public FileVersionLegalHold build() {
            return new FileVersionLegalHold(
                id,
                type,
                fileVersion,
                file,
                legalHoldPolicyAssignments,
                deletedAt
            );
        }
    }
}
