// Code generated by box-gantry 0.1.0 (spec ee7d55aedefe2fa0) for Box API 2024.0. DO NOT EDIT.
package dev.unofficialbox.model.schemas;

import module java.base;
import dev.unofficialbox.core.Tristate;

public record FileVersion(
    String id,
    FileVersionType type,
    Optional<String> sha1,
    Optional<String> name,
    Optional<Long> size,
    Optional<OffsetDateTime> createdAt,
    Optional<OffsetDateTime> modifiedAt,
    Optional<UserMini> modifiedBy,
    Tristate<OffsetDateTime> trashedAt,
    Optional<UserMini> trashedBy,
    Tristate<OffsetDateTime> restoredAt,
    Optional<UserMini> restoredBy,
    Tristate<OffsetDateTime> purgedAt,
    Optional<String> uploaderDisplayName) {
    public java.util.Map<String, Object> toJson() {
        java.util.Map<String, Object> _m = new java.util.LinkedHashMap<>();
        _m.put("id", id());
        _m.put("type", (type() == null ? null : type().toJson()));
        sha1().ifPresent(_v -> _m.put("sha1", _v));
        name().ifPresent(_v -> _m.put("name", _v));
        size().ifPresent(_v -> _m.put("size", _v));
        createdAt().ifPresent(_v -> _m.put("created_at", (_v == null ? null : _v.toString())));
        modifiedAt().ifPresent(_v -> _m.put("modified_at", (_v == null ? null : _v.toString())));
        modifiedBy().ifPresent(_v -> _m.put("modified_by", (_v == null ? null : _v.toJson())));
        if (trashedAt().isPresent()) { _m.put("trashed_at", (trashedAt().value() == null ? null : trashedAt().value().toString())); }
        else if (trashedAt().isNull()) { _m.put("trashed_at", null); }
        trashedBy().ifPresent(_v -> _m.put("trashed_by", (_v == null ? null : _v.toJson())));
        if (restoredAt().isPresent()) { _m.put("restored_at", (restoredAt().value() == null ? null : restoredAt().value().toString())); }
        else if (restoredAt().isNull()) { _m.put("restored_at", null); }
        restoredBy().ifPresent(_v -> _m.put("restored_by", (_v == null ? null : _v.toJson())));
        if (purgedAt().isPresent()) { _m.put("purged_at", (purgedAt().value() == null ? null : purgedAt().value().toString())); }
        else if (purgedAt().isNull()) { _m.put("purged_at", null); }
        uploaderDisplayName().ifPresent(_v -> _m.put("uploader_display_name", _v));
        return _m;
    }

    public static FileVersion fromJson(Object _json) {
        java.util.Map<String, Object> _m = dev.unofficialbox.core.Json.asObject(_json);
        return new FileVersion(
            dev.unofficialbox.core.Json.asString(_m.get("id")),
            (_m.get("type") == null ? null : FileVersionType.fromJson(_m.get("type"))),
            (!_m.containsKey("sha1") || _m.get("sha1") == null) ? java.util.Optional.<String>empty() : java.util.Optional.of(dev.unofficialbox.core.Json.asString(_m.get("sha1"))),
            (!_m.containsKey("name") || _m.get("name") == null) ? java.util.Optional.<String>empty() : java.util.Optional.of(dev.unofficialbox.core.Json.asString(_m.get("name"))),
            (!_m.containsKey("size") || _m.get("size") == null) ? java.util.Optional.<Long>empty() : java.util.Optional.of(dev.unofficialbox.core.Json.asLong(_m.get("size"))),
            (!_m.containsKey("created_at") || _m.get("created_at") == null) ? java.util.Optional.<OffsetDateTime>empty() : java.util.Optional.of((_m.get("created_at") == null ? null : java.time.OffsetDateTime.parse(dev.unofficialbox.core.Json.asString(_m.get("created_at"))))),
            (!_m.containsKey("modified_at") || _m.get("modified_at") == null) ? java.util.Optional.<OffsetDateTime>empty() : java.util.Optional.of((_m.get("modified_at") == null ? null : java.time.OffsetDateTime.parse(dev.unofficialbox.core.Json.asString(_m.get("modified_at"))))),
            (!_m.containsKey("modified_by") || _m.get("modified_by") == null) ? java.util.Optional.<UserMini>empty() : java.util.Optional.of((_m.get("modified_by") == null ? null : UserMini.fromJson(_m.get("modified_by")))),
            !_m.containsKey("trashed_at") ? dev.unofficialbox.core.Tristate.<OffsetDateTime>absent() : (_m.get("trashed_at") == null ? dev.unofficialbox.core.Tristate.<OffsetDateTime>ofNull() : dev.unofficialbox.core.Tristate.of((_m.get("trashed_at") == null ? null : java.time.OffsetDateTime.parse(dev.unofficialbox.core.Json.asString(_m.get("trashed_at")))))),
            (!_m.containsKey("trashed_by") || _m.get("trashed_by") == null) ? java.util.Optional.<UserMini>empty() : java.util.Optional.of((_m.get("trashed_by") == null ? null : UserMini.fromJson(_m.get("trashed_by")))),
            !_m.containsKey("restored_at") ? dev.unofficialbox.core.Tristate.<OffsetDateTime>absent() : (_m.get("restored_at") == null ? dev.unofficialbox.core.Tristate.<OffsetDateTime>ofNull() : dev.unofficialbox.core.Tristate.of((_m.get("restored_at") == null ? null : java.time.OffsetDateTime.parse(dev.unofficialbox.core.Json.asString(_m.get("restored_at")))))),
            (!_m.containsKey("restored_by") || _m.get("restored_by") == null) ? java.util.Optional.<UserMini>empty() : java.util.Optional.of((_m.get("restored_by") == null ? null : UserMini.fromJson(_m.get("restored_by")))),
            !_m.containsKey("purged_at") ? dev.unofficialbox.core.Tristate.<OffsetDateTime>absent() : (_m.get("purged_at") == null ? dev.unofficialbox.core.Tristate.<OffsetDateTime>ofNull() : dev.unofficialbox.core.Tristate.of((_m.get("purged_at") == null ? null : java.time.OffsetDateTime.parse(dev.unofficialbox.core.Json.asString(_m.get("purged_at")))))),
            (!_m.containsKey("uploader_display_name") || _m.get("uploader_display_name") == null) ? java.util.Optional.<String>empty() : java.util.Optional.of(dev.unofficialbox.core.Json.asString(_m.get("uploader_display_name")))
        );
    }
}
