// Code generated by box-gantry 0.1.0 (spec ee7d55aedefe2fa0) for Box API 2024.0. DO NOT EDIT.
package dev.unofficialbox.model.schemas;

import module java.base;

public record FileCopyRequest(
    Optional<String> name,
    Optional<String> version,
    AttributesParent parent) {
    public java.util.Map<String, Object> toJson() {
        java.util.Map<String, Object> _m = new java.util.LinkedHashMap<>();
        name().ifPresent(_v -> _m.put("name", _v));
        version().ifPresent(_v -> _m.put("version", _v));
        _m.put("parent", (parent() == null ? null : parent().toJson()));
        return _m;
    }

    public static FileCopyRequest fromJson(Object _json) {
        java.util.Map<String, Object> _m = dev.unofficialbox.core.Json.asObject(_json);
        return new FileCopyRequest(
            (!_m.containsKey("name") || _m.get("name") == null) ? java.util.Optional.<String>empty() : java.util.Optional.of(dev.unofficialbox.core.Json.asString(_m.get("name"))),
            (!_m.containsKey("version") || _m.get("version") == null) ? java.util.Optional.<String>empty() : java.util.Optional.of(dev.unofficialbox.core.Json.asString(_m.get("version"))),
            (_m.get("parent") == null ? null : AttributesParent.fromJson(_m.get("parent")))
        );
    }
}
