// Code generated by box-gantry 0.1.0 (spec ee7d55aedefe2fa0) for Box API 2024.0. DO NOT EDIT.
package dev.unofficialbox.model.schemas;

import module java.base;

public record FolderLockCreateRequest(
    Optional<FolderLockLockedOperations> lockedOperations,
    PostFolder folder) {
    public java.util.Map<String, Object> toJson() {
        java.util.Map<String, Object> _m = new java.util.LinkedHashMap<>();
        lockedOperations().ifPresent(_v -> _m.put("locked_operations", (_v == null ? null : _v.toJson())));
        _m.put("folder", (folder() == null ? null : folder().toJson()));
        return _m;
    }

    public static FolderLockCreateRequest fromJson(Object _json) {
        java.util.Map<String, Object> _m = dev.unofficialbox.core.Json.asObject(_json);
        return new FolderLockCreateRequest(
            (!_m.containsKey("locked_operations") || _m.get("locked_operations") == null) ? java.util.Optional.<FolderLockLockedOperations>empty() : java.util.Optional.of((_m.get("locked_operations") == null ? null : FolderLockLockedOperations.fromJson(_m.get("locked_operations")))),
            (_m.get("folder") == null ? null : PostFolder.fromJson(_m.get("folder")))
        );
    }

    /** A fluent builder; unset optional fields default to empty. */
    public static Builder builder() {
        return new Builder();
    }

    public static final class Builder {
        private Optional<FolderLockLockedOperations> lockedOperations = java.util.Optional.empty();
        private PostFolder folder;

        public Builder lockedOperations(FolderLockLockedOperations lockedOperations) {
            this.lockedOperations = java.util.Optional.ofNullable(lockedOperations);
            return this;
        }
        public Builder folder(PostFolder folder) {
            this.folder = folder;
            return this;
        }

        public FolderLockCreateRequest build() {
            return new FolderLockCreateRequest(
                lockedOperations,
                folder
            );
        }
    }
}
