// Code generated by box-gantry 0.1.0 (spec ee7d55aedefe2fa0) for Box API 2024.0. DO NOT EDIT.
package dev.unofficialbox.model.schemas;

import module java.base;
import dev.unofficialbox.core.Tristate;

public record Folder(
    String id,
    Tristate<String> etag,
    FolderType type,
    Optional<String> sequenceId,
    Optional<String> name,
    Tristate<OffsetDateTime> createdAt,
    Tristate<OffsetDateTime> modifiedAt,
    Optional<String> description,
    Optional<Long> size,
    Optional<FilePathCollection> pathCollection,
    Optional<UserMini> createdBy,
    Optional<UserMini> modifiedBy,
    Tristate<OffsetDateTime> trashedAt,
    Tristate<OffsetDateTime> purgedAt,
    Tristate<OffsetDateTime> contentCreatedAt,
    Tristate<OffsetDateTime> contentModifiedAt,
    Optional<UserMini> ownedBy,
    Tristate<FileSharedLink> sharedLink,
    Tristate<FolderFolderUploadEmail> folderUploadEmail,
    Tristate<FolderMini> parent,
    Optional<FileItemStatus> itemStatus,
    Optional<Items> itemCollection) implements CollaborationItem {
    public java.util.Map<String, Object> toJson() {
        java.util.Map<String, Object> _m = new java.util.LinkedHashMap<>();
        _m.put("id", id());
        if (etag().isPresent()) { _m.put("etag", etag().value()); }
        else if (etag().isNull()) { _m.put("etag", null); }
        _m.put("type", (type() == null ? null : type().toJson()));
        sequenceId().ifPresent(_v -> _m.put("sequence_id", _v));
        name().ifPresent(_v -> _m.put("name", _v));
        if (createdAt().isPresent()) { _m.put("created_at", (createdAt().value() == null ? null : createdAt().value().toString())); }
        else if (createdAt().isNull()) { _m.put("created_at", null); }
        if (modifiedAt().isPresent()) { _m.put("modified_at", (modifiedAt().value() == null ? null : modifiedAt().value().toString())); }
        else if (modifiedAt().isNull()) { _m.put("modified_at", null); }
        description().ifPresent(_v -> _m.put("description", _v));
        size().ifPresent(_v -> _m.put("size", _v));
        pathCollection().ifPresent(_v -> _m.put("path_collection", (_v == null ? null : _v.toJson())));
        createdBy().ifPresent(_v -> _m.put("created_by", (_v == null ? null : _v.toJson())));
        modifiedBy().ifPresent(_v -> _m.put("modified_by", (_v == null ? null : _v.toJson())));
        if (trashedAt().isPresent()) { _m.put("trashed_at", (trashedAt().value() == null ? null : trashedAt().value().toString())); }
        else if (trashedAt().isNull()) { _m.put("trashed_at", null); }
        if (purgedAt().isPresent()) { _m.put("purged_at", (purgedAt().value() == null ? null : purgedAt().value().toString())); }
        else if (purgedAt().isNull()) { _m.put("purged_at", null); }
        if (contentCreatedAt().isPresent()) { _m.put("content_created_at", (contentCreatedAt().value() == null ? null : contentCreatedAt().value().toString())); }
        else if (contentCreatedAt().isNull()) { _m.put("content_created_at", null); }
        if (contentModifiedAt().isPresent()) { _m.put("content_modified_at", (contentModifiedAt().value() == null ? null : contentModifiedAt().value().toString())); }
        else if (contentModifiedAt().isNull()) { _m.put("content_modified_at", null); }
        ownedBy().ifPresent(_v -> _m.put("owned_by", (_v == null ? null : _v.toJson())));
        if (sharedLink().isPresent()) { _m.put("shared_link", (sharedLink().value() == null ? null : sharedLink().value().toJson())); }
        else if (sharedLink().isNull()) { _m.put("shared_link", null); }
        if (folderUploadEmail().isPresent()) { _m.put("folder_upload_email", (folderUploadEmail().value() == null ? null : folderUploadEmail().value().toJson())); }
        else if (folderUploadEmail().isNull()) { _m.put("folder_upload_email", null); }
        if (parent().isPresent()) { _m.put("parent", (parent().value() == null ? null : parent().value().toJson())); }
        else if (parent().isNull()) { _m.put("parent", null); }
        itemStatus().ifPresent(_v -> _m.put("item_status", (_v == null ? null : _v.toJson())));
        itemCollection().ifPresent(_v -> _m.put("item_collection", (_v == null ? null : _v.toJson())));
        return _m;
    }

    public static Folder fromJson(Object _json) {
        java.util.Map<String, Object> _m = dev.unofficialbox.core.Json.asObject(_json);
        return new Folder(
            dev.unofficialbox.core.Json.asString(_m.get("id")),
            !_m.containsKey("etag") ? dev.unofficialbox.core.Tristate.<String>absent() : (_m.get("etag") == null ? dev.unofficialbox.core.Tristate.<String>ofNull() : dev.unofficialbox.core.Tristate.of(dev.unofficialbox.core.Json.asString(_m.get("etag")))),
            (_m.get("type") == null ? null : FolderType.fromJson(_m.get("type"))),
            (!_m.containsKey("sequence_id") || _m.get("sequence_id") == null) ? java.util.Optional.<String>empty() : java.util.Optional.of(dev.unofficialbox.core.Json.asString(_m.get("sequence_id"))),
            (!_m.containsKey("name") || _m.get("name") == null) ? java.util.Optional.<String>empty() : java.util.Optional.of(dev.unofficialbox.core.Json.asString(_m.get("name"))),
            !_m.containsKey("created_at") ? dev.unofficialbox.core.Tristate.<OffsetDateTime>absent() : (_m.get("created_at") == null ? dev.unofficialbox.core.Tristate.<OffsetDateTime>ofNull() : dev.unofficialbox.core.Tristate.of((_m.get("created_at") == null ? null : java.time.OffsetDateTime.parse(dev.unofficialbox.core.Json.asString(_m.get("created_at")))))),
            !_m.containsKey("modified_at") ? dev.unofficialbox.core.Tristate.<OffsetDateTime>absent() : (_m.get("modified_at") == null ? dev.unofficialbox.core.Tristate.<OffsetDateTime>ofNull() : dev.unofficialbox.core.Tristate.of((_m.get("modified_at") == null ? null : java.time.OffsetDateTime.parse(dev.unofficialbox.core.Json.asString(_m.get("modified_at")))))),
            (!_m.containsKey("description") || _m.get("description") == null) ? java.util.Optional.<String>empty() : java.util.Optional.of(dev.unofficialbox.core.Json.asString(_m.get("description"))),
            (!_m.containsKey("size") || _m.get("size") == null) ? java.util.Optional.<Long>empty() : java.util.Optional.of(dev.unofficialbox.core.Json.asLong(_m.get("size"))),
            (!_m.containsKey("path_collection") || _m.get("path_collection") == null) ? java.util.Optional.<FilePathCollection>empty() : java.util.Optional.of((_m.get("path_collection") == null ? null : FilePathCollection.fromJson(_m.get("path_collection")))),
            (!_m.containsKey("created_by") || _m.get("created_by") == null) ? java.util.Optional.<UserMini>empty() : java.util.Optional.of((_m.get("created_by") == null ? null : UserMini.fromJson(_m.get("created_by")))),
            (!_m.containsKey("modified_by") || _m.get("modified_by") == null) ? java.util.Optional.<UserMini>empty() : java.util.Optional.of((_m.get("modified_by") == null ? null : UserMini.fromJson(_m.get("modified_by")))),
            !_m.containsKey("trashed_at") ? dev.unofficialbox.core.Tristate.<OffsetDateTime>absent() : (_m.get("trashed_at") == null ? dev.unofficialbox.core.Tristate.<OffsetDateTime>ofNull() : dev.unofficialbox.core.Tristate.of((_m.get("trashed_at") == null ? null : java.time.OffsetDateTime.parse(dev.unofficialbox.core.Json.asString(_m.get("trashed_at")))))),
            !_m.containsKey("purged_at") ? dev.unofficialbox.core.Tristate.<OffsetDateTime>absent() : (_m.get("purged_at") == null ? dev.unofficialbox.core.Tristate.<OffsetDateTime>ofNull() : dev.unofficialbox.core.Tristate.of((_m.get("purged_at") == null ? null : java.time.OffsetDateTime.parse(dev.unofficialbox.core.Json.asString(_m.get("purged_at")))))),
            !_m.containsKey("content_created_at") ? dev.unofficialbox.core.Tristate.<OffsetDateTime>absent() : (_m.get("content_created_at") == null ? dev.unofficialbox.core.Tristate.<OffsetDateTime>ofNull() : dev.unofficialbox.core.Tristate.of((_m.get("content_created_at") == null ? null : java.time.OffsetDateTime.parse(dev.unofficialbox.core.Json.asString(_m.get("content_created_at")))))),
            !_m.containsKey("content_modified_at") ? dev.unofficialbox.core.Tristate.<OffsetDateTime>absent() : (_m.get("content_modified_at") == null ? dev.unofficialbox.core.Tristate.<OffsetDateTime>ofNull() : dev.unofficialbox.core.Tristate.of((_m.get("content_modified_at") == null ? null : java.time.OffsetDateTime.parse(dev.unofficialbox.core.Json.asString(_m.get("content_modified_at")))))),
            (!_m.containsKey("owned_by") || _m.get("owned_by") == null) ? java.util.Optional.<UserMini>empty() : java.util.Optional.of((_m.get("owned_by") == null ? null : UserMini.fromJson(_m.get("owned_by")))),
            !_m.containsKey("shared_link") ? dev.unofficialbox.core.Tristate.<FileSharedLink>absent() : (_m.get("shared_link") == null ? dev.unofficialbox.core.Tristate.<FileSharedLink>ofNull() : dev.unofficialbox.core.Tristate.of((_m.get("shared_link") == null ? null : FileSharedLink.fromJson(_m.get("shared_link"))))),
            !_m.containsKey("folder_upload_email") ? dev.unofficialbox.core.Tristate.<FolderFolderUploadEmail>absent() : (_m.get("folder_upload_email") == null ? dev.unofficialbox.core.Tristate.<FolderFolderUploadEmail>ofNull() : dev.unofficialbox.core.Tristate.of((_m.get("folder_upload_email") == null ? null : FolderFolderUploadEmail.fromJson(_m.get("folder_upload_email"))))),
            !_m.containsKey("parent") ? dev.unofficialbox.core.Tristate.<FolderMini>absent() : (_m.get("parent") == null ? dev.unofficialbox.core.Tristate.<FolderMini>ofNull() : dev.unofficialbox.core.Tristate.of((_m.get("parent") == null ? null : FolderMini.fromJson(_m.get("parent"))))),
            (!_m.containsKey("item_status") || _m.get("item_status") == null) ? java.util.Optional.<FileItemStatus>empty() : java.util.Optional.of((_m.get("item_status") == null ? null : FileItemStatus.fromJson(_m.get("item_status")))),
            (!_m.containsKey("item_collection") || _m.get("item_collection") == null) ? java.util.Optional.<Items>empty() : java.util.Optional.of((_m.get("item_collection") == null ? null : Items.fromJson(_m.get("item_collection"))))
        );
    }
}
