// Code generated by box-gantry 0.1.0 (spec ee7d55aedefe2fa0) for Box API 2024.0. DO NOT EDIT.
package dev.unofficialbox.model.schemas;

import module java.base;
import dev.unofficialbox.core.Tristate;

public record FolderFull(
    String id,
    Tristate<String> etag,
    FolderType type,
    Optional<String> sequenceId,
    Optional<String> name,
    Tristate<OffsetDateTime> createdAt,
    Tristate<OffsetDateTime> modifiedAt,
    Optional<String> description,
    Optional<Long> size,
    Optional<FilePathCollection> pathCollection,
    Optional<UserMini> createdBy,
    Optional<UserMini> modifiedBy,
    Tristate<OffsetDateTime> trashedAt,
    Tristate<OffsetDateTime> purgedAt,
    Tristate<OffsetDateTime> contentCreatedAt,
    Tristate<OffsetDateTime> contentModifiedAt,
    Optional<UserMini> ownedBy,
    Tristate<FileSharedLink> sharedLink,
    Tristate<FolderFolderUploadEmail> folderUploadEmail,
    Tristate<FolderMini> parent,
    Optional<FileItemStatus> itemStatus,
    Optional<Items> itemCollection,
    Optional<FolderFullSyncState> syncState,
    Optional<Boolean> hasCollaborations,
    Optional<FolderFullPermissions> permissions,
    Optional<List<String>> tags,
    Optional<Boolean> canNonOwnersInvite,
    Optional<Boolean> isExternallyOwned,
    Optional<Map<String, Map<String, MetadataFull>>> metadata,
    Optional<Boolean> isCollaborationRestrictedToEnterprise,
    Optional<List<SharedLinkAccess>> allowedSharedLinkAccessLevels,
    Optional<List<FileFullAllowedInviteeRoles>> allowedInviteeRoles,
    Optional<FileFullWatermarkInfo> watermarkInfo,
    Optional<Boolean> isAccessibleViaSharedLink,
    Optional<Boolean> canNonOwnersViewCollaborators,
    Tristate<FileFullClassification> classification,
    Optional<Boolean> isAssociatedWithAppItem) implements MetadataQueryResultItem, RecentItemResource, SearchResultItem, SearchResultWithSharedLinkItem {
    public java.util.Map<String, Object> toJson() {
        java.util.Map<String, Object> _m = new java.util.LinkedHashMap<>();
        _m.put("id", id());
        if (etag().isPresent()) { _m.put("etag", etag().value()); }
        else if (etag().isNull()) { _m.put("etag", null); }
        _m.put("type", (type() == null ? null : type().toJson()));
        sequenceId().ifPresent(_v -> _m.put("sequence_id", _v));
        name().ifPresent(_v -> _m.put("name", _v));
        if (createdAt().isPresent()) { _m.put("created_at", (createdAt().value() == null ? null : createdAt().value().toString())); }
        else if (createdAt().isNull()) { _m.put("created_at", null); }
        if (modifiedAt().isPresent()) { _m.put("modified_at", (modifiedAt().value() == null ? null : modifiedAt().value().toString())); }
        else if (modifiedAt().isNull()) { _m.put("modified_at", null); }
        description().ifPresent(_v -> _m.put("description", _v));
        size().ifPresent(_v -> _m.put("size", _v));
        pathCollection().ifPresent(_v -> _m.put("path_collection", (_v == null ? null : _v.toJson())));
        createdBy().ifPresent(_v -> _m.put("created_by", (_v == null ? null : _v.toJson())));
        modifiedBy().ifPresent(_v -> _m.put("modified_by", (_v == null ? null : _v.toJson())));
        if (trashedAt().isPresent()) { _m.put("trashed_at", (trashedAt().value() == null ? null : trashedAt().value().toString())); }
        else if (trashedAt().isNull()) { _m.put("trashed_at", null); }
        if (purgedAt().isPresent()) { _m.put("purged_at", (purgedAt().value() == null ? null : purgedAt().value().toString())); }
        else if (purgedAt().isNull()) { _m.put("purged_at", null); }
        if (contentCreatedAt().isPresent()) { _m.put("content_created_at", (contentCreatedAt().value() == null ? null : contentCreatedAt().value().toString())); }
        else if (contentCreatedAt().isNull()) { _m.put("content_created_at", null); }
        if (contentModifiedAt().isPresent()) { _m.put("content_modified_at", (contentModifiedAt().value() == null ? null : contentModifiedAt().value().toString())); }
        else if (contentModifiedAt().isNull()) { _m.put("content_modified_at", null); }
        ownedBy().ifPresent(_v -> _m.put("owned_by", (_v == null ? null : _v.toJson())));
        if (sharedLink().isPresent()) { _m.put("shared_link", (sharedLink().value() == null ? null : sharedLink().value().toJson())); }
        else if (sharedLink().isNull()) { _m.put("shared_link", null); }
        if (folderUploadEmail().isPresent()) { _m.put("folder_upload_email", (folderUploadEmail().value() == null ? null : folderUploadEmail().value().toJson())); }
        else if (folderUploadEmail().isNull()) { _m.put("folder_upload_email", null); }
        if (parent().isPresent()) { _m.put("parent", (parent().value() == null ? null : parent().value().toJson())); }
        else if (parent().isNull()) { _m.put("parent", null); }
        itemStatus().ifPresent(_v -> _m.put("item_status", (_v == null ? null : _v.toJson())));
        itemCollection().ifPresent(_v -> _m.put("item_collection", (_v == null ? null : _v.toJson())));
        syncState().ifPresent(_v -> _m.put("sync_state", (_v == null ? null : _v.toJson())));
        hasCollaborations().ifPresent(_v -> _m.put("has_collaborations", _v));
        permissions().ifPresent(_v -> _m.put("permissions", (_v == null ? null : _v.toJson())));
        tags().ifPresent(_v -> _m.put("tags", _v));
        canNonOwnersInvite().ifPresent(_v -> _m.put("can_non_owners_invite", _v));
        isExternallyOwned().ifPresent(_v -> _m.put("is_externally_owned", _v));
        metadata().ifPresent(_v -> _m.put("metadata", dev.unofficialbox.core.Json.encodeMap(_v, _x0 -> dev.unofficialbox.core.Json.encodeMap(_x0, _x1 -> (_x1 == null ? null : _x1.toJson())))));
        isCollaborationRestrictedToEnterprise().ifPresent(_v -> _m.put("is_collaboration_restricted_to_enterprise", _v));
        allowedSharedLinkAccessLevels().ifPresent(_v -> _m.put("allowed_shared_link_access_levels", dev.unofficialbox.core.Json.encodeList(_v, _x0 -> (_x0 == null ? null : _x0.toJson()))));
        allowedInviteeRoles().ifPresent(_v -> _m.put("allowed_invitee_roles", dev.unofficialbox.core.Json.encodeList(_v, _x0 -> (_x0 == null ? null : _x0.toJson()))));
        watermarkInfo().ifPresent(_v -> _m.put("watermark_info", (_v == null ? null : _v.toJson())));
        isAccessibleViaSharedLink().ifPresent(_v -> _m.put("is_accessible_via_shared_link", _v));
        canNonOwnersViewCollaborators().ifPresent(_v -> _m.put("can_non_owners_view_collaborators", _v));
        if (classification().isPresent()) { _m.put("classification", (classification().value() == null ? null : classification().value().toJson())); }
        else if (classification().isNull()) { _m.put("classification", null); }
        isAssociatedWithAppItem().ifPresent(_v -> _m.put("is_associated_with_app_item", _v));
        return _m;
    }

    public static FolderFull fromJson(Object _json) {
        java.util.Map<String, Object> _m = dev.unofficialbox.core.Json.asObject(_json);
        return new FolderFull(
            dev.unofficialbox.core.Json.asString(_m.get("id")),
            !_m.containsKey("etag") ? dev.unofficialbox.core.Tristate.<String>absent() : (_m.get("etag") == null ? dev.unofficialbox.core.Tristate.<String>ofNull() : dev.unofficialbox.core.Tristate.of(dev.unofficialbox.core.Json.asString(_m.get("etag")))),
            (_m.get("type") == null ? null : FolderType.fromJson(_m.get("type"))),
            (!_m.containsKey("sequence_id") || _m.get("sequence_id") == null) ? java.util.Optional.<String>empty() : java.util.Optional.of(dev.unofficialbox.core.Json.asString(_m.get("sequence_id"))),
            (!_m.containsKey("name") || _m.get("name") == null) ? java.util.Optional.<String>empty() : java.util.Optional.of(dev.unofficialbox.core.Json.asString(_m.get("name"))),
            !_m.containsKey("created_at") ? dev.unofficialbox.core.Tristate.<OffsetDateTime>absent() : (_m.get("created_at") == null ? dev.unofficialbox.core.Tristate.<OffsetDateTime>ofNull() : dev.unofficialbox.core.Tristate.of((_m.get("created_at") == null ? null : java.time.OffsetDateTime.parse(dev.unofficialbox.core.Json.asString(_m.get("created_at")))))),
            !_m.containsKey("modified_at") ? dev.unofficialbox.core.Tristate.<OffsetDateTime>absent() : (_m.get("modified_at") == null ? dev.unofficialbox.core.Tristate.<OffsetDateTime>ofNull() : dev.unofficialbox.core.Tristate.of((_m.get("modified_at") == null ? null : java.time.OffsetDateTime.parse(dev.unofficialbox.core.Json.asString(_m.get("modified_at")))))),
            (!_m.containsKey("description") || _m.get("description") == null) ? java.util.Optional.<String>empty() : java.util.Optional.of(dev.unofficialbox.core.Json.asString(_m.get("description"))),
            (!_m.containsKey("size") || _m.get("size") == null) ? java.util.Optional.<Long>empty() : java.util.Optional.of(dev.unofficialbox.core.Json.asLong(_m.get("size"))),
            (!_m.containsKey("path_collection") || _m.get("path_collection") == null) ? java.util.Optional.<FilePathCollection>empty() : java.util.Optional.of((_m.get("path_collection") == null ? null : FilePathCollection.fromJson(_m.get("path_collection")))),
            (!_m.containsKey("created_by") || _m.get("created_by") == null) ? java.util.Optional.<UserMini>empty() : java.util.Optional.of((_m.get("created_by") == null ? null : UserMini.fromJson(_m.get("created_by")))),
            (!_m.containsKey("modified_by") || _m.get("modified_by") == null) ? java.util.Optional.<UserMini>empty() : java.util.Optional.of((_m.get("modified_by") == null ? null : UserMini.fromJson(_m.get("modified_by")))),
            !_m.containsKey("trashed_at") ? dev.unofficialbox.core.Tristate.<OffsetDateTime>absent() : (_m.get("trashed_at") == null ? dev.unofficialbox.core.Tristate.<OffsetDateTime>ofNull() : dev.unofficialbox.core.Tristate.of((_m.get("trashed_at") == null ? null : java.time.OffsetDateTime.parse(dev.unofficialbox.core.Json.asString(_m.get("trashed_at")))))),
            !_m.containsKey("purged_at") ? dev.unofficialbox.core.Tristate.<OffsetDateTime>absent() : (_m.get("purged_at") == null ? dev.unofficialbox.core.Tristate.<OffsetDateTime>ofNull() : dev.unofficialbox.core.Tristate.of((_m.get("purged_at") == null ? null : java.time.OffsetDateTime.parse(dev.unofficialbox.core.Json.asString(_m.get("purged_at")))))),
            !_m.containsKey("content_created_at") ? dev.unofficialbox.core.Tristate.<OffsetDateTime>absent() : (_m.get("content_created_at") == null ? dev.unofficialbox.core.Tristate.<OffsetDateTime>ofNull() : dev.unofficialbox.core.Tristate.of((_m.get("content_created_at") == null ? null : java.time.OffsetDateTime.parse(dev.unofficialbox.core.Json.asString(_m.get("content_created_at")))))),
            !_m.containsKey("content_modified_at") ? dev.unofficialbox.core.Tristate.<OffsetDateTime>absent() : (_m.get("content_modified_at") == null ? dev.unofficialbox.core.Tristate.<OffsetDateTime>ofNull() : dev.unofficialbox.core.Tristate.of((_m.get("content_modified_at") == null ? null : java.time.OffsetDateTime.parse(dev.unofficialbox.core.Json.asString(_m.get("content_modified_at")))))),
            (!_m.containsKey("owned_by") || _m.get("owned_by") == null) ? java.util.Optional.<UserMini>empty() : java.util.Optional.of((_m.get("owned_by") == null ? null : UserMini.fromJson(_m.get("owned_by")))),
            !_m.containsKey("shared_link") ? dev.unofficialbox.core.Tristate.<FileSharedLink>absent() : (_m.get("shared_link") == null ? dev.unofficialbox.core.Tristate.<FileSharedLink>ofNull() : dev.unofficialbox.core.Tristate.of((_m.get("shared_link") == null ? null : FileSharedLink.fromJson(_m.get("shared_link"))))),
            !_m.containsKey("folder_upload_email") ? dev.unofficialbox.core.Tristate.<FolderFolderUploadEmail>absent() : (_m.get("folder_upload_email") == null ? dev.unofficialbox.core.Tristate.<FolderFolderUploadEmail>ofNull() : dev.unofficialbox.core.Tristate.of((_m.get("folder_upload_email") == null ? null : FolderFolderUploadEmail.fromJson(_m.get("folder_upload_email"))))),
            !_m.containsKey("parent") ? dev.unofficialbox.core.Tristate.<FolderMini>absent() : (_m.get("parent") == null ? dev.unofficialbox.core.Tristate.<FolderMini>ofNull() : dev.unofficialbox.core.Tristate.of((_m.get("parent") == null ? null : FolderMini.fromJson(_m.get("parent"))))),
            (!_m.containsKey("item_status") || _m.get("item_status") == null) ? java.util.Optional.<FileItemStatus>empty() : java.util.Optional.of((_m.get("item_status") == null ? null : FileItemStatus.fromJson(_m.get("item_status")))),
            (!_m.containsKey("item_collection") || _m.get("item_collection") == null) ? java.util.Optional.<Items>empty() : java.util.Optional.of((_m.get("item_collection") == null ? null : Items.fromJson(_m.get("item_collection")))),
            (!_m.containsKey("sync_state") || _m.get("sync_state") == null) ? java.util.Optional.<FolderFullSyncState>empty() : java.util.Optional.of((_m.get("sync_state") == null ? null : FolderFullSyncState.fromJson(_m.get("sync_state")))),
            (!_m.containsKey("has_collaborations") || _m.get("has_collaborations") == null) ? java.util.Optional.<Boolean>empty() : java.util.Optional.of(dev.unofficialbox.core.Json.asBoolean(_m.get("has_collaborations"))),
            (!_m.containsKey("permissions") || _m.get("permissions") == null) ? java.util.Optional.<FolderFullPermissions>empty() : java.util.Optional.of((_m.get("permissions") == null ? null : FolderFullPermissions.fromJson(_m.get("permissions")))),
            (!_m.containsKey("tags") || _m.get("tags") == null) ? java.util.Optional.<List<String>>empty() : java.util.Optional.of(dev.unofficialbox.core.Json.decodeList(_m.get("tags"), _x0 -> dev.unofficialbox.core.Json.asString(_x0))),
            (!_m.containsKey("can_non_owners_invite") || _m.get("can_non_owners_invite") == null) ? java.util.Optional.<Boolean>empty() : java.util.Optional.of(dev.unofficialbox.core.Json.asBoolean(_m.get("can_non_owners_invite"))),
            (!_m.containsKey("is_externally_owned") || _m.get("is_externally_owned") == null) ? java.util.Optional.<Boolean>empty() : java.util.Optional.of(dev.unofficialbox.core.Json.asBoolean(_m.get("is_externally_owned"))),
            (!_m.containsKey("metadata") || _m.get("metadata") == null) ? java.util.Optional.<Map<String, Map<String, MetadataFull>>>empty() : java.util.Optional.of(dev.unofficialbox.core.Json.decodeMap(_m.get("metadata"), _x0 -> dev.unofficialbox.core.Json.decodeMap(_x0, _x1 -> (_x1 == null ? null : MetadataFull.fromJson(_x1))))),
            (!_m.containsKey("is_collaboration_restricted_to_enterprise") || _m.get("is_collaboration_restricted_to_enterprise") == null) ? java.util.Optional.<Boolean>empty() : java.util.Optional.of(dev.unofficialbox.core.Json.asBoolean(_m.get("is_collaboration_restricted_to_enterprise"))),
            (!_m.containsKey("allowed_shared_link_access_levels") || _m.get("allowed_shared_link_access_levels") == null) ? java.util.Optional.<List<SharedLinkAccess>>empty() : java.util.Optional.of(dev.unofficialbox.core.Json.decodeList(_m.get("allowed_shared_link_access_levels"), _x0 -> (_x0 == null ? null : SharedLinkAccess.fromJson(_x0)))),
            (!_m.containsKey("allowed_invitee_roles") || _m.get("allowed_invitee_roles") == null) ? java.util.Optional.<List<FileFullAllowedInviteeRoles>>empty() : java.util.Optional.of(dev.unofficialbox.core.Json.decodeList(_m.get("allowed_invitee_roles"), _x0 -> (_x0 == null ? null : FileFullAllowedInviteeRoles.fromJson(_x0)))),
            (!_m.containsKey("watermark_info") || _m.get("watermark_info") == null) ? java.util.Optional.<FileFullWatermarkInfo>empty() : java.util.Optional.of((_m.get("watermark_info") == null ? null : FileFullWatermarkInfo.fromJson(_m.get("watermark_info")))),
            (!_m.containsKey("is_accessible_via_shared_link") || _m.get("is_accessible_via_shared_link") == null) ? java.util.Optional.<Boolean>empty() : java.util.Optional.of(dev.unofficialbox.core.Json.asBoolean(_m.get("is_accessible_via_shared_link"))),
            (!_m.containsKey("can_non_owners_view_collaborators") || _m.get("can_non_owners_view_collaborators") == null) ? java.util.Optional.<Boolean>empty() : java.util.Optional.of(dev.unofficialbox.core.Json.asBoolean(_m.get("can_non_owners_view_collaborators"))),
            !_m.containsKey("classification") ? dev.unofficialbox.core.Tristate.<FileFullClassification>absent() : (_m.get("classification") == null ? dev.unofficialbox.core.Tristate.<FileFullClassification>ofNull() : dev.unofficialbox.core.Tristate.of((_m.get("classification") == null ? null : FileFullClassification.fromJson(_m.get("classification"))))),
            (!_m.containsKey("is_associated_with_app_item") || _m.get("is_associated_with_app_item") == null) ? java.util.Optional.<Boolean>empty() : java.util.Optional.of(dev.unofficialbox.core.Json.asBoolean(_m.get("is_associated_with_app_item")))
        );
    }
}
