// Code generated by box-gantry 0.1.0 (spec ee7d55aedefe2fa0) for Box API 2024.0. DO NOT EDIT.
package dev.unofficialbox.model.schemas;

import module java.base;

public record FolderFullPermissions(
    Boolean canDelete,
    Boolean canDownload,
    Boolean canInviteCollaborator,
    Boolean canRename,
    Boolean canSetShareAccess,
    Boolean canShare,
    Boolean canUpload,
    Optional<Boolean> canApplyWatermark) {
    public java.util.Map<String, Object> toJson() {
        java.util.Map<String, Object> _m = new java.util.LinkedHashMap<>();
        _m.put("can_delete", canDelete());
        _m.put("can_download", canDownload());
        _m.put("can_invite_collaborator", canInviteCollaborator());
        _m.put("can_rename", canRename());
        _m.put("can_set_share_access", canSetShareAccess());
        _m.put("can_share", canShare());
        _m.put("can_upload", canUpload());
        canApplyWatermark().ifPresent(_v -> _m.put("can_apply_watermark", _v));
        return _m;
    }

    public static FolderFullPermissions fromJson(Object _json) {
        java.util.Map<String, Object> _m = dev.unofficialbox.core.Json.asObject(_json);
        return new FolderFullPermissions(
            dev.unofficialbox.core.Json.asBoolean(_m.get("can_delete")),
            dev.unofficialbox.core.Json.asBoolean(_m.get("can_download")),
            dev.unofficialbox.core.Json.asBoolean(_m.get("can_invite_collaborator")),
            dev.unofficialbox.core.Json.asBoolean(_m.get("can_rename")),
            dev.unofficialbox.core.Json.asBoolean(_m.get("can_set_share_access")),
            dev.unofficialbox.core.Json.asBoolean(_m.get("can_share")),
            dev.unofficialbox.core.Json.asBoolean(_m.get("can_upload")),
            (!_m.containsKey("can_apply_watermark") || _m.get("can_apply_watermark") == null) ? java.util.Optional.<Boolean>empty() : java.util.Optional.of(dev.unofficialbox.core.Json.asBoolean(_m.get("can_apply_watermark")))
        );
    }
}
