// Code generated by box-gantry 0.1.0 (spec ee7d55aedefe2fa0) for Box API 2026.0. DO NOT EDIT.
package dev.unofficialbox.model.schemas;

public record FolderReferenceType(String value) {
    public static final FolderReferenceType FOLDER = new FolderReferenceType("folder");

    public String toJson() {
        return value;
    }

    public static FolderReferenceType fromJson(Object _json) {
        return new FolderReferenceType(dev.unofficialbox.core.Json.asString(_json));
    }
}
