// Code generated by box-gantry 0.1.0 (spec ee7d55aedefe2fa0) for Box API 2024.0. DO NOT EDIT.
package dev.unofficialbox.model.schemas;

public record GetAuthorizeResponseType(String value) {
    public static final GetAuthorizeResponseType CODE = new GetAuthorizeResponseType("code");

    public String toJson() {
        return value;
    }

    public static GetAuthorizeResponseType fromJson(Object _json) {
        return new GetAuthorizeResponseType(dev.unofficialbox.core.Json.asString(_json));
    }
}
