// Code generated by box-gantry 0.1.0 (spec ee7d55aedefe2fa0) for Box API 2024.0. DO NOT EDIT.
package dev.unofficialbox.model.schemas;

public record GetScope(String value) {
    public static final GetScope USER_CONTENT = new GetScope("user_content");
    public static final GetScope ENTERPRISE_CONTENT = new GetScope("enterprise_content");

    public String toJson() {
        return value;
    }

    public static GetScope fromJson(Object _json) {
        return new GetScope(dev.unofficialbox.core.Json.asString(_json));
    }
}
