// Code generated by box-gantry 0.1.0 (spec ee7d55aedefe2fa0) for Box API 2024.0. DO NOT EDIT.
package dev.unofficialbox.model.schemas;

public record GetTosType(String value) {
    public static final GetTosType EXTERNAL = new GetTosType("external");
    public static final GetTosType MANAGED = new GetTosType("managed");

    public String toJson() {
        return value;
    }

    public static GetTosType fromJson(Object _json) {
        return new GetTosType(dev.unofficialbox.core.Json.asString(_json));
    }
}
