// Code generated by box-gantry 0.1.0 (spec ee7d55aedefe2fa0) for Box API 2024.0. DO NOT EDIT.
package dev.unofficialbox.model.schemas;

public record GroupType(String value) {
    public static final GroupType GROUP = new GroupType("group");

    public String toJson() {
        return value;
    }

    public static GroupType fromJson(Object _json) {
        return new GroupType(dev.unofficialbox.core.Json.asString(_json));
    }
}
