// Code generated by box-gantry 0.1.0 (spec ee7d55aedefe2fa0) for Box API 2025.0. DO NOT EDIT.
package dev.unofficialbox.model.schemas;

public record GroupMiniGroupType(String value) {
    public static final GroupMiniGroupType MANAGED_GROUP = new GroupMiniGroupType("managed_group");
    public static final GroupMiniGroupType ALL_USERS_GROUP = new GroupMiniGroupType("all_users_group");

    public String toJson() {
        return value;
    }

    public static GroupMiniGroupType fromJson(Object _json) {
        return new GroupMiniGroupType(dev.unofficialbox.core.Json.asString(_json));
    }
}
