// Code generated by box-gantry 0.1.0 (spec ee7d55aedefe2fa0) for Box API 2024.0. DO NOT EDIT.
package dev.unofficialbox.model.schemas;

import module java.base;

public record GroupUpdateRequest(
    Optional<String> name,
    Optional<String> provenance,
    Optional<String> externalSyncIdentifier,
    Optional<String> description,
    Optional<GroupFullInvitabilityLevel> invitabilityLevel,
    Optional<GroupFullInvitabilityLevel> memberViewabilityLevel) {
    public java.util.Map<String, Object> toJson() {
        java.util.Map<String, Object> _m = new java.util.LinkedHashMap<>();
        name().ifPresent(_v -> _m.put("name", _v));
        provenance().ifPresent(_v -> _m.put("provenance", _v));
        externalSyncIdentifier().ifPresent(_v -> _m.put("external_sync_identifier", _v));
        description().ifPresent(_v -> _m.put("description", _v));
        invitabilityLevel().ifPresent(_v -> _m.put("invitability_level", (_v == null ? null : _v.toJson())));
        memberViewabilityLevel().ifPresent(_v -> _m.put("member_viewability_level", (_v == null ? null : _v.toJson())));
        return _m;
    }

    public static GroupUpdateRequest fromJson(Object _json) {
        java.util.Map<String, Object> _m = dev.unofficialbox.core.Json.asObject(_json);
        return new GroupUpdateRequest(
            (!_m.containsKey("name") || _m.get("name") == null) ? java.util.Optional.<String>empty() : java.util.Optional.of(dev.unofficialbox.core.Json.asString(_m.get("name"))),
            (!_m.containsKey("provenance") || _m.get("provenance") == null) ? java.util.Optional.<String>empty() : java.util.Optional.of(dev.unofficialbox.core.Json.asString(_m.get("provenance"))),
            (!_m.containsKey("external_sync_identifier") || _m.get("external_sync_identifier") == null) ? java.util.Optional.<String>empty() : java.util.Optional.of(dev.unofficialbox.core.Json.asString(_m.get("external_sync_identifier"))),
            (!_m.containsKey("description") || _m.get("description") == null) ? java.util.Optional.<String>empty() : java.util.Optional.of(dev.unofficialbox.core.Json.asString(_m.get("description"))),
            (!_m.containsKey("invitability_level") || _m.get("invitability_level") == null) ? java.util.Optional.<GroupFullInvitabilityLevel>empty() : java.util.Optional.of((_m.get("invitability_level") == null ? null : GroupFullInvitabilityLevel.fromJson(_m.get("invitability_level")))),
            (!_m.containsKey("member_viewability_level") || _m.get("member_viewability_level") == null) ? java.util.Optional.<GroupFullInvitabilityLevel>empty() : java.util.Optional.of((_m.get("member_viewability_level") == null ? null : GroupFullInvitabilityLevel.fromJson(_m.get("member_viewability_level"))))
        );
    }

    /** A fluent builder; unset optional fields default to empty. */
    public static Builder builder() {
        return new Builder();
    }

    public static final class Builder {
        private Optional<String> name = java.util.Optional.empty();
        private Optional<String> provenance = java.util.Optional.empty();
        private Optional<String> externalSyncIdentifier = java.util.Optional.empty();
        private Optional<String> description = java.util.Optional.empty();
        private Optional<GroupFullInvitabilityLevel> invitabilityLevel = java.util.Optional.empty();
        private Optional<GroupFullInvitabilityLevel> memberViewabilityLevel = java.util.Optional.empty();

        public Builder name(String name) {
            this.name = java.util.Optional.ofNullable(name);
            return this;
        }
        public Builder provenance(String provenance) {
            this.provenance = java.util.Optional.ofNullable(provenance);
            return this;
        }
        public Builder externalSyncIdentifier(String externalSyncIdentifier) {
            this.externalSyncIdentifier = java.util.Optional.ofNullable(externalSyncIdentifier);
            return this;
        }
        public Builder description(String description) {
            this.description = java.util.Optional.ofNullable(description);
            return this;
        }
        public Builder invitabilityLevel(GroupFullInvitabilityLevel invitabilityLevel) {
            this.invitabilityLevel = java.util.Optional.ofNullable(invitabilityLevel);
            return this;
        }
        public Builder memberViewabilityLevel(GroupFullInvitabilityLevel memberViewabilityLevel) {
            this.memberViewabilityLevel = java.util.Optional.ofNullable(memberViewabilityLevel);
            return this;
        }

        public GroupUpdateRequest build() {
            return new GroupUpdateRequest(
                name,
                provenance,
                externalSyncIdentifier,
                description,
                invitabilityLevel,
                memberViewabilityLevel
            );
        }
    }
}
