// Code generated by box-gantry 0.1.0 (spec ee7d55aedefe2fa0) for Box API 2025.0. DO NOT EDIT.
package dev.unofficialbox.model.schemas;

public sealed interface HubAccessGrantee
    permits HubCollaborationUser, GroupMini, HubAccessGrantee.Unknown {
    /** Serialize this variant, discriminator and all. */
    Object toJson();

    /** Dispatch on the discriminator to the matching variant. */
    static HubAccessGrantee fromJson(Object _json) {
        java.util.Map<String, Object> _m = dev.unofficialbox.core.Json.asObject(_json);
        String _tag = dev.unofficialbox.core.Json.asString(_m.get("type"));
        return switch (_tag) {
            case "user" -> HubCollaborationUser.fromJson(_json);
            case "group" -> GroupMini.fromJson(_json);
            case null, default -> new Unknown(_json);
        };
    }

    /** An unrecognized discriminator, retained verbatim (open union). */
    record Unknown(Object value) implements HubAccessGrantee {
        public Object toJson() {
            return value;
        }
    }
}
