// Code generated by box-gantry 0.1.0 (spec ee7d55aedefe2fa0) for Box API 2025.0. DO NOT EDIT.
package dev.unofficialbox.model.schemas;

public record HubCopyHubAccess(String value) {
    public static final HubCopyHubAccess ALL = new HubCopyHubAccess("all");
    public static final HubCopyHubAccess COMPANY = new HubCopyHubAccess("company");
    public static final HubCopyHubAccess NONE = new HubCopyHubAccess("none");

    public String toJson() {
        return value;
    }

    public static HubCopyHubAccess fromJson(Object _json) {
        return new HubCopyHubAccess(dev.unofficialbox.core.Json.asString(_json));
    }
}
