// Code generated by box-gantry 0.1.0 (spec ee7d55aedefe2fa0) for Box API 2025.0. DO NOT EDIT.
package dev.unofficialbox.model.schemas;

public record HubCollaborationUserType(String value) {
    public static final HubCollaborationUserType USER = new HubCollaborationUserType("user");

    public String toJson() {
        return value;
    }

    public static HubCollaborationUserType fromJson(Object _json) {
        return new HubCollaborationUserType(dev.unofficialbox.core.Json.asString(_json));
    }
}
