// Code generated by box-gantry 0.1.0 (spec ee7d55aedefe2fa0) for Box API 2025.0. DO NOT EDIT.
package dev.unofficialbox.model.schemas;

public record HubDividerBlockType(String value) {
    public static final HubDividerBlockType DIVIDER = new HubDividerBlockType("divider");

    public String toJson() {
        return value;
    }

    public static HubDividerBlockType fromJson(Object _json) {
        return new HubDividerBlockType(dev.unofficialbox.core.Json.asString(_json));
    }
}
