// Code generated by box-gantry 0.1.0 (spec ee7d55aedefe2fa0) for Box API 2024.0. DO NOT EDIT.
package dev.unofficialbox.model.schemas;

import module java.base;

public record IntegrationMappingsTeams(Optional<List<IntegrationMappingTeams>> entries) {
    public java.util.Map<String, Object> toJson() {
        java.util.Map<String, Object> _m = new java.util.LinkedHashMap<>();
        entries().ifPresent(_v -> _m.put("entries", dev.unofficialbox.core.Json.encodeList(_v, _x0 -> (_x0 == null ? null : _x0.toJson()))));
        return _m;
    }

    public static IntegrationMappingsTeams fromJson(Object _json) {
        java.util.Map<String, Object> _m = dev.unofficialbox.core.Json.asObject(_json);
        return new IntegrationMappingsTeams(
            (!_m.containsKey("entries") || _m.get("entries") == null) ? java.util.Optional.<List<IntegrationMappingTeams>>empty() : java.util.Optional.of(dev.unofficialbox.core.Json.decodeList(_m.get("entries"), _x0 -> (_x0 == null ? null : IntegrationMappingTeams.fromJson(_x0))))
        );
    }

    /** A fluent builder; unset optional fields default to empty. */
    public static Builder builder() {
        return new Builder();
    }

    public static final class Builder {
        private Optional<List<IntegrationMappingTeams>> entries = java.util.Optional.empty();

        public Builder entries(List<IntegrationMappingTeams> entries) {
            this.entries = java.util.Optional.ofNullable(entries);
            return this;
        }

        public IntegrationMappingsTeams build() {
            return new IntegrationMappingsTeams(
                entries
            );
        }
    }
}
