// Code generated by box-gantry 0.1.0 (spec ee7d55aedefe2fa0) for Box API 2024.0. DO NOT EDIT.
package dev.unofficialbox.model.schemas;

public record IntegrationMappingPartnerItemSlackType(String value) {
    public static final IntegrationMappingPartnerItemSlackType CHANNEL = new IntegrationMappingPartnerItemSlackType("channel");

    public String toJson() {
        return value;
    }

    public static IntegrationMappingPartnerItemSlackType fromJson(Object _json) {
        return new IntegrationMappingPartnerItemSlackType(dev.unofficialbox.core.Json.asString(_json));
    }
}
