// Code generated by box-gantry 0.1.0 (spec ee7d55aedefe2fa0) for Box API 2024.0. DO NOT EDIT.
package dev.unofficialbox.model.schemas;

import module java.base;

public record IntegrationMappingSlackCreateRequest(
    IntegrationMappingPartnerItemSlack partnerItem,
    IntegrationMappingBoxItemSlack boxItem,
    Optional<IntegrationMappingSlackOptions> options) {
    public java.util.Map<String, Object> toJson() {
        java.util.Map<String, Object> _m = new java.util.LinkedHashMap<>();
        _m.put("partner_item", (partnerItem() == null ? null : partnerItem().toJson()));
        _m.put("box_item", (boxItem() == null ? null : boxItem().toJson()));
        options().ifPresent(_v -> _m.put("options", (_v == null ? null : _v.toJson())));
        return _m;
    }

    public static IntegrationMappingSlackCreateRequest fromJson(Object _json) {
        java.util.Map<String, Object> _m = dev.unofficialbox.core.Json.asObject(_json);
        return new IntegrationMappingSlackCreateRequest(
            (_m.get("partner_item") == null ? null : IntegrationMappingPartnerItemSlack.fromJson(_m.get("partner_item"))),
            (_m.get("box_item") == null ? null : IntegrationMappingBoxItemSlack.fromJson(_m.get("box_item"))),
            (!_m.containsKey("options") || _m.get("options") == null) ? java.util.Optional.<IntegrationMappingSlackOptions>empty() : java.util.Optional.of((_m.get("options") == null ? null : IntegrationMappingSlackOptions.fromJson(_m.get("options"))))
        );
    }
}
