// Code generated by box-gantry 0.1.0 (spec ee7d55aedefe2fa0) for Box API 2024.0. DO NOT EDIT.
package dev.unofficialbox.model.schemas;

public record IntegrationMappingTeamsIntegrationType(String value) {
    public static final IntegrationMappingTeamsIntegrationType TEAMS = new IntegrationMappingTeamsIntegrationType("teams");

    public String toJson() {
        return value;
    }

    public static IntegrationMappingTeamsIntegrationType fromJson(Object _json) {
        return new IntegrationMappingTeamsIntegrationType(dev.unofficialbox.core.Json.asString(_json));
    }
}
