// Code generated by box-gantry 0.1.0 (spec ee7d55aedefe2fa0) for Box API 2024.0. DO NOT EDIT.
package dev.unofficialbox.model.schemas;

public record ItemType(String value) {
    public static final ItemType FILE = new ItemType("file");
    public static final ItemType COMMENT = new ItemType("comment");

    public String toJson() {
        return value;
    }

    public static ItemType fromJson(Object _json) {
        return new ItemType(dev.unofficialbox.core.Json.asString(_json));
    }
}
