// Code generated by box-gantry 0.1.0 (spec ee7d55aedefe2fa0) for Box API 2025.0. DO NOT EDIT.
package dev.unofficialbox.model.schemas;

import module java.base;
import dev.unofficialbox.core.Tristate;

public record KeysafeSettings(
    Optional<Boolean> keysafeEnabled,
    Tristate<String> cloudProvider,
    Tristate<String> keyId,
    Tristate<String> accountId,
    Tristate<String> locationId,
    Tristate<String> projectId,
    Tristate<String> keyringId) {
    public java.util.Map<String, Object> toJson() {
        java.util.Map<String, Object> _m = new java.util.LinkedHashMap<>();
        keysafeEnabled().ifPresent(_v -> _m.put("keysafe_enabled", _v));
        if (cloudProvider().isPresent()) { _m.put("cloud_provider", cloudProvider().value()); }
        else if (cloudProvider().isNull()) { _m.put("cloud_provider", null); }
        if (keyId().isPresent()) { _m.put("key_id", keyId().value()); }
        else if (keyId().isNull()) { _m.put("key_id", null); }
        if (accountId().isPresent()) { _m.put("account_id", accountId().value()); }
        else if (accountId().isNull()) { _m.put("account_id", null); }
        if (locationId().isPresent()) { _m.put("location_id", locationId().value()); }
        else if (locationId().isNull()) { _m.put("location_id", null); }
        if (projectId().isPresent()) { _m.put("project_id", projectId().value()); }
        else if (projectId().isNull()) { _m.put("project_id", null); }
        if (keyringId().isPresent()) { _m.put("keyring_id", keyringId().value()); }
        else if (keyringId().isNull()) { _m.put("keyring_id", null); }
        return _m;
    }

    public static KeysafeSettings fromJson(Object _json) {
        java.util.Map<String, Object> _m = dev.unofficialbox.core.Json.asObject(_json);
        return new KeysafeSettings(
            (!_m.containsKey("keysafe_enabled") || _m.get("keysafe_enabled") == null) ? java.util.Optional.<Boolean>empty() : java.util.Optional.of(dev.unofficialbox.core.Json.asBoolean(_m.get("keysafe_enabled"))),
            !_m.containsKey("cloud_provider") ? dev.unofficialbox.core.Tristate.<String>absent() : (_m.get("cloud_provider") == null ? dev.unofficialbox.core.Tristate.<String>ofNull() : dev.unofficialbox.core.Tristate.of(dev.unofficialbox.core.Json.asString(_m.get("cloud_provider")))),
            !_m.containsKey("key_id") ? dev.unofficialbox.core.Tristate.<String>absent() : (_m.get("key_id") == null ? dev.unofficialbox.core.Tristate.<String>ofNull() : dev.unofficialbox.core.Tristate.of(dev.unofficialbox.core.Json.asString(_m.get("key_id")))),
            !_m.containsKey("account_id") ? dev.unofficialbox.core.Tristate.<String>absent() : (_m.get("account_id") == null ? dev.unofficialbox.core.Tristate.<String>ofNull() : dev.unofficialbox.core.Tristate.of(dev.unofficialbox.core.Json.asString(_m.get("account_id")))),
            !_m.containsKey("location_id") ? dev.unofficialbox.core.Tristate.<String>absent() : (_m.get("location_id") == null ? dev.unofficialbox.core.Tristate.<String>ofNull() : dev.unofficialbox.core.Tristate.of(dev.unofficialbox.core.Json.asString(_m.get("location_id")))),
            !_m.containsKey("project_id") ? dev.unofficialbox.core.Tristate.<String>absent() : (_m.get("project_id") == null ? dev.unofficialbox.core.Tristate.<String>ofNull() : dev.unofficialbox.core.Tristate.of(dev.unofficialbox.core.Json.asString(_m.get("project_id")))),
            !_m.containsKey("keyring_id") ? dev.unofficialbox.core.Tristate.<String>absent() : (_m.get("keyring_id") == null ? dev.unofficialbox.core.Tristate.<String>ofNull() : dev.unofficialbox.core.Tristate.of(dev.unofficialbox.core.Json.asString(_m.get("keyring_id"))))
        );
    }

    /** A fluent builder; unset optional fields default to empty. */
    public static Builder builder() {
        return new Builder();
    }

    public static final class Builder {
        private Optional<Boolean> keysafeEnabled = java.util.Optional.empty();
        private Tristate<String> cloudProvider;
        private Tristate<String> keyId;
        private Tristate<String> accountId;
        private Tristate<String> locationId;
        private Tristate<String> projectId;
        private Tristate<String> keyringId;

        public Builder keysafeEnabled(Boolean keysafeEnabled) {
            this.keysafeEnabled = java.util.Optional.ofNullable(keysafeEnabled);
            return this;
        }
        public Builder cloudProvider(Tristate<String> cloudProvider) {
            this.cloudProvider = cloudProvider;
            return this;
        }
        public Builder keyId(Tristate<String> keyId) {
            this.keyId = keyId;
            return this;
        }
        public Builder accountId(Tristate<String> accountId) {
            this.accountId = accountId;
            return this;
        }
        public Builder locationId(Tristate<String> locationId) {
            this.locationId = locationId;
            return this;
        }
        public Builder projectId(Tristate<String> projectId) {
            this.projectId = projectId;
            return this;
        }
        public Builder keyringId(Tristate<String> keyringId) {
            this.keyringId = keyringId;
            return this;
        }

        public KeysafeSettings build() {
            return new KeysafeSettings(
                keysafeEnabled,
                cloudProvider,
                keyId,
                accountId,
                locationId,
                projectId,
                keyringId
            );
        }
    }
}
