// Code generated by box-gantry 0.1.0 (spec ee7d55aedefe2fa0) for Box API 2025.0. DO NOT EDIT.
package dev.unofficialbox.model.schemas;

public record KeysafeValue(Object value) {
    public Object toJson() {
        return value;
    }

    public static KeysafeValue fromJson(Object _json) {
        return new KeysafeValue(_json);
    }
}
