// Code generated by box-gantry 0.1.0 (spec ee7d55aedefe2fa0) for Box API 2024.0. DO NOT EDIT.
package dev.unofficialbox.model.schemas;

public record KeywordSkillCardType(String value) {
    public static final KeywordSkillCardType SKILL_CARD = new KeywordSkillCardType("skill_card");

    public String toJson() {
        return value;
    }

    public static KeywordSkillCardType fromJson(Object _json) {
        return new KeywordSkillCardType(dev.unofficialbox.core.Json.asString(_json));
    }
}
