// Code generated by box-gantry 0.1.0 (spec ee7d55aedefe2fa0) for Box API 2024.0. DO NOT EDIT.
package dev.unofficialbox.model.schemas;

import module java.base;

public record KeywordSkillCardEntries(Optional<String> text) {
    public java.util.Map<String, Object> toJson() {
        java.util.Map<String, Object> _m = new java.util.LinkedHashMap<>();
        text().ifPresent(_v -> _m.put("text", _v));
        return _m;
    }

    public static KeywordSkillCardEntries fromJson(Object _json) {
        java.util.Map<String, Object> _m = dev.unofficialbox.core.Json.asObject(_json);
        return new KeywordSkillCardEntries(
            (!_m.containsKey("text") || _m.get("text") == null) ? java.util.Optional.<String>empty() : java.util.Optional.of(dev.unofficialbox.core.Json.asString(_m.get("text")))
        );
    }
}
