// Code generated by box-gantry 0.1.0 (spec ee7d55aedefe2fa0) for Box API 2024.0. DO NOT EDIT.
package dev.unofficialbox.model.schemas;

import module java.base;

public record KeywordSkillCardSkillCardTitle(Optional<String> code, String message) {
    public java.util.Map<String, Object> toJson() {
        java.util.Map<String, Object> _m = new java.util.LinkedHashMap<>();
        code().ifPresent(_v -> _m.put("code", _v));
        _m.put("message", message());
        return _m;
    }

    public static KeywordSkillCardSkillCardTitle fromJson(Object _json) {
        java.util.Map<String, Object> _m = dev.unofficialbox.core.Json.asObject(_json);
        return new KeywordSkillCardSkillCardTitle(
            (!_m.containsKey("code") || _m.get("code") == null) ? java.util.Optional.<String>empty() : java.util.Optional.of(dev.unofficialbox.core.Json.asString(_m.get("code"))),
            dev.unofficialbox.core.Json.asString(_m.get("message"))
        );
    }

    /** A fluent builder; unset optional fields default to empty. */
    public static Builder builder() {
        return new Builder();
    }

    public static final class Builder {
        private Optional<String> code = java.util.Optional.empty();
        private String message;

        public Builder code(String code) {
            this.code = java.util.Optional.ofNullable(code);
            return this;
        }
        public Builder message(String message) {
            this.message = message;
            return this;
        }

        public KeywordSkillCardSkillCardTitle build() {
            return new KeywordSkillCardSkillCardTitle(
                code,
                message
            );
        }
    }
}
