// Code generated by box-gantry 0.1.0 (spec ee7d55aedefe2fa0) for Box API 2024.0. DO NOT EDIT.
package dev.unofficialbox.model.schemas;

public record KeywordSkillCardSkillCardType(String value) {
    public static final KeywordSkillCardSkillCardType KEYWORD = new KeywordSkillCardSkillCardType("keyword");

    public String toJson() {
        return value;
    }

    public static KeywordSkillCardSkillCardType fromJson(Object _json) {
        return new KeywordSkillCardSkillCardType(dev.unofficialbox.core.Json.asString(_json));
    }
}
