// Code generated by box-gantry 0.1.0 (spec ee7d55aedefe2fa0) for Box API 2024.0. DO NOT EDIT.
package dev.unofficialbox.model.schemas;

import module java.base;

public record LegalHoldPolicyUpdateRequest(
    Optional<String> policyName,
    Optional<String> description,
    Optional<String> releaseNotes) {
    public java.util.Map<String, Object> toJson() {
        java.util.Map<String, Object> _m = new java.util.LinkedHashMap<>();
        policyName().ifPresent(_v -> _m.put("policy_name", _v));
        description().ifPresent(_v -> _m.put("description", _v));
        releaseNotes().ifPresent(_v -> _m.put("release_notes", _v));
        return _m;
    }

    public static LegalHoldPolicyUpdateRequest fromJson(Object _json) {
        java.util.Map<String, Object> _m = dev.unofficialbox.core.Json.asObject(_json);
        return new LegalHoldPolicyUpdateRequest(
            (!_m.containsKey("policy_name") || _m.get("policy_name") == null) ? java.util.Optional.<String>empty() : java.util.Optional.of(dev.unofficialbox.core.Json.asString(_m.get("policy_name"))),
            (!_m.containsKey("description") || _m.get("description") == null) ? java.util.Optional.<String>empty() : java.util.Optional.of(dev.unofficialbox.core.Json.asString(_m.get("description"))),
            (!_m.containsKey("release_notes") || _m.get("release_notes") == null) ? java.util.Optional.<String>empty() : java.util.Optional.of(dev.unofficialbox.core.Json.asString(_m.get("release_notes")))
        );
    }

    /** A fluent builder; unset optional fields default to empty. */
    public static Builder builder() {
        return new Builder();
    }

    public static final class Builder {
        private Optional<String> policyName = java.util.Optional.empty();
        private Optional<String> description = java.util.Optional.empty();
        private Optional<String> releaseNotes = java.util.Optional.empty();

        public Builder policyName(String policyName) {
            this.policyName = java.util.Optional.ofNullable(policyName);
            return this;
        }
        public Builder description(String description) {
            this.description = java.util.Optional.ofNullable(description);
            return this;
        }
        public Builder releaseNotes(String releaseNotes) {
            this.releaseNotes = java.util.Optional.ofNullable(releaseNotes);
            return this;
        }

        public LegalHoldPolicyUpdateRequest build() {
            return new LegalHoldPolicyUpdateRequest(
                policyName,
                description,
                releaseNotes
            );
        }
    }
}
