// Code generated by box-gantry 0.1.0 (spec ee7d55aedefe2fa0) for Box API 2024.0. DO NOT EDIT.
package dev.unofficialbox.model.schemas;

import module java.base;

public record LegalHoldPolicyAssignment(
    Optional<String> id,
    Optional<LegalHoldPolicyAssignmentType> type,
    Optional<LegalHoldPolicyMini> legalHoldPolicy,
    Optional<LegalHoldPolicyAssignedItem> assignedTo,
    Optional<UserMini> assignedBy,
    Optional<OffsetDateTime> assignedAt,
    Optional<OffsetDateTime> deletedAt) {
    public java.util.Map<String, Object> toJson() {
        java.util.Map<String, Object> _m = new java.util.LinkedHashMap<>();
        id().ifPresent(_v -> _m.put("id", _v));
        type().ifPresent(_v -> _m.put("type", (_v == null ? null : _v.toJson())));
        legalHoldPolicy().ifPresent(_v -> _m.put("legal_hold_policy", (_v == null ? null : _v.toJson())));
        assignedTo().ifPresent(_v -> _m.put("assigned_to", (_v == null ? null : _v.toJson())));
        assignedBy().ifPresent(_v -> _m.put("assigned_by", (_v == null ? null : _v.toJson())));
        assignedAt().ifPresent(_v -> _m.put("assigned_at", (_v == null ? null : _v.toString())));
        deletedAt().ifPresent(_v -> _m.put("deleted_at", (_v == null ? null : _v.toString())));
        return _m;
    }

    public static LegalHoldPolicyAssignment fromJson(Object _json) {
        java.util.Map<String, Object> _m = dev.unofficialbox.core.Json.asObject(_json);
        return new LegalHoldPolicyAssignment(
            (!_m.containsKey("id") || _m.get("id") == null) ? java.util.Optional.<String>empty() : java.util.Optional.of(dev.unofficialbox.core.Json.asString(_m.get("id"))),
            (!_m.containsKey("type") || _m.get("type") == null) ? java.util.Optional.<LegalHoldPolicyAssignmentType>empty() : java.util.Optional.of((_m.get("type") == null ? null : LegalHoldPolicyAssignmentType.fromJson(_m.get("type")))),
            (!_m.containsKey("legal_hold_policy") || _m.get("legal_hold_policy") == null) ? java.util.Optional.<LegalHoldPolicyMini>empty() : java.util.Optional.of((_m.get("legal_hold_policy") == null ? null : LegalHoldPolicyMini.fromJson(_m.get("legal_hold_policy")))),
            (!_m.containsKey("assigned_to") || _m.get("assigned_to") == null) ? java.util.Optional.<LegalHoldPolicyAssignedItem>empty() : java.util.Optional.of((_m.get("assigned_to") == null ? null : LegalHoldPolicyAssignedItem.fromJson(_m.get("assigned_to")))),
            (!_m.containsKey("assigned_by") || _m.get("assigned_by") == null) ? java.util.Optional.<UserMini>empty() : java.util.Optional.of((_m.get("assigned_by") == null ? null : UserMini.fromJson(_m.get("assigned_by")))),
            (!_m.containsKey("assigned_at") || _m.get("assigned_at") == null) ? java.util.Optional.<OffsetDateTime>empty() : java.util.Optional.of((_m.get("assigned_at") == null ? null : java.time.OffsetDateTime.parse(dev.unofficialbox.core.Json.asString(_m.get("assigned_at"))))),
            (!_m.containsKey("deleted_at") || _m.get("deleted_at") == null) ? java.util.Optional.<OffsetDateTime>empty() : java.util.Optional.of((_m.get("deleted_at") == null ? null : java.time.OffsetDateTime.parse(dev.unofficialbox.core.Json.asString(_m.get("deleted_at")))))
        );
    }

    /** A fluent builder; unset optional fields default to empty. */
    public static Builder builder() {
        return new Builder();
    }

    public static final class Builder {
        private Optional<String> id = java.util.Optional.empty();
        private Optional<LegalHoldPolicyAssignmentType> type = java.util.Optional.empty();
        private Optional<LegalHoldPolicyMini> legalHoldPolicy = java.util.Optional.empty();
        private Optional<LegalHoldPolicyAssignedItem> assignedTo = java.util.Optional.empty();
        private Optional<UserMini> assignedBy = java.util.Optional.empty();
        private Optional<OffsetDateTime> assignedAt = java.util.Optional.empty();
        private Optional<OffsetDateTime> deletedAt = java.util.Optional.empty();

        public Builder id(String id) {
            this.id = java.util.Optional.ofNullable(id);
            return this;
        }
        public Builder type(LegalHoldPolicyAssignmentType type) {
            this.type = java.util.Optional.ofNullable(type);
            return this;
        }
        public Builder legalHoldPolicy(LegalHoldPolicyMini legalHoldPolicy) {
            this.legalHoldPolicy = java.util.Optional.ofNullable(legalHoldPolicy);
            return this;
        }
        public Builder assignedTo(LegalHoldPolicyAssignedItem assignedTo) {
            this.assignedTo = java.util.Optional.ofNullable(assignedTo);
            return this;
        }
        public Builder assignedBy(UserMini assignedBy) {
            this.assignedBy = java.util.Optional.ofNullable(assignedBy);
            return this;
        }
        public Builder assignedAt(OffsetDateTime assignedAt) {
            this.assignedAt = java.util.Optional.ofNullable(assignedAt);
            return this;
        }
        public Builder deletedAt(OffsetDateTime deletedAt) {
            this.deletedAt = java.util.Optional.ofNullable(deletedAt);
            return this;
        }

        public LegalHoldPolicyAssignment build() {
            return new LegalHoldPolicyAssignment(
                id,
                type,
                legalHoldPolicy,
                assignedTo,
                assignedBy,
                assignedAt,
                deletedAt
            );
        }
    }
}
