// Code generated by box-gantry 0.1.0 (spec ee7d55aedefe2fa0) for Box API 2024.0. DO NOT EDIT.
package dev.unofficialbox.model.schemas;

import module java.base;

public record LegalHoldPolicyCreateRequest(
    String policyName,
    Optional<String> description,
    Optional<OffsetDateTime> filterStartedAt,
    Optional<OffsetDateTime> filterEndedAt,
    Optional<Boolean> isOngoing) {
    public java.util.Map<String, Object> toJson() {
        java.util.Map<String, Object> _m = new java.util.LinkedHashMap<>();
        _m.put("policy_name", policyName());
        description().ifPresent(_v -> _m.put("description", _v));
        filterStartedAt().ifPresent(_v -> _m.put("filter_started_at", (_v == null ? null : _v.toString())));
        filterEndedAt().ifPresent(_v -> _m.put("filter_ended_at", (_v == null ? null : _v.toString())));
        isOngoing().ifPresent(_v -> _m.put("is_ongoing", _v));
        return _m;
    }

    public static LegalHoldPolicyCreateRequest fromJson(Object _json) {
        java.util.Map<String, Object> _m = dev.unofficialbox.core.Json.asObject(_json);
        return new LegalHoldPolicyCreateRequest(
            dev.unofficialbox.core.Json.asString(_m.get("policy_name")),
            (!_m.containsKey("description") || _m.get("description") == null) ? java.util.Optional.<String>empty() : java.util.Optional.of(dev.unofficialbox.core.Json.asString(_m.get("description"))),
            (!_m.containsKey("filter_started_at") || _m.get("filter_started_at") == null) ? java.util.Optional.<OffsetDateTime>empty() : java.util.Optional.of((_m.get("filter_started_at") == null ? null : java.time.OffsetDateTime.parse(dev.unofficialbox.core.Json.asString(_m.get("filter_started_at"))))),
            (!_m.containsKey("filter_ended_at") || _m.get("filter_ended_at") == null) ? java.util.Optional.<OffsetDateTime>empty() : java.util.Optional.of((_m.get("filter_ended_at") == null ? null : java.time.OffsetDateTime.parse(dev.unofficialbox.core.Json.asString(_m.get("filter_ended_at"))))),
            (!_m.containsKey("is_ongoing") || _m.get("is_ongoing") == null) ? java.util.Optional.<Boolean>empty() : java.util.Optional.of(dev.unofficialbox.core.Json.asBoolean(_m.get("is_ongoing")))
        );
    }

    /** A fluent builder; unset optional fields default to empty. */
    public static Builder builder() {
        return new Builder();
    }

    public static final class Builder {
        private String policyName;
        private Optional<String> description = java.util.Optional.empty();
        private Optional<OffsetDateTime> filterStartedAt = java.util.Optional.empty();
        private Optional<OffsetDateTime> filterEndedAt = java.util.Optional.empty();
        private Optional<Boolean> isOngoing = java.util.Optional.empty();

        public Builder policyName(String policyName) {
            this.policyName = policyName;
            return this;
        }
        public Builder description(String description) {
            this.description = java.util.Optional.ofNullable(description);
            return this;
        }
        public Builder filterStartedAt(OffsetDateTime filterStartedAt) {
            this.filterStartedAt = java.util.Optional.ofNullable(filterStartedAt);
            return this;
        }
        public Builder filterEndedAt(OffsetDateTime filterEndedAt) {
            this.filterEndedAt = java.util.Optional.ofNullable(filterEndedAt);
            return this;
        }
        public Builder isOngoing(Boolean isOngoing) {
            this.isOngoing = java.util.Optional.ofNullable(isOngoing);
            return this;
        }

        public LegalHoldPolicyCreateRequest build() {
            return new LegalHoldPolicyCreateRequest(
                policyName,
                description,
                filterStartedAt,
                filterEndedAt,
                isOngoing
            );
        }
    }
}
