// Code generated by box-gantry 0.1.0 (spec ee7d55aedefe2fa0) for Box API 2024.0. DO NOT EDIT.
package dev.unofficialbox.model.schemas;

import module java.base;

public record LevelUpdateRequest(String displayName, Optional<String> description) {
    public java.util.Map<String, Object> toJson() {
        java.util.Map<String, Object> _m = new java.util.LinkedHashMap<>();
        _m.put("displayName", displayName());
        description().ifPresent(_v -> _m.put("description", _v));
        return _m;
    }

    public static LevelUpdateRequest fromJson(Object _json) {
        java.util.Map<String, Object> _m = dev.unofficialbox.core.Json.asObject(_json);
        return new LevelUpdateRequest(
            dev.unofficialbox.core.Json.asString(_m.get("displayName")),
            (!_m.containsKey("description") || _m.get("description") == null) ? java.util.Optional.<String>empty() : java.util.Optional.of(dev.unofficialbox.core.Json.asString(_m.get("description")))
        );
    }
}
