// Code generated by box-gantry 0.1.0 (spec ee7d55aedefe2fa0) for Box API 2024.0. DO NOT EDIT.
package dev.unofficialbox.model.schemas;

import module java.base;

public record MetadataTemplateSchemaCreateRequest(
    EnterpriseType scope,
    ClassificationTemplate2 templateKey,
    ClassificationTemplateDisplayName displayName,
    Optional<Boolean> hidden,
    Optional<Boolean> copyInstanceOnItemCopy,
    List<PostMetadataTemplateSchemaClassificationsFields> fields) {
    public java.util.Map<String, Object> toJson() {
        java.util.Map<String, Object> _m = new java.util.LinkedHashMap<>();
        _m.put("scope", (scope() == null ? null : scope().toJson()));
        _m.put("templateKey", (templateKey() == null ? null : templateKey().toJson()));
        _m.put("displayName", (displayName() == null ? null : displayName().toJson()));
        hidden().ifPresent(_v -> _m.put("hidden", _v));
        copyInstanceOnItemCopy().ifPresent(_v -> _m.put("copyInstanceOnItemCopy", _v));
        _m.put("fields", dev.unofficialbox.core.Json.encodeList(fields(), _x0 -> (_x0 == null ? null : _x0.toJson())));
        return _m;
    }

    public static MetadataTemplateSchemaCreateRequest fromJson(Object _json) {
        java.util.Map<String, Object> _m = dev.unofficialbox.core.Json.asObject(_json);
        return new MetadataTemplateSchemaCreateRequest(
            (_m.get("scope") == null ? null : EnterpriseType.fromJson(_m.get("scope"))),
            (_m.get("templateKey") == null ? null : ClassificationTemplate2.fromJson(_m.get("templateKey"))),
            (_m.get("displayName") == null ? null : ClassificationTemplateDisplayName.fromJson(_m.get("displayName"))),
            (!_m.containsKey("hidden") || _m.get("hidden") == null) ? java.util.Optional.<Boolean>empty() : java.util.Optional.of(dev.unofficialbox.core.Json.asBoolean(_m.get("hidden"))),
            (!_m.containsKey("copyInstanceOnItemCopy") || _m.get("copyInstanceOnItemCopy") == null) ? java.util.Optional.<Boolean>empty() : java.util.Optional.of(dev.unofficialbox.core.Json.asBoolean(_m.get("copyInstanceOnItemCopy"))),
            dev.unofficialbox.core.Json.decodeList(_m.get("fields"), _x0 -> (_x0 == null ? null : PostMetadataTemplateSchemaClassificationsFields.fromJson(_x0)))
        );
    }

    /** A fluent builder; unset optional fields default to empty. */
    public static Builder builder() {
        return new Builder();
    }

    public static final class Builder {
        private EnterpriseType scope;
        private ClassificationTemplate2 templateKey;
        private ClassificationTemplateDisplayName displayName;
        private Optional<Boolean> hidden = java.util.Optional.empty();
        private Optional<Boolean> copyInstanceOnItemCopy = java.util.Optional.empty();
        private List<PostMetadataTemplateSchemaClassificationsFields> fields;

        public Builder scope(EnterpriseType scope) {
            this.scope = scope;
            return this;
        }
        public Builder templateKey(ClassificationTemplate2 templateKey) {
            this.templateKey = templateKey;
            return this;
        }
        public Builder displayName(ClassificationTemplateDisplayName displayName) {
            this.displayName = displayName;
            return this;
        }
        public Builder hidden(Boolean hidden) {
            this.hidden = java.util.Optional.ofNullable(hidden);
            return this;
        }
        public Builder copyInstanceOnItemCopy(Boolean copyInstanceOnItemCopy) {
            this.copyInstanceOnItemCopy = java.util.Optional.ofNullable(copyInstanceOnItemCopy);
            return this;
        }
        public Builder fields(List<PostMetadataTemplateSchemaClassificationsFields> fields) {
            this.fields = fields;
            return this;
        }

        public MetadataTemplateSchemaCreateRequest build() {
            return new MetadataTemplateSchemaCreateRequest(
                scope,
                templateKey,
                displayName,
                hidden,
                copyInstanceOnItemCopy,
                fields
            );
        }
    }
}
