// Code generated by box-gantry 0.1.0 (spec ee7d55aedefe2fa0) for Box API 2024.0. DO NOT EDIT.
package dev.unofficialbox.model.schemas;

import module java.base;

public record MetadataTaxonomyLevel(
    Optional<String> displayName,
    Optional<String> description,
    Optional<Long> level) {
    public java.util.Map<String, Object> toJson() {
        java.util.Map<String, Object> _m = new java.util.LinkedHashMap<>();
        displayName().ifPresent(_v -> _m.put("displayName", _v));
        description().ifPresent(_v -> _m.put("description", _v));
        level().ifPresent(_v -> _m.put("level", _v));
        return _m;
    }

    public static MetadataTaxonomyLevel fromJson(Object _json) {
        java.util.Map<String, Object> _m = dev.unofficialbox.core.Json.asObject(_json);
        return new MetadataTaxonomyLevel(
            (!_m.containsKey("displayName") || _m.get("displayName") == null) ? java.util.Optional.<String>empty() : java.util.Optional.of(dev.unofficialbox.core.Json.asString(_m.get("displayName"))),
            (!_m.containsKey("description") || _m.get("description") == null) ? java.util.Optional.<String>empty() : java.util.Optional.of(dev.unofficialbox.core.Json.asString(_m.get("description"))),
            (!_m.containsKey("level") || _m.get("level") == null) ? java.util.Optional.<Long>empty() : java.util.Optional.of(dev.unofficialbox.core.Json.asLong(_m.get("level")))
        );
    }

    /** A fluent builder; unset optional fields default to empty. */
    public static Builder builder() {
        return new Builder();
    }

    public static final class Builder {
        private Optional<String> displayName = java.util.Optional.empty();
        private Optional<String> description = java.util.Optional.empty();
        private Optional<Long> level = java.util.Optional.empty();

        public Builder displayName(String displayName) {
            this.displayName = java.util.Optional.ofNullable(displayName);
            return this;
        }
        public Builder description(String description) {
            this.description = java.util.Optional.ofNullable(description);
            return this;
        }
        public Builder level(Long level) {
            this.level = java.util.Optional.ofNullable(level);
            return this;
        }

        public MetadataTaxonomyLevel build() {
            return new MetadataTaxonomyLevel(
                displayName,
                description,
                level
            );
        }
    }
}
