// Code generated by box-gantry 0.1.0 (spec ee7d55aedefe2fa0) for Box API 2024.0. DO NOT EDIT.
package dev.unofficialbox.model.schemas;

import module java.base;

public record MetadataTemplateFields(
    FieldsType2 type,
    String key,
    String displayName,
    Optional<String> description,
    Optional<Boolean> hidden,
    Optional<List<FieldsOptions3>> options,
    Optional<String> taxonomyKey,
    Optional<String> taxonomyId,
    Optional<String> namespace,
    Optional<FieldsOptionsRules> optionsRules,
    Optional<String> id) {
    public java.util.Map<String, Object> toJson() {
        java.util.Map<String, Object> _m = new java.util.LinkedHashMap<>();
        _m.put("type", (type() == null ? null : type().toJson()));
        _m.put("key", key());
        _m.put("displayName", displayName());
        description().ifPresent(_v -> _m.put("description", _v));
        hidden().ifPresent(_v -> _m.put("hidden", _v));
        options().ifPresent(_v -> _m.put("options", dev.unofficialbox.core.Json.encodeList(_v, _x0 -> (_x0 == null ? null : _x0.toJson()))));
        taxonomyKey().ifPresent(_v -> _m.put("taxonomyKey", _v));
        taxonomyId().ifPresent(_v -> _m.put("taxonomyId", _v));
        namespace().ifPresent(_v -> _m.put("namespace", _v));
        optionsRules().ifPresent(_v -> _m.put("optionsRules", (_v == null ? null : _v.toJson())));
        id().ifPresent(_v -> _m.put("id", _v));
        return _m;
    }

    public static MetadataTemplateFields fromJson(Object _json) {
        java.util.Map<String, Object> _m = dev.unofficialbox.core.Json.asObject(_json);
        return new MetadataTemplateFields(
            (_m.get("type") == null ? null : FieldsType2.fromJson(_m.get("type"))),
            dev.unofficialbox.core.Json.asString(_m.get("key")),
            dev.unofficialbox.core.Json.asString(_m.get("displayName")),
            (!_m.containsKey("description") || _m.get("description") == null) ? java.util.Optional.<String>empty() : java.util.Optional.of(dev.unofficialbox.core.Json.asString(_m.get("description"))),
            (!_m.containsKey("hidden") || _m.get("hidden") == null) ? java.util.Optional.<Boolean>empty() : java.util.Optional.of(dev.unofficialbox.core.Json.asBoolean(_m.get("hidden"))),
            (!_m.containsKey("options") || _m.get("options") == null) ? java.util.Optional.<List<FieldsOptions3>>empty() : java.util.Optional.of(dev.unofficialbox.core.Json.decodeList(_m.get("options"), _x0 -> (_x0 == null ? null : FieldsOptions3.fromJson(_x0)))),
            (!_m.containsKey("taxonomyKey") || _m.get("taxonomyKey") == null) ? java.util.Optional.<String>empty() : java.util.Optional.of(dev.unofficialbox.core.Json.asString(_m.get("taxonomyKey"))),
            (!_m.containsKey("taxonomyId") || _m.get("taxonomyId") == null) ? java.util.Optional.<String>empty() : java.util.Optional.of(dev.unofficialbox.core.Json.asString(_m.get("taxonomyId"))),
            (!_m.containsKey("namespace") || _m.get("namespace") == null) ? java.util.Optional.<String>empty() : java.util.Optional.of(dev.unofficialbox.core.Json.asString(_m.get("namespace"))),
            (!_m.containsKey("optionsRules") || _m.get("optionsRules") == null) ? java.util.Optional.<FieldsOptionsRules>empty() : java.util.Optional.of((_m.get("optionsRules") == null ? null : FieldsOptionsRules.fromJson(_m.get("optionsRules")))),
            (!_m.containsKey("id") || _m.get("id") == null) ? java.util.Optional.<String>empty() : java.util.Optional.of(dev.unofficialbox.core.Json.asString(_m.get("id")))
        );
    }
}
