// Code generated by box-gantry 0.1.0 (spec ee7d55aedefe2fa0) for Box API 2024.0. DO NOT EDIT.
package dev.unofficialbox.model.schemas;

import module java.base;

public record MetadataQuery(
    String from,
    Optional<String> query,
    Optional<Map<String, Object>> queryParams,
    String ancestorFolderId,
    Optional<List<MetadataQueryOrderBy>> orderBy,
    Optional<Long> limit,
    Optional<String> marker,
    Optional<List<String>> fields) {
    public java.util.Map<String, Object> toJson() {
        java.util.Map<String, Object> _m = new java.util.LinkedHashMap<>();
        _m.put("from", from());
        query().ifPresent(_v -> _m.put("query", _v));
        queryParams().ifPresent(_v -> _m.put("query_params", _v));
        _m.put("ancestor_folder_id", ancestorFolderId());
        orderBy().ifPresent(_v -> _m.put("order_by", dev.unofficialbox.core.Json.encodeList(_v, _x0 -> (_x0 == null ? null : _x0.toJson()))));
        limit().ifPresent(_v -> _m.put("limit", _v));
        marker().ifPresent(_v -> _m.put("marker", _v));
        fields().ifPresent(_v -> _m.put("fields", _v));
        return _m;
    }

    public static MetadataQuery fromJson(Object _json) {
        java.util.Map<String, Object> _m = dev.unofficialbox.core.Json.asObject(_json);
        return new MetadataQuery(
            dev.unofficialbox.core.Json.asString(_m.get("from")),
            (!_m.containsKey("query") || _m.get("query") == null) ? java.util.Optional.<String>empty() : java.util.Optional.of(dev.unofficialbox.core.Json.asString(_m.get("query"))),
            (!_m.containsKey("query_params") || _m.get("query_params") == null) ? java.util.Optional.<Map<String, Object>>empty() : java.util.Optional.of(dev.unofficialbox.core.Json.decodeMap(_m.get("query_params"), _x0 -> _x0)),
            dev.unofficialbox.core.Json.asString(_m.get("ancestor_folder_id")),
            (!_m.containsKey("order_by") || _m.get("order_by") == null) ? java.util.Optional.<List<MetadataQueryOrderBy>>empty() : java.util.Optional.of(dev.unofficialbox.core.Json.decodeList(_m.get("order_by"), _x0 -> (_x0 == null ? null : MetadataQueryOrderBy.fromJson(_x0)))),
            (!_m.containsKey("limit") || _m.get("limit") == null) ? java.util.Optional.<Long>empty() : java.util.Optional.of(dev.unofficialbox.core.Json.asLong(_m.get("limit"))),
            (!_m.containsKey("marker") || _m.get("marker") == null) ? java.util.Optional.<String>empty() : java.util.Optional.of(dev.unofficialbox.core.Json.asString(_m.get("marker"))),
            (!_m.containsKey("fields") || _m.get("fields") == null) ? java.util.Optional.<List<String>>empty() : java.util.Optional.of(dev.unofficialbox.core.Json.decodeList(_m.get("fields"), _x0 -> dev.unofficialbox.core.Json.asString(_x0)))
        );
    }
}
