// Code generated by box-gantry 0.1.0 (spec ee7d55aedefe2fa0) for Box API 2024.0. DO NOT EDIT.
package dev.unofficialbox.model.schemas;

import module java.base;

public record MetadataTaxonomyAncestor(
    Optional<String> id,
    Optional<String> displayName,
    Optional<Long> level) {
    public java.util.Map<String, Object> toJson() {
        java.util.Map<String, Object> _m = new java.util.LinkedHashMap<>();
        id().ifPresent(_v -> _m.put("id", _v));
        displayName().ifPresent(_v -> _m.put("displayName", _v));
        level().ifPresent(_v -> _m.put("level", _v));
        return _m;
    }

    public static MetadataTaxonomyAncestor fromJson(Object _json) {
        java.util.Map<String, Object> _m = dev.unofficialbox.core.Json.asObject(_json);
        return new MetadataTaxonomyAncestor(
            (!_m.containsKey("id") || _m.get("id") == null) ? java.util.Optional.<String>empty() : java.util.Optional.of(dev.unofficialbox.core.Json.asString(_m.get("id"))),
            (!_m.containsKey("displayName") || _m.get("displayName") == null) ? java.util.Optional.<String>empty() : java.util.Optional.of(dev.unofficialbox.core.Json.asString(_m.get("displayName"))),
            (!_m.containsKey("level") || _m.get("level") == null) ? java.util.Optional.<Long>empty() : java.util.Optional.of(dev.unofficialbox.core.Json.asLong(_m.get("level")))
        );
    }
}
