// Code generated by box-gantry 0.1.0 (spec ee7d55aedefe2fa0) for Box API 2024.0. DO NOT EDIT.
package dev.unofficialbox.model.schemas;

import module java.base;

public record MetadataTaxonomyNode(
    String id,
    String displayName,
    Long level,
    Optional<String> parentId,
    Optional<List<String>> nodePath,
    Optional<List<MetadataTaxonomyAncestor>> ancestors) {
    public java.util.Map<String, Object> toJson() {
        java.util.Map<String, Object> _m = new java.util.LinkedHashMap<>();
        _m.put("id", id());
        _m.put("displayName", displayName());
        _m.put("level", level());
        parentId().ifPresent(_v -> _m.put("parentId", _v));
        nodePath().ifPresent(_v -> _m.put("nodePath", _v));
        ancestors().ifPresent(_v -> _m.put("ancestors", dev.unofficialbox.core.Json.encodeList(_v, _x0 -> (_x0 == null ? null : _x0.toJson()))));
        return _m;
    }

    public static MetadataTaxonomyNode fromJson(Object _json) {
        java.util.Map<String, Object> _m = dev.unofficialbox.core.Json.asObject(_json);
        return new MetadataTaxonomyNode(
            dev.unofficialbox.core.Json.asString(_m.get("id")),
            dev.unofficialbox.core.Json.asString(_m.get("displayName")),
            dev.unofficialbox.core.Json.asLong(_m.get("level")),
            (!_m.containsKey("parentId") || _m.get("parentId") == null) ? java.util.Optional.<String>empty() : java.util.Optional.of(dev.unofficialbox.core.Json.asString(_m.get("parentId"))),
            (!_m.containsKey("nodePath") || _m.get("nodePath") == null) ? java.util.Optional.<List<String>>empty() : java.util.Optional.of(dev.unofficialbox.core.Json.decodeList(_m.get("nodePath"), _x0 -> dev.unofficialbox.core.Json.asString(_x0))),
            (!_m.containsKey("ancestors") || _m.get("ancestors") == null) ? java.util.Optional.<List<MetadataTaxonomyAncestor>>empty() : java.util.Optional.of(dev.unofficialbox.core.Json.decodeList(_m.get("ancestors"), _x0 -> (_x0 == null ? null : MetadataTaxonomyAncestor.fromJson(_x0))))
        );
    }
}
