// Code generated by box-gantry 0.1.0 (spec ee7d55aedefe2fa0) for Box API 2024.0. DO NOT EDIT.
package dev.unofficialbox.model.schemas;

import module java.base;

public record OptionFileContentRequest(
    Optional<String> name,
    Optional<Long> size,
    Optional<PostFileIdParent> parent) {
    public java.util.Map<String, Object> toJson() {
        java.util.Map<String, Object> _m = new java.util.LinkedHashMap<>();
        name().ifPresent(_v -> _m.put("name", _v));
        size().ifPresent(_v -> _m.put("size", _v));
        parent().ifPresent(_v -> _m.put("parent", (_v == null ? null : _v.toJson())));
        return _m;
    }

    public static OptionFileContentRequest fromJson(Object _json) {
        java.util.Map<String, Object> _m = dev.unofficialbox.core.Json.asObject(_json);
        return new OptionFileContentRequest(
            (!_m.containsKey("name") || _m.get("name") == null) ? java.util.Optional.<String>empty() : java.util.Optional.of(dev.unofficialbox.core.Json.asString(_m.get("name"))),
            (!_m.containsKey("size") || _m.get("size") == null) ? java.util.Optional.<Long>empty() : java.util.Optional.of(dev.unofficialbox.core.Json.asLong(_m.get("size"))),
            (!_m.containsKey("parent") || _m.get("parent") == null) ? java.util.Optional.<PostFileIdParent>empty() : java.util.Optional.of((_m.get("parent") == null ? null : PostFileIdParent.fromJson(_m.get("parent"))))
        );
    }
}
