// Code generated by box-gantry 0.1.0 (spec ee7d55aedefe2fa0) for Box API 2024.0. DO NOT EDIT.
package dev.unofficialbox.model.schemas;

public record OutcomesActionType(String value) {
    public static final OutcomesActionType ADD_METADATA = new OutcomesActionType("add_metadata");
    public static final OutcomesActionType ASSIGN_TASK = new OutcomesActionType("assign_task");
    public static final OutcomesActionType COPY_FILE = new OutcomesActionType("copy_file");
    public static final OutcomesActionType COPY_FOLDER = new OutcomesActionType("copy_folder");
    public static final OutcomesActionType CREATE_FOLDER = new OutcomesActionType("create_folder");
    public static final OutcomesActionType DELETE_FILE = new OutcomesActionType("delete_file");
    public static final OutcomesActionType DELETE_FOLDER = new OutcomesActionType("delete_folder");
    public static final OutcomesActionType LOCK_FILE = new OutcomesActionType("lock_file");
    public static final OutcomesActionType MOVE_FILE = new OutcomesActionType("move_file");
    public static final OutcomesActionType MOVE_FOLDER = new OutcomesActionType("move_folder");
    public static final OutcomesActionType REMOVE_WATERMARK_FILE = new OutcomesActionType("remove_watermark_file");
    public static final OutcomesActionType RENAME_FOLDER = new OutcomesActionType("rename_folder");
    public static final OutcomesActionType RESTORE_FOLDER = new OutcomesActionType("restore_folder");
    public static final OutcomesActionType SHARE_FILE = new OutcomesActionType("share_file");
    public static final OutcomesActionType SHARE_FOLDER = new OutcomesActionType("share_folder");
    public static final OutcomesActionType UNLOCK_FILE = new OutcomesActionType("unlock_file");
    public static final OutcomesActionType UPLOAD_FILE = new OutcomesActionType("upload_file");
    public static final OutcomesActionType WAIT_FOR_TASK = new OutcomesActionType("wait_for_task");
    public static final OutcomesActionType WATERMARK_FILE = new OutcomesActionType("watermark_file");
    public static final OutcomesActionType GO_BACK_TO_STEP = new OutcomesActionType("go_back_to_step");
    public static final OutcomesActionType APPLY_FILE_CLASSIFICATION = new OutcomesActionType("apply_file_classification");
    public static final OutcomesActionType APPLY_FOLDER_CLASSIFICATION = new OutcomesActionType("apply_folder_classification");
    public static final OutcomesActionType SEND_NOTIFICATION = new OutcomesActionType("send_notification");

    public String toJson() {
        return value;
    }

    public static OutcomesActionType fromJson(Object _json) {
        return new OutcomesActionType(dev.unofficialbox.core.Json.asString(_json));
    }
}
