// Code generated by box-gantry 0.1.0 (spec ee7d55aedefe2fa0) for Box API 2024.0. DO NOT EDIT.
package dev.unofficialbox.model.schemas;

import module java.base;

public record PostCollaborationsAccessibleBy(
    AccessibleByType type,
    Optional<String> id,
    Optional<String> login) {
    public java.util.Map<String, Object> toJson() {
        java.util.Map<String, Object> _m = new java.util.LinkedHashMap<>();
        _m.put("type", (type() == null ? null : type().toJson()));
        id().ifPresent(_v -> _m.put("id", _v));
        login().ifPresent(_v -> _m.put("login", _v));
        return _m;
    }

    public static PostCollaborationsAccessibleBy fromJson(Object _json) {
        java.util.Map<String, Object> _m = dev.unofficialbox.core.Json.asObject(_json);
        return new PostCollaborationsAccessibleBy(
            (_m.get("type") == null ? null : AccessibleByType.fromJson(_m.get("type"))),
            (!_m.containsKey("id") || _m.get("id") == null) ? java.util.Optional.<String>empty() : java.util.Optional.of(dev.unofficialbox.core.Json.asString(_m.get("id"))),
            (!_m.containsKey("login") || _m.get("login") == null) ? java.util.Optional.<String>empty() : java.util.Optional.of(dev.unofficialbox.core.Json.asString(_m.get("login")))
        );
    }

    /** A fluent builder; unset optional fields default to empty. */
    public static Builder builder() {
        return new Builder();
    }

    public static final class Builder {
        private AccessibleByType type;
        private Optional<String> id = java.util.Optional.empty();
        private Optional<String> login = java.util.Optional.empty();

        public Builder type(AccessibleByType type) {
            this.type = type;
            return this;
        }
        public Builder id(String id) {
            this.id = java.util.Optional.ofNullable(id);
            return this;
        }
        public Builder login(String login) {
            this.login = java.util.Optional.ofNullable(login);
            return this;
        }

        public PostCollaborationsAccessibleBy build() {
            return new PostCollaborationsAccessibleBy(
                type,
                id,
                login
            );
        }
    }
}
