// Code generated by box-gantry 0.1.0 (spec ee7d55aedefe2fa0) for Box API 2024.0. DO NOT EDIT.
package dev.unofficialbox.model.schemas;

public record PostOAuth2TokenBoxSubjectType(String value) {
    public static final PostOAuth2TokenBoxSubjectType ENTERPRISE = new PostOAuth2TokenBoxSubjectType("enterprise");
    public static final PostOAuth2TokenBoxSubjectType USER = new PostOAuth2TokenBoxSubjectType("user");

    public String toJson() {
        return value;
    }

    public static PostOAuth2TokenBoxSubjectType fromJson(Object _json) {
        return new PostOAuth2TokenBoxSubjectType(dev.unofficialbox.core.Json.asString(_json));
    }
}
