// Code generated by box-gantry 0.1.0 (spec ee7d55aedefe2fa0) for Box API 2024.0. DO NOT EDIT.
package dev.unofficialbox.model.schemas;

import module java.base;

public record PostFileContentAttributes(
    String name,
    AttributesParent parent,
    Optional<OffsetDateTime> contentCreatedAt,
    Optional<OffsetDateTime> contentModifiedAt) {
    public java.util.Map<String, Object> toJson() {
        java.util.Map<String, Object> _m = new java.util.LinkedHashMap<>();
        _m.put("name", name());
        _m.put("parent", (parent() == null ? null : parent().toJson()));
        contentCreatedAt().ifPresent(_v -> _m.put("content_created_at", (_v == null ? null : _v.toString())));
        contentModifiedAt().ifPresent(_v -> _m.put("content_modified_at", (_v == null ? null : _v.toString())));
        return _m;
    }

    public static PostFileContentAttributes fromJson(Object _json) {
        java.util.Map<String, Object> _m = dev.unofficialbox.core.Json.asObject(_json);
        return new PostFileContentAttributes(
            dev.unofficialbox.core.Json.asString(_m.get("name")),
            (_m.get("parent") == null ? null : AttributesParent.fromJson(_m.get("parent"))),
            (!_m.containsKey("content_created_at") || _m.get("content_created_at") == null) ? java.util.Optional.<OffsetDateTime>empty() : java.util.Optional.of((_m.get("content_created_at") == null ? null : java.time.OffsetDateTime.parse(dev.unofficialbox.core.Json.asString(_m.get("content_created_at"))))),
            (!_m.containsKey("content_modified_at") || _m.get("content_modified_at") == null) ? java.util.Optional.<OffsetDateTime>empty() : java.util.Optional.of((_m.get("content_modified_at") == null ? null : java.time.OffsetDateTime.parse(dev.unofficialbox.core.Json.asString(_m.get("content_modified_at")))))
        );
    }
}
