// Code generated by box-gantry 0.1.0 (spec ee7d55aedefe2fa0) for Box API 2024.0. DO NOT EDIT.
package dev.unofficialbox.model.schemas;

import module java.base;

public record PostCollaborationsItem(Optional<EventSourceItemType> type, Optional<String> id) {
    public java.util.Map<String, Object> toJson() {
        java.util.Map<String, Object> _m = new java.util.LinkedHashMap<>();
        type().ifPresent(_v -> _m.put("type", (_v == null ? null : _v.toJson())));
        id().ifPresent(_v -> _m.put("id", _v));
        return _m;
    }

    public static PostCollaborationsItem fromJson(Object _json) {
        java.util.Map<String, Object> _m = dev.unofficialbox.core.Json.asObject(_json);
        return new PostCollaborationsItem(
            (!_m.containsKey("type") || _m.get("type") == null) ? java.util.Optional.<EventSourceItemType>empty() : java.util.Optional.of((_m.get("type") == null ? null : EventSourceItemType.fromJson(_m.get("type")))),
            (!_m.containsKey("id") || _m.get("id") == null) ? java.util.Optional.<String>empty() : java.util.Optional.of(dev.unofficialbox.core.Json.asString(_m.get("id")))
        );
    }
}
