// Code generated by box-gantry 0.1.0 (spec ee7d55aedefe2fa0) for Box API 2024.0. DO NOT EDIT.
package dev.unofficialbox.model.schemas;

public record PostOAuth2TokenGrantType(String value) {
    public static final PostOAuth2TokenGrantType AUTHORIZATION_CODE = new PostOAuth2TokenGrantType("authorization_code");
    public static final PostOAuth2TokenGrantType REFRESH_TOKEN = new PostOAuth2TokenGrantType("refresh_token");
    public static final PostOAuth2TokenGrantType CLIENT_CREDENTIALS = new PostOAuth2TokenGrantType("client_credentials");
    public static final PostOAuth2TokenGrantType URN_IETF_PARAMS_OAUTH_GRANT_TYPE_JWT_BEARER = new PostOAuth2TokenGrantType("urn:ietf:params:oauth:grant-type:jwt-bearer");
    public static final PostOAuth2TokenGrantType URN_IETF_PARAMS_OAUTH_GRANT_TYPE_TOKEN_EXCHANGE = new PostOAuth2TokenGrantType("urn:ietf:params:oauth:grant-type:token-exchange");

    public String toJson() {
        return value;
    }

    public static PostOAuth2TokenGrantType fromJson(Object _json) {
        return new PostOAuth2TokenGrantType(dev.unofficialbox.core.Json.asString(_json));
    }
}
