// Code generated by box-gantry 0.1.0 (spec ee7d55aedefe2fa0) for Box API 2024.0. DO NOT EDIT.
package dev.unofficialbox.model.schemas;

public record PostOAuth2TokenRefreshAccessTokenGrantType(String value) {
    public static final PostOAuth2TokenRefreshAccessTokenGrantType REFRESH_TOKEN = new PostOAuth2TokenRefreshAccessTokenGrantType("refresh_token");

    public String toJson() {
        return value;
    }

    public static PostOAuth2TokenRefreshAccessTokenGrantType fromJson(Object _json) {
        return new PostOAuth2TokenRefreshAccessTokenGrantType(dev.unofficialbox.core.Json.asString(_json));
    }
}
