// Code generated by box-gantry 0.1.0 (spec ee7d55aedefe2fa0) for Box API 2024.0. DO NOT EDIT.
package dev.unofficialbox.model.schemas;

import module java.base;
import dev.unofficialbox.core.Tristate;

public record PutIdSharedLink2(
    Optional<SharedLinkAccess> access,
    Tristate<String> password,
    Optional<String> vanityName,
    Optional<OffsetDateTime> unsharedAt) {
    public java.util.Map<String, Object> toJson() {
        java.util.Map<String, Object> _m = new java.util.LinkedHashMap<>();
        access().ifPresent(_v -> _m.put("access", (_v == null ? null : _v.toJson())));
        if (password().isPresent()) { _m.put("password", password().value()); }
        else if (password().isNull()) { _m.put("password", null); }
        vanityName().ifPresent(_v -> _m.put("vanity_name", _v));
        unsharedAt().ifPresent(_v -> _m.put("unshared_at", (_v == null ? null : _v.toString())));
        return _m;
    }

    public static PutIdSharedLink2 fromJson(Object _json) {
        java.util.Map<String, Object> _m = dev.unofficialbox.core.Json.asObject(_json);
        return new PutIdSharedLink2(
            (!_m.containsKey("access") || _m.get("access") == null) ? java.util.Optional.<SharedLinkAccess>empty() : java.util.Optional.of((_m.get("access") == null ? null : SharedLinkAccess.fromJson(_m.get("access")))),
            !_m.containsKey("password") ? dev.unofficialbox.core.Tristate.<String>absent() : (_m.get("password") == null ? dev.unofficialbox.core.Tristate.<String>ofNull() : dev.unofficialbox.core.Tristate.of(dev.unofficialbox.core.Json.asString(_m.get("password")))),
            (!_m.containsKey("vanity_name") || _m.get("vanity_name") == null) ? java.util.Optional.<String>empty() : java.util.Optional.of(dev.unofficialbox.core.Json.asString(_m.get("vanity_name"))),
            (!_m.containsKey("unshared_at") || _m.get("unshared_at") == null) ? java.util.Optional.<OffsetDateTime>empty() : java.util.Optional.of((_m.get("unshared_at") == null ? null : java.time.OffsetDateTime.parse(dev.unofficialbox.core.Json.asString(_m.get("unshared_at")))))
        );
    }

    /** A fluent builder; unset optional fields default to empty. */
    public static Builder builder() {
        return new Builder();
    }

    public static final class Builder {
        private Optional<SharedLinkAccess> access = java.util.Optional.empty();
        private Tristate<String> password;
        private Optional<String> vanityName = java.util.Optional.empty();
        private Optional<OffsetDateTime> unsharedAt = java.util.Optional.empty();

        public Builder access(SharedLinkAccess access) {
            this.access = java.util.Optional.ofNullable(access);
            return this;
        }
        public Builder password(Tristate<String> password) {
            this.password = password;
            return this;
        }
        public Builder vanityName(String vanityName) {
            this.vanityName = java.util.Optional.ofNullable(vanityName);
            return this;
        }
        public Builder unsharedAt(OffsetDateTime unsharedAt) {
            this.unsharedAt = java.util.Optional.ofNullable(unsharedAt);
            return this;
        }

        public PutIdSharedLink2 build() {
            return new PutIdSharedLink2(
                access,
                password,
                vanityName,
                unsharedAt
            );
        }
    }
}
