// Code generated by box-gantry 0.1.0 (spec ee7d55aedefe2fa0) for Box API 2024.0. DO NOT EDIT.
package dev.unofficialbox.model.schemas;

import module java.base;

public record PutIdLock(
    Optional<LockType> access,
    Optional<OffsetDateTime> expiresAt,
    Optional<Boolean> isDownloadPrevented) {
    public java.util.Map<String, Object> toJson() {
        java.util.Map<String, Object> _m = new java.util.LinkedHashMap<>();
        access().ifPresent(_v -> _m.put("access", (_v == null ? null : _v.toJson())));
        expiresAt().ifPresent(_v -> _m.put("expires_at", (_v == null ? null : _v.toString())));
        isDownloadPrevented().ifPresent(_v -> _m.put("is_download_prevented", _v));
        return _m;
    }

    public static PutIdLock fromJson(Object _json) {
        java.util.Map<String, Object> _m = dev.unofficialbox.core.Json.asObject(_json);
        return new PutIdLock(
            (!_m.containsKey("access") || _m.get("access") == null) ? java.util.Optional.<LockType>empty() : java.util.Optional.of((_m.get("access") == null ? null : LockType.fromJson(_m.get("access")))),
            (!_m.containsKey("expires_at") || _m.get("expires_at") == null) ? java.util.Optional.<OffsetDateTime>empty() : java.util.Optional.of((_m.get("expires_at") == null ? null : java.time.OffsetDateTime.parse(dev.unofficialbox.core.Json.asString(_m.get("expires_at"))))),
            (!_m.containsKey("is_download_prevented") || _m.get("is_download_prevented") == null) ? java.util.Optional.<Boolean>empty() : java.util.Optional.of(dev.unofficialbox.core.Json.asBoolean(_m.get("is_download_prevented")))
        );
    }
}
