// Code generated by box-gantry 0.1.0 (spec ee7d55aedefe2fa0) for Box API 2024.0. DO NOT EDIT.
package dev.unofficialbox.model.schemas;

public record PutOp(String value) {
    public static final PutOp REPLACE = new PutOp("replace");

    public String toJson() {
        return value;
    }

    public static PutOp fromJson(Object _json) {
        return new PutOp(dev.unofficialbox.core.Json.asString(_json));
    }
}
