// Code generated by box-gantry 0.1.0 (spec ee7d55aedefe2fa0) for Box API 2024.0. DO NOT EDIT.
package dev.unofficialbox.model.schemas;

import module java.base;

public record PutSkillInvocationIdMetadata(Optional<List<SkillCard>> cards) {
    public java.util.Map<String, Object> toJson() {
        java.util.Map<String, Object> _m = new java.util.LinkedHashMap<>();
        cards().ifPresent(_v -> _m.put("cards", dev.unofficialbox.core.Json.encodeList(_v, _x0 -> (_x0 == null ? null : _x0.toJson()))));
        return _m;
    }

    public static PutSkillInvocationIdMetadata fromJson(Object _json) {
        java.util.Map<String, Object> _m = dev.unofficialbox.core.Json.asObject(_json);
        return new PutSkillInvocationIdMetadata(
            (!_m.containsKey("cards") || _m.get("cards") == null) ? java.util.Optional.<List<SkillCard>>empty() : java.util.Optional.of(dev.unofficialbox.core.Json.decodeList(_m.get("cards"), _x0 -> (_x0 == null ? null : SkillCard.fromJson(_x0))))
        );
    }
}
