// Code generated by box-gantry 0.1.0 (spec ee7d55aedefe2fa0) for Box API 2024.0. DO NOT EDIT.
package dev.unofficialbox.model.schemas;

import module java.base;

public record RealtimeServers(Optional<Long> chunkSize, Optional<List<RealtimeServer>> entries) {
    public java.util.Map<String, Object> toJson() {
        java.util.Map<String, Object> _m = new java.util.LinkedHashMap<>();
        chunkSize().ifPresent(_v -> _m.put("chunk_size", _v));
        entries().ifPresent(_v -> _m.put("entries", dev.unofficialbox.core.Json.encodeList(_v, _x0 -> (_x0 == null ? null : _x0.toJson()))));
        return _m;
    }

    public static RealtimeServers fromJson(Object _json) {
        java.util.Map<String, Object> _m = dev.unofficialbox.core.Json.asObject(_json);
        return new RealtimeServers(
            (!_m.containsKey("chunk_size") || _m.get("chunk_size") == null) ? java.util.Optional.<Long>empty() : java.util.Optional.of(dev.unofficialbox.core.Json.asLong(_m.get("chunk_size"))),
            (!_m.containsKey("entries") || _m.get("entries") == null) ? java.util.Optional.<List<RealtimeServer>>empty() : java.util.Optional.of(dev.unofficialbox.core.Json.decodeList(_m.get("entries"), _x0 -> (_x0 == null ? null : RealtimeServer.fromJson(_x0))))
        );
    }
}
