// Code generated by box-gantry 0.1.0 (spec ee7d55aedefe2fa0) for Box API 2024.0. DO NOT EDIT.
package dev.unofficialbox.model.schemas;

import module java.base;

public record ResourceScope(Optional<ResourceScopeScope> scope, Optional<Resource> object) {
    public java.util.Map<String, Object> toJson() {
        java.util.Map<String, Object> _m = new java.util.LinkedHashMap<>();
        scope().ifPresent(_v -> _m.put("scope", (_v == null ? null : _v.toJson())));
        object().ifPresent(_v -> _m.put("object", (_v == null ? null : _v.toJson())));
        return _m;
    }

    public static ResourceScope fromJson(Object _json) {
        java.util.Map<String, Object> _m = dev.unofficialbox.core.Json.asObject(_json);
        return new ResourceScope(
            (!_m.containsKey("scope") || _m.get("scope") == null) ? java.util.Optional.<ResourceScopeScope>empty() : java.util.Optional.of((_m.get("scope") == null ? null : ResourceScopeScope.fromJson(_m.get("scope")))),
            (!_m.containsKey("object") || _m.get("object") == null) ? java.util.Optional.<Resource>empty() : java.util.Optional.of((_m.get("object") == null ? null : Resource.fromJson(_m.get("object"))))
        );
    }

    /** A fluent builder; unset optional fields default to empty. */
    public static Builder builder() {
        return new Builder();
    }

    public static final class Builder {
        private Optional<ResourceScopeScope> scope = java.util.Optional.empty();
        private Optional<Resource> object = java.util.Optional.empty();

        public Builder scope(ResourceScopeScope scope) {
            this.scope = java.util.Optional.ofNullable(scope);
            return this;
        }
        public Builder object(Resource object) {
            this.object = java.util.Optional.ofNullable(object);
            return this;
        }

        public ResourceScope build() {
            return new ResourceScope(
                scope,
                object
            );
        }
    }
}
