// Code generated by box-gantry 0.1.0 (spec ee7d55aedefe2fa0) for Box API 2024.0. DO NOT EDIT.
package dev.unofficialbox.model.schemas;

public record RetentionPolicyDispositionAction(String value) {
    public static final RetentionPolicyDispositionAction PERMANENTLY_DELETE = new RetentionPolicyDispositionAction("permanently_delete");
    public static final RetentionPolicyDispositionAction REMOVE_RETENTION = new RetentionPolicyDispositionAction("remove_retention");

    public String toJson() {
        return value;
    }

    public static RetentionPolicyDispositionAction fromJson(Object _json) {
        return new RetentionPolicyDispositionAction(dev.unofficialbox.core.Json.asString(_json));
    }
}
