// Code generated by box-gantry 0.1.0 (spec ee7d55aedefe2fa0) for Box API 2024.0. DO NOT EDIT.
package dev.unofficialbox.model.schemas;

import dev.unofficialbox.core.Tristate;

public record RetentionPolicyAssignmentFilterFields(Tristate<String> field, Tristate<String> value) {
    public java.util.Map<String, Object> toJson() {
        java.util.Map<String, Object> _m = new java.util.LinkedHashMap<>();
        if (field().isPresent()) { _m.put("field", field().value()); }
        else if (field().isNull()) { _m.put("field", null); }
        if (value().isPresent()) { _m.put("value", value().value()); }
        else if (value().isNull()) { _m.put("value", null); }
        return _m;
    }

    public static RetentionPolicyAssignmentFilterFields fromJson(Object _json) {
        java.util.Map<String, Object> _m = dev.unofficialbox.core.Json.asObject(_json);
        return new RetentionPolicyAssignmentFilterFields(
            !_m.containsKey("field") ? dev.unofficialbox.core.Tristate.<String>absent() : (_m.get("field") == null ? dev.unofficialbox.core.Tristate.<String>ofNull() : dev.unofficialbox.core.Tristate.of(dev.unofficialbox.core.Json.asString(_m.get("field")))),
            !_m.containsKey("value") ? dev.unofficialbox.core.Tristate.<String>absent() : (_m.get("value") == null ? dev.unofficialbox.core.Tristate.<String>ofNull() : dev.unofficialbox.core.Tristate.of(dev.unofficialbox.core.Json.asString(_m.get("value"))))
        );
    }
}
