// Code generated by box-gantry 0.1.0 (spec ee7d55aedefe2fa0) for Box API 2024.0. DO NOT EDIT.
package dev.unofficialbox.model.schemas;

import module java.base;
import dev.unofficialbox.core.Tristate;

public record RetentionPolicyAssignment(
    String id,
    RetentionPolicyAssignmentType type,
    Optional<RetentionPolicyMini> retentionPolicy,
    Optional<RetentionPolicyAssignmentAssignedTo> assignedTo,
    Tristate<List<RetentionPolicyAssignmentFilterFields>> filterFields,
    Optional<UserMini> assignedBy,
    Optional<OffsetDateTime> assignedAt,
    Optional<String> startDateField) {
    public java.util.Map<String, Object> toJson() {
        java.util.Map<String, Object> _m = new java.util.LinkedHashMap<>();
        _m.put("id", id());
        _m.put("type", (type() == null ? null : type().toJson()));
        retentionPolicy().ifPresent(_v -> _m.put("retention_policy", (_v == null ? null : _v.toJson())));
        assignedTo().ifPresent(_v -> _m.put("assigned_to", (_v == null ? null : _v.toJson())));
        if (filterFields().isPresent()) { _m.put("filter_fields", dev.unofficialbox.core.Json.encodeList(filterFields().value(), _x0 -> (_x0 == null ? null : _x0.toJson()))); }
        else if (filterFields().isNull()) { _m.put("filter_fields", null); }
        assignedBy().ifPresent(_v -> _m.put("assigned_by", (_v == null ? null : _v.toJson())));
        assignedAt().ifPresent(_v -> _m.put("assigned_at", (_v == null ? null : _v.toString())));
        startDateField().ifPresent(_v -> _m.put("start_date_field", _v));
        return _m;
    }

    public static RetentionPolicyAssignment fromJson(Object _json) {
        java.util.Map<String, Object> _m = dev.unofficialbox.core.Json.asObject(_json);
        return new RetentionPolicyAssignment(
            dev.unofficialbox.core.Json.asString(_m.get("id")),
            (_m.get("type") == null ? null : RetentionPolicyAssignmentType.fromJson(_m.get("type"))),
            (!_m.containsKey("retention_policy") || _m.get("retention_policy") == null) ? java.util.Optional.<RetentionPolicyMini>empty() : java.util.Optional.of((_m.get("retention_policy") == null ? null : RetentionPolicyMini.fromJson(_m.get("retention_policy")))),
            (!_m.containsKey("assigned_to") || _m.get("assigned_to") == null) ? java.util.Optional.<RetentionPolicyAssignmentAssignedTo>empty() : java.util.Optional.of((_m.get("assigned_to") == null ? null : RetentionPolicyAssignmentAssignedTo.fromJson(_m.get("assigned_to")))),
            !_m.containsKey("filter_fields") ? dev.unofficialbox.core.Tristate.<List<RetentionPolicyAssignmentFilterFields>>absent() : (_m.get("filter_fields") == null ? dev.unofficialbox.core.Tristate.<List<RetentionPolicyAssignmentFilterFields>>ofNull() : dev.unofficialbox.core.Tristate.of(dev.unofficialbox.core.Json.decodeList(_m.get("filter_fields"), _x0 -> (_x0 == null ? null : RetentionPolicyAssignmentFilterFields.fromJson(_x0))))),
            (!_m.containsKey("assigned_by") || _m.get("assigned_by") == null) ? java.util.Optional.<UserMini>empty() : java.util.Optional.of((_m.get("assigned_by") == null ? null : UserMini.fromJson(_m.get("assigned_by")))),
            (!_m.containsKey("assigned_at") || _m.get("assigned_at") == null) ? java.util.Optional.<OffsetDateTime>empty() : java.util.Optional.of((_m.get("assigned_at") == null ? null : java.time.OffsetDateTime.parse(dev.unofficialbox.core.Json.asString(_m.get("assigned_at"))))),
            (!_m.containsKey("start_date_field") || _m.get("start_date_field") == null) ? java.util.Optional.<String>empty() : java.util.Optional.of(dev.unofficialbox.core.Json.asString(_m.get("start_date_field")))
        );
    }

    /** A fluent builder; unset optional fields default to empty. */
    public static Builder builder() {
        return new Builder();
    }

    public static final class Builder {
        private String id;
        private RetentionPolicyAssignmentType type;
        private Optional<RetentionPolicyMini> retentionPolicy = java.util.Optional.empty();
        private Optional<RetentionPolicyAssignmentAssignedTo> assignedTo = java.util.Optional.empty();
        private Tristate<List<RetentionPolicyAssignmentFilterFields>> filterFields;
        private Optional<UserMini> assignedBy = java.util.Optional.empty();
        private Optional<OffsetDateTime> assignedAt = java.util.Optional.empty();
        private Optional<String> startDateField = java.util.Optional.empty();

        public Builder id(String id) {
            this.id = id;
            return this;
        }
        public Builder type(RetentionPolicyAssignmentType type) {
            this.type = type;
            return this;
        }
        public Builder retentionPolicy(RetentionPolicyMini retentionPolicy) {
            this.retentionPolicy = java.util.Optional.ofNullable(retentionPolicy);
            return this;
        }
        public Builder assignedTo(RetentionPolicyAssignmentAssignedTo assignedTo) {
            this.assignedTo = java.util.Optional.ofNullable(assignedTo);
            return this;
        }
        public Builder filterFields(Tristate<List<RetentionPolicyAssignmentFilterFields>> filterFields) {
            this.filterFields = filterFields;
            return this;
        }
        public Builder assignedBy(UserMini assignedBy) {
            this.assignedBy = java.util.Optional.ofNullable(assignedBy);
            return this;
        }
        public Builder assignedAt(OffsetDateTime assignedAt) {
            this.assignedAt = java.util.Optional.ofNullable(assignedAt);
            return this;
        }
        public Builder startDateField(String startDateField) {
            this.startDateField = java.util.Optional.ofNullable(startDateField);
            return this;
        }

        public RetentionPolicyAssignment build() {
            return new RetentionPolicyAssignment(
                id,
                type,
                retentionPolicy,
                assignedTo,
                filterFields,
                assignedBy,
                assignedAt,
                startDateField
            );
        }
    }
}
