// Code generated by box-gantry 0.1.0 (spec ee7d55aedefe2fa0) for Box API 2024.0. DO NOT EDIT.
package dev.unofficialbox.model.schemas;

public record SharedLinkEffectivePermission(String value) {
    public static final SharedLinkEffectivePermission CAN_EDIT = new SharedLinkEffectivePermission("can_edit");
    public static final SharedLinkEffectivePermission CAN_DOWNLOAD = new SharedLinkEffectivePermission("can_download");
    public static final SharedLinkEffectivePermission CAN_PREVIEW = new SharedLinkEffectivePermission("can_preview");
    public static final SharedLinkEffectivePermission NO_ACCESS = new SharedLinkEffectivePermission("no_access");

    public String toJson() {
        return value;
    }

    public static SharedLinkEffectivePermission fromJson(Object _json) {
        return new SharedLinkEffectivePermission(dev.unofficialbox.core.Json.asString(_json));
    }
}
