// Code generated by box-gantry 0.1.0 (spec ee7d55aedefe2fa0) for Box API 2025.0. DO NOT EDIT.
package dev.unofficialbox.model.schemas;

public record ShieldListMini(
    String id,
    ShieldListMiniType type,
    String name,
    ShieldListMiniContent content) {
    public java.util.Map<String, Object> toJson() {
        java.util.Map<String, Object> _m = new java.util.LinkedHashMap<>();
        _m.put("id", id());
        _m.put("type", (type() == null ? null : type().toJson()));
        _m.put("name", name());
        _m.put("content", (content() == null ? null : content().toJson()));
        return _m;
    }

    public static ShieldListMini fromJson(Object _json) {
        java.util.Map<String, Object> _m = dev.unofficialbox.core.Json.asObject(_json);
        return new ShieldListMini(
            dev.unofficialbox.core.Json.asString(_m.get("id")),
            (_m.get("type") == null ? null : ShieldListMiniType.fromJson(_m.get("type"))),
            dev.unofficialbox.core.Json.asString(_m.get("name")),
            (_m.get("content") == null ? null : ShieldListMiniContent.fromJson(_m.get("content")))
        );
    }
}
