// Code generated by box-gantry 0.1.0 (spec ee7d55aedefe2fa0) for Box API 2025.0. DO NOT EDIT.
package dev.unofficialbox.model.schemas;

import module java.base;

public record ShieldListContentCountry(
    ShieldListContentCountryType type,
    List<String> countryCodes) implements ShieldListContent, ShieldListContentRequest {
    public java.util.Map<String, Object> toJson() {
        java.util.Map<String, Object> _m = new java.util.LinkedHashMap<>();
        _m.put("type", (type() == null ? null : type().toJson()));
        _m.put("country_codes", countryCodes());
        return _m;
    }

    public static ShieldListContentCountry fromJson(Object _json) {
        java.util.Map<String, Object> _m = dev.unofficialbox.core.Json.asObject(_json);
        return new ShieldListContentCountry(
            (_m.get("type") == null ? null : ShieldListContentCountryType.fromJson(_m.get("type"))),
            dev.unofficialbox.core.Json.decodeList(_m.get("country_codes"), _x0 -> dev.unofficialbox.core.Json.asString(_x0))
        );
    }
}
