// Code generated by box-gantry 0.1.0 (spec ee7d55aedefe2fa0) for Box API 2024.0. DO NOT EDIT.
package dev.unofficialbox.model.schemas;

import module java.base;

public record ShieldInformationBarrierSegmentCreateRequest(
    ShieldInformationBarrierBase shieldInformationBarrier,
    String name,
    Optional<String> description) {
    public java.util.Map<String, Object> toJson() {
        java.util.Map<String, Object> _m = new java.util.LinkedHashMap<>();
        _m.put("shield_information_barrier", (shieldInformationBarrier() == null ? null : shieldInformationBarrier().toJson()));
        _m.put("name", name());
        description().ifPresent(_v -> _m.put("description", _v));
        return _m;
    }

    public static ShieldInformationBarrierSegmentCreateRequest fromJson(Object _json) {
        java.util.Map<String, Object> _m = dev.unofficialbox.core.Json.asObject(_json);
        return new ShieldInformationBarrierSegmentCreateRequest(
            (_m.get("shield_information_barrier") == null ? null : ShieldInformationBarrierBase.fromJson(_m.get("shield_information_barrier"))),
            dev.unofficialbox.core.Json.asString(_m.get("name")),
            (!_m.containsKey("description") || _m.get("description") == null) ? java.util.Optional.<String>empty() : java.util.Optional.of(dev.unofficialbox.core.Json.asString(_m.get("description")))
        );
    }

    /** A fluent builder; unset optional fields default to empty. */
    public static Builder builder() {
        return new Builder();
    }

    public static final class Builder {
        private ShieldInformationBarrierBase shieldInformationBarrier;
        private String name;
        private Optional<String> description = java.util.Optional.empty();

        public Builder shieldInformationBarrier(ShieldInformationBarrierBase shieldInformationBarrier) {
            this.shieldInformationBarrier = shieldInformationBarrier;
            return this;
        }
        public Builder name(String name) {
            this.name = name;
            return this;
        }
        public Builder description(String description) {
            this.description = java.util.Optional.ofNullable(description);
            return this;
        }

        public ShieldInformationBarrierSegmentCreateRequest build() {
            return new ShieldInformationBarrierSegmentCreateRequest(
                shieldInformationBarrier,
                name,
                description
            );
        }
    }
}
