// Code generated by box-gantry 0.1.0 (spec ee7d55aedefe2fa0) for Box API 2024.0. DO NOT EDIT.
package dev.unofficialbox.model.schemas;

import module java.base;

public record ShieldInformationBarrierSegmentMember(
    Optional<String> id,
    Optional<ShieldInformationBarrierSegmentMemberType> type,
    Optional<UserBase> user,
    Optional<ShieldInformationBarrierBase> shieldInformationBarrier,
    Optional<ShieldInformationBarrierSegmentMemberShieldInformationBarrierSegment> shieldInformationBarrierSegment,
    Optional<OffsetDateTime> createdAt,
    Optional<UserBase> createdBy,
    Optional<OffsetDateTime> updatedAt,
    Optional<UserBase> updatedBy) {
    public java.util.Map<String, Object> toJson() {
        java.util.Map<String, Object> _m = new java.util.LinkedHashMap<>();
        id().ifPresent(_v -> _m.put("id", _v));
        type().ifPresent(_v -> _m.put("type", (_v == null ? null : _v.toJson())));
        user().ifPresent(_v -> _m.put("user", (_v == null ? null : _v.toJson())));
        shieldInformationBarrier().ifPresent(_v -> _m.put("shield_information_barrier", (_v == null ? null : _v.toJson())));
        shieldInformationBarrierSegment().ifPresent(_v -> _m.put("shield_information_barrier_segment", (_v == null ? null : _v.toJson())));
        createdAt().ifPresent(_v -> _m.put("created_at", (_v == null ? null : _v.toString())));
        createdBy().ifPresent(_v -> _m.put("created_by", (_v == null ? null : _v.toJson())));
        updatedAt().ifPresent(_v -> _m.put("updated_at", (_v == null ? null : _v.toString())));
        updatedBy().ifPresent(_v -> _m.put("updated_by", (_v == null ? null : _v.toJson())));
        return _m;
    }

    public static ShieldInformationBarrierSegmentMember fromJson(Object _json) {
        java.util.Map<String, Object> _m = dev.unofficialbox.core.Json.asObject(_json);
        return new ShieldInformationBarrierSegmentMember(
            (!_m.containsKey("id") || _m.get("id") == null) ? java.util.Optional.<String>empty() : java.util.Optional.of(dev.unofficialbox.core.Json.asString(_m.get("id"))),
            (!_m.containsKey("type") || _m.get("type") == null) ? java.util.Optional.<ShieldInformationBarrierSegmentMemberType>empty() : java.util.Optional.of((_m.get("type") == null ? null : ShieldInformationBarrierSegmentMemberType.fromJson(_m.get("type")))),
            (!_m.containsKey("user") || _m.get("user") == null) ? java.util.Optional.<UserBase>empty() : java.util.Optional.of((_m.get("user") == null ? null : UserBase.fromJson(_m.get("user")))),
            (!_m.containsKey("shield_information_barrier") || _m.get("shield_information_barrier") == null) ? java.util.Optional.<ShieldInformationBarrierBase>empty() : java.util.Optional.of((_m.get("shield_information_barrier") == null ? null : ShieldInformationBarrierBase.fromJson(_m.get("shield_information_barrier")))),
            (!_m.containsKey("shield_information_barrier_segment") || _m.get("shield_information_barrier_segment") == null) ? java.util.Optional.<ShieldInformationBarrierSegmentMemberShieldInformationBarrierSegment>empty() : java.util.Optional.of((_m.get("shield_information_barrier_segment") == null ? null : ShieldInformationBarrierSegmentMemberShieldInformationBarrierSegment.fromJson(_m.get("shield_information_barrier_segment")))),
            (!_m.containsKey("created_at") || _m.get("created_at") == null) ? java.util.Optional.<OffsetDateTime>empty() : java.util.Optional.of((_m.get("created_at") == null ? null : java.time.OffsetDateTime.parse(dev.unofficialbox.core.Json.asString(_m.get("created_at"))))),
            (!_m.containsKey("created_by") || _m.get("created_by") == null) ? java.util.Optional.<UserBase>empty() : java.util.Optional.of((_m.get("created_by") == null ? null : UserBase.fromJson(_m.get("created_by")))),
            (!_m.containsKey("updated_at") || _m.get("updated_at") == null) ? java.util.Optional.<OffsetDateTime>empty() : java.util.Optional.of((_m.get("updated_at") == null ? null : java.time.OffsetDateTime.parse(dev.unofficialbox.core.Json.asString(_m.get("updated_at"))))),
            (!_m.containsKey("updated_by") || _m.get("updated_by") == null) ? java.util.Optional.<UserBase>empty() : java.util.Optional.of((_m.get("updated_by") == null ? null : UserBase.fromJson(_m.get("updated_by"))))
        );
    }
}
