// Code generated by box-gantry 0.1.0 (spec ee7d55aedefe2fa0) for Box API 2024.0. DO NOT EDIT.
package dev.unofficialbox.model.schemas;

public record ShieldInformationBarrierReportType(String value) {
    public static final ShieldInformationBarrierReportType SHIELD_INFORMATION_BARRIER_REPORT = new ShieldInformationBarrierReportType("shield_information_barrier_report");

    public String toJson() {
        return value;
    }

    public static ShieldInformationBarrierReportType fromJson(Object _json) {
        return new ShieldInformationBarrierReportType(dev.unofficialbox.core.Json.asString(_json));
    }
}
