// Code generated by box-gantry 0.1.0 (spec ee7d55aedefe2fa0) for Box API 2024.0. DO NOT EDIT.
package dev.unofficialbox.model.schemas;

import module java.base;

public record ShieldInformationBarrierReportDetailsDetails(Optional<String> folderId) {
    public java.util.Map<String, Object> toJson() {
        java.util.Map<String, Object> _m = new java.util.LinkedHashMap<>();
        folderId().ifPresent(_v -> _m.put("folder_id", _v));
        return _m;
    }

    public static ShieldInformationBarrierReportDetailsDetails fromJson(Object _json) {
        java.util.Map<String, Object> _m = dev.unofficialbox.core.Json.asObject(_json);
        return new ShieldInformationBarrierReportDetailsDetails(
            (!_m.containsKey("folder_id") || _m.get("folder_id") == null) ? java.util.Optional.<String>empty() : java.util.Optional.of(dev.unofficialbox.core.Json.asString(_m.get("folder_id")))
        );
    }

    /** A fluent builder; unset optional fields default to empty. */
    public static Builder builder() {
        return new Builder();
    }

    public static final class Builder {
        private Optional<String> folderId = java.util.Optional.empty();

        public Builder folderId(String folderId) {
            this.folderId = java.util.Optional.ofNullable(folderId);
            return this;
        }

        public ShieldInformationBarrierReportDetailsDetails build() {
            return new ShieldInformationBarrierReportDetailsDetails(
                folderId
            );
        }
    }
}
