// Code generated by box-gantry 0.1.0 (spec ee7d55aedefe2fa0) for Box API 2024.0. DO NOT EDIT.
package dev.unofficialbox.model.schemas;

import module java.base;

public record ShieldInformationBarrierReference(
    Optional<ShieldInformationBarrierBase> shieldInformationBarrier) {
    public java.util.Map<String, Object> toJson() {
        java.util.Map<String, Object> _m = new java.util.LinkedHashMap<>();
        shieldInformationBarrier().ifPresent(_v -> _m.put("shield_information_barrier", (_v == null ? null : _v.toJson())));
        return _m;
    }

    public static ShieldInformationBarrierReference fromJson(Object _json) {
        java.util.Map<String, Object> _m = dev.unofficialbox.core.Json.asObject(_json);
        return new ShieldInformationBarrierReference(
            (!_m.containsKey("shield_information_barrier") || _m.get("shield_information_barrier") == null) ? java.util.Optional.<ShieldInformationBarrierBase>empty() : java.util.Optional.of((_m.get("shield_information_barrier") == null ? null : ShieldInformationBarrierBase.fromJson(_m.get("shield_information_barrier"))))
        );
    }

    /** A fluent builder; unset optional fields default to empty. */
    public static Builder builder() {
        return new Builder();
    }

    public static final class Builder {
        private Optional<ShieldInformationBarrierBase> shieldInformationBarrier = java.util.Optional.empty();

        public Builder shieldInformationBarrier(ShieldInformationBarrierBase shieldInformationBarrier) {
            this.shieldInformationBarrier = java.util.Optional.ofNullable(shieldInformationBarrier);
            return this;
        }

        public ShieldInformationBarrierReference build() {
            return new ShieldInformationBarrierReference(
                shieldInformationBarrier
            );
        }
    }
}
