// Code generated by box-gantry 0.1.0 (spec ee7d55aedefe2fa0) for Box API 2025.0. DO NOT EDIT.
package dev.unofficialbox.model.schemas;

import module java.base;

public record ShieldListContentIntegration(
    ShieldListContentIntegrationType type,
    List<ShieldListContentIntegrationIntegrations> integrations) implements ShieldListContent {
    public java.util.Map<String, Object> toJson() {
        java.util.Map<String, Object> _m = new java.util.LinkedHashMap<>();
        _m.put("type", (type() == null ? null : type().toJson()));
        _m.put("integrations", dev.unofficialbox.core.Json.encodeList(integrations(), _x0 -> (_x0 == null ? null : _x0.toJson())));
        return _m;
    }

    public static ShieldListContentIntegration fromJson(Object _json) {
        java.util.Map<String, Object> _m = dev.unofficialbox.core.Json.asObject(_json);
        return new ShieldListContentIntegration(
            (_m.get("type") == null ? null : ShieldListContentIntegrationType.fromJson(_m.get("type"))),
            dev.unofficialbox.core.Json.decodeList(_m.get("integrations"), _x0 -> (_x0 == null ? null : ShieldListContentIntegrationIntegrations.fromJson(_x0)))
        );
    }

    /** A fluent builder; unset optional fields default to empty. */
    public static Builder builder() {
        return new Builder();
    }

    public static final class Builder {
        private ShieldListContentIntegrationType type;
        private List<ShieldListContentIntegrationIntegrations> integrations;

        public Builder type(ShieldListContentIntegrationType type) {
            this.type = type;
            return this;
        }
        public Builder integrations(List<ShieldListContentIntegrationIntegrations> integrations) {
            this.integrations = integrations;
            return this;
        }

        public ShieldListContentIntegration build() {
            return new ShieldListContentIntegration(
                type,
                integrations
            );
        }
    }
}
