// Code generated by box-gantry 0.1.0 (spec ee7d55aedefe2fa0) for Box API 2024.0. DO NOT EDIT.
package dev.unofficialbox.model.schemas;

import module java.base;

public record SignRequestSignFiles(
    Optional<List<FileMini>> files,
    Optional<Boolean> isReadyForDownload) {
    public java.util.Map<String, Object> toJson() {
        java.util.Map<String, Object> _m = new java.util.LinkedHashMap<>();
        files().ifPresent(_v -> _m.put("files", dev.unofficialbox.core.Json.encodeList(_v, _x0 -> (_x0 == null ? null : _x0.toJson()))));
        isReadyForDownload().ifPresent(_v -> _m.put("is_ready_for_download", _v));
        return _m;
    }

    public static SignRequestSignFiles fromJson(Object _json) {
        java.util.Map<String, Object> _m = dev.unofficialbox.core.Json.asObject(_json);
        return new SignRequestSignFiles(
            (!_m.containsKey("files") || _m.get("files") == null) ? java.util.Optional.<List<FileMini>>empty() : java.util.Optional.of(dev.unofficialbox.core.Json.decodeList(_m.get("files"), _x0 -> (_x0 == null ? null : FileMini.fromJson(_x0)))),
            (!_m.containsKey("is_ready_for_download") || _m.get("is_ready_for_download") == null) ? java.util.Optional.<Boolean>empty() : java.util.Optional.of(dev.unofficialbox.core.Json.asBoolean(_m.get("is_ready_for_download")))
        );
    }

    /** A fluent builder; unset optional fields default to empty. */
    public static Builder builder() {
        return new Builder();
    }

    public static final class Builder {
        private Optional<List<FileMini>> files = java.util.Optional.empty();
        private Optional<Boolean> isReadyForDownload = java.util.Optional.empty();

        public Builder files(List<FileMini> files) {
            this.files = java.util.Optional.ofNullable(files);
            return this;
        }
        public Builder isReadyForDownload(Boolean isReadyForDownload) {
            this.isReadyForDownload = java.util.Optional.ofNullable(isReadyForDownload);
            return this;
        }

        public SignRequestSignFiles build() {
            return new SignRequestSignFiles(
                files,
                isReadyForDownload
            );
        }
    }
}
