// Code generated by box-gantry 0.1.0 (spec ee7d55aedefe2fa0) for Box API 2024.0. DO NOT EDIT.
package dev.unofficialbox.model.schemas;

import module java.base;
import dev.unofficialbox.core.Tristate;

public record SignRequestCreateRequest(
    Optional<Boolean> isDocumentPreparationNeeded,
    Tristate<String> redirectUrl,
    Tristate<String> declinedRedirectUrl,
    Optional<Boolean> areTextSignaturesEnabled,
    Tristate<String> emailSubject,
    Tristate<String> emailMessage,
    Optional<Boolean> areRemindersEnabled,
    Optional<String> name,
    Optional<List<SignRequestPrefillTag>> prefillTags,
    Tristate<Long> daysValid,
    Tristate<String> externalId,
    Tristate<String> templateId,
    Tristate<String> externalSystemName,
    Tristate<String> requestFlow,
    Tristate<List<FileBase>> sourceFiles,
    Tristate<SignRequestCreateRequestSignatureColor> signatureColor,
    List<SignRequestCreateSigner> signers,
    Optional<FolderMini> parentFolder) {
    public java.util.Map<String, Object> toJson() {
        java.util.Map<String, Object> _m = new java.util.LinkedHashMap<>();
        isDocumentPreparationNeeded().ifPresent(_v -> _m.put("is_document_preparation_needed", _v));
        if (redirectUrl().isPresent()) { _m.put("redirect_url", redirectUrl().value()); }
        else if (redirectUrl().isNull()) { _m.put("redirect_url", null); }
        if (declinedRedirectUrl().isPresent()) { _m.put("declined_redirect_url", declinedRedirectUrl().value()); }
        else if (declinedRedirectUrl().isNull()) { _m.put("declined_redirect_url", null); }
        areTextSignaturesEnabled().ifPresent(_v -> _m.put("are_text_signatures_enabled", _v));
        if (emailSubject().isPresent()) { _m.put("email_subject", emailSubject().value()); }
        else if (emailSubject().isNull()) { _m.put("email_subject", null); }
        if (emailMessage().isPresent()) { _m.put("email_message", emailMessage().value()); }
        else if (emailMessage().isNull()) { _m.put("email_message", null); }
        areRemindersEnabled().ifPresent(_v -> _m.put("are_reminders_enabled", _v));
        name().ifPresent(_v -> _m.put("name", _v));
        prefillTags().ifPresent(_v -> _m.put("prefill_tags", dev.unofficialbox.core.Json.encodeList(_v, _x0 -> (_x0 == null ? null : _x0.toJson()))));
        if (daysValid().isPresent()) { _m.put("days_valid", daysValid().value()); }
        else if (daysValid().isNull()) { _m.put("days_valid", null); }
        if (externalId().isPresent()) { _m.put("external_id", externalId().value()); }
        else if (externalId().isNull()) { _m.put("external_id", null); }
        if (templateId().isPresent()) { _m.put("template_id", templateId().value()); }
        else if (templateId().isNull()) { _m.put("template_id", null); }
        if (externalSystemName().isPresent()) { _m.put("external_system_name", externalSystemName().value()); }
        else if (externalSystemName().isNull()) { _m.put("external_system_name", null); }
        if (requestFlow().isPresent()) { _m.put("request_flow", requestFlow().value()); }
        else if (requestFlow().isNull()) { _m.put("request_flow", null); }
        if (sourceFiles().isPresent()) { _m.put("source_files", dev.unofficialbox.core.Json.encodeList(sourceFiles().value(), _x0 -> (_x0 == null ? null : _x0.toJson()))); }
        else if (sourceFiles().isNull()) { _m.put("source_files", null); }
        if (signatureColor().isPresent()) { _m.put("signature_color", (signatureColor().value() == null ? null : signatureColor().value().toJson())); }
        else if (signatureColor().isNull()) { _m.put("signature_color", null); }
        _m.put("signers", dev.unofficialbox.core.Json.encodeList(signers(), _x0 -> (_x0 == null ? null : _x0.toJson())));
        parentFolder().ifPresent(_v -> _m.put("parent_folder", (_v == null ? null : _v.toJson())));
        return _m;
    }

    public static SignRequestCreateRequest fromJson(Object _json) {
        java.util.Map<String, Object> _m = dev.unofficialbox.core.Json.asObject(_json);
        return new SignRequestCreateRequest(
            (!_m.containsKey("is_document_preparation_needed") || _m.get("is_document_preparation_needed") == null) ? java.util.Optional.<Boolean>empty() : java.util.Optional.of(dev.unofficialbox.core.Json.asBoolean(_m.get("is_document_preparation_needed"))),
            !_m.containsKey("redirect_url") ? dev.unofficialbox.core.Tristate.<String>absent() : (_m.get("redirect_url") == null ? dev.unofficialbox.core.Tristate.<String>ofNull() : dev.unofficialbox.core.Tristate.of(dev.unofficialbox.core.Json.asString(_m.get("redirect_url")))),
            !_m.containsKey("declined_redirect_url") ? dev.unofficialbox.core.Tristate.<String>absent() : (_m.get("declined_redirect_url") == null ? dev.unofficialbox.core.Tristate.<String>ofNull() : dev.unofficialbox.core.Tristate.of(dev.unofficialbox.core.Json.asString(_m.get("declined_redirect_url")))),
            (!_m.containsKey("are_text_signatures_enabled") || _m.get("are_text_signatures_enabled") == null) ? java.util.Optional.<Boolean>empty() : java.util.Optional.of(dev.unofficialbox.core.Json.asBoolean(_m.get("are_text_signatures_enabled"))),
            !_m.containsKey("email_subject") ? dev.unofficialbox.core.Tristate.<String>absent() : (_m.get("email_subject") == null ? dev.unofficialbox.core.Tristate.<String>ofNull() : dev.unofficialbox.core.Tristate.of(dev.unofficialbox.core.Json.asString(_m.get("email_subject")))),
            !_m.containsKey("email_message") ? dev.unofficialbox.core.Tristate.<String>absent() : (_m.get("email_message") == null ? dev.unofficialbox.core.Tristate.<String>ofNull() : dev.unofficialbox.core.Tristate.of(dev.unofficialbox.core.Json.asString(_m.get("email_message")))),
            (!_m.containsKey("are_reminders_enabled") || _m.get("are_reminders_enabled") == null) ? java.util.Optional.<Boolean>empty() : java.util.Optional.of(dev.unofficialbox.core.Json.asBoolean(_m.get("are_reminders_enabled"))),
            (!_m.containsKey("name") || _m.get("name") == null) ? java.util.Optional.<String>empty() : java.util.Optional.of(dev.unofficialbox.core.Json.asString(_m.get("name"))),
            (!_m.containsKey("prefill_tags") || _m.get("prefill_tags") == null) ? java.util.Optional.<List<SignRequestPrefillTag>>empty() : java.util.Optional.of(dev.unofficialbox.core.Json.decodeList(_m.get("prefill_tags"), _x0 -> (_x0 == null ? null : SignRequestPrefillTag.fromJson(_x0)))),
            !_m.containsKey("days_valid") ? dev.unofficialbox.core.Tristate.<Long>absent() : (_m.get("days_valid") == null ? dev.unofficialbox.core.Tristate.<Long>ofNull() : dev.unofficialbox.core.Tristate.of(dev.unofficialbox.core.Json.asLong(_m.get("days_valid")))),
            !_m.containsKey("external_id") ? dev.unofficialbox.core.Tristate.<String>absent() : (_m.get("external_id") == null ? dev.unofficialbox.core.Tristate.<String>ofNull() : dev.unofficialbox.core.Tristate.of(dev.unofficialbox.core.Json.asString(_m.get("external_id")))),
            !_m.containsKey("template_id") ? dev.unofficialbox.core.Tristate.<String>absent() : (_m.get("template_id") == null ? dev.unofficialbox.core.Tristate.<String>ofNull() : dev.unofficialbox.core.Tristate.of(dev.unofficialbox.core.Json.asString(_m.get("template_id")))),
            !_m.containsKey("external_system_name") ? dev.unofficialbox.core.Tristate.<String>absent() : (_m.get("external_system_name") == null ? dev.unofficialbox.core.Tristate.<String>ofNull() : dev.unofficialbox.core.Tristate.of(dev.unofficialbox.core.Json.asString(_m.get("external_system_name")))),
            !_m.containsKey("request_flow") ? dev.unofficialbox.core.Tristate.<String>absent() : (_m.get("request_flow") == null ? dev.unofficialbox.core.Tristate.<String>ofNull() : dev.unofficialbox.core.Tristate.of(dev.unofficialbox.core.Json.asString(_m.get("request_flow")))),
            !_m.containsKey("source_files") ? dev.unofficialbox.core.Tristate.<List<FileBase>>absent() : (_m.get("source_files") == null ? dev.unofficialbox.core.Tristate.<List<FileBase>>ofNull() : dev.unofficialbox.core.Tristate.of(dev.unofficialbox.core.Json.decodeList(_m.get("source_files"), _x0 -> (_x0 == null ? null : FileBase.fromJson(_x0))))),
            !_m.containsKey("signature_color") ? dev.unofficialbox.core.Tristate.<SignRequestCreateRequestSignatureColor>absent() : (_m.get("signature_color") == null ? dev.unofficialbox.core.Tristate.<SignRequestCreateRequestSignatureColor>ofNull() : dev.unofficialbox.core.Tristate.of((_m.get("signature_color") == null ? null : SignRequestCreateRequestSignatureColor.fromJson(_m.get("signature_color"))))),
            dev.unofficialbox.core.Json.decodeList(_m.get("signers"), _x0 -> (_x0 == null ? null : SignRequestCreateSigner.fromJson(_x0))),
            (!_m.containsKey("parent_folder") || _m.get("parent_folder") == null) ? java.util.Optional.<FolderMini>empty() : java.util.Optional.of((_m.get("parent_folder") == null ? null : FolderMini.fromJson(_m.get("parent_folder"))))
        );
    }
}
