// Code generated by box-gantry 0.1.0 (spec ee7d55aedefe2fa0) for Box API 2024.0. DO NOT EDIT.
package dev.unofficialbox.model.schemas;

import module java.base;

public record SignRequestCancelRequest(Optional<String> reason) {
    public java.util.Map<String, Object> toJson() {
        java.util.Map<String, Object> _m = new java.util.LinkedHashMap<>();
        reason().ifPresent(_v -> _m.put("reason", _v));
        return _m;
    }

    public static SignRequestCancelRequest fromJson(Object _json) {
        java.util.Map<String, Object> _m = dev.unofficialbox.core.Json.asObject(_json);
        return new SignRequestCancelRequest(
            (!_m.containsKey("reason") || _m.get("reason") == null) ? java.util.Optional.<String>empty() : java.util.Optional.of(dev.unofficialbox.core.Json.asString(_m.get("reason")))
        );
    }
}
