// Code generated by box-gantry 0.1.0 (spec ee7d55aedefe2fa0) for Box API 2024.0. DO NOT EDIT.
package dev.unofficialbox.model.schemas;

public record SignTemplateType(String value) {
    public static final SignTemplateType SIGN_TEMPLATE = new SignTemplateType("sign-template");

    public String toJson() {
        return value;
    }

    public static SignTemplateType fromJson(Object _json) {
        return new SignTemplateType(dev.unofficialbox.core.Json.asString(_json));
    }
}
