// Code generated by box-gantry 0.1.0 (spec ee7d55aedefe2fa0) for Box API 2024.0. DO NOT EDIT.
package dev.unofficialbox.model.schemas;

import module java.base;
import dev.unofficialbox.core.Tristate;

public record SignRequestSigner(
    String email,
    Optional<SignRequestCreateSignerRole> role,
    Optional<Boolean> isInPerson,
    Optional<Long> order,
    Tristate<String> embedUrlExternalUserId,
    Tristate<String> redirectUrl,
    Tristate<String> declinedRedirectUrl,
    Tristate<Boolean> loginRequired,
    Tristate<String> verificationPhoneNumber,
    Tristate<String> password,
    Tristate<String> signerGroupId,
    Tristate<Boolean> suppressNotifications,
    Tristate<String> language,
    Optional<Boolean> hasViewedDocument,
    Tristate<SignRequestSignerSignerDecision> signerDecision,
    Optional<List<SignRequestSignerInput>> inputs,
    Tristate<String> embedUrl,
    Tristate<String> iframeableEmbedUrl,
    Tristate<List<SignRequestSignerAttachment>> attachments) {
    public java.util.Map<String, Object> toJson() {
        java.util.Map<String, Object> _m = new java.util.LinkedHashMap<>();
        _m.put("email", email());
        role().ifPresent(_v -> _m.put("role", (_v == null ? null : _v.toJson())));
        isInPerson().ifPresent(_v -> _m.put("is_in_person", _v));
        order().ifPresent(_v -> _m.put("order", _v));
        if (embedUrlExternalUserId().isPresent()) { _m.put("embed_url_external_user_id", embedUrlExternalUserId().value()); }
        else if (embedUrlExternalUserId().isNull()) { _m.put("embed_url_external_user_id", null); }
        if (redirectUrl().isPresent()) { _m.put("redirect_url", redirectUrl().value()); }
        else if (redirectUrl().isNull()) { _m.put("redirect_url", null); }
        if (declinedRedirectUrl().isPresent()) { _m.put("declined_redirect_url", declinedRedirectUrl().value()); }
        else if (declinedRedirectUrl().isNull()) { _m.put("declined_redirect_url", null); }
        if (loginRequired().isPresent()) { _m.put("login_required", loginRequired().value()); }
        else if (loginRequired().isNull()) { _m.put("login_required", null); }
        if (verificationPhoneNumber().isPresent()) { _m.put("verification_phone_number", verificationPhoneNumber().value()); }
        else if (verificationPhoneNumber().isNull()) { _m.put("verification_phone_number", null); }
        if (password().isPresent()) { _m.put("password", password().value()); }
        else if (password().isNull()) { _m.put("password", null); }
        if (signerGroupId().isPresent()) { _m.put("signer_group_id", signerGroupId().value()); }
        else if (signerGroupId().isNull()) { _m.put("signer_group_id", null); }
        if (suppressNotifications().isPresent()) { _m.put("suppress_notifications", suppressNotifications().value()); }
        else if (suppressNotifications().isNull()) { _m.put("suppress_notifications", null); }
        if (language().isPresent()) { _m.put("language", language().value()); }
        else if (language().isNull()) { _m.put("language", null); }
        hasViewedDocument().ifPresent(_v -> _m.put("has_viewed_document", _v));
        if (signerDecision().isPresent()) { _m.put("signer_decision", (signerDecision().value() == null ? null : signerDecision().value().toJson())); }
        else if (signerDecision().isNull()) { _m.put("signer_decision", null); }
        inputs().ifPresent(_v -> _m.put("inputs", dev.unofficialbox.core.Json.encodeList(_v, _x0 -> (_x0 == null ? null : _x0.toJson()))));
        if (embedUrl().isPresent()) { _m.put("embed_url", embedUrl().value()); }
        else if (embedUrl().isNull()) { _m.put("embed_url", null); }
        if (iframeableEmbedUrl().isPresent()) { _m.put("iframeable_embed_url", iframeableEmbedUrl().value()); }
        else if (iframeableEmbedUrl().isNull()) { _m.put("iframeable_embed_url", null); }
        if (attachments().isPresent()) { _m.put("attachments", dev.unofficialbox.core.Json.encodeList(attachments().value(), _x0 -> (_x0 == null ? null : _x0.toJson()))); }
        else if (attachments().isNull()) { _m.put("attachments", null); }
        return _m;
    }

    public static SignRequestSigner fromJson(Object _json) {
        java.util.Map<String, Object> _m = dev.unofficialbox.core.Json.asObject(_json);
        return new SignRequestSigner(
            _m.get("email") == null ? null : dev.unofficialbox.core.Json.asString(_m.get("email")),
            (!_m.containsKey("role") || _m.get("role") == null) ? java.util.Optional.<SignRequestCreateSignerRole>empty() : java.util.Optional.of((_m.get("role") == null ? null : SignRequestCreateSignerRole.fromJson(_m.get("role")))),
            (!_m.containsKey("is_in_person") || _m.get("is_in_person") == null) ? java.util.Optional.<Boolean>empty() : java.util.Optional.of(dev.unofficialbox.core.Json.asBoolean(_m.get("is_in_person"))),
            (!_m.containsKey("order") || _m.get("order") == null) ? java.util.Optional.<Long>empty() : java.util.Optional.of(dev.unofficialbox.core.Json.asLong(_m.get("order"))),
            !_m.containsKey("embed_url_external_user_id") ? dev.unofficialbox.core.Tristate.<String>absent() : (_m.get("embed_url_external_user_id") == null ? dev.unofficialbox.core.Tristate.<String>ofNull() : dev.unofficialbox.core.Tristate.of(dev.unofficialbox.core.Json.asString(_m.get("embed_url_external_user_id")))),
            !_m.containsKey("redirect_url") ? dev.unofficialbox.core.Tristate.<String>absent() : (_m.get("redirect_url") == null ? dev.unofficialbox.core.Tristate.<String>ofNull() : dev.unofficialbox.core.Tristate.of(dev.unofficialbox.core.Json.asString(_m.get("redirect_url")))),
            !_m.containsKey("declined_redirect_url") ? dev.unofficialbox.core.Tristate.<String>absent() : (_m.get("declined_redirect_url") == null ? dev.unofficialbox.core.Tristate.<String>ofNull() : dev.unofficialbox.core.Tristate.of(dev.unofficialbox.core.Json.asString(_m.get("declined_redirect_url")))),
            !_m.containsKey("login_required") ? dev.unofficialbox.core.Tristate.<Boolean>absent() : (_m.get("login_required") == null ? dev.unofficialbox.core.Tristate.<Boolean>ofNull() : dev.unofficialbox.core.Tristate.of(dev.unofficialbox.core.Json.asBoolean(_m.get("login_required")))),
            !_m.containsKey("verification_phone_number") ? dev.unofficialbox.core.Tristate.<String>absent() : (_m.get("verification_phone_number") == null ? dev.unofficialbox.core.Tristate.<String>ofNull() : dev.unofficialbox.core.Tristate.of(dev.unofficialbox.core.Json.asString(_m.get("verification_phone_number")))),
            !_m.containsKey("password") ? dev.unofficialbox.core.Tristate.<String>absent() : (_m.get("password") == null ? dev.unofficialbox.core.Tristate.<String>ofNull() : dev.unofficialbox.core.Tristate.of(dev.unofficialbox.core.Json.asString(_m.get("password")))),
            !_m.containsKey("signer_group_id") ? dev.unofficialbox.core.Tristate.<String>absent() : (_m.get("signer_group_id") == null ? dev.unofficialbox.core.Tristate.<String>ofNull() : dev.unofficialbox.core.Tristate.of(dev.unofficialbox.core.Json.asString(_m.get("signer_group_id")))),
            !_m.containsKey("suppress_notifications") ? dev.unofficialbox.core.Tristate.<Boolean>absent() : (_m.get("suppress_notifications") == null ? dev.unofficialbox.core.Tristate.<Boolean>ofNull() : dev.unofficialbox.core.Tristate.of(dev.unofficialbox.core.Json.asBoolean(_m.get("suppress_notifications")))),
            !_m.containsKey("language") ? dev.unofficialbox.core.Tristate.<String>absent() : (_m.get("language") == null ? dev.unofficialbox.core.Tristate.<String>ofNull() : dev.unofficialbox.core.Tristate.of(dev.unofficialbox.core.Json.asString(_m.get("language")))),
            (!_m.containsKey("has_viewed_document") || _m.get("has_viewed_document") == null) ? java.util.Optional.<Boolean>empty() : java.util.Optional.of(dev.unofficialbox.core.Json.asBoolean(_m.get("has_viewed_document"))),
            !_m.containsKey("signer_decision") ? dev.unofficialbox.core.Tristate.<SignRequestSignerSignerDecision>absent() : (_m.get("signer_decision") == null ? dev.unofficialbox.core.Tristate.<SignRequestSignerSignerDecision>ofNull() : dev.unofficialbox.core.Tristate.of((_m.get("signer_decision") == null ? null : SignRequestSignerSignerDecision.fromJson(_m.get("signer_decision"))))),
            (!_m.containsKey("inputs") || _m.get("inputs") == null) ? java.util.Optional.<List<SignRequestSignerInput>>empty() : java.util.Optional.of(dev.unofficialbox.core.Json.decodeList(_m.get("inputs"), _x0 -> (_x0 == null ? null : SignRequestSignerInput.fromJson(_x0)))),
            !_m.containsKey("embed_url") ? dev.unofficialbox.core.Tristate.<String>absent() : (_m.get("embed_url") == null ? dev.unofficialbox.core.Tristate.<String>ofNull() : dev.unofficialbox.core.Tristate.of(dev.unofficialbox.core.Json.asString(_m.get("embed_url")))),
            !_m.containsKey("iframeable_embed_url") ? dev.unofficialbox.core.Tristate.<String>absent() : (_m.get("iframeable_embed_url") == null ? dev.unofficialbox.core.Tristate.<String>ofNull() : dev.unofficialbox.core.Tristate.of(dev.unofficialbox.core.Json.asString(_m.get("iframeable_embed_url")))),
            !_m.containsKey("attachments") ? dev.unofficialbox.core.Tristate.<List<SignRequestSignerAttachment>>absent() : (_m.get("attachments") == null ? dev.unofficialbox.core.Tristate.<List<SignRequestSignerAttachment>>ofNull() : dev.unofficialbox.core.Tristate.of(dev.unofficialbox.core.Json.decodeList(_m.get("attachments"), _x0 -> (_x0 == null ? null : SignRequestSignerAttachment.fromJson(_x0)))))
        );
    }

    /** A fluent builder; unset optional fields default to empty. */
    public static Builder builder() {
        return new Builder();
    }

    public static final class Builder {
        private String email;
        private Optional<SignRequestCreateSignerRole> role = java.util.Optional.empty();
        private Optional<Boolean> isInPerson = java.util.Optional.empty();
        private Optional<Long> order = java.util.Optional.empty();
        private Tristate<String> embedUrlExternalUserId;
        private Tristate<String> redirectUrl;
        private Tristate<String> declinedRedirectUrl;
        private Tristate<Boolean> loginRequired;
        private Tristate<String> verificationPhoneNumber;
        private Tristate<String> password;
        private Tristate<String> signerGroupId;
        private Tristate<Boolean> suppressNotifications;
        private Tristate<String> language;
        private Optional<Boolean> hasViewedDocument = java.util.Optional.empty();
        private Tristate<SignRequestSignerSignerDecision> signerDecision;
        private Optional<List<SignRequestSignerInput>> inputs = java.util.Optional.empty();
        private Tristate<String> embedUrl;
        private Tristate<String> iframeableEmbedUrl;
        private Tristate<List<SignRequestSignerAttachment>> attachments;

        public Builder email(String email) {
            this.email = email;
            return this;
        }
        public Builder role(SignRequestCreateSignerRole role) {
            this.role = java.util.Optional.ofNullable(role);
            return this;
        }
        public Builder isInPerson(Boolean isInPerson) {
            this.isInPerson = java.util.Optional.ofNullable(isInPerson);
            return this;
        }
        public Builder order(Long order) {
            this.order = java.util.Optional.ofNullable(order);
            return this;
        }
        public Builder embedUrlExternalUserId(Tristate<String> embedUrlExternalUserId) {
            this.embedUrlExternalUserId = embedUrlExternalUserId;
            return this;
        }
        public Builder redirectUrl(Tristate<String> redirectUrl) {
            this.redirectUrl = redirectUrl;
            return this;
        }
        public Builder declinedRedirectUrl(Tristate<String> declinedRedirectUrl) {
            this.declinedRedirectUrl = declinedRedirectUrl;
            return this;
        }
        public Builder loginRequired(Tristate<Boolean> loginRequired) {
            this.loginRequired = loginRequired;
            return this;
        }
        public Builder verificationPhoneNumber(Tristate<String> verificationPhoneNumber) {
            this.verificationPhoneNumber = verificationPhoneNumber;
            return this;
        }
        public Builder password(Tristate<String> password) {
            this.password = password;
            return this;
        }
        public Builder signerGroupId(Tristate<String> signerGroupId) {
            this.signerGroupId = signerGroupId;
            return this;
        }
        public Builder suppressNotifications(Tristate<Boolean> suppressNotifications) {
            this.suppressNotifications = suppressNotifications;
            return this;
        }
        public Builder language(Tristate<String> language) {
            this.language = language;
            return this;
        }
        public Builder hasViewedDocument(Boolean hasViewedDocument) {
            this.hasViewedDocument = java.util.Optional.ofNullable(hasViewedDocument);
            return this;
        }
        public Builder signerDecision(Tristate<SignRequestSignerSignerDecision> signerDecision) {
            this.signerDecision = signerDecision;
            return this;
        }
        public Builder inputs(List<SignRequestSignerInput> inputs) {
            this.inputs = java.util.Optional.ofNullable(inputs);
            return this;
        }
        public Builder embedUrl(Tristate<String> embedUrl) {
            this.embedUrl = embedUrl;
            return this;
        }
        public Builder iframeableEmbedUrl(Tristate<String> iframeableEmbedUrl) {
            this.iframeableEmbedUrl = iframeableEmbedUrl;
            return this;
        }
        public Builder attachments(Tristate<List<SignRequestSignerAttachment>> attachments) {
            this.attachments = attachments;
            return this;
        }

        public SignRequestSigner build() {
            return new SignRequestSigner(
                email,
                role,
                isInPerson,
                order,
                embedUrlExternalUserId,
                redirectUrl,
                declinedRedirectUrl,
                loginRequired,
                verificationPhoneNumber,
                password,
                signerGroupId,
                suppressNotifications,
                language,
                hasViewedDocument,
                signerDecision,
                inputs,
                embedUrl,
                iframeableEmbedUrl,
                attachments
            );
        }
    }
}
