// Code generated by box-gantry 0.1.0 (spec ee7d55aedefe2fa0) for Box API 2024.0. DO NOT EDIT.
package dev.unofficialbox.model.schemas;

import module java.base;

public record SkillUpdateRequest(
    Optional<PutOp> op,
    Optional<String> path,
    Optional<SkillCard> value) {
    public java.util.Map<String, Object> toJson() {
        java.util.Map<String, Object> _m = new java.util.LinkedHashMap<>();
        op().ifPresent(_v -> _m.put("op", (_v == null ? null : _v.toJson())));
        path().ifPresent(_v -> _m.put("path", _v));
        value().ifPresent(_v -> _m.put("value", (_v == null ? null : _v.toJson())));
        return _m;
    }

    public static SkillUpdateRequest fromJson(Object _json) {
        java.util.Map<String, Object> _m = dev.unofficialbox.core.Json.asObject(_json);
        return new SkillUpdateRequest(
            (!_m.containsKey("op") || _m.get("op") == null) ? java.util.Optional.<PutOp>empty() : java.util.Optional.of((_m.get("op") == null ? null : PutOp.fromJson(_m.get("op")))),
            (!_m.containsKey("path") || _m.get("path") == null) ? java.util.Optional.<String>empty() : java.util.Optional.of(dev.unofficialbox.core.Json.asString(_m.get("path"))),
            (!_m.containsKey("value") || _m.get("value") == null) ? java.util.Optional.<SkillCard>empty() : java.util.Optional.of((_m.get("value") == null ? null : SkillCard.fromJson(_m.get("value"))))
        );
    }

    /** A fluent builder; unset optional fields default to empty. */
    public static Builder builder() {
        return new Builder();
    }

    public static final class Builder {
        private Optional<PutOp> op = java.util.Optional.empty();
        private Optional<String> path = java.util.Optional.empty();
        private Optional<SkillCard> value = java.util.Optional.empty();

        public Builder op(PutOp op) {
            this.op = java.util.Optional.ofNullable(op);
            return this;
        }
        public Builder path(String path) {
            this.path = java.util.Optional.ofNullable(path);
            return this;
        }
        public Builder value(SkillCard value) {
            this.value = java.util.Optional.ofNullable(value);
            return this;
        }

        public SkillUpdateRequest build() {
            return new SkillUpdateRequest(
                op,
                path,
                value
            );
        }
    }
}
