// Code generated by box-gantry 0.1.0 (spec ee7d55aedefe2fa0) for Box API 2024.0. DO NOT EDIT.
package dev.unofficialbox.model.schemas;

public record StatusState(String value) {
    public static final StatusState SUCCESS = new StatusState("success");
    public static final StatusState VIEWABLE = new StatusState("viewable");
    public static final StatusState PENDING = new StatusState("pending");
    public static final StatusState NONE = new StatusState("none");

    public String toJson() {
        return value;
    }

    public static StatusState fromJson(Object _json) {
        return new StatusState(dev.unofficialbox.core.Json.asString(_json));
    }
}
