// Code generated by box-gantry 0.1.0 (spec ee7d55aedefe2fa0) for Box API 2024.0. DO NOT EDIT.
package dev.unofficialbox.model.schemas;

import module java.base;

public record StoragePolicy(String id, StoragePolicyType type, Optional<String> name) {
    public java.util.Map<String, Object> toJson() {
        java.util.Map<String, Object> _m = new java.util.LinkedHashMap<>();
        _m.put("id", id());
        _m.put("type", (type() == null ? null : type().toJson()));
        name().ifPresent(_v -> _m.put("name", _v));
        return _m;
    }

    public static StoragePolicy fromJson(Object _json) {
        java.util.Map<String, Object> _m = dev.unofficialbox.core.Json.asObject(_json);
        return new StoragePolicy(
            dev.unofficialbox.core.Json.asString(_m.get("id")),
            (_m.get("type") == null ? null : StoragePolicyType.fromJson(_m.get("type"))),
            (!_m.containsKey("name") || _m.get("name") == null) ? java.util.Optional.<String>empty() : java.util.Optional.of(dev.unofficialbox.core.Json.asString(_m.get("name")))
        );
    }

    /** A fluent builder; unset optional fields default to empty. */
    public static Builder builder() {
        return new Builder();
    }

    public static final class Builder {
        private String id;
        private StoragePolicyType type;
        private Optional<String> name = java.util.Optional.empty();

        public Builder id(String id) {
            this.id = id;
            return this;
        }
        public Builder type(StoragePolicyType type) {
            this.type = type;
            return this;
        }
        public Builder name(String name) {
            this.name = java.util.Optional.ofNullable(name);
            return this;
        }

        public StoragePolicy build() {
            return new StoragePolicy(
                id,
                type,
                name
            );
        }
    }
}
