// Code generated by box-gantry 0.1.0 (spec ee7d55aedefe2fa0) for Box API 2024.0. DO NOT EDIT.
package dev.unofficialbox.model.schemas;

public record TaskAssignmentResolutionState(String value) {
    public static final TaskAssignmentResolutionState COMPLETED = new TaskAssignmentResolutionState("completed");
    public static final TaskAssignmentResolutionState INCOMPLETE = new TaskAssignmentResolutionState("incomplete");
    public static final TaskAssignmentResolutionState APPROVED = new TaskAssignmentResolutionState("approved");
    public static final TaskAssignmentResolutionState REJECTED = new TaskAssignmentResolutionState("rejected");

    public String toJson() {
        return value;
    }

    public static TaskAssignmentResolutionState fromJson(Object _json) {
        return new TaskAssignmentResolutionState(dev.unofficialbox.core.Json.asString(_json));
    }
}
