// Code generated by box-gantry 0.1.0 (spec ee7d55aedefe2fa0) for Box API 2024.0. DO NOT EDIT.
package dev.unofficialbox.model.schemas;

import module java.base;

public record TermsOfService(
    String id,
    TermsOfServiceType type,
    Optional<TermsOfServiceStatus> status,
    Optional<CollaborationAllowlistEntryEnterprise> enterprise,
    Optional<TermsOfServiceTosType> tosType,
    Optional<String> text,
    Optional<OffsetDateTime> createdAt,
    Optional<OffsetDateTime> modifiedAt) {
    public java.util.Map<String, Object> toJson() {
        java.util.Map<String, Object> _m = new java.util.LinkedHashMap<>();
        _m.put("id", id());
        _m.put("type", (type() == null ? null : type().toJson()));
        status().ifPresent(_v -> _m.put("status", (_v == null ? null : _v.toJson())));
        enterprise().ifPresent(_v -> _m.put("enterprise", (_v == null ? null : _v.toJson())));
        tosType().ifPresent(_v -> _m.put("tos_type", (_v == null ? null : _v.toJson())));
        text().ifPresent(_v -> _m.put("text", _v));
        createdAt().ifPresent(_v -> _m.put("created_at", (_v == null ? null : _v.toString())));
        modifiedAt().ifPresent(_v -> _m.put("modified_at", (_v == null ? null : _v.toString())));
        return _m;
    }

    public static TermsOfService fromJson(Object _json) {
        java.util.Map<String, Object> _m = dev.unofficialbox.core.Json.asObject(_json);
        return new TermsOfService(
            dev.unofficialbox.core.Json.asString(_m.get("id")),
            (_m.get("type") == null ? null : TermsOfServiceType.fromJson(_m.get("type"))),
            (!_m.containsKey("status") || _m.get("status") == null) ? java.util.Optional.<TermsOfServiceStatus>empty() : java.util.Optional.of((_m.get("status") == null ? null : TermsOfServiceStatus.fromJson(_m.get("status")))),
            (!_m.containsKey("enterprise") || _m.get("enterprise") == null) ? java.util.Optional.<CollaborationAllowlistEntryEnterprise>empty() : java.util.Optional.of((_m.get("enterprise") == null ? null : CollaborationAllowlistEntryEnterprise.fromJson(_m.get("enterprise")))),
            (!_m.containsKey("tos_type") || _m.get("tos_type") == null) ? java.util.Optional.<TermsOfServiceTosType>empty() : java.util.Optional.of((_m.get("tos_type") == null ? null : TermsOfServiceTosType.fromJson(_m.get("tos_type")))),
            (!_m.containsKey("text") || _m.get("text") == null) ? java.util.Optional.<String>empty() : java.util.Optional.of(dev.unofficialbox.core.Json.asString(_m.get("text"))),
            (!_m.containsKey("created_at") || _m.get("created_at") == null) ? java.util.Optional.<OffsetDateTime>empty() : java.util.Optional.of((_m.get("created_at") == null ? null : java.time.OffsetDateTime.parse(dev.unofficialbox.core.Json.asString(_m.get("created_at"))))),
            (!_m.containsKey("modified_at") || _m.get("modified_at") == null) ? java.util.Optional.<OffsetDateTime>empty() : java.util.Optional.of((_m.get("modified_at") == null ? null : java.time.OffsetDateTime.parse(dev.unofficialbox.core.Json.asString(_m.get("modified_at")))))
        );
    }

    /** A fluent builder; unset optional fields default to empty. */
    public static Builder builder() {
        return new Builder();
    }

    public static final class Builder {
        private String id;
        private TermsOfServiceType type;
        private Optional<TermsOfServiceStatus> status = java.util.Optional.empty();
        private Optional<CollaborationAllowlistEntryEnterprise> enterprise = java.util.Optional.empty();
        private Optional<TermsOfServiceTosType> tosType = java.util.Optional.empty();
        private Optional<String> text = java.util.Optional.empty();
        private Optional<OffsetDateTime> createdAt = java.util.Optional.empty();
        private Optional<OffsetDateTime> modifiedAt = java.util.Optional.empty();

        public Builder id(String id) {
            this.id = id;
            return this;
        }
        public Builder type(TermsOfServiceType type) {
            this.type = type;
            return this;
        }
        public Builder status(TermsOfServiceStatus status) {
            this.status = java.util.Optional.ofNullable(status);
            return this;
        }
        public Builder enterprise(CollaborationAllowlistEntryEnterprise enterprise) {
            this.enterprise = java.util.Optional.ofNullable(enterprise);
            return this;
        }
        public Builder tosType(TermsOfServiceTosType tosType) {
            this.tosType = java.util.Optional.ofNullable(tosType);
            return this;
        }
        public Builder text(String text) {
            this.text = java.util.Optional.ofNullable(text);
            return this;
        }
        public Builder createdAt(OffsetDateTime createdAt) {
            this.createdAt = java.util.Optional.ofNullable(createdAt);
            return this;
        }
        public Builder modifiedAt(OffsetDateTime modifiedAt) {
            this.modifiedAt = java.util.Optional.ofNullable(modifiedAt);
            return this;
        }

        public TermsOfService build() {
            return new TermsOfService(
                id,
                type,
                status,
                enterprise,
                tosType,
                text,
                createdAt,
                modifiedAt
            );
        }
    }
}
