// Code generated by box-gantry 0.1.0 (spec ee7d55aedefe2fa0) for Box API 2024.0. DO NOT EDIT.
package dev.unofficialbox.model.schemas;

import module java.base;

public record TimelineSkillCardEntries(
    Optional<String> text,
    Optional<List<EntriesAppears>> appears,
    Optional<String> imageUrl) {
    public java.util.Map<String, Object> toJson() {
        java.util.Map<String, Object> _m = new java.util.LinkedHashMap<>();
        text().ifPresent(_v -> _m.put("text", _v));
        appears().ifPresent(_v -> _m.put("appears", dev.unofficialbox.core.Json.encodeList(_v, _x0 -> (_x0 == null ? null : _x0.toJson()))));
        imageUrl().ifPresent(_v -> _m.put("image_url", _v));
        return _m;
    }

    public static TimelineSkillCardEntries fromJson(Object _json) {
        java.util.Map<String, Object> _m = dev.unofficialbox.core.Json.asObject(_json);
        return new TimelineSkillCardEntries(
            (!_m.containsKey("text") || _m.get("text") == null) ? java.util.Optional.<String>empty() : java.util.Optional.of(dev.unofficialbox.core.Json.asString(_m.get("text"))),
            (!_m.containsKey("appears") || _m.get("appears") == null) ? java.util.Optional.<List<EntriesAppears>>empty() : java.util.Optional.of(dev.unofficialbox.core.Json.decodeList(_m.get("appears"), _x0 -> (_x0 == null ? null : EntriesAppears.fromJson(_x0)))),
            (!_m.containsKey("image_url") || _m.get("image_url") == null) ? java.util.Optional.<String>empty() : java.util.Optional.of(dev.unofficialbox.core.Json.asString(_m.get("image_url")))
        );
    }
}
