// Code generated by box-gantry 0.1.0 (spec ee7d55aedefe2fa0) for Box API 2024.0. DO NOT EDIT.
package dev.unofficialbox.model.schemas;

import module java.base;

public record TrackingCode(
    Optional<TrackingCodeType> type,
    Optional<String> name,
    Optional<String> value) {
    public java.util.Map<String, Object> toJson() {
        java.util.Map<String, Object> _m = new java.util.LinkedHashMap<>();
        type().ifPresent(_v -> _m.put("type", (_v == null ? null : _v.toJson())));
        name().ifPresent(_v -> _m.put("name", _v));
        value().ifPresent(_v -> _m.put("value", _v));
        return _m;
    }

    public static TrackingCode fromJson(Object _json) {
        java.util.Map<String, Object> _m = dev.unofficialbox.core.Json.asObject(_json);
        return new TrackingCode(
            (!_m.containsKey("type") || _m.get("type") == null) ? java.util.Optional.<TrackingCodeType>empty() : java.util.Optional.of((_m.get("type") == null ? null : TrackingCodeType.fromJson(_m.get("type")))),
            (!_m.containsKey("name") || _m.get("name") == null) ? java.util.Optional.<String>empty() : java.util.Optional.of(dev.unofficialbox.core.Json.asString(_m.get("name"))),
            (!_m.containsKey("value") || _m.get("value") == null) ? java.util.Optional.<String>empty() : java.util.Optional.of(dev.unofficialbox.core.Json.asString(_m.get("value")))
        );
    }
}
