// Code generated by box-gantry 0.1.0 (spec ee7d55aedefe2fa0) for Box API 2024.0. DO NOT EDIT.
package dev.unofficialbox.model.schemas;

import module java.base;
import dev.unofficialbox.core.Tristate;

public record TrashFolderRestored(
    Optional<String> id,
    Tristate<String> etag,
    Optional<FolderType> type,
    Optional<String> sequenceId,
    Optional<String> name,
    Tristate<OffsetDateTime> createdAt,
    Tristate<OffsetDateTime> modifiedAt,
    Optional<String> description,
    Optional<Long> size,
    Optional<FilePathCollection> pathCollection,
    Optional<UserMini> createdBy,
    Optional<UserMini> modifiedBy,
    Tristate<String> trashedAt,
    Tristate<String> purgedAt,
    Tristate<OffsetDateTime> contentCreatedAt,
    Tristate<OffsetDateTime> contentModifiedAt,
    Optional<UserMini> ownedBy,
    Tristate<String> sharedLink,
    Tristate<String> folderUploadEmail,
    Tristate<FolderMini> parent,
    Optional<FileItemStatus> itemStatus) {
    public java.util.Map<String, Object> toJson() {
        java.util.Map<String, Object> _m = new java.util.LinkedHashMap<>();
        id().ifPresent(_v -> _m.put("id", _v));
        if (etag().isPresent()) { _m.put("etag", etag().value()); }
        else if (etag().isNull()) { _m.put("etag", null); }
        type().ifPresent(_v -> _m.put("type", (_v == null ? null : _v.toJson())));
        sequenceId().ifPresent(_v -> _m.put("sequence_id", _v));
        name().ifPresent(_v -> _m.put("name", _v));
        if (createdAt().isPresent()) { _m.put("created_at", (createdAt().value() == null ? null : createdAt().value().toString())); }
        else if (createdAt().isNull()) { _m.put("created_at", null); }
        if (modifiedAt().isPresent()) { _m.put("modified_at", (modifiedAt().value() == null ? null : modifiedAt().value().toString())); }
        else if (modifiedAt().isNull()) { _m.put("modified_at", null); }
        description().ifPresent(_v -> _m.put("description", _v));
        size().ifPresent(_v -> _m.put("size", _v));
        pathCollection().ifPresent(_v -> _m.put("path_collection", (_v == null ? null : _v.toJson())));
        createdBy().ifPresent(_v -> _m.put("created_by", (_v == null ? null : _v.toJson())));
        modifiedBy().ifPresent(_v -> _m.put("modified_by", (_v == null ? null : _v.toJson())));
        if (trashedAt().isPresent()) { _m.put("trashed_at", trashedAt().value()); }
        else if (trashedAt().isNull()) { _m.put("trashed_at", null); }
        if (purgedAt().isPresent()) { _m.put("purged_at", purgedAt().value()); }
        else if (purgedAt().isNull()) { _m.put("purged_at", null); }
        if (contentCreatedAt().isPresent()) { _m.put("content_created_at", (contentCreatedAt().value() == null ? null : contentCreatedAt().value().toString())); }
        else if (contentCreatedAt().isNull()) { _m.put("content_created_at", null); }
        if (contentModifiedAt().isPresent()) { _m.put("content_modified_at", (contentModifiedAt().value() == null ? null : contentModifiedAt().value().toString())); }
        else if (contentModifiedAt().isNull()) { _m.put("content_modified_at", null); }
        ownedBy().ifPresent(_v -> _m.put("owned_by", (_v == null ? null : _v.toJson())));
        if (sharedLink().isPresent()) { _m.put("shared_link", sharedLink().value()); }
        else if (sharedLink().isNull()) { _m.put("shared_link", null); }
        if (folderUploadEmail().isPresent()) { _m.put("folder_upload_email", folderUploadEmail().value()); }
        else if (folderUploadEmail().isNull()) { _m.put("folder_upload_email", null); }
        if (parent().isPresent()) { _m.put("parent", (parent().value() == null ? null : parent().value().toJson())); }
        else if (parent().isNull()) { _m.put("parent", null); }
        itemStatus().ifPresent(_v -> _m.put("item_status", (_v == null ? null : _v.toJson())));
        return _m;
    }

    public static TrashFolderRestored fromJson(Object _json) {
        java.util.Map<String, Object> _m = dev.unofficialbox.core.Json.asObject(_json);
        return new TrashFolderRestored(
            (!_m.containsKey("id") || _m.get("id") == null) ? java.util.Optional.<String>empty() : java.util.Optional.of(dev.unofficialbox.core.Json.asString(_m.get("id"))),
            !_m.containsKey("etag") ? dev.unofficialbox.core.Tristate.<String>absent() : (_m.get("etag") == null ? dev.unofficialbox.core.Tristate.<String>ofNull() : dev.unofficialbox.core.Tristate.of(dev.unofficialbox.core.Json.asString(_m.get("etag")))),
            (!_m.containsKey("type") || _m.get("type") == null) ? java.util.Optional.<FolderType>empty() : java.util.Optional.of((_m.get("type") == null ? null : FolderType.fromJson(_m.get("type")))),
            (!_m.containsKey("sequence_id") || _m.get("sequence_id") == null) ? java.util.Optional.<String>empty() : java.util.Optional.of(dev.unofficialbox.core.Json.asString(_m.get("sequence_id"))),
            (!_m.containsKey("name") || _m.get("name") == null) ? java.util.Optional.<String>empty() : java.util.Optional.of(dev.unofficialbox.core.Json.asString(_m.get("name"))),
            !_m.containsKey("created_at") ? dev.unofficialbox.core.Tristate.<OffsetDateTime>absent() : (_m.get("created_at") == null ? dev.unofficialbox.core.Tristate.<OffsetDateTime>ofNull() : dev.unofficialbox.core.Tristate.of((_m.get("created_at") == null ? null : java.time.OffsetDateTime.parse(dev.unofficialbox.core.Json.asString(_m.get("created_at")))))),
            !_m.containsKey("modified_at") ? dev.unofficialbox.core.Tristate.<OffsetDateTime>absent() : (_m.get("modified_at") == null ? dev.unofficialbox.core.Tristate.<OffsetDateTime>ofNull() : dev.unofficialbox.core.Tristate.of((_m.get("modified_at") == null ? null : java.time.OffsetDateTime.parse(dev.unofficialbox.core.Json.asString(_m.get("modified_at")))))),
            (!_m.containsKey("description") || _m.get("description") == null) ? java.util.Optional.<String>empty() : java.util.Optional.of(dev.unofficialbox.core.Json.asString(_m.get("description"))),
            (!_m.containsKey("size") || _m.get("size") == null) ? java.util.Optional.<Long>empty() : java.util.Optional.of(dev.unofficialbox.core.Json.asLong(_m.get("size"))),
            (!_m.containsKey("path_collection") || _m.get("path_collection") == null) ? java.util.Optional.<FilePathCollection>empty() : java.util.Optional.of((_m.get("path_collection") == null ? null : FilePathCollection.fromJson(_m.get("path_collection")))),
            (!_m.containsKey("created_by") || _m.get("created_by") == null) ? java.util.Optional.<UserMini>empty() : java.util.Optional.of((_m.get("created_by") == null ? null : UserMini.fromJson(_m.get("created_by")))),
            (!_m.containsKey("modified_by") || _m.get("modified_by") == null) ? java.util.Optional.<UserMini>empty() : java.util.Optional.of((_m.get("modified_by") == null ? null : UserMini.fromJson(_m.get("modified_by")))),
            !_m.containsKey("trashed_at") ? dev.unofficialbox.core.Tristate.<String>absent() : (_m.get("trashed_at") == null ? dev.unofficialbox.core.Tristate.<String>ofNull() : dev.unofficialbox.core.Tristate.of(dev.unofficialbox.core.Json.asString(_m.get("trashed_at")))),
            !_m.containsKey("purged_at") ? dev.unofficialbox.core.Tristate.<String>absent() : (_m.get("purged_at") == null ? dev.unofficialbox.core.Tristate.<String>ofNull() : dev.unofficialbox.core.Tristate.of(dev.unofficialbox.core.Json.asString(_m.get("purged_at")))),
            !_m.containsKey("content_created_at") ? dev.unofficialbox.core.Tristate.<OffsetDateTime>absent() : (_m.get("content_created_at") == null ? dev.unofficialbox.core.Tristate.<OffsetDateTime>ofNull() : dev.unofficialbox.core.Tristate.of((_m.get("content_created_at") == null ? null : java.time.OffsetDateTime.parse(dev.unofficialbox.core.Json.asString(_m.get("content_created_at")))))),
            !_m.containsKey("content_modified_at") ? dev.unofficialbox.core.Tristate.<OffsetDateTime>absent() : (_m.get("content_modified_at") == null ? dev.unofficialbox.core.Tristate.<OffsetDateTime>ofNull() : dev.unofficialbox.core.Tristate.of((_m.get("content_modified_at") == null ? null : java.time.OffsetDateTime.parse(dev.unofficialbox.core.Json.asString(_m.get("content_modified_at")))))),
            (!_m.containsKey("owned_by") || _m.get("owned_by") == null) ? java.util.Optional.<UserMini>empty() : java.util.Optional.of((_m.get("owned_by") == null ? null : UserMini.fromJson(_m.get("owned_by")))),
            !_m.containsKey("shared_link") ? dev.unofficialbox.core.Tristate.<String>absent() : (_m.get("shared_link") == null ? dev.unofficialbox.core.Tristate.<String>ofNull() : dev.unofficialbox.core.Tristate.of(dev.unofficialbox.core.Json.asString(_m.get("shared_link")))),
            !_m.containsKey("folder_upload_email") ? dev.unofficialbox.core.Tristate.<String>absent() : (_m.get("folder_upload_email") == null ? dev.unofficialbox.core.Tristate.<String>ofNull() : dev.unofficialbox.core.Tristate.of(dev.unofficialbox.core.Json.asString(_m.get("folder_upload_email")))),
            !_m.containsKey("parent") ? dev.unofficialbox.core.Tristate.<FolderMini>absent() : (_m.get("parent") == null ? dev.unofficialbox.core.Tristate.<FolderMini>ofNull() : dev.unofficialbox.core.Tristate.of((_m.get("parent") == null ? null : FolderMini.fromJson(_m.get("parent"))))),
            (!_m.containsKey("item_status") || _m.get("item_status") == null) ? java.util.Optional.<FileItemStatus>empty() : java.util.Optional.of((_m.get("item_status") == null ? null : FileItemStatus.fromJson(_m.get("item_status"))))
        );
    }

    /** A fluent builder; unset optional fields default to empty. */
    public static Builder builder() {
        return new Builder();
    }

    public static final class Builder {
        private Optional<String> id = java.util.Optional.empty();
        private Tristate<String> etag;
        private Optional<FolderType> type = java.util.Optional.empty();
        private Optional<String> sequenceId = java.util.Optional.empty();
        private Optional<String> name = java.util.Optional.empty();
        private Tristate<OffsetDateTime> createdAt;
        private Tristate<OffsetDateTime> modifiedAt;
        private Optional<String> description = java.util.Optional.empty();
        private Optional<Long> size = java.util.Optional.empty();
        private Optional<FilePathCollection> pathCollection = java.util.Optional.empty();
        private Optional<UserMini> createdBy = java.util.Optional.empty();
        private Optional<UserMini> modifiedBy = java.util.Optional.empty();
        private Tristate<String> trashedAt;
        private Tristate<String> purgedAt;
        private Tristate<OffsetDateTime> contentCreatedAt;
        private Tristate<OffsetDateTime> contentModifiedAt;
        private Optional<UserMini> ownedBy = java.util.Optional.empty();
        private Tristate<String> sharedLink;
        private Tristate<String> folderUploadEmail;
        private Tristate<FolderMini> parent;
        private Optional<FileItemStatus> itemStatus = java.util.Optional.empty();

        public Builder id(String id) {
            this.id = java.util.Optional.ofNullable(id);
            return this;
        }
        public Builder etag(Tristate<String> etag) {
            this.etag = etag;
            return this;
        }
        public Builder type(FolderType type) {
            this.type = java.util.Optional.ofNullable(type);
            return this;
        }
        public Builder sequenceId(String sequenceId) {
            this.sequenceId = java.util.Optional.ofNullable(sequenceId);
            return this;
        }
        public Builder name(String name) {
            this.name = java.util.Optional.ofNullable(name);
            return this;
        }
        public Builder createdAt(Tristate<OffsetDateTime> createdAt) {
            this.createdAt = createdAt;
            return this;
        }
        public Builder modifiedAt(Tristate<OffsetDateTime> modifiedAt) {
            this.modifiedAt = modifiedAt;
            return this;
        }
        public Builder description(String description) {
            this.description = java.util.Optional.ofNullable(description);
            return this;
        }
        public Builder size(Long size) {
            this.size = java.util.Optional.ofNullable(size);
            return this;
        }
        public Builder pathCollection(FilePathCollection pathCollection) {
            this.pathCollection = java.util.Optional.ofNullable(pathCollection);
            return this;
        }
        public Builder createdBy(UserMini createdBy) {
            this.createdBy = java.util.Optional.ofNullable(createdBy);
            return this;
        }
        public Builder modifiedBy(UserMini modifiedBy) {
            this.modifiedBy = java.util.Optional.ofNullable(modifiedBy);
            return this;
        }
        public Builder trashedAt(Tristate<String> trashedAt) {
            this.trashedAt = trashedAt;
            return this;
        }
        public Builder purgedAt(Tristate<String> purgedAt) {
            this.purgedAt = purgedAt;
            return this;
        }
        public Builder contentCreatedAt(Tristate<OffsetDateTime> contentCreatedAt) {
            this.contentCreatedAt = contentCreatedAt;
            return this;
        }
        public Builder contentModifiedAt(Tristate<OffsetDateTime> contentModifiedAt) {
            this.contentModifiedAt = contentModifiedAt;
            return this;
        }
        public Builder ownedBy(UserMini ownedBy) {
            this.ownedBy = java.util.Optional.ofNullable(ownedBy);
            return this;
        }
        public Builder sharedLink(Tristate<String> sharedLink) {
            this.sharedLink = sharedLink;
            return this;
        }
        public Builder folderUploadEmail(Tristate<String> folderUploadEmail) {
            this.folderUploadEmail = folderUploadEmail;
            return this;
        }
        public Builder parent(Tristate<FolderMini> parent) {
            this.parent = parent;
            return this;
        }
        public Builder itemStatus(FileItemStatus itemStatus) {
            this.itemStatus = java.util.Optional.ofNullable(itemStatus);
            return this;
        }

        public TrashFolderRestored build() {
            return new TrashFolderRestored(
                id,
                etag,
                type,
                sequenceId,
                name,
                createdAt,
                modifiedAt,
                description,
                size,
                pathCollection,
                createdBy,
                modifiedBy,
                trashedAt,
                purgedAt,
                contentCreatedAt,
                contentModifiedAt,
                ownedBy,
                sharedLink,
                folderUploadEmail,
                parent,
                itemStatus
            );
        }
    }
}
