// Code generated by box-gantry 0.1.0 (spec ee7d55aedefe2fa0) for Box API 2024.0. DO NOT EDIT.
package dev.unofficialbox.model.schemas;

import module java.base;
import dev.unofficialbox.core.Tristate;

public record TrashFolder(
    String id,
    Tristate<String> etag,
    FolderType type,
    Optional<String> sequenceId,
    String name,
    Tristate<OffsetDateTime> createdAt,
    Tristate<OffsetDateTime> modifiedAt,
    String description,
    Long size,
    TrashFilePathCollection pathCollection,
    UserMini createdBy,
    UserMini modifiedBy,
    Tristate<OffsetDateTime> trashedAt,
    Tristate<OffsetDateTime> purgedAt,
    Tristate<OffsetDateTime> contentCreatedAt,
    Tristate<OffsetDateTime> contentModifiedAt,
    UserMini ownedBy,
    Tristate<String> sharedLink,
    Tristate<String> folderUploadEmail,
    Tristate<FolderMini> parent,
    FileItemStatus itemStatus) {
    public java.util.Map<String, Object> toJson() {
        java.util.Map<String, Object> _m = new java.util.LinkedHashMap<>();
        _m.put("id", id());
        if (etag().isPresent()) { _m.put("etag", etag().value()); }
        else if (etag().isNull()) { _m.put("etag", null); }
        _m.put("type", (type() == null ? null : type().toJson()));
        sequenceId().ifPresent(_v -> _m.put("sequence_id", _v));
        _m.put("name", name());
        if (createdAt().isPresent()) { _m.put("created_at", (createdAt().value() == null ? null : createdAt().value().toString())); }
        else if (createdAt().isNull()) { _m.put("created_at", null); }
        if (modifiedAt().isPresent()) { _m.put("modified_at", (modifiedAt().value() == null ? null : modifiedAt().value().toString())); }
        else if (modifiedAt().isNull()) { _m.put("modified_at", null); }
        _m.put("description", description());
        _m.put("size", size());
        _m.put("path_collection", (pathCollection() == null ? null : pathCollection().toJson()));
        _m.put("created_by", (createdBy() == null ? null : createdBy().toJson()));
        _m.put("modified_by", (modifiedBy() == null ? null : modifiedBy().toJson()));
        if (trashedAt().isPresent()) { _m.put("trashed_at", (trashedAt().value() == null ? null : trashedAt().value().toString())); }
        else if (trashedAt().isNull()) { _m.put("trashed_at", null); }
        if (purgedAt().isPresent()) { _m.put("purged_at", (purgedAt().value() == null ? null : purgedAt().value().toString())); }
        else if (purgedAt().isNull()) { _m.put("purged_at", null); }
        if (contentCreatedAt().isPresent()) { _m.put("content_created_at", (contentCreatedAt().value() == null ? null : contentCreatedAt().value().toString())); }
        else if (contentCreatedAt().isNull()) { _m.put("content_created_at", null); }
        if (contentModifiedAt().isPresent()) { _m.put("content_modified_at", (contentModifiedAt().value() == null ? null : contentModifiedAt().value().toString())); }
        else if (contentModifiedAt().isNull()) { _m.put("content_modified_at", null); }
        _m.put("owned_by", (ownedBy() == null ? null : ownedBy().toJson()));
        if (sharedLink().isPresent()) { _m.put("shared_link", sharedLink().value()); }
        else if (sharedLink().isNull()) { _m.put("shared_link", null); }
        if (folderUploadEmail().isPresent()) { _m.put("folder_upload_email", folderUploadEmail().value()); }
        else if (folderUploadEmail().isNull()) { _m.put("folder_upload_email", null); }
        if (parent().isPresent()) { _m.put("parent", (parent().value() == null ? null : parent().value().toJson())); }
        else if (parent().isNull()) { _m.put("parent", null); }
        _m.put("item_status", (itemStatus() == null ? null : itemStatus().toJson()));
        return _m;
    }

    public static TrashFolder fromJson(Object _json) {
        java.util.Map<String, Object> _m = dev.unofficialbox.core.Json.asObject(_json);
        return new TrashFolder(
            dev.unofficialbox.core.Json.asString(_m.get("id")),
            !_m.containsKey("etag") ? dev.unofficialbox.core.Tristate.<String>absent() : (_m.get("etag") == null ? dev.unofficialbox.core.Tristate.<String>ofNull() : dev.unofficialbox.core.Tristate.of(dev.unofficialbox.core.Json.asString(_m.get("etag")))),
            (_m.get("type") == null ? null : FolderType.fromJson(_m.get("type"))),
            (!_m.containsKey("sequence_id") || _m.get("sequence_id") == null) ? java.util.Optional.<String>empty() : java.util.Optional.of(dev.unofficialbox.core.Json.asString(_m.get("sequence_id"))),
            dev.unofficialbox.core.Json.asString(_m.get("name")),
            !_m.containsKey("created_at") ? dev.unofficialbox.core.Tristate.<OffsetDateTime>absent() : (_m.get("created_at") == null ? dev.unofficialbox.core.Tristate.<OffsetDateTime>ofNull() : dev.unofficialbox.core.Tristate.of((_m.get("created_at") == null ? null : java.time.OffsetDateTime.parse(dev.unofficialbox.core.Json.asString(_m.get("created_at")))))),
            !_m.containsKey("modified_at") ? dev.unofficialbox.core.Tristate.<OffsetDateTime>absent() : (_m.get("modified_at") == null ? dev.unofficialbox.core.Tristate.<OffsetDateTime>ofNull() : dev.unofficialbox.core.Tristate.of((_m.get("modified_at") == null ? null : java.time.OffsetDateTime.parse(dev.unofficialbox.core.Json.asString(_m.get("modified_at")))))),
            dev.unofficialbox.core.Json.asString(_m.get("description")),
            dev.unofficialbox.core.Json.asLong(_m.get("size")),
            (_m.get("path_collection") == null ? null : TrashFilePathCollection.fromJson(_m.get("path_collection"))),
            (_m.get("created_by") == null ? null : UserMini.fromJson(_m.get("created_by"))),
            (_m.get("modified_by") == null ? null : UserMini.fromJson(_m.get("modified_by"))),
            !_m.containsKey("trashed_at") ? dev.unofficialbox.core.Tristate.<OffsetDateTime>absent() : (_m.get("trashed_at") == null ? dev.unofficialbox.core.Tristate.<OffsetDateTime>ofNull() : dev.unofficialbox.core.Tristate.of((_m.get("trashed_at") == null ? null : java.time.OffsetDateTime.parse(dev.unofficialbox.core.Json.asString(_m.get("trashed_at")))))),
            !_m.containsKey("purged_at") ? dev.unofficialbox.core.Tristate.<OffsetDateTime>absent() : (_m.get("purged_at") == null ? dev.unofficialbox.core.Tristate.<OffsetDateTime>ofNull() : dev.unofficialbox.core.Tristate.of((_m.get("purged_at") == null ? null : java.time.OffsetDateTime.parse(dev.unofficialbox.core.Json.asString(_m.get("purged_at")))))),
            !_m.containsKey("content_created_at") ? dev.unofficialbox.core.Tristate.<OffsetDateTime>absent() : (_m.get("content_created_at") == null ? dev.unofficialbox.core.Tristate.<OffsetDateTime>ofNull() : dev.unofficialbox.core.Tristate.of((_m.get("content_created_at") == null ? null : java.time.OffsetDateTime.parse(dev.unofficialbox.core.Json.asString(_m.get("content_created_at")))))),
            !_m.containsKey("content_modified_at") ? dev.unofficialbox.core.Tristate.<OffsetDateTime>absent() : (_m.get("content_modified_at") == null ? dev.unofficialbox.core.Tristate.<OffsetDateTime>ofNull() : dev.unofficialbox.core.Tristate.of((_m.get("content_modified_at") == null ? null : java.time.OffsetDateTime.parse(dev.unofficialbox.core.Json.asString(_m.get("content_modified_at")))))),
            (_m.get("owned_by") == null ? null : UserMini.fromJson(_m.get("owned_by"))),
            !_m.containsKey("shared_link") ? dev.unofficialbox.core.Tristate.<String>absent() : (_m.get("shared_link") == null ? dev.unofficialbox.core.Tristate.<String>ofNull() : dev.unofficialbox.core.Tristate.of(dev.unofficialbox.core.Json.asString(_m.get("shared_link")))),
            !_m.containsKey("folder_upload_email") ? dev.unofficialbox.core.Tristate.<String>absent() : (_m.get("folder_upload_email") == null ? dev.unofficialbox.core.Tristate.<String>ofNull() : dev.unofficialbox.core.Tristate.of(dev.unofficialbox.core.Json.asString(_m.get("folder_upload_email")))),
            !_m.containsKey("parent") ? dev.unofficialbox.core.Tristate.<FolderMini>absent() : (_m.get("parent") == null ? dev.unofficialbox.core.Tristate.<FolderMini>ofNull() : dev.unofficialbox.core.Tristate.of((_m.get("parent") == null ? null : FolderMini.fromJson(_m.get("parent"))))),
            (_m.get("item_status") == null ? null : FileItemStatus.fromJson(_m.get("item_status")))
        );
    }
}
