// Code generated by box-gantry 0.1.0 (spec ee7d55aedefe2fa0) for Box API 2024.0. DO NOT EDIT.
package dev.unofficialbox.model.schemas;

import module java.base;
import dev.unofficialbox.core.Tristate;

public record TrashWebLinkRestored(
    Optional<TrashWebLinkType> type,
    Optional<String> id,
    String sequenceId,
    Optional<String> etag,
    Optional<String> name,
    Optional<String> url,
    Optional<FolderMini> parent,
    Optional<String> description,
    FilePathCollection pathCollection,
    Optional<OffsetDateTime> createdAt,
    Optional<OffsetDateTime> modifiedAt,
    Tristate<String> trashedAt,
    Tristate<String> purgedAt,
    Optional<UserMini> createdBy,
    Optional<UserMini> modifiedBy,
    Optional<UserMini> ownedBy,
    Tristate<String> sharedLink,
    Optional<FileItemStatus> itemStatus) {
    public java.util.Map<String, Object> toJson() {
        java.util.Map<String, Object> _m = new java.util.LinkedHashMap<>();
        type().ifPresent(_v -> _m.put("type", (_v == null ? null : _v.toJson())));
        id().ifPresent(_v -> _m.put("id", _v));
        _m.put("sequence_id", sequenceId());
        etag().ifPresent(_v -> _m.put("etag", _v));
        name().ifPresent(_v -> _m.put("name", _v));
        url().ifPresent(_v -> _m.put("url", _v));
        parent().ifPresent(_v -> _m.put("parent", (_v == null ? null : _v.toJson())));
        description().ifPresent(_v -> _m.put("description", _v));
        _m.put("path_collection", (pathCollection() == null ? null : pathCollection().toJson()));
        createdAt().ifPresent(_v -> _m.put("created_at", (_v == null ? null : _v.toString())));
        modifiedAt().ifPresent(_v -> _m.put("modified_at", (_v == null ? null : _v.toString())));
        if (trashedAt().isPresent()) { _m.put("trashed_at", trashedAt().value()); }
        else if (trashedAt().isNull()) { _m.put("trashed_at", null); }
        if (purgedAt().isPresent()) { _m.put("purged_at", purgedAt().value()); }
        else if (purgedAt().isNull()) { _m.put("purged_at", null); }
        createdBy().ifPresent(_v -> _m.put("created_by", (_v == null ? null : _v.toJson())));
        modifiedBy().ifPresent(_v -> _m.put("modified_by", (_v == null ? null : _v.toJson())));
        ownedBy().ifPresent(_v -> _m.put("owned_by", (_v == null ? null : _v.toJson())));
        if (sharedLink().isPresent()) { _m.put("shared_link", sharedLink().value()); }
        else if (sharedLink().isNull()) { _m.put("shared_link", null); }
        itemStatus().ifPresent(_v -> _m.put("item_status", (_v == null ? null : _v.toJson())));
        return _m;
    }

    public static TrashWebLinkRestored fromJson(Object _json) {
        java.util.Map<String, Object> _m = dev.unofficialbox.core.Json.asObject(_json);
        return new TrashWebLinkRestored(
            (!_m.containsKey("type") || _m.get("type") == null) ? java.util.Optional.<TrashWebLinkType>empty() : java.util.Optional.of((_m.get("type") == null ? null : TrashWebLinkType.fromJson(_m.get("type")))),
            (!_m.containsKey("id") || _m.get("id") == null) ? java.util.Optional.<String>empty() : java.util.Optional.of(dev.unofficialbox.core.Json.asString(_m.get("id"))),
            dev.unofficialbox.core.Json.asString(_m.get("sequence_id")),
            (!_m.containsKey("etag") || _m.get("etag") == null) ? java.util.Optional.<String>empty() : java.util.Optional.of(dev.unofficialbox.core.Json.asString(_m.get("etag"))),
            (!_m.containsKey("name") || _m.get("name") == null) ? java.util.Optional.<String>empty() : java.util.Optional.of(dev.unofficialbox.core.Json.asString(_m.get("name"))),
            (!_m.containsKey("url") || _m.get("url") == null) ? java.util.Optional.<String>empty() : java.util.Optional.of(dev.unofficialbox.core.Json.asString(_m.get("url"))),
            (!_m.containsKey("parent") || _m.get("parent") == null) ? java.util.Optional.<FolderMini>empty() : java.util.Optional.of((_m.get("parent") == null ? null : FolderMini.fromJson(_m.get("parent")))),
            (!_m.containsKey("description") || _m.get("description") == null) ? java.util.Optional.<String>empty() : java.util.Optional.of(dev.unofficialbox.core.Json.asString(_m.get("description"))),
            (_m.get("path_collection") == null ? null : FilePathCollection.fromJson(_m.get("path_collection"))),
            (!_m.containsKey("created_at") || _m.get("created_at") == null) ? java.util.Optional.<OffsetDateTime>empty() : java.util.Optional.of((_m.get("created_at") == null ? null : java.time.OffsetDateTime.parse(dev.unofficialbox.core.Json.asString(_m.get("created_at"))))),
            (!_m.containsKey("modified_at") || _m.get("modified_at") == null) ? java.util.Optional.<OffsetDateTime>empty() : java.util.Optional.of((_m.get("modified_at") == null ? null : java.time.OffsetDateTime.parse(dev.unofficialbox.core.Json.asString(_m.get("modified_at"))))),
            !_m.containsKey("trashed_at") ? dev.unofficialbox.core.Tristate.<String>absent() : (_m.get("trashed_at") == null ? dev.unofficialbox.core.Tristate.<String>ofNull() : dev.unofficialbox.core.Tristate.of(dev.unofficialbox.core.Json.asString(_m.get("trashed_at")))),
            !_m.containsKey("purged_at") ? dev.unofficialbox.core.Tristate.<String>absent() : (_m.get("purged_at") == null ? dev.unofficialbox.core.Tristate.<String>ofNull() : dev.unofficialbox.core.Tristate.of(dev.unofficialbox.core.Json.asString(_m.get("purged_at")))),
            (!_m.containsKey("created_by") || _m.get("created_by") == null) ? java.util.Optional.<UserMini>empty() : java.util.Optional.of((_m.get("created_by") == null ? null : UserMini.fromJson(_m.get("created_by")))),
            (!_m.containsKey("modified_by") || _m.get("modified_by") == null) ? java.util.Optional.<UserMini>empty() : java.util.Optional.of((_m.get("modified_by") == null ? null : UserMini.fromJson(_m.get("modified_by")))),
            (!_m.containsKey("owned_by") || _m.get("owned_by") == null) ? java.util.Optional.<UserMini>empty() : java.util.Optional.of((_m.get("owned_by") == null ? null : UserMini.fromJson(_m.get("owned_by")))),
            !_m.containsKey("shared_link") ? dev.unofficialbox.core.Tristate.<String>absent() : (_m.get("shared_link") == null ? dev.unofficialbox.core.Tristate.<String>ofNull() : dev.unofficialbox.core.Tristate.of(dev.unofficialbox.core.Json.asString(_m.get("shared_link")))),
            (!_m.containsKey("item_status") || _m.get("item_status") == null) ? java.util.Optional.<FileItemStatus>empty() : java.util.Optional.of((_m.get("item_status") == null ? null : FileItemStatus.fromJson(_m.get("item_status"))))
        );
    }
}
