// Code generated by box-gantry 0.1.0 (spec ee7d55aedefe2fa0) for Box API 2024.0. DO NOT EDIT.
package dev.unofficialbox.model.schemas;

import module java.base;

public record UploadSessionSessionEndpoints(
    Optional<String> uploadPart,
    Optional<String> commit,
    Optional<String> abort,
    Optional<String> listParts,
    Optional<String> status,
    Optional<String> logEvent) {
    public java.util.Map<String, Object> toJson() {
        java.util.Map<String, Object> _m = new java.util.LinkedHashMap<>();
        uploadPart().ifPresent(_v -> _m.put("upload_part", _v));
        commit().ifPresent(_v -> _m.put("commit", _v));
        abort().ifPresent(_v -> _m.put("abort", _v));
        listParts().ifPresent(_v -> _m.put("list_parts", _v));
        status().ifPresent(_v -> _m.put("status", _v));
        logEvent().ifPresent(_v -> _m.put("log_event", _v));
        return _m;
    }

    public static UploadSessionSessionEndpoints fromJson(Object _json) {
        java.util.Map<String, Object> _m = dev.unofficialbox.core.Json.asObject(_json);
        return new UploadSessionSessionEndpoints(
            (!_m.containsKey("upload_part") || _m.get("upload_part") == null) ? java.util.Optional.<String>empty() : java.util.Optional.of(dev.unofficialbox.core.Json.asString(_m.get("upload_part"))),
            (!_m.containsKey("commit") || _m.get("commit") == null) ? java.util.Optional.<String>empty() : java.util.Optional.of(dev.unofficialbox.core.Json.asString(_m.get("commit"))),
            (!_m.containsKey("abort") || _m.get("abort") == null) ? java.util.Optional.<String>empty() : java.util.Optional.of(dev.unofficialbox.core.Json.asString(_m.get("abort"))),
            (!_m.containsKey("list_parts") || _m.get("list_parts") == null) ? java.util.Optional.<String>empty() : java.util.Optional.of(dev.unofficialbox.core.Json.asString(_m.get("list_parts"))),
            (!_m.containsKey("status") || _m.get("status") == null) ? java.util.Optional.<String>empty() : java.util.Optional.of(dev.unofficialbox.core.Json.asString(_m.get("status"))),
            (!_m.containsKey("log_event") || _m.get("log_event") == null) ? java.util.Optional.<String>empty() : java.util.Optional.of(dev.unofficialbox.core.Json.asString(_m.get("log_event")))
        );
    }

    /** A fluent builder; unset optional fields default to empty. */
    public static Builder builder() {
        return new Builder();
    }

    public static final class Builder {
        private Optional<String> uploadPart = java.util.Optional.empty();
        private Optional<String> commit = java.util.Optional.empty();
        private Optional<String> abort = java.util.Optional.empty();
        private Optional<String> listParts = java.util.Optional.empty();
        private Optional<String> status = java.util.Optional.empty();
        private Optional<String> logEvent = java.util.Optional.empty();

        public Builder uploadPart(String uploadPart) {
            this.uploadPart = java.util.Optional.ofNullable(uploadPart);
            return this;
        }
        public Builder commit(String commit) {
            this.commit = java.util.Optional.ofNullable(commit);
            return this;
        }
        public Builder abort(String abort) {
            this.abort = java.util.Optional.ofNullable(abort);
            return this;
        }
        public Builder listParts(String listParts) {
            this.listParts = java.util.Optional.ofNullable(listParts);
            return this;
        }
        public Builder status(String status) {
            this.status = java.util.Optional.ofNullable(status);
            return this;
        }
        public Builder logEvent(String logEvent) {
            this.logEvent = java.util.Optional.ofNullable(logEvent);
            return this;
        }

        public UploadSessionSessionEndpoints build() {
            return new UploadSessionSessionEndpoints(
                uploadPart,
                commit,
                abort,
                listParts,
                status,
                logEvent
            );
        }
    }
}
