// Code generated by box-gantry 0.1.0 (spec ee7d55aedefe2fa0) for Box API 2025.0. DO NOT EDIT.
package dev.unofficialbox.model.schemas;

public record UserOrGroupReferenceType(String value) {
    public static final UserOrGroupReferenceType USER = new UserOrGroupReferenceType("user");
    public static final UserOrGroupReferenceType GROUP = new UserOrGroupReferenceType("group");

    public String toJson() {
        return value;
    }

    public static UserOrGroupReferenceType fromJson(Object _json) {
        return new UserOrGroupReferenceType(dev.unofficialbox.core.Json.asString(_json));
    }
}
