// Code generated by box-gantry 0.1.0 (spec ee7d55aedefe2fa0) for Box API 2024.0. DO NOT EDIT.
package dev.unofficialbox.model.schemas;

public record UserIdCreateRequest(String email) {
    public java.util.Map<String, Object> toJson() {
        java.util.Map<String, Object> _m = new java.util.LinkedHashMap<>();
        _m.put("email", email());
        return _m;
    }

    public static UserIdCreateRequest fromJson(Object _json) {
        java.util.Map<String, Object> _m = dev.unofficialbox.core.Json.asObject(_json);
        return new UserIdCreateRequest(
            dev.unofficialbox.core.Json.asString(_m.get("email"))
        );
    }

    /** A fluent builder; unset optional fields default to empty. */
    public static Builder builder() {
        return new Builder();
    }

    public static final class Builder {
        private String email;

        public Builder email(String email) {
            this.email = email;
            return this;
        }

        public UserIdCreateRequest build() {
            return new UserIdCreateRequest(
                email
            );
        }
    }
}
