// Code generated by box-gantry 0.1.0 (spec ee7d55aedefe2fa0) for Box API 2024.0. DO NOT EDIT.
package dev.unofficialbox.model.schemas;

public record UserStatus(String value) {
    public static final UserStatus ACTIVE = new UserStatus("active");
    public static final UserStatus INACTIVE = new UserStatus("inactive");
    public static final UserStatus CANNOT_DELETE_EDIT = new UserStatus("cannot_delete_edit");
    public static final UserStatus CANNOT_DELETE_EDIT_UPLOAD = new UserStatus("cannot_delete_edit_upload");

    public String toJson() {
        return value;
    }

    public static UserStatus fromJson(Object _json) {
        return new UserStatus(dev.unofficialbox.core.Json.asString(_json));
    }
}
