// Code generated by box-gantry 0.1.0 (spec ee7d55aedefe2fa0) for Box API 2024.0. DO NOT EDIT.
package dev.unofficialbox.model.schemas;

public record VariableValueType(String value) {
    public static final VariableValueType USER = new VariableValueType("user");

    public String toJson() {
        return value;
    }

    public static VariableValueType fromJson(Object _json) {
        return new VariableValueType(dev.unofficialbox.core.Json.asString(_json));
    }
}
