// Code generated by box-gantry 0.1.0 (spec ee7d55aedefe2fa0) for Box API 2024.0. DO NOT EDIT.
package dev.unofficialbox.model.schemas;

import module java.base;

public record Webhook(
    Optional<String> id,
    Optional<WebhookType> type,
    Optional<WebhookTarget> target,
    Optional<UserMini> createdBy,
    Optional<OffsetDateTime> createdAt,
    Optional<String> address,
    Optional<List<WebhookTriggers>> triggers) {
    public java.util.Map<String, Object> toJson() {
        java.util.Map<String, Object> _m = new java.util.LinkedHashMap<>();
        id().ifPresent(_v -> _m.put("id", _v));
        type().ifPresent(_v -> _m.put("type", (_v == null ? null : _v.toJson())));
        target().ifPresent(_v -> _m.put("target", (_v == null ? null : _v.toJson())));
        createdBy().ifPresent(_v -> _m.put("created_by", (_v == null ? null : _v.toJson())));
        createdAt().ifPresent(_v -> _m.put("created_at", (_v == null ? null : _v.toString())));
        address().ifPresent(_v -> _m.put("address", _v));
        triggers().ifPresent(_v -> _m.put("triggers", dev.unofficialbox.core.Json.encodeList(_v, _x0 -> (_x0 == null ? null : _x0.toJson()))));
        return _m;
    }

    public static Webhook fromJson(Object _json) {
        java.util.Map<String, Object> _m = dev.unofficialbox.core.Json.asObject(_json);
        return new Webhook(
            (!_m.containsKey("id") || _m.get("id") == null) ? java.util.Optional.<String>empty() : java.util.Optional.of(dev.unofficialbox.core.Json.asString(_m.get("id"))),
            (!_m.containsKey("type") || _m.get("type") == null) ? java.util.Optional.<WebhookType>empty() : java.util.Optional.of((_m.get("type") == null ? null : WebhookType.fromJson(_m.get("type")))),
            (!_m.containsKey("target") || _m.get("target") == null) ? java.util.Optional.<WebhookTarget>empty() : java.util.Optional.of((_m.get("target") == null ? null : WebhookTarget.fromJson(_m.get("target")))),
            (!_m.containsKey("created_by") || _m.get("created_by") == null) ? java.util.Optional.<UserMini>empty() : java.util.Optional.of((_m.get("created_by") == null ? null : UserMini.fromJson(_m.get("created_by")))),
            (!_m.containsKey("created_at") || _m.get("created_at") == null) ? java.util.Optional.<OffsetDateTime>empty() : java.util.Optional.of((_m.get("created_at") == null ? null : java.time.OffsetDateTime.parse(dev.unofficialbox.core.Json.asString(_m.get("created_at"))))),
            (!_m.containsKey("address") || _m.get("address") == null) ? java.util.Optional.<String>empty() : java.util.Optional.of(dev.unofficialbox.core.Json.asString(_m.get("address"))),
            (!_m.containsKey("triggers") || _m.get("triggers") == null) ? java.util.Optional.<List<WebhookTriggers>>empty() : java.util.Optional.of(dev.unofficialbox.core.Json.decodeList(_m.get("triggers"), _x0 -> (_x0 == null ? null : WebhookTriggers.fromJson(_x0))))
        );
    }

    /** A fluent builder; unset optional fields default to empty. */
    public static Builder builder() {
        return new Builder();
    }

    public static final class Builder {
        private Optional<String> id = java.util.Optional.empty();
        private Optional<WebhookType> type = java.util.Optional.empty();
        private Optional<WebhookTarget> target = java.util.Optional.empty();
        private Optional<UserMini> createdBy = java.util.Optional.empty();
        private Optional<OffsetDateTime> createdAt = java.util.Optional.empty();
        private Optional<String> address = java.util.Optional.empty();
        private Optional<List<WebhookTriggers>> triggers = java.util.Optional.empty();

        public Builder id(String id) {
            this.id = java.util.Optional.ofNullable(id);
            return this;
        }
        public Builder type(WebhookType type) {
            this.type = java.util.Optional.ofNullable(type);
            return this;
        }
        public Builder target(WebhookTarget target) {
            this.target = java.util.Optional.ofNullable(target);
            return this;
        }
        public Builder createdBy(UserMini createdBy) {
            this.createdBy = java.util.Optional.ofNullable(createdBy);
            return this;
        }
        public Builder createdAt(OffsetDateTime createdAt) {
            this.createdAt = java.util.Optional.ofNullable(createdAt);
            return this;
        }
        public Builder address(String address) {
            this.address = java.util.Optional.ofNullable(address);
            return this;
        }
        public Builder triggers(List<WebhookTriggers> triggers) {
            this.triggers = java.util.Optional.ofNullable(triggers);
            return this;
        }

        public Webhook build() {
            return new Webhook(
                id,
                type,
                target,
                createdBy,
                createdAt,
                address,
                triggers
            );
        }
    }
}
