// Code generated by box-gantry 0.1.0 (spec ee7d55aedefe2fa0) for Box API 2025.0. DO NOT EDIT.
package dev.unofficialbox.model.schemas;

public record WeblinkReference(WeblinkReferenceType type, String id) implements HubItemReference {
    public java.util.Map<String, Object> toJson() {
        java.util.Map<String, Object> _m = new java.util.LinkedHashMap<>();
        _m.put("type", (type() == null ? null : type().toJson()));
        _m.put("id", id());
        return _m;
    }

    public static WeblinkReference fromJson(Object _json) {
        java.util.Map<String, Object> _m = dev.unofficialbox.core.Json.asObject(_json);
        return new WeblinkReference(
            (_m.get("type") == null ? null : WeblinkReferenceType.fromJson(_m.get("type"))),
            dev.unofficialbox.core.Json.asString(_m.get("id"))
        );
    }
}
