// Code generated by box-gantry 0.1.0 (spec ee7d55aedefe2fa0) for Box API 2024.0. DO NOT EDIT.
package dev.unofficialbox.model.schemas;

import module java.base;

public record WorkflowStartRequest(
    Optional<PostIdStartType> type,
    PostIdStartFlow flow,
    List<PutSkillInvocationIdFile> files,
    MetadataCascadePolicyParent folder,
    Optional<List<Outcome>> outcomes) {
    public java.util.Map<String, Object> toJson() {
        java.util.Map<String, Object> _m = new java.util.LinkedHashMap<>();
        type().ifPresent(_v -> _m.put("type", (_v == null ? null : _v.toJson())));
        _m.put("flow", (flow() == null ? null : flow().toJson()));
        _m.put("files", dev.unofficialbox.core.Json.encodeList(files(), _x0 -> (_x0 == null ? null : _x0.toJson())));
        _m.put("folder", (folder() == null ? null : folder().toJson()));
        outcomes().ifPresent(_v -> _m.put("outcomes", dev.unofficialbox.core.Json.encodeList(_v, _x0 -> (_x0 == null ? null : _x0.toJson()))));
        return _m;
    }

    public static WorkflowStartRequest fromJson(Object _json) {
        java.util.Map<String, Object> _m = dev.unofficialbox.core.Json.asObject(_json);
        return new WorkflowStartRequest(
            (!_m.containsKey("type") || _m.get("type") == null) ? java.util.Optional.<PostIdStartType>empty() : java.util.Optional.of((_m.get("type") == null ? null : PostIdStartType.fromJson(_m.get("type")))),
            (_m.get("flow") == null ? null : PostIdStartFlow.fromJson(_m.get("flow"))),
            dev.unofficialbox.core.Json.decodeList(_m.get("files"), _x0 -> (_x0 == null ? null : PutSkillInvocationIdFile.fromJson(_x0))),
            (_m.get("folder") == null ? null : MetadataCascadePolicyParent.fromJson(_m.get("folder"))),
            (!_m.containsKey("outcomes") || _m.get("outcomes") == null) ? java.util.Optional.<List<Outcome>>empty() : java.util.Optional.of(dev.unofficialbox.core.Json.decodeList(_m.get("outcomes"), _x0 -> (_x0 == null ? null : Outcome.fromJson(_x0))))
        );
    }

    /** A fluent builder; unset optional fields default to empty. */
    public static Builder builder() {
        return new Builder();
    }

    public static final class Builder {
        private Optional<PostIdStartType> type = java.util.Optional.empty();
        private PostIdStartFlow flow;
        private List<PutSkillInvocationIdFile> files;
        private MetadataCascadePolicyParent folder;
        private Optional<List<Outcome>> outcomes = java.util.Optional.empty();

        public Builder type(PostIdStartType type) {
            this.type = java.util.Optional.ofNullable(type);
            return this;
        }
        public Builder flow(PostIdStartFlow flow) {
            this.flow = flow;
            return this;
        }
        public Builder files(List<PutSkillInvocationIdFile> files) {
            this.files = files;
            return this;
        }
        public Builder folder(MetadataCascadePolicyParent folder) {
            this.folder = folder;
            return this;
        }
        public Builder outcomes(List<Outcome> outcomes) {
            this.outcomes = java.util.Optional.ofNullable(outcomes);
            return this;
        }

        public WorkflowStartRequest build() {
            return new WorkflowStartRequest(
                type,
                flow,
                files,
                folder,
                outcomes
            );
        }
    }
}
