// Code generated by box-gantry 0.1.0 (spec ee7d55aedefe2fa0) for Box API 2024.0. DO NOT EDIT.
package dev.unofficialbox.model.schemas;

import module java.base;

public record ZipDownload(
    Optional<String> downloadUrl,
    Optional<String> statusUrl,
    Optional<OffsetDateTime> expiresAt,
    Optional<List<List<ZipDownloadNameConflicts>>> nameConflicts) {
    public java.util.Map<String, Object> toJson() {
        java.util.Map<String, Object> _m = new java.util.LinkedHashMap<>();
        downloadUrl().ifPresent(_v -> _m.put("download_url", _v));
        statusUrl().ifPresent(_v -> _m.put("status_url", _v));
        expiresAt().ifPresent(_v -> _m.put("expires_at", (_v == null ? null : _v.toString())));
        nameConflicts().ifPresent(_v -> _m.put("name_conflicts", dev.unofficialbox.core.Json.encodeList(_v, _x0 -> dev.unofficialbox.core.Json.encodeList(_x0, _x1 -> (_x1 == null ? null : _x1.toJson())))));
        return _m;
    }

    public static ZipDownload fromJson(Object _json) {
        java.util.Map<String, Object> _m = dev.unofficialbox.core.Json.asObject(_json);
        return new ZipDownload(
            (!_m.containsKey("download_url") || _m.get("download_url") == null) ? java.util.Optional.<String>empty() : java.util.Optional.of(dev.unofficialbox.core.Json.asString(_m.get("download_url"))),
            (!_m.containsKey("status_url") || _m.get("status_url") == null) ? java.util.Optional.<String>empty() : java.util.Optional.of(dev.unofficialbox.core.Json.asString(_m.get("status_url"))),
            (!_m.containsKey("expires_at") || _m.get("expires_at") == null) ? java.util.Optional.<OffsetDateTime>empty() : java.util.Optional.of((_m.get("expires_at") == null ? null : java.time.OffsetDateTime.parse(dev.unofficialbox.core.Json.asString(_m.get("expires_at"))))),
            (!_m.containsKey("name_conflicts") || _m.get("name_conflicts") == null) ? java.util.Optional.<List<List<ZipDownloadNameConflicts>>>empty() : java.util.Optional.of(dev.unofficialbox.core.Json.decodeList(_m.get("name_conflicts"), _x0 -> dev.unofficialbox.core.Json.decodeList(_x0, _x1 -> (_x1 == null ? null : ZipDownloadNameConflicts.fromJson(_x1)))))
        );
    }
}
