// Code generated by box-gantry 0.1.0 (spec ee7d55aedefe2fa0). DO NOT EDIT.
package dev.unofficialbox.managers;

/** Operations for the aiStudio API area. */
public final class AiStudioManager {
    private final dev.unofficialbox.runtime.Runtime.Session session;

    /** Construct over a shared runtime session (used by {@link dev.unofficialbox.Client}). */
    public AiStudioManager(dev.unofficialbox.runtime.Runtime.Session session) {
        this.session = session;
    }

    /** GET /ai_agents. */
    dev.unofficialbox.model.schemas.AiMultipleAgentResponse listAiAgentsPage(ListAiAgentsOptions options) {
        StringBuilder _url = new StringBuilder(session.baseUrl("api"));
        _url.append("/ai_agents");
        dev.unofficialbox.runtime.Runtime.Request _req = session.newRequest("GET", _url.toString());
        if (options != null && options.mode != null) {
            java.util.List<String> _v = options.mode;
            _req = dev.unofficialbox.runtime.Runtime.withQuery(_req, "mode", String.join(",", _v));
        }
        if (options != null && options.fields != null) {
            java.util.List<String> _v = options.fields;
            _req = dev.unofficialbox.runtime.Runtime.withQuery(_req, "fields", String.join(",", _v));
        }
        if (options != null && options.agentState != null) {
            java.util.List<String> _v = options.agentState;
            _req = dev.unofficialbox.runtime.Runtime.withQuery(_req, "agent_state", String.join(",", _v));
        }
        if (options != null && options.includeBoxDefault != null) {
            Boolean _v = options.includeBoxDefault;
            _req = dev.unofficialbox.runtime.Runtime.withQuery(_req, "include_box_default", String.valueOf(_v));
        }
        if (options != null && options.marker != null) {
            String _v = options.marker;
            _req = dev.unofficialbox.runtime.Runtime.withQuery(_req, "marker", _v);
        }
        if (options != null && options.limit != null) {
            Long _v = options.limit;
            _req = dev.unofficialbox.runtime.Runtime.withQuery(_req, "limit", String.valueOf(_v));
        }
        Object _tree = dev.unofficialbox.core.Json.parse(new String(dev.unofficialbox.runtime.Runtime.responseBytes(session.fetch(_req)), java.nio.charset.StandardCharsets.UTF_8));
        return (_tree == null ? null : dev.unofficialbox.model.schemas.AiMultipleAgentResponse.fromJson(_tree));
    }

    /** Iterate every dev.unofficialbox.model.schemas.AiSingleAgentResponseFull across pages, threading the cursor (FR-7.3). */
    public AiStudioListAiAgentsPaginator listAiAgents(ListAiAgentsOptions options) {
        return new AiStudioListAiAgentsPaginator(session, options);
    }

    /** POST /ai_agents. */
    public dev.unofficialbox.model.schemas.AiSingleAgentResponseFull createAiAgents(dev.unofficialbox.model.schemas.CreateAiAgent body) {
        StringBuilder _url = new StringBuilder(session.baseUrl("api"));
        _url.append("/ai_agents");
        dev.unofficialbox.runtime.Runtime.Request _req = session.newRequest("POST", _url.toString());
        byte[] _payload = dev.unofficialbox.core.Json.write((body == null ? null : body.toJson())).getBytes(java.nio.charset.StandardCharsets.UTF_8);
        _req = dev.unofficialbox.runtime.Runtime.withJsonBody(_req, _payload);
        Object _tree = dev.unofficialbox.core.Json.parse(new String(dev.unofficialbox.runtime.Runtime.responseBytes(session.fetch(_req)), java.nio.charset.StandardCharsets.UTF_8));
        return (_tree == null ? null : dev.unofficialbox.model.schemas.AiSingleAgentResponseFull.fromJson(_tree));
    }

    /** GET /ai_agents/{agent_id}. */
    public dev.unofficialbox.model.schemas.AiSingleAgentResponseFull getAiAgent(String agentId, GetAiAgentOptions options) {
        StringBuilder _url = new StringBuilder(session.baseUrl("api"));
        _url.append("/ai_agents");
        _url.append("/").append(dev.unofficialbox.internal.Internal.pathEscape(agentId));
        dev.unofficialbox.runtime.Runtime.Request _req = session.newRequest("GET", _url.toString());
        if (options != null && options.fields != null) {
            java.util.List<String> _v = options.fields;
            _req = dev.unofficialbox.runtime.Runtime.withQuery(_req, "fields", String.join(",", _v));
        }
        Object _tree = dev.unofficialbox.core.Json.parse(new String(dev.unofficialbox.runtime.Runtime.responseBytes(session.fetch(_req)), java.nio.charset.StandardCharsets.UTF_8));
        return (_tree == null ? null : dev.unofficialbox.model.schemas.AiSingleAgentResponseFull.fromJson(_tree));
    }

    /** PUT /ai_agents/{agent_id}. */
    public dev.unofficialbox.model.schemas.AiSingleAgentResponseFull updateAiAgent(String agentId, dev.unofficialbox.model.schemas.CreateAiAgent body) {
        StringBuilder _url = new StringBuilder(session.baseUrl("api"));
        _url.append("/ai_agents");
        _url.append("/").append(dev.unofficialbox.internal.Internal.pathEscape(agentId));
        dev.unofficialbox.runtime.Runtime.Request _req = session.newRequest("PUT", _url.toString());
        byte[] _payload = dev.unofficialbox.core.Json.write((body == null ? null : body.toJson())).getBytes(java.nio.charset.StandardCharsets.UTF_8);
        _req = dev.unofficialbox.runtime.Runtime.withJsonBody(_req, _payload);
        Object _tree = dev.unofficialbox.core.Json.parse(new String(dev.unofficialbox.runtime.Runtime.responseBytes(session.fetch(_req)), java.nio.charset.StandardCharsets.UTF_8));
        return (_tree == null ? null : dev.unofficialbox.model.schemas.AiSingleAgentResponseFull.fromJson(_tree));
    }

    /** DELETE /ai_agents/{agent_id}. */
    public void deleteAiAgent(String agentId) {
        StringBuilder _url = new StringBuilder(session.baseUrl("api"));
        _url.append("/ai_agents");
        _url.append("/").append(dev.unofficialbox.internal.Internal.pathEscape(agentId));
        dev.unofficialbox.runtime.Runtime.Request _req = session.newRequest("DELETE", _url.toString());
        session.fetch(_req);
    }

    /** Optional parameters for listAiAgents. */
    public static final class ListAiAgentsOptions {
        /** The mode parameter. */
        public java.util.List<String> mode;
        /** The fields parameter. */
        public java.util.List<String> fields;
        /** The agent_state parameter. */
        public java.util.List<String> agentState;
        /** The include_box_default parameter. */
        public Boolean includeBoxDefault;
        /** The marker parameter. */
        public String marker;
        /** The limit parameter. */
        public Long limit;
    }

    /** Optional parameters for getAiAgent. */
    public static final class GetAiAgentOptions {
        /** The fields parameter. */
        public java.util.List<String> fields;
    }
}
