// Code generated by box-gantry 0.1.0 (spec ee7d55aedefe2fa0). DO NOT EDIT.
package dev.unofficialbox.managers;

/**
 * Paginator over {@link ChunkedUploadsManager#listFileUploadSessionPartsPage}, iterating every
 * {@code dev.unofficialbox.model.schemas.UploadPart} across pages (FR-7.3). Threads the response cursor back
 * into the request so callers can write {@code for (var item : paginator)}.
 * Re-iterable: each {@code iterator()} is an independent pass over a private
 * copy of the options, so the caller's options are never mutated.
 */
public final class ChunkedUploadsListFileUploadSessionPartsPaginator implements java.lang.Iterable<dev.unofficialbox.model.schemas.UploadPart> {
    private final dev.unofficialbox.runtime.Runtime.Session session;
    private final String uploadSessionId;
    private final ChunkedUploadsManager.ListFileUploadSessionPartsOptions options;

    ChunkedUploadsListFileUploadSessionPartsPaginator(dev.unofficialbox.runtime.Runtime.Session session, String uploadSessionId, ChunkedUploadsManager.ListFileUploadSessionPartsOptions options) {
        this.session = session;
        this.uploadSessionId = uploadSessionId;
        this.options = options;
    }

    private ChunkedUploadsManager.ListFileUploadSessionPartsOptions _freshOptions() {
        ChunkedUploadsManager.ListFileUploadSessionPartsOptions _o = new ChunkedUploadsManager.ListFileUploadSessionPartsOptions();
        if (options != null) {
            _o.offset = options.offset;
            _o.limit = options.limit;
        }
        return _o;
    }

    @Override
    public java.util.Iterator<dev.unofficialbox.model.schemas.UploadPart> iterator() {
        return new java.util.Iterator<dev.unofficialbox.model.schemas.UploadPart>() {
            private final ChunkedUploadsManager _manager = new ChunkedUploadsManager(session);
            private final ChunkedUploadsManager.ListFileUploadSessionPartsOptions _opts = _freshOptions();
            private long _cursor = _opts.offset != null ? _opts.offset : 0L;
            private java.util.Iterator<dev.unofficialbox.model.schemas.UploadPart> _buffer = java.util.Collections.emptyIterator();
            private boolean _done = false;

            private void _advance() {
                while (!_buffer.hasNext() && !_done) {
                    _opts.offset = _cursor;
                    dev.unofficialbox.model.schemas.UploadParts _page = _manager.listFileUploadSessionPartsPage(uploadSessionId, _opts);
                    java.util.List<dev.unofficialbox.model.schemas.UploadPart> _items = _page.entries().orElse(java.util.List.of());
                    _buffer = _items.iterator();
                    if (_items.isEmpty()) {
                        _done = true;
                    } else {
                        _cursor += _items.size();
                    }
                }
            }

            @Override
            public boolean hasNext() {
                _advance();
                return _buffer.hasNext();
            }

            @Override
            public dev.unofficialbox.model.schemas.UploadPart next() {
                _advance();
                if (!_buffer.hasNext()) {
                    throw new java.util.NoSuchElementException();
                }
                return _buffer.next();
            }
        };
    }
}
