// Code generated by box-gantry 0.1.0 (spec ee7d55aedefe2fa0). DO NOT EDIT.
package dev.unofficialbox.managers;

/**
 * Paginator over {@link CollectionsManager#listPage}, iterating every
 * {@code dev.unofficialbox.model.schemas.Collection} across pages (FR-7.3). Threads the response cursor back
 * into the request so callers can write {@code for (var item : paginator)}.
 * Re-iterable: each {@code iterator()} is an independent pass over a private
 * copy of the options, so the caller's options are never mutated.
 */
public final class CollectionsListPaginator implements java.lang.Iterable<dev.unofficialbox.model.schemas.Collection> {
    private final dev.unofficialbox.runtime.Runtime.Session session;
    private final CollectionsManager.ListOptions options;

    CollectionsListPaginator(dev.unofficialbox.runtime.Runtime.Session session, CollectionsManager.ListOptions options) {
        this.session = session;
        this.options = options;
    }

    private CollectionsManager.ListOptions _freshOptions() {
        CollectionsManager.ListOptions _o = new CollectionsManager.ListOptions();
        if (options != null) {
            _o.fields = options.fields;
            _o.offset = options.offset;
            _o.limit = options.limit;
        }
        return _o;
    }

    @Override
    public java.util.Iterator<dev.unofficialbox.model.schemas.Collection> iterator() {
        return new java.util.Iterator<dev.unofficialbox.model.schemas.Collection>() {
            private final CollectionsManager _manager = new CollectionsManager(session);
            private final CollectionsManager.ListOptions _opts = _freshOptions();
            private long _cursor = _opts.offset != null ? _opts.offset : 0L;
            private java.util.Iterator<dev.unofficialbox.model.schemas.Collection> _buffer = java.util.Collections.emptyIterator();
            private boolean _done = false;

            private void _advance() {
                while (!_buffer.hasNext() && !_done) {
                    _opts.offset = _cursor;
                    dev.unofficialbox.model.schemas.Collections _page = _manager.listPage(_opts);
                    java.util.List<dev.unofficialbox.model.schemas.Collection> _items = _page.entries().orElse(java.util.List.of());
                    _buffer = _items.iterator();
                    if (_items.isEmpty()) {
                        _done = true;
                    } else {
                        _cursor += _items.size();
                    }
                }
            }

            @Override
            public boolean hasNext() {
                _advance();
                return _buffer.hasNext();
            }

            @Override
            public dev.unofficialbox.model.schemas.Collection next() {
                _advance();
                if (!_buffer.hasNext()) {
                    throw new java.util.NoSuchElementException();
                }
                return _buffer.next();
            }
        };
    }
}
