// Code generated by box-gantry 0.1.0 (spec ee7d55aedefe2fa0). DO NOT EDIT.
package dev.unofficialbox.managers;

/** Operations for the docgen API area. */
public final class DocgenManager {
    private final dev.unofficialbox.runtime.Runtime.Session session;

    /** Construct over a shared runtime session (used by {@link dev.unofficialbox.Client}). */
    public DocgenManager(dev.unofficialbox.runtime.Runtime.Session session) {
        this.session = session;
    }

    /** GET /docgen_jobs/{job_id}. */
    public dev.unofficialbox.model.schemas.DocGenJob getJob(String jobId) {
        StringBuilder _url = new StringBuilder(session.baseUrl("api"));
        _url.append("/docgen_jobs");
        _url.append("/").append(dev.unofficialbox.internal.Internal.pathEscape(jobId));
        dev.unofficialbox.runtime.Runtime.Request _req = session.newRequest("GET", _url.toString());
        _req = dev.unofficialbox.runtime.Runtime.withHeader(_req, "box-version", "2025.0");
        Object _tree = dev.unofficialbox.core.Json.parse(new String(dev.unofficialbox.runtime.Runtime.responseBytes(session.fetch(_req)), java.nio.charset.StandardCharsets.UTF_8));
        return (_tree == null ? null : dev.unofficialbox.model.schemas.DocGenJob.fromJson(_tree));
    }

    /** GET /docgen_jobs. */
    dev.unofficialbox.model.schemas.DocGenJobsFull listJobsPage(ListJobsOptions options) {
        StringBuilder _url = new StringBuilder(session.baseUrl("api"));
        _url.append("/docgen_jobs");
        dev.unofficialbox.runtime.Runtime.Request _req = session.newRequest("GET", _url.toString());
        if (options != null && options.marker != null) {
            String _v = options.marker;
            _req = dev.unofficialbox.runtime.Runtime.withQuery(_req, "marker", _v);
        }
        if (options != null && options.limit != null) {
            Long _v = options.limit;
            _req = dev.unofficialbox.runtime.Runtime.withQuery(_req, "limit", String.valueOf(_v));
        }
        _req = dev.unofficialbox.runtime.Runtime.withHeader(_req, "box-version", "2025.0");
        Object _tree = dev.unofficialbox.core.Json.parse(new String(dev.unofficialbox.runtime.Runtime.responseBytes(session.fetch(_req)), java.nio.charset.StandardCharsets.UTF_8));
        return (_tree == null ? null : dev.unofficialbox.model.schemas.DocGenJobsFull.fromJson(_tree));
    }

    /** Iterate every dev.unofficialbox.model.schemas.DocGenJobFull across pages, threading the cursor (FR-7.3). */
    public DocgenListJobsPaginator listJobs(ListJobsOptions options) {
        return new DocgenListJobsPaginator(session, options);
    }

    /** GET /docgen_batch_jobs/{batch_id}. */
    dev.unofficialbox.model.schemas.DocGenJobs listBatchJobPage(String batchId, ListBatchJobOptions options) {
        StringBuilder _url = new StringBuilder(session.baseUrl("api"));
        _url.append("/docgen_batch_jobs");
        _url.append("/").append(dev.unofficialbox.internal.Internal.pathEscape(batchId));
        dev.unofficialbox.runtime.Runtime.Request _req = session.newRequest("GET", _url.toString());
        if (options != null && options.marker != null) {
            String _v = options.marker;
            _req = dev.unofficialbox.runtime.Runtime.withQuery(_req, "marker", _v);
        }
        if (options != null && options.limit != null) {
            Long _v = options.limit;
            _req = dev.unofficialbox.runtime.Runtime.withQuery(_req, "limit", String.valueOf(_v));
        }
        _req = dev.unofficialbox.runtime.Runtime.withHeader(_req, "box-version", "2025.0");
        Object _tree = dev.unofficialbox.core.Json.parse(new String(dev.unofficialbox.runtime.Runtime.responseBytes(session.fetch(_req)), java.nio.charset.StandardCharsets.UTF_8));
        return (_tree == null ? null : dev.unofficialbox.model.schemas.DocGenJobs.fromJson(_tree));
    }

    /** Iterate every dev.unofficialbox.model.schemas.DocGenJob across pages, threading the cursor (FR-7.3). */
    public DocgenListBatchJobPaginator listBatchJob(String batchId, ListBatchJobOptions options) {
        return new DocgenListBatchJobPaginator(session, batchId, options);
    }

    /** POST /docgen_batches. */
    public dev.unofficialbox.model.schemas.DocGenBatchBase createBatches(dev.unofficialbox.model.schemas.DocGenBatchCreateRequest body) {
        StringBuilder _url = new StringBuilder(session.baseUrl("api"));
        _url.append("/docgen_batches");
        dev.unofficialbox.runtime.Runtime.Request _req = session.newRequest("POST", _url.toString());
        _req = dev.unofficialbox.runtime.Runtime.withHeader(_req, "box-version", "2025.0");
        byte[] _payload = dev.unofficialbox.core.Json.write((body == null ? null : body.toJson())).getBytes(java.nio.charset.StandardCharsets.UTF_8);
        _req = dev.unofficialbox.runtime.Runtime.withJsonBody(_req, _payload);
        Object _tree = dev.unofficialbox.core.Json.parse(new String(dev.unofficialbox.runtime.Runtime.responseBytes(session.fetch(_req)), java.nio.charset.StandardCharsets.UTF_8));
        return (_tree == null ? null : dev.unofficialbox.model.schemas.DocGenBatchBase.fromJson(_tree));
    }

    /** Optional parameters for listJobs. */
    public static final class ListJobsOptions {
        /** The marker parameter. */
        public String marker;
        /** The limit parameter. */
        public Long limit;
    }

    /** Optional parameters for listBatchJob. */
    public static final class ListBatchJobOptions {
        /** The marker parameter. */
        public String marker;
        /** The limit parameter. */
        public Long limit;
    }
}
