// Code generated by box-gantry 0.1.0 (spec ee7d55aedefe2fa0). DO NOT EDIT.
package dev.unofficialbox.managers;

/**
 * Paginator over {@link FileVersionsManager#listFileVersionsPage}, iterating every
 * {@code dev.unofficialbox.model.schemas.FileVersionFull} across pages (FR-7.3). Threads the response cursor back
 * into the request so callers can write {@code for (var item : paginator)}.
 * Re-iterable: each {@code iterator()} is an independent pass over a private
 * copy of the options, so the caller's options are never mutated.
 */
public final class FileVersionsListFileVersionsPaginator implements java.lang.Iterable<dev.unofficialbox.model.schemas.FileVersionFull> {
    private final dev.unofficialbox.runtime.Runtime.Session session;
    private final String fileId;
    private final FileVersionsManager.ListFileVersionsOptions options;

    FileVersionsListFileVersionsPaginator(dev.unofficialbox.runtime.Runtime.Session session, String fileId, FileVersionsManager.ListFileVersionsOptions options) {
        this.session = session;
        this.fileId = fileId;
        this.options = options;
    }

    private FileVersionsManager.ListFileVersionsOptions _freshOptions() {
        FileVersionsManager.ListFileVersionsOptions _o = new FileVersionsManager.ListFileVersionsOptions();
        if (options != null) {
            _o.fields = options.fields;
            _o.limit = options.limit;
            _o.offset = options.offset;
        }
        return _o;
    }

    @Override
    public java.util.Iterator<dev.unofficialbox.model.schemas.FileVersionFull> iterator() {
        return new java.util.Iterator<dev.unofficialbox.model.schemas.FileVersionFull>() {
            private final FileVersionsManager _manager = new FileVersionsManager(session);
            private final FileVersionsManager.ListFileVersionsOptions _opts = _freshOptions();
            private long _cursor = _opts.offset != null ? _opts.offset : 0L;
            private java.util.Iterator<dev.unofficialbox.model.schemas.FileVersionFull> _buffer = java.util.Collections.emptyIterator();
            private boolean _done = false;

            private void _advance() {
                while (!_buffer.hasNext() && !_done) {
                    _opts.offset = _cursor;
                    dev.unofficialbox.model.schemas.FileVersions _page = _manager.listFileVersionsPage(fileId, _opts);
                    java.util.List<dev.unofficialbox.model.schemas.FileVersionFull> _items = _page.entries().orElse(java.util.List.of());
                    _buffer = _items.iterator();
                    if (_items.isEmpty()) {
                        _done = true;
                    } else {
                        _cursor += _items.size();
                    }
                }
            }

            @Override
            public boolean hasNext() {
                _advance();
                return _buffer.hasNext();
            }

            @Override
            public dev.unofficialbox.model.schemas.FileVersionFull next() {
                _advance();
                if (!_buffer.hasNext()) {
                    throw new java.util.NoSuchElementException();
                }
                return _buffer.next();
            }
        };
    }
}
