// Code generated by box-gantry 0.1.0 (spec ee7d55aedefe2fa0). DO NOT EDIT.
package dev.unofficialbox.managers;

/** Operations for the folderWatermarks API area. */
public final class FolderWatermarksManager {
    private final dev.unofficialbox.runtime.Runtime.Session session;

    /** Construct over a shared runtime session (used by {@link dev.unofficialbox.Client}). */
    public FolderWatermarksManager(dev.unofficialbox.runtime.Runtime.Session session) {
        this.session = session;
    }

    /** GET /folders/{folder_id}/watermark. */
    public dev.unofficialbox.model.schemas.Watermark getFolderWatermark(String folderId) {
        StringBuilder _url = new StringBuilder(session.baseUrl("api"));
        _url.append("/folders");
        _url.append("/").append(dev.unofficialbox.internal.Internal.pathEscape(folderId));
        _url.append("/watermark");
        dev.unofficialbox.runtime.Runtime.Request _req = session.newRequest("GET", _url.toString());
        Object _tree = dev.unofficialbox.core.Json.parse(new String(dev.unofficialbox.runtime.Runtime.responseBytes(session.fetch(_req)), java.nio.charset.StandardCharsets.UTF_8));
        return (_tree == null ? null : dev.unofficialbox.model.schemas.Watermark.fromJson(_tree));
    }

    /** PUT /folders/{folder_id}/watermark. */
    public dev.unofficialbox.model.schemas.Watermark updateFolderWatermark(String folderId, dev.unofficialbox.model.schemas.FileWatermarkUpdateRequest body) {
        StringBuilder _url = new StringBuilder(session.baseUrl("api"));
        _url.append("/folders");
        _url.append("/").append(dev.unofficialbox.internal.Internal.pathEscape(folderId));
        _url.append("/watermark");
        dev.unofficialbox.runtime.Runtime.Request _req = session.newRequest("PUT", _url.toString());
        byte[] _payload = dev.unofficialbox.core.Json.write((body == null ? null : body.toJson())).getBytes(java.nio.charset.StandardCharsets.UTF_8);
        _req = dev.unofficialbox.runtime.Runtime.withJsonBody(_req, _payload);
        Object _tree = dev.unofficialbox.core.Json.parse(new String(dev.unofficialbox.runtime.Runtime.responseBytes(session.fetch(_req)), java.nio.charset.StandardCharsets.UTF_8));
        return (_tree == null ? null : dev.unofficialbox.model.schemas.Watermark.fromJson(_tree));
    }

    /** DELETE /folders/{folder_id}/watermark. */
    public void deleteFolderWatermark(String folderId) {
        StringBuilder _url = new StringBuilder(session.baseUrl("api"));
        _url.append("/folders");
        _url.append("/").append(dev.unofficialbox.internal.Internal.pathEscape(folderId));
        _url.append("/watermark");
        dev.unofficialbox.runtime.Runtime.Request _req = session.newRequest("DELETE", _url.toString());
        session.fetch(_req);
    }
}
