// Code generated by box-gantry 0.1.0 (spec ee7d55aedefe2fa0). DO NOT EDIT.
package dev.unofficialbox.managers;

/**
 * Paginator over {@link HubDocumentManager#listPagesPage}, iterating every
 * {@code dev.unofficialbox.model.schemas.HubDocumentPage} across pages (FR-7.3). Threads the response cursor back
 * into the request so callers can write {@code for (var item : paginator)}.
 * Re-iterable: each {@code iterator()} is an independent pass over a private
 * copy of the options, so the caller's options are never mutated.
 */
public final class HubDocumentListPagesPaginator implements java.lang.Iterable<dev.unofficialbox.model.schemas.HubDocumentPage> {
    private final dev.unofficialbox.runtime.Runtime.Session session;
    private final String hubId;
    private final HubDocumentManager.ListPagesOptions options;

    HubDocumentListPagesPaginator(dev.unofficialbox.runtime.Runtime.Session session, String hubId, HubDocumentManager.ListPagesOptions options) {
        this.session = session;
        this.hubId = hubId;
        this.options = options;
    }

    private HubDocumentManager.ListPagesOptions _freshOptions() {
        HubDocumentManager.ListPagesOptions _o = new HubDocumentManager.ListPagesOptions();
        if (options != null) {
            _o.marker = options.marker;
            _o.limit = options.limit;
        }
        return _o;
    }

    @Override
    public java.util.Iterator<dev.unofficialbox.model.schemas.HubDocumentPage> iterator() {
        return new java.util.Iterator<dev.unofficialbox.model.schemas.HubDocumentPage>() {
            private final HubDocumentManager _manager = new HubDocumentManager(session);
            private final HubDocumentManager.ListPagesOptions _opts = _freshOptions();
            private String _cursor = _opts.marker;
            private java.util.Iterator<dev.unofficialbox.model.schemas.HubDocumentPage> _buffer = java.util.Collections.emptyIterator();
            private boolean _done = false;

            private void _advance() {
                while (!_buffer.hasNext() && !_done) {
                    _opts.marker = _cursor;
                    dev.unofficialbox.model.schemas.HubDocumentPages _page = _manager.listPagesPage(hubId, _opts);
                    java.util.List<dev.unofficialbox.model.schemas.HubDocumentPage> _items = _page.entries();
                    _buffer = _items.iterator();
                    String _next = _page.nextMarker().isPresent() ? _page.nextMarker().value() : null;
                    if (_next != null && !_next.isEmpty()) {
                        _cursor = _next;
                    } else {
                        _done = true;
                    }
                }
            }

            @Override
            public boolean hasNext() {
                _advance();
                return _buffer.hasNext();
            }

            @Override
            public dev.unofficialbox.model.schemas.HubDocumentPage next() {
                _advance();
                if (!_buffer.hasNext()) {
                    throw new java.util.NoSuchElementException();
                }
                return _buffer.next();
            }
        };
    }
}
