// Code generated by box-gantry 0.1.0 (spec ee7d55aedefe2fa0). DO NOT EDIT.
package dev.unofficialbox.managers;

/** Operations for the hubs API area. */
public final class HubsManager {
    private final dev.unofficialbox.runtime.Runtime.Session session;

    /** Construct over a shared runtime session (used by {@link dev.unofficialbox.Client}). */
    public HubsManager(dev.unofficialbox.runtime.Runtime.Session session) {
        this.session = session;
    }

    /** GET /hubs. */
    dev.unofficialbox.model.schemas.Hubs listPage(ListOptions options) {
        StringBuilder _url = new StringBuilder(session.baseUrl("api"));
        _url.append("/hubs");
        dev.unofficialbox.runtime.Runtime.Request _req = session.newRequest("GET", _url.toString());
        if (options != null && options.query != null) {
            String _v = options.query;
            _req = dev.unofficialbox.runtime.Runtime.withQuery(_req, "query", _v);
        }
        if (options != null && options.scope != null) {
            String _v = options.scope;
            _req = dev.unofficialbox.runtime.Runtime.withQuery(_req, "scope", _v);
        }
        if (options != null && options.sort != null) {
            String _v = options.sort;
            _req = dev.unofficialbox.runtime.Runtime.withQuery(_req, "sort", _v);
        }
        if (options != null && options.direction != null) {
            dev.unofficialbox.model.schemas.GetDirection _v = options.direction;
            _req = dev.unofficialbox.runtime.Runtime.withQuery(_req, "direction", _v.value());
        }
        if (options != null && options.marker != null) {
            String _v = options.marker;
            _req = dev.unofficialbox.runtime.Runtime.withQuery(_req, "marker", _v);
        }
        if (options != null && options.limit != null) {
            Long _v = options.limit;
            _req = dev.unofficialbox.runtime.Runtime.withQuery(_req, "limit", String.valueOf(_v));
        }
        _req = dev.unofficialbox.runtime.Runtime.withHeader(_req, "box-version", "2025.0");
        Object _tree = dev.unofficialbox.core.Json.parse(new String(dev.unofficialbox.runtime.Runtime.responseBytes(session.fetch(_req)), java.nio.charset.StandardCharsets.UTF_8));
        return (_tree == null ? null : dev.unofficialbox.model.schemas.Hubs.fromJson(_tree));
    }

    /** Iterate every dev.unofficialbox.model.schemas.Hub across pages, threading the cursor (FR-7.3). */
    public HubsListPaginator list(ListOptions options) {
        return new HubsListPaginator(session, options);
    }

    /** POST /hubs. */
    public dev.unofficialbox.model.schemas.Hub create(dev.unofficialbox.model.schemas.HubCreateRequest body) {
        StringBuilder _url = new StringBuilder(session.baseUrl("api"));
        _url.append("/hubs");
        dev.unofficialbox.runtime.Runtime.Request _req = session.newRequest("POST", _url.toString());
        _req = dev.unofficialbox.runtime.Runtime.withHeader(_req, "box-version", "2025.0");
        byte[] _payload = dev.unofficialbox.core.Json.write((body == null ? null : body.toJson())).getBytes(java.nio.charset.StandardCharsets.UTF_8);
        _req = dev.unofficialbox.runtime.Runtime.withJsonBody(_req, _payload);
        Object _tree = dev.unofficialbox.core.Json.parse(new String(dev.unofficialbox.runtime.Runtime.responseBytes(session.fetch(_req)), java.nio.charset.StandardCharsets.UTF_8));
        return (_tree == null ? null : dev.unofficialbox.model.schemas.Hub.fromJson(_tree));
    }

    /** GET /enterprise_hubs. */
    dev.unofficialbox.model.schemas.Hubs listEnterprisePage(ListEnterpriseOptions options) {
        StringBuilder _url = new StringBuilder(session.baseUrl("api"));
        _url.append("/enterprise_hubs");
        dev.unofficialbox.runtime.Runtime.Request _req = session.newRequest("GET", _url.toString());
        if (options != null && options.query != null) {
            String _v = options.query;
            _req = dev.unofficialbox.runtime.Runtime.withQuery(_req, "query", _v);
        }
        if (options != null && options.sort != null) {
            String _v = options.sort;
            _req = dev.unofficialbox.runtime.Runtime.withQuery(_req, "sort", _v);
        }
        if (options != null && options.direction != null) {
            dev.unofficialbox.model.schemas.GetDirection _v = options.direction;
            _req = dev.unofficialbox.runtime.Runtime.withQuery(_req, "direction", _v.value());
        }
        if (options != null && options.marker != null) {
            String _v = options.marker;
            _req = dev.unofficialbox.runtime.Runtime.withQuery(_req, "marker", _v);
        }
        if (options != null && options.limit != null) {
            Long _v = options.limit;
            _req = dev.unofficialbox.runtime.Runtime.withQuery(_req, "limit", String.valueOf(_v));
        }
        _req = dev.unofficialbox.runtime.Runtime.withHeader(_req, "box-version", "2025.0");
        Object _tree = dev.unofficialbox.core.Json.parse(new String(dev.unofficialbox.runtime.Runtime.responseBytes(session.fetch(_req)), java.nio.charset.StandardCharsets.UTF_8));
        return (_tree == null ? null : dev.unofficialbox.model.schemas.Hubs.fromJson(_tree));
    }

    /** Iterate every dev.unofficialbox.model.schemas.Hub across pages, threading the cursor (FR-7.3). */
    public HubsListEnterprisePaginator listEnterprise(ListEnterpriseOptions options) {
        return new HubsListEnterprisePaginator(session, options);
    }

    /** GET /hubs/{hub_id}. */
    public dev.unofficialbox.model.schemas.Hub get(String hubId) {
        StringBuilder _url = new StringBuilder(session.baseUrl("api"));
        _url.append("/hubs");
        _url.append("/").append(dev.unofficialbox.internal.Internal.pathEscape(hubId));
        dev.unofficialbox.runtime.Runtime.Request _req = session.newRequest("GET", _url.toString());
        _req = dev.unofficialbox.runtime.Runtime.withHeader(_req, "box-version", "2025.0");
        Object _tree = dev.unofficialbox.core.Json.parse(new String(dev.unofficialbox.runtime.Runtime.responseBytes(session.fetch(_req)), java.nio.charset.StandardCharsets.UTF_8));
        return (_tree == null ? null : dev.unofficialbox.model.schemas.Hub.fromJson(_tree));
    }

    /** PUT /hubs/{hub_id}. */
    public dev.unofficialbox.model.schemas.Hub update(String hubId, dev.unofficialbox.model.schemas.HubUpdateRequest body) {
        StringBuilder _url = new StringBuilder(session.baseUrl("api"));
        _url.append("/hubs");
        _url.append("/").append(dev.unofficialbox.internal.Internal.pathEscape(hubId));
        dev.unofficialbox.runtime.Runtime.Request _req = session.newRequest("PUT", _url.toString());
        _req = dev.unofficialbox.runtime.Runtime.withHeader(_req, "box-version", "2025.0");
        byte[] _payload = dev.unofficialbox.core.Json.write((body == null ? null : body.toJson())).getBytes(java.nio.charset.StandardCharsets.UTF_8);
        _req = dev.unofficialbox.runtime.Runtime.withJsonBody(_req, _payload);
        Object _tree = dev.unofficialbox.core.Json.parse(new String(dev.unofficialbox.runtime.Runtime.responseBytes(session.fetch(_req)), java.nio.charset.StandardCharsets.UTF_8));
        return (_tree == null ? null : dev.unofficialbox.model.schemas.Hub.fromJson(_tree));
    }

    /** DELETE /hubs/{hub_id}. */
    public void delete(String hubId) {
        StringBuilder _url = new StringBuilder(session.baseUrl("api"));
        _url.append("/hubs");
        _url.append("/").append(dev.unofficialbox.internal.Internal.pathEscape(hubId));
        dev.unofficialbox.runtime.Runtime.Request _req = session.newRequest("DELETE", _url.toString());
        _req = dev.unofficialbox.runtime.Runtime.withHeader(_req, "box-version", "2025.0");
        session.fetch(_req);
    }

    /** POST /hubs/{hub_id}/copy. */
    public dev.unofficialbox.model.schemas.Hub copy(String hubId, dev.unofficialbox.model.schemas.HubCopyRequest body) {
        StringBuilder _url = new StringBuilder(session.baseUrl("api"));
        _url.append("/hubs");
        _url.append("/").append(dev.unofficialbox.internal.Internal.pathEscape(hubId));
        _url.append("/copy");
        dev.unofficialbox.runtime.Runtime.Request _req = session.newRequest("POST", _url.toString());
        _req = dev.unofficialbox.runtime.Runtime.withHeader(_req, "box-version", "2025.0");
        byte[] _payload = dev.unofficialbox.core.Json.write((body == null ? null : body.toJson())).getBytes(java.nio.charset.StandardCharsets.UTF_8);
        _req = dev.unofficialbox.runtime.Runtime.withJsonBody(_req, _payload);
        Object _tree = dev.unofficialbox.core.Json.parse(new String(dev.unofficialbox.runtime.Runtime.responseBytes(session.fetch(_req)), java.nio.charset.StandardCharsets.UTF_8));
        return (_tree == null ? null : dev.unofficialbox.model.schemas.Hub.fromJson(_tree));
    }

    /** Optional parameters for list. */
    public static final class ListOptions {
        /** The query parameter. */
        public String query;
        /** The scope parameter. */
        public String scope;
        /** The sort parameter. */
        public String sort;
        /** The direction parameter. */
        public dev.unofficialbox.model.schemas.GetDirection direction;
        /** The marker parameter. */
        public String marker;
        /** The limit parameter. */
        public Long limit;
    }

    /** Optional parameters for listEnterprise. */
    public static final class ListEnterpriseOptions {
        /** The query parameter. */
        public String query;
        /** The sort parameter. */
        public String sort;
        /** The direction parameter. */
        public dev.unofficialbox.model.schemas.GetDirection direction;
        /** The marker parameter. */
        public String marker;
        /** The limit parameter. */
        public Long limit;
    }
}
