// Code generated by box-gantry 0.1.0 (spec ee7d55aedefe2fa0). DO NOT EDIT.
package dev.unofficialbox.managers;

/** Operations for the invites API area. */
public final class InvitesManager {
    private final dev.unofficialbox.runtime.Runtime.Session session;

    /** Construct over a shared runtime session (used by {@link dev.unofficialbox.Client}). */
    public InvitesManager(dev.unofficialbox.runtime.Runtime.Session session) {
        this.session = session;
    }

    /** POST /invites. */
    public dev.unofficialbox.model.schemas.Invite create(dev.unofficialbox.model.schemas.InviteCreateRequest body, CreateOptions options) {
        StringBuilder _url = new StringBuilder(session.baseUrl("api"));
        _url.append("/invites");
        dev.unofficialbox.runtime.Runtime.Request _req = session.newRequest("POST", _url.toString());
        if (options != null && options.fields != null) {
            java.util.List<String> _v = options.fields;
            _req = dev.unofficialbox.runtime.Runtime.withQuery(_req, "fields", String.join(",", _v));
        }
        byte[] _payload = dev.unofficialbox.core.Json.write((body == null ? null : body.toJson())).getBytes(java.nio.charset.StandardCharsets.UTF_8);
        _req = dev.unofficialbox.runtime.Runtime.withJsonBody(_req, _payload);
        Object _tree = dev.unofficialbox.core.Json.parse(new String(dev.unofficialbox.runtime.Runtime.responseBytes(session.fetch(_req)), java.nio.charset.StandardCharsets.UTF_8));
        return (_tree == null ? null : dev.unofficialbox.model.schemas.Invite.fromJson(_tree));
    }

    /** GET /invites/{invite_id}. */
    public dev.unofficialbox.model.schemas.Invite get(String inviteId, GetOptions options) {
        StringBuilder _url = new StringBuilder(session.baseUrl("api"));
        _url.append("/invites");
        _url.append("/").append(dev.unofficialbox.internal.Internal.pathEscape(inviteId));
        dev.unofficialbox.runtime.Runtime.Request _req = session.newRequest("GET", _url.toString());
        if (options != null && options.fields != null) {
            java.util.List<String> _v = options.fields;
            _req = dev.unofficialbox.runtime.Runtime.withQuery(_req, "fields", String.join(",", _v));
        }
        Object _tree = dev.unofficialbox.core.Json.parse(new String(dev.unofficialbox.runtime.Runtime.responseBytes(session.fetch(_req)), java.nio.charset.StandardCharsets.UTF_8));
        return (_tree == null ? null : dev.unofficialbox.model.schemas.Invite.fromJson(_tree));
    }

    /** Optional parameters for create. */
    public static final class CreateOptions {
        /** The fields parameter. */
        public java.util.List<String> fields;
    }

    /** Optional parameters for get. */
    public static final class GetOptions {
        /** The fields parameter. */
        public java.util.List<String> fields;
    }
}
