// Code generated by box-gantry 0.1.0 (spec ee7d55aedefe2fa0). DO NOT EDIT.
package dev.unofficialbox.managers;

/** Operations for the listCollaborations API area. */
public final class ListCollaborationsManager {
    private final dev.unofficialbox.runtime.Runtime.Session session;

    /** Construct over a shared runtime session (used by {@link dev.unofficialbox.Client}). */
    public ListCollaborationsManager(dev.unofficialbox.runtime.Runtime.Session session) {
        this.session = session;
    }

    /** GET /files/{file_id}/collaborations. */
    dev.unofficialbox.model.schemas.Collaborations listFileCollaborationsPage(String fileId, ListFileCollaborationsOptions options) {
        StringBuilder _url = new StringBuilder(session.baseUrl("api"));
        _url.append("/files");
        _url.append("/").append(dev.unofficialbox.internal.Internal.pathEscape(fileId));
        _url.append("/collaborations");
        dev.unofficialbox.runtime.Runtime.Request _req = session.newRequest("GET", _url.toString());
        if (options != null && options.fields != null) {
            java.util.List<String> _v = options.fields;
            _req = dev.unofficialbox.runtime.Runtime.withQuery(_req, "fields", String.join(",", _v));
        }
        if (options != null && options.limit != null) {
            Long _v = options.limit;
            _req = dev.unofficialbox.runtime.Runtime.withQuery(_req, "limit", String.valueOf(_v));
        }
        if (options != null && options.marker != null) {
            String _v = options.marker;
            _req = dev.unofficialbox.runtime.Runtime.withQuery(_req, "marker", _v);
        }
        Object _tree = dev.unofficialbox.core.Json.parse(new String(dev.unofficialbox.runtime.Runtime.responseBytes(session.fetch(_req)), java.nio.charset.StandardCharsets.UTF_8));
        return (_tree == null ? null : dev.unofficialbox.model.schemas.Collaborations.fromJson(_tree));
    }

    /** Iterate every dev.unofficialbox.model.schemas.Collaboration across pages, threading the cursor (FR-7.3). */
    public ListCollaborationsListFileCollaborationsPaginator listFileCollaborations(String fileId, ListFileCollaborationsOptions options) {
        return new ListCollaborationsListFileCollaborationsPaginator(session, fileId, options);
    }

    /** GET /folders/{folder_id}/collaborations. */
    dev.unofficialbox.model.schemas.Collaborations listFolderCollaborationsPage(String folderId, ListFolderCollaborationsOptions options) {
        StringBuilder _url = new StringBuilder(session.baseUrl("api"));
        _url.append("/folders");
        _url.append("/").append(dev.unofficialbox.internal.Internal.pathEscape(folderId));
        _url.append("/collaborations");
        dev.unofficialbox.runtime.Runtime.Request _req = session.newRequest("GET", _url.toString());
        if (options != null && options.fields != null) {
            java.util.List<String> _v = options.fields;
            _req = dev.unofficialbox.runtime.Runtime.withQuery(_req, "fields", String.join(",", _v));
        }
        if (options != null && options.limit != null) {
            Long _v = options.limit;
            _req = dev.unofficialbox.runtime.Runtime.withQuery(_req, "limit", String.valueOf(_v));
        }
        if (options != null && options.marker != null) {
            String _v = options.marker;
            _req = dev.unofficialbox.runtime.Runtime.withQuery(_req, "marker", _v);
        }
        Object _tree = dev.unofficialbox.core.Json.parse(new String(dev.unofficialbox.runtime.Runtime.responseBytes(session.fetch(_req)), java.nio.charset.StandardCharsets.UTF_8));
        return (_tree == null ? null : dev.unofficialbox.model.schemas.Collaborations.fromJson(_tree));
    }

    /** Iterate every dev.unofficialbox.model.schemas.Collaboration across pages, threading the cursor (FR-7.3). */
    public ListCollaborationsListFolderCollaborationsPaginator listFolderCollaborations(String folderId, ListFolderCollaborationsOptions options) {
        return new ListCollaborationsListFolderCollaborationsPaginator(session, folderId, options);
    }

    /** GET /collaborations. */
    dev.unofficialbox.model.schemas.CollaborationsOffsetPaginated listCollaborationsPage(dev.unofficialbox.model.schemas.GetCollaborationsStatus status, ListCollaborationsOptions options) {
        StringBuilder _url = new StringBuilder(session.baseUrl("api"));
        _url.append("/collaborations");
        dev.unofficialbox.runtime.Runtime.Request _req = session.newRequest("GET", _url.toString());
        _req = dev.unofficialbox.runtime.Runtime.withQuery(_req, "status", status.value());
        if (options != null && options.fields != null) {
            java.util.List<String> _v = options.fields;
            _req = dev.unofficialbox.runtime.Runtime.withQuery(_req, "fields", String.join(",", _v));
        }
        if (options != null && options.offset != null) {
            Long _v = options.offset;
            _req = dev.unofficialbox.runtime.Runtime.withQuery(_req, "offset", String.valueOf(_v));
        }
        if (options != null && options.limit != null) {
            Long _v = options.limit;
            _req = dev.unofficialbox.runtime.Runtime.withQuery(_req, "limit", String.valueOf(_v));
        }
        Object _tree = dev.unofficialbox.core.Json.parse(new String(dev.unofficialbox.runtime.Runtime.responseBytes(session.fetch(_req)), java.nio.charset.StandardCharsets.UTF_8));
        return (_tree == null ? null : dev.unofficialbox.model.schemas.CollaborationsOffsetPaginated.fromJson(_tree));
    }

    /** Iterate every dev.unofficialbox.model.schemas.Collaboration across pages, threading the cursor (FR-7.3). */
    public ListCollaborationsListCollaborationsPaginator listCollaborations(dev.unofficialbox.model.schemas.GetCollaborationsStatus status, ListCollaborationsOptions options) {
        return new ListCollaborationsListCollaborationsPaginator(session, status, options);
    }

    /** GET /groups/{group_id}/collaborations. */
    dev.unofficialbox.model.schemas.CollaborationsOffsetPaginated listGroupCollaborationsPage(String groupId, ListGroupCollaborationsOptions options) {
        StringBuilder _url = new StringBuilder(session.baseUrl("api"));
        _url.append("/groups");
        _url.append("/").append(dev.unofficialbox.internal.Internal.pathEscape(groupId));
        _url.append("/collaborations");
        dev.unofficialbox.runtime.Runtime.Request _req = session.newRequest("GET", _url.toString());
        if (options != null && options.limit != null) {
            Long _v = options.limit;
            _req = dev.unofficialbox.runtime.Runtime.withQuery(_req, "limit", String.valueOf(_v));
        }
        if (options != null && options.offset != null) {
            Long _v = options.offset;
            _req = dev.unofficialbox.runtime.Runtime.withQuery(_req, "offset", String.valueOf(_v));
        }
        Object _tree = dev.unofficialbox.core.Json.parse(new String(dev.unofficialbox.runtime.Runtime.responseBytes(session.fetch(_req)), java.nio.charset.StandardCharsets.UTF_8));
        return (_tree == null ? null : dev.unofficialbox.model.schemas.CollaborationsOffsetPaginated.fromJson(_tree));
    }

    /** Iterate every dev.unofficialbox.model.schemas.Collaboration across pages, threading the cursor (FR-7.3). */
    public ListCollaborationsListGroupCollaborationsPaginator listGroupCollaborations(String groupId, ListGroupCollaborationsOptions options) {
        return new ListCollaborationsListGroupCollaborationsPaginator(session, groupId, options);
    }

    /** Optional parameters for listFileCollaborations. */
    public static final class ListFileCollaborationsOptions {
        /** The fields parameter. */
        public java.util.List<String> fields;
        /** The limit parameter. */
        public Long limit;
        /** The marker parameter. */
        public String marker;
    }

    /** Optional parameters for listFolderCollaborations. */
    public static final class ListFolderCollaborationsOptions {
        /** The fields parameter. */
        public java.util.List<String> fields;
        /** The limit parameter. */
        public Long limit;
        /** The marker parameter. */
        public String marker;
    }

    /** Optional parameters for listCollaborations. */
    public static final class ListCollaborationsOptions {
        /** The fields parameter. */
        public java.util.List<String> fields;
        /** The offset parameter. */
        public Long offset;
        /** The limit parameter. */
        public Long limit;
    }

    /** Optional parameters for listGroupCollaborations. */
    public static final class ListGroupCollaborationsOptions {
        /** The limit parameter. */
        public Long limit;
        /** The offset parameter. */
        public Long offset;
    }
}
