// Code generated by box-gantry 0.1.0 (spec ee7d55aedefe2fa0). DO NOT EDIT.
package dev.unofficialbox.managers;

/**
 * Paginator over {@link ListCollaborationsManager#listFileCollaborationsPage}, iterating every
 * {@code dev.unofficialbox.model.schemas.Collaboration} across pages (FR-7.3). Threads the response cursor back
 * into the request so callers can write {@code for (var item : paginator)}.
 * Re-iterable: each {@code iterator()} is an independent pass over a private
 * copy of the options, so the caller's options are never mutated.
 */
public final class ListCollaborationsListFileCollaborationsPaginator implements java.lang.Iterable<dev.unofficialbox.model.schemas.Collaboration> {
    private final dev.unofficialbox.runtime.Runtime.Session session;
    private final String fileId;
    private final ListCollaborationsManager.ListFileCollaborationsOptions options;

    ListCollaborationsListFileCollaborationsPaginator(dev.unofficialbox.runtime.Runtime.Session session, String fileId, ListCollaborationsManager.ListFileCollaborationsOptions options) {
        this.session = session;
        this.fileId = fileId;
        this.options = options;
    }

    private ListCollaborationsManager.ListFileCollaborationsOptions _freshOptions() {
        ListCollaborationsManager.ListFileCollaborationsOptions _o = new ListCollaborationsManager.ListFileCollaborationsOptions();
        if (options != null) {
            _o.fields = options.fields;
            _o.limit = options.limit;
            _o.marker = options.marker;
        }
        return _o;
    }

    @Override
    public java.util.Iterator<dev.unofficialbox.model.schemas.Collaboration> iterator() {
        return new java.util.Iterator<dev.unofficialbox.model.schemas.Collaboration>() {
            private final ListCollaborationsManager _manager = new ListCollaborationsManager(session);
            private final ListCollaborationsManager.ListFileCollaborationsOptions _opts = _freshOptions();
            private String _cursor = _opts.marker;
            private java.util.Iterator<dev.unofficialbox.model.schemas.Collaboration> _buffer = java.util.Collections.emptyIterator();
            private boolean _done = false;

            private void _advance() {
                while (!_buffer.hasNext() && !_done) {
                    _opts.marker = _cursor;
                    dev.unofficialbox.model.schemas.Collaborations _page = _manager.listFileCollaborationsPage(fileId, _opts);
                    java.util.List<dev.unofficialbox.model.schemas.Collaboration> _items = _page.entries().orElse(java.util.List.of());
                    _buffer = _items.iterator();
                    String _next = _page.nextMarker().isPresent() ? _page.nextMarker().value() : null;
                    if (_next != null && !_next.isEmpty()) {
                        _cursor = _next;
                    } else {
                        _done = true;
                    }
                }
            }

            @Override
            public boolean hasNext() {
                _advance();
                return _buffer.hasNext();
            }

            @Override
            public dev.unofficialbox.model.schemas.Collaboration next() {
                _advance();
                if (!_buffer.hasNext()) {
                    throw new java.util.NoSuchElementException();
                }
                return _buffer.next();
            }
        };
    }
}
