// Code generated by box-gantry 0.1.0 (spec ee7d55aedefe2fa0). DO NOT EDIT.
package dev.unofficialbox.managers;

/**
 * Paginator over {@link MembershipsManager#listUserPage}, iterating every
 * {@code dev.unofficialbox.model.schemas.GroupMembership} across pages (FR-7.3). Threads the response cursor back
 * into the request so callers can write {@code for (var item : paginator)}.
 * Re-iterable: each {@code iterator()} is an independent pass over a private
 * copy of the options, so the caller's options are never mutated.
 */
public final class MembershipsListUserPaginator implements java.lang.Iterable<dev.unofficialbox.model.schemas.GroupMembership> {
    private final dev.unofficialbox.runtime.Runtime.Session session;
    private final String userId;
    private final MembershipsManager.ListUserOptions options;

    MembershipsListUserPaginator(dev.unofficialbox.runtime.Runtime.Session session, String userId, MembershipsManager.ListUserOptions options) {
        this.session = session;
        this.userId = userId;
        this.options = options;
    }

    private MembershipsManager.ListUserOptions _freshOptions() {
        MembershipsManager.ListUserOptions _o = new MembershipsManager.ListUserOptions();
        if (options != null) {
            _o.limit = options.limit;
            _o.offset = options.offset;
        }
        return _o;
    }

    @Override
    public java.util.Iterator<dev.unofficialbox.model.schemas.GroupMembership> iterator() {
        return new java.util.Iterator<dev.unofficialbox.model.schemas.GroupMembership>() {
            private final MembershipsManager _manager = new MembershipsManager(session);
            private final MembershipsManager.ListUserOptions _opts = _freshOptions();
            private long _cursor = _opts.offset != null ? _opts.offset : 0L;
            private java.util.Iterator<dev.unofficialbox.model.schemas.GroupMembership> _buffer = java.util.Collections.emptyIterator();
            private boolean _done = false;

            private void _advance() {
                while (!_buffer.hasNext() && !_done) {
                    _opts.offset = _cursor;
                    dev.unofficialbox.model.schemas.GroupMemberships _page = _manager.listUserPage(userId, _opts);
                    java.util.List<dev.unofficialbox.model.schemas.GroupMembership> _items = _page.entries().orElse(java.util.List.of());
                    _buffer = _items.iterator();
                    if (_items.isEmpty()) {
                        _done = true;
                    } else {
                        _cursor += _items.size();
                    }
                }
            }

            @Override
            public boolean hasNext() {
                _advance();
                return _buffer.hasNext();
            }

            @Override
            public dev.unofficialbox.model.schemas.GroupMembership next() {
                _advance();
                if (!_buffer.hasNext()) {
                    throw new java.util.NoSuchElementException();
                }
                return _buffer.next();
            }
        };
    }
}
