// Code generated by box-gantry 0.1.0 (spec ee7d55aedefe2fa0). DO NOT EDIT.
package dev.unofficialbox.managers;

/** Operations for the sharedLinksFolders API area. */
public final class SharedLinksFoldersManager {
    private final dev.unofficialbox.runtime.Runtime.Session session;

    /** Construct over a shared runtime session (used by {@link dev.unofficialbox.Client}). */
    public SharedLinksFoldersManager(dev.unofficialbox.runtime.Runtime.Session session) {
        this.session = session;
    }

    /** GET /shared_items. */
    public dev.unofficialbox.model.schemas.FolderFull getSharedItemsFolders(String boxapi, GetSharedItemsFoldersOptions options) {
        StringBuilder _url = new StringBuilder(session.baseUrl("api"));
        _url.append("/shared_items");
        dev.unofficialbox.runtime.Runtime.Request _req = session.newRequest("GET", _url.toString());
        _req = dev.unofficialbox.runtime.Runtime.withHeader(_req, "boxapi", boxapi);
        if (options != null && options.ifNoneMatch != null) {
            String _v = options.ifNoneMatch;
            _req = dev.unofficialbox.runtime.Runtime.withHeader(_req, "if-none-match", _v);
        }
        if (options != null && options.fields != null) {
            java.util.List<String> _v = options.fields;
            _req = dev.unofficialbox.runtime.Runtime.withQuery(_req, "fields", String.join(",", _v));
        }
        Object _tree = dev.unofficialbox.core.Json.parse(new String(dev.unofficialbox.runtime.Runtime.responseBytes(session.fetch(_req)), java.nio.charset.StandardCharsets.UTF_8));
        return (_tree == null ? null : dev.unofficialbox.model.schemas.FolderFull.fromJson(_tree));
    }

    /** GET /folders/{folder_id}. */
    public dev.unofficialbox.model.schemas.FolderFull getFolderGetSharedLink(String folderId, String fields) {
        StringBuilder _url = new StringBuilder(session.baseUrl("api"));
        _url.append("/folders");
        _url.append("/").append(dev.unofficialbox.internal.Internal.pathEscape(folderId));
        dev.unofficialbox.runtime.Runtime.Request _req = session.newRequest("GET", _url.toString());
        _req = dev.unofficialbox.runtime.Runtime.withQuery(_req, "fields", fields);
        Object _tree = dev.unofficialbox.core.Json.parse(new String(dev.unofficialbox.runtime.Runtime.responseBytes(session.fetch(_req)), java.nio.charset.StandardCharsets.UTF_8));
        return (_tree == null ? null : dev.unofficialbox.model.schemas.FolderFull.fromJson(_tree));
    }

    /** PUT /folders/{folder_id}. */
    public dev.unofficialbox.model.schemas.FolderFull updateFolderAddSharedLink(String folderId, String fields, dev.unofficialbox.model.schemas.FileUpdateRequest2 body) {
        StringBuilder _url = new StringBuilder(session.baseUrl("api"));
        _url.append("/folders");
        _url.append("/").append(dev.unofficialbox.internal.Internal.pathEscape(folderId));
        dev.unofficialbox.runtime.Runtime.Request _req = session.newRequest("PUT", _url.toString());
        _req = dev.unofficialbox.runtime.Runtime.withQuery(_req, "fields", fields);
        byte[] _payload = dev.unofficialbox.core.Json.write((body == null ? null : body.toJson())).getBytes(java.nio.charset.StandardCharsets.UTF_8);
        _req = dev.unofficialbox.runtime.Runtime.withJsonBody(_req, _payload);
        Object _tree = dev.unofficialbox.core.Json.parse(new String(dev.unofficialbox.runtime.Runtime.responseBytes(session.fetch(_req)), java.nio.charset.StandardCharsets.UTF_8));
        return (_tree == null ? null : dev.unofficialbox.model.schemas.FolderFull.fromJson(_tree));
    }

    /** PUT /folders/{folder_id}. */
    public dev.unofficialbox.model.schemas.FolderFull updateFolderUpdateSharedLink(String folderId, String fields, dev.unofficialbox.model.schemas.FolderUpdateRequest2 body) {
        StringBuilder _url = new StringBuilder(session.baseUrl("api"));
        _url.append("/folders");
        _url.append("/").append(dev.unofficialbox.internal.Internal.pathEscape(folderId));
        dev.unofficialbox.runtime.Runtime.Request _req = session.newRequest("PUT", _url.toString());
        _req = dev.unofficialbox.runtime.Runtime.withQuery(_req, "fields", fields);
        byte[] _payload = dev.unofficialbox.core.Json.write((body == null ? null : body.toJson())).getBytes(java.nio.charset.StandardCharsets.UTF_8);
        _req = dev.unofficialbox.runtime.Runtime.withJsonBody(_req, _payload);
        Object _tree = dev.unofficialbox.core.Json.parse(new String(dev.unofficialbox.runtime.Runtime.responseBytes(session.fetch(_req)), java.nio.charset.StandardCharsets.UTF_8));
        return (_tree == null ? null : dev.unofficialbox.model.schemas.FolderFull.fromJson(_tree));
    }

    /** PUT /folders/{folder_id}. */
    public dev.unofficialbox.model.schemas.FolderFull updateFolderRemoveSharedLink(String folderId, String fields, dev.unofficialbox.model.schemas.FileUpdateRequest3 body) {
        StringBuilder _url = new StringBuilder(session.baseUrl("api"));
        _url.append("/folders");
        _url.append("/").append(dev.unofficialbox.internal.Internal.pathEscape(folderId));
        dev.unofficialbox.runtime.Runtime.Request _req = session.newRequest("PUT", _url.toString());
        _req = dev.unofficialbox.runtime.Runtime.withQuery(_req, "fields", fields);
        byte[] _payload = dev.unofficialbox.core.Json.write((body == null ? null : body.toJson())).getBytes(java.nio.charset.StandardCharsets.UTF_8);
        _req = dev.unofficialbox.runtime.Runtime.withJsonBody(_req, _payload);
        Object _tree = dev.unofficialbox.core.Json.parse(new String(dev.unofficialbox.runtime.Runtime.responseBytes(session.fetch(_req)), java.nio.charset.StandardCharsets.UTF_8));
        return (_tree == null ? null : dev.unofficialbox.model.schemas.FolderFull.fromJson(_tree));
    }

    /** Optional parameters for getSharedItemsFolders. */
    public static final class GetSharedItemsFoldersOptions {
        /** The if-none-match parameter. */
        public String ifNoneMatch;
        /** The fields parameter. */
        public java.util.List<String> fields;
    }
}
