// Code generated by box-gantry 0.1.0 (spec ee7d55aedefe2fa0). DO NOT EDIT.
package dev.unofficialbox.managers;

/**
 * Paginator over {@link ShieldInformationBarrierSegmentRestrictionsManager#listPage}, iterating every
 * {@code dev.unofficialbox.model.schemas.ShieldInformationBarrierSegmentRestriction} across pages (FR-7.3). Threads the response cursor back
 * into the request so callers can write {@code for (var item : paginator)}.
 * Re-iterable: each {@code iterator()} is an independent pass over a private
 * copy of the options, so the caller's options are never mutated.
 */
public final class ShieldInformationBarrierSegmentRestrictionsListPaginator implements java.lang.Iterable<dev.unofficialbox.model.schemas.ShieldInformationBarrierSegmentRestriction> {
    private final dev.unofficialbox.runtime.Runtime.Session session;
    private final String shieldInformationBarrierSegmentId;
    private final ShieldInformationBarrierSegmentRestrictionsManager.ListOptions options;

    ShieldInformationBarrierSegmentRestrictionsListPaginator(dev.unofficialbox.runtime.Runtime.Session session, String shieldInformationBarrierSegmentId, ShieldInformationBarrierSegmentRestrictionsManager.ListOptions options) {
        this.session = session;
        this.shieldInformationBarrierSegmentId = shieldInformationBarrierSegmentId;
        this.options = options;
    }

    private ShieldInformationBarrierSegmentRestrictionsManager.ListOptions _freshOptions() {
        ShieldInformationBarrierSegmentRestrictionsManager.ListOptions _o = new ShieldInformationBarrierSegmentRestrictionsManager.ListOptions();
        if (options != null) {
            _o.marker = options.marker;
            _o.limit = options.limit;
        }
        return _o;
    }

    @Override
    public java.util.Iterator<dev.unofficialbox.model.schemas.ShieldInformationBarrierSegmentRestriction> iterator() {
        return new java.util.Iterator<dev.unofficialbox.model.schemas.ShieldInformationBarrierSegmentRestriction>() {
            private final ShieldInformationBarrierSegmentRestrictionsManager _manager = new ShieldInformationBarrierSegmentRestrictionsManager(session);
            private final ShieldInformationBarrierSegmentRestrictionsManager.ListOptions _opts = _freshOptions();
            private String _cursor = _opts.marker;
            private java.util.Iterator<dev.unofficialbox.model.schemas.ShieldInformationBarrierSegmentRestriction> _buffer = java.util.Collections.emptyIterator();
            private boolean _done = false;

            private void _advance() {
                while (!_buffer.hasNext() && !_done) {
                    _opts.marker = _cursor;
                    dev.unofficialbox.model.schemas.ShieldInformationBarrierSegmentRestrictions _page = _manager.listPage(shieldInformationBarrierSegmentId, _opts);
                    java.util.List<dev.unofficialbox.model.schemas.ShieldInformationBarrierSegmentRestriction> _items = _page.entries().orElse(java.util.List.of());
                    _buffer = _items.iterator();
                    String _next = _page.nextMarker().isPresent() ? _page.nextMarker().value() : null;
                    if (_next != null && !_next.isEmpty()) {
                        _cursor = _next;
                    } else {
                        _done = true;
                    }
                }
            }

            @Override
            public boolean hasNext() {
                _advance();
                return _buffer.hasNext();
            }

            @Override
            public dev.unofficialbox.model.schemas.ShieldInformationBarrierSegmentRestriction next() {
                _advance();
                if (!_buffer.hasNext()) {
                    throw new java.util.NoSuchElementException();
                }
                return _buffer.next();
            }
        };
    }
}
