// Code generated by box-gantry 0.1.0 (spec ee7d55aedefe2fa0). DO NOT EDIT.
package dev.unofficialbox.managers;

/** Operations for the shieldLists API area. */
public final class ShieldListsManager {
    private final dev.unofficialbox.runtime.Runtime.Session session;

    /** Construct over a shared runtime session (used by {@link dev.unofficialbox.Client}). */
    public ShieldListsManager(dev.unofficialbox.runtime.Runtime.Session session) {
        this.session = session;
    }

    /** GET /shield_lists. */
    public dev.unofficialbox.model.schemas.ShieldLists list() {
        StringBuilder _url = new StringBuilder(session.baseUrl("api"));
        _url.append("/shield_lists");
        dev.unofficialbox.runtime.Runtime.Request _req = session.newRequest("GET", _url.toString());
        _req = dev.unofficialbox.runtime.Runtime.withHeader(_req, "box-version", "2025.0");
        Object _tree = dev.unofficialbox.core.Json.parse(new String(dev.unofficialbox.runtime.Runtime.responseBytes(session.fetch(_req)), java.nio.charset.StandardCharsets.UTF_8));
        return (_tree == null ? null : dev.unofficialbox.model.schemas.ShieldLists.fromJson(_tree));
    }

    /** POST /shield_lists. */
    public dev.unofficialbox.model.schemas.ShieldList create(dev.unofficialbox.model.schemas.ShieldListsCreate body) {
        StringBuilder _url = new StringBuilder(session.baseUrl("api"));
        _url.append("/shield_lists");
        dev.unofficialbox.runtime.Runtime.Request _req = session.newRequest("POST", _url.toString());
        _req = dev.unofficialbox.runtime.Runtime.withHeader(_req, "box-version", "2025.0");
        byte[] _payload = dev.unofficialbox.core.Json.write((body == null ? null : body.toJson())).getBytes(java.nio.charset.StandardCharsets.UTF_8);
        _req = dev.unofficialbox.runtime.Runtime.withJsonBody(_req, _payload);
        Object _tree = dev.unofficialbox.core.Json.parse(new String(dev.unofficialbox.runtime.Runtime.responseBytes(session.fetch(_req)), java.nio.charset.StandardCharsets.UTF_8));
        return (_tree == null ? null : dev.unofficialbox.model.schemas.ShieldList.fromJson(_tree));
    }

    /** GET /shield_lists/{shield_list_id}. */
    public dev.unofficialbox.model.schemas.ShieldList get(String shieldListId) {
        StringBuilder _url = new StringBuilder(session.baseUrl("api"));
        _url.append("/shield_lists");
        _url.append("/").append(dev.unofficialbox.internal.Internal.pathEscape(shieldListId));
        dev.unofficialbox.runtime.Runtime.Request _req = session.newRequest("GET", _url.toString());
        _req = dev.unofficialbox.runtime.Runtime.withHeader(_req, "box-version", "2025.0");
        Object _tree = dev.unofficialbox.core.Json.parse(new String(dev.unofficialbox.runtime.Runtime.responseBytes(session.fetch(_req)), java.nio.charset.StandardCharsets.UTF_8));
        return (_tree == null ? null : dev.unofficialbox.model.schemas.ShieldList.fromJson(_tree));
    }

    /** PUT /shield_lists/{shield_list_id}. */
    public dev.unofficialbox.model.schemas.ShieldList update(String shieldListId, dev.unofficialbox.model.schemas.ShieldListsUpdate body) {
        StringBuilder _url = new StringBuilder(session.baseUrl("api"));
        _url.append("/shield_lists");
        _url.append("/").append(dev.unofficialbox.internal.Internal.pathEscape(shieldListId));
        dev.unofficialbox.runtime.Runtime.Request _req = session.newRequest("PUT", _url.toString());
        _req = dev.unofficialbox.runtime.Runtime.withHeader(_req, "box-version", "2025.0");
        byte[] _payload = dev.unofficialbox.core.Json.write((body == null ? null : body.toJson())).getBytes(java.nio.charset.StandardCharsets.UTF_8);
        _req = dev.unofficialbox.runtime.Runtime.withJsonBody(_req, _payload);
        Object _tree = dev.unofficialbox.core.Json.parse(new String(dev.unofficialbox.runtime.Runtime.responseBytes(session.fetch(_req)), java.nio.charset.StandardCharsets.UTF_8));
        return (_tree == null ? null : dev.unofficialbox.model.schemas.ShieldList.fromJson(_tree));
    }

    /** DELETE /shield_lists/{shield_list_id}. */
    public void delete(String shieldListId) {
        StringBuilder _url = new StringBuilder(session.baseUrl("api"));
        _url.append("/shield_lists");
        _url.append("/").append(dev.unofficialbox.internal.Internal.pathEscape(shieldListId));
        dev.unofficialbox.runtime.Runtime.Request _req = session.newRequest("DELETE", _url.toString());
        _req = dev.unofficialbox.runtime.Runtime.withHeader(_req, "box-version", "2025.0");
        session.fetch(_req);
    }
}
