// Code generated by box-gantry 0.1.0 (spec ee7d55aedefe2fa0). DO NOT EDIT.
package dev.unofficialbox.managers;

/**
 * Paginator over {@link SignTemplatesManager#listPage}, iterating every
 * {@code dev.unofficialbox.model.schemas.SignTemplate} across pages (FR-7.3). Threads the response cursor back
 * into the request so callers can write {@code for (var item : paginator)}.
 * Re-iterable: each {@code iterator()} is an independent pass over a private
 * copy of the options, so the caller's options are never mutated.
 */
public final class SignTemplatesListPaginator implements java.lang.Iterable<dev.unofficialbox.model.schemas.SignTemplate> {
    private final dev.unofficialbox.runtime.Runtime.Session session;
    private final SignTemplatesManager.ListOptions options;

    SignTemplatesListPaginator(dev.unofficialbox.runtime.Runtime.Session session, SignTemplatesManager.ListOptions options) {
        this.session = session;
        this.options = options;
    }

    private SignTemplatesManager.ListOptions _freshOptions() {
        SignTemplatesManager.ListOptions _o = new SignTemplatesManager.ListOptions();
        if (options != null) {
            _o.marker = options.marker;
            _o.limit = options.limit;
        }
        return _o;
    }

    @Override
    public java.util.Iterator<dev.unofficialbox.model.schemas.SignTemplate> iterator() {
        return new java.util.Iterator<dev.unofficialbox.model.schemas.SignTemplate>() {
            private final SignTemplatesManager _manager = new SignTemplatesManager(session);
            private final SignTemplatesManager.ListOptions _opts = _freshOptions();
            private String _cursor = _opts.marker;
            private java.util.Iterator<dev.unofficialbox.model.schemas.SignTemplate> _buffer = java.util.Collections.emptyIterator();
            private boolean _done = false;

            private void _advance() {
                while (!_buffer.hasNext() && !_done) {
                    _opts.marker = _cursor;
                    dev.unofficialbox.model.schemas.SignTemplates _page = _manager.listPage(_opts);
                    java.util.List<dev.unofficialbox.model.schemas.SignTemplate> _items = _page.entries().orElse(java.util.List.of());
                    _buffer = _items.iterator();
                    String _next = _page.nextMarker().isPresent() ? _page.nextMarker().value() : null;
                    if (_next != null && !_next.isEmpty()) {
                        _cursor = _next;
                    } else {
                        _done = true;
                    }
                }
            }

            @Override
            public boolean hasNext() {
                _advance();
                return _buffer.hasNext();
            }

            @Override
            public dev.unofficialbox.model.schemas.SignTemplate next() {
                _advance();
                if (!_buffer.hasNext()) {
                    throw new java.util.NoSuchElementException();
                }
                return _buffer.next();
            }
        };
    }
}
