// Code generated by box-gantry 0.1.0 (spec ee7d55aedefe2fa0). DO NOT EDIT.
package dev.unofficialbox.managers;

/** Operations for the trashedWebLinks API area. */
public final class TrashedWebLinksManager {
    private final dev.unofficialbox.runtime.Runtime.Session session;

    /** Construct over a shared runtime session (used by {@link dev.unofficialbox.Client}). */
    public TrashedWebLinksManager(dev.unofficialbox.runtime.Runtime.Session session) {
        this.session = session;
    }

    /** POST /web_links/{web_link_id}. */
    public dev.unofficialbox.model.schemas.TrashWebLinkRestored createWebLink(String webLinkId, dev.unofficialbox.model.schemas.FileCreateRequest body, CreateWebLinkOptions options) {
        StringBuilder _url = new StringBuilder(session.baseUrl("api"));
        _url.append("/web_links");
        _url.append("/").append(dev.unofficialbox.internal.Internal.pathEscape(webLinkId));
        dev.unofficialbox.runtime.Runtime.Request _req = session.newRequest("POST", _url.toString());
        if (options != null && options.fields != null) {
            java.util.List<String> _v = options.fields;
            _req = dev.unofficialbox.runtime.Runtime.withQuery(_req, "fields", String.join(",", _v));
        }
        byte[] _payload = dev.unofficialbox.core.Json.write((body == null ? null : body.toJson())).getBytes(java.nio.charset.StandardCharsets.UTF_8);
        _req = dev.unofficialbox.runtime.Runtime.withJsonBody(_req, _payload);
        Object _tree = dev.unofficialbox.core.Json.parse(new String(dev.unofficialbox.runtime.Runtime.responseBytes(session.fetch(_req)), java.nio.charset.StandardCharsets.UTF_8));
        return (_tree == null ? null : dev.unofficialbox.model.schemas.TrashWebLinkRestored.fromJson(_tree));
    }

    /** GET /web_links/{web_link_id}/trash. */
    public dev.unofficialbox.model.schemas.TrashWebLink getWebLinkTrash(String webLinkId, GetWebLinkTrashOptions options) {
        StringBuilder _url = new StringBuilder(session.baseUrl("api"));
        _url.append("/web_links");
        _url.append("/").append(dev.unofficialbox.internal.Internal.pathEscape(webLinkId));
        _url.append("/trash");
        dev.unofficialbox.runtime.Runtime.Request _req = session.newRequest("GET", _url.toString());
        if (options != null && options.fields != null) {
            java.util.List<String> _v = options.fields;
            _req = dev.unofficialbox.runtime.Runtime.withQuery(_req, "fields", String.join(",", _v));
        }
        Object _tree = dev.unofficialbox.core.Json.parse(new String(dev.unofficialbox.runtime.Runtime.responseBytes(session.fetch(_req)), java.nio.charset.StandardCharsets.UTF_8));
        return (_tree == null ? null : dev.unofficialbox.model.schemas.TrashWebLink.fromJson(_tree));
    }

    /** DELETE /web_links/{web_link_id}/trash. */
    public void deleteWebLinkTrash(String webLinkId) {
        StringBuilder _url = new StringBuilder(session.baseUrl("api"));
        _url.append("/web_links");
        _url.append("/").append(dev.unofficialbox.internal.Internal.pathEscape(webLinkId));
        _url.append("/trash");
        dev.unofficialbox.runtime.Runtime.Request _req = session.newRequest("DELETE", _url.toString());
        session.fetch(_req);
    }

    /** Optional parameters for createWebLink. */
    public static final class CreateWebLinkOptions {
        /** The fields parameter. */
        public java.util.List<String> fields;
    }

    /** Optional parameters for getWebLinkTrash. */
    public static final class GetWebLinkTrashOptions {
        /** The fields parameter. */
        public java.util.List<String> fields;
    }
}
