// Code generated by box-gantry 0.1.0 (spec ee7d55aedefe2fa0). DO NOT EDIT.
package dev.unofficialbox.managers;

/** Operations for the trashedItems API area. */
public final class TrashedItemsManager {
    private final dev.unofficialbox.runtime.Runtime.Session session;

    /** Construct over a shared runtime session (used by {@link dev.unofficialbox.Client}). */
    public TrashedItemsManager(dev.unofficialbox.runtime.Runtime.Session session) {
        this.session = session;
    }

    /** GET /folders/trash/items. */
    dev.unofficialbox.model.schemas.Items listFolderTrashItemsPage(ListFolderTrashItemsOptions options) {
        StringBuilder _url = new StringBuilder(session.baseUrl("api"));
        _url.append("/folders");
        _url.append("/trash");
        _url.append("/items");
        dev.unofficialbox.runtime.Runtime.Request _req = session.newRequest("GET", _url.toString());
        if (options != null && options.fields != null) {
            java.util.List<String> _v = options.fields;
            _req = dev.unofficialbox.runtime.Runtime.withQuery(_req, "fields", String.join(",", _v));
        }
        if (options != null && options.limit != null) {
            Long _v = options.limit;
            _req = dev.unofficialbox.runtime.Runtime.withQuery(_req, "limit", String.valueOf(_v));
        }
        if (options != null && options.offset != null) {
            Long _v = options.offset;
            _req = dev.unofficialbox.runtime.Runtime.withQuery(_req, "offset", String.valueOf(_v));
        }
        if (options != null && options.usemarker != null) {
            Boolean _v = options.usemarker;
            _req = dev.unofficialbox.runtime.Runtime.withQuery(_req, "usemarker", String.valueOf(_v));
        }
        if (options != null && options.marker != null) {
            String _v = options.marker;
            _req = dev.unofficialbox.runtime.Runtime.withQuery(_req, "marker", _v);
        }
        if (options != null && options.direction != null) {
            dev.unofficialbox.model.schemas.OrderDirection _v = options.direction;
            _req = dev.unofficialbox.runtime.Runtime.withQuery(_req, "direction", _v.value());
        }
        if (options != null && options.sort != null) {
            dev.unofficialbox.model.schemas.GetFolderTrashItemsSort _v = options.sort;
            _req = dev.unofficialbox.runtime.Runtime.withQuery(_req, "sort", _v.value());
        }
        Object _tree = dev.unofficialbox.core.Json.parse(new String(dev.unofficialbox.runtime.Runtime.responseBytes(session.fetch(_req)), java.nio.charset.StandardCharsets.UTF_8));
        return (_tree == null ? null : dev.unofficialbox.model.schemas.Items.fromJson(_tree));
    }

    /** Iterate every dev.unofficialbox.model.schemas.Item across pages, threading the cursor (FR-7.3). */
    public TrashedItemsListFolderTrashItemsPaginator listFolderTrashItems(ListFolderTrashItemsOptions options) {
        return new TrashedItemsListFolderTrashItemsPaginator(session, options);
    }

    /** Optional parameters for listFolderTrashItems. */
    public static final class ListFolderTrashItemsOptions {
        /** The fields parameter. */
        public java.util.List<String> fields;
        /** The limit parameter. */
        public Long limit;
        /** The offset parameter. */
        public Long offset;
        /** The usemarker parameter. */
        public Boolean usemarker;
        /** The marker parameter. */
        public String marker;
        /** The direction parameter. */
        public dev.unofficialbox.model.schemas.OrderDirection direction;
        /** The sort parameter. */
        public dev.unofficialbox.model.schemas.GetFolderTrashItemsSort sort;
    }
}
