// Code generated by box-gantry 0.1.0 (spec ee7d55aedefe2fa0). DO NOT EDIT.
package dev.unofficialbox.managers;

/** Operations for the zipDownloads API area. */
public final class ZipDownloadsManager {
    private final dev.unofficialbox.runtime.Runtime.Session session;

    /** Construct over a shared runtime session (used by {@link dev.unofficialbox.Client}). */
    public ZipDownloadsManager(dev.unofficialbox.runtime.Runtime.Session session) {
        this.session = session;
    }

    /** POST /zip_downloads. */
    public dev.unofficialbox.model.schemas.ZipDownload create(dev.unofficialbox.model.schemas.ZipDownloadRequest body) {
        StringBuilder _url = new StringBuilder(session.baseUrl("api"));
        _url.append("/zip_downloads");
        dev.unofficialbox.runtime.Runtime.Request _req = session.newRequest("POST", _url.toString());
        byte[] _payload = dev.unofficialbox.core.Json.write((body == null ? null : body.toJson())).getBytes(java.nio.charset.StandardCharsets.UTF_8);
        _req = dev.unofficialbox.runtime.Runtime.withJsonBody(_req, _payload);
        Object _tree = dev.unofficialbox.core.Json.parse(new String(dev.unofficialbox.runtime.Runtime.responseBytes(session.fetch(_req)), java.nio.charset.StandardCharsets.UTF_8));
        return (_tree == null ? null : dev.unofficialbox.model.schemas.ZipDownload.fromJson(_tree));
    }

    /** GET /zip_downloads/{zip_download_id}/content. */
    public dev.unofficialbox.runtime.Runtime.Stream getContent(String zipDownloadId) {
        StringBuilder _url = new StringBuilder(session.baseUrl("download"));
        _url.append("/zip_downloads");
        _url.append("/").append(dev.unofficialbox.internal.Internal.pathEscape(zipDownloadId));
        _url.append("/content");
        dev.unofficialbox.runtime.Runtime.Request _req = session.newRequest("GET", _url.toString());
        return dev.unofficialbox.runtime.Runtime.responseStream(session.fetch(_req));
    }

    /** GET /zip_downloads/{zip_download_id}/status. */
    public dev.unofficialbox.model.schemas.ZipDownloadStatus getStatus(String zipDownloadId) {
        StringBuilder _url = new StringBuilder(session.baseUrl("api"));
        _url.append("/zip_downloads");
        _url.append("/").append(dev.unofficialbox.internal.Internal.pathEscape(zipDownloadId));
        _url.append("/status");
        dev.unofficialbox.runtime.Runtime.Request _req = session.newRequest("GET", _url.toString());
        Object _tree = dev.unofficialbox.core.Json.parse(new String(dev.unofficialbox.runtime.Runtime.responseBytes(session.fetch(_req)), java.nio.charset.StandardCharsets.UTF_8));
        return (_tree == null ? null : dev.unofficialbox.model.schemas.ZipDownloadStatus.fromJson(_tree));
    }
}
